import Ix.CompileCert.SourcePinGen
import Ix.Meta
import IxC.Kernel.PinGen.Certs

/-! # `source-pin-gen`: the source-named Nat-operation pins (untrusted generator)

Usage: `lake exe source-pin-gen <SourceNatOpPinData.lean>`.

1. Loads the Lean environment of `IxC.Kernel.PinGen.Certs` (Init and the
   certificate theorems, as Lean elaborated and its kernel checked them).
2. Generates the source variant (`SourcePinGen.generate`: the operations' Lean
   values and the certificate theorems' values, exported by `exportSourceExpr`,
   closed by `kernel-pin-gen`'s rule over each operation's Lean cone).
3. Verifies it through the S route: per operation, the source cone of the
   operation and its certificate ground is installed by the normalised source
   installation (the verified fold) with the variant, and must be accepted;
   with no pins the same cone must be refused (the operation's decline).
4. Encodes the variant as a share table, decodes it with the committed decoder
   and requires the decoded variant to equal the generated one.
5. Writes the data file. Nothing is written unless every step passed. -/

namespace Ix.CompileCert.SourcePinGen

def recipe : String := "    lake build IxC.Kernel.PinGen.Certs source-pin-gen\n    \
  lake exe source-pin-gen Ix/CompileCert/SourceNatOpPinData.lean"

def run (args : List String) : IO UInt32 := do
  let [output] := args
    | IO.eprintln "usage: source-pin-gen <SourceNatOpPinData.lean>"; return 2
  let t0 ← IO.monoMsNow
  let env ← getCompileEnv #[`IxC.Kernel.PinGen.Certs]
  IO.eprintln s!"source-pin-gen: environment of IxC.Kernel.PinGen.Certs: {env.constants.fold (fun n _ _ => n + 1) 0} constants; \
    {(← IO.monoMsNow) - t0} ms"
  let toolchain := (← IO.FS.readFile "lean-toolchain").trimAscii.toString
  let (ps, log) ← match generate env.find? toolchain with
    | .ok r => pure r
    | .error why => IO.eprintln s!"source-pin-gen: generation failed: {why}"; return 1
  for line in log do IO.eprintln s!"source-pin-gen: {line}"
  -- 3. verification through the S route, with a negative control per operation
  let mut bad := 0
  for (op, opK, _) in certSpecs do
    let ground := (groundOf env.find? ps opK).toList
    let roots := op :: ground.filter (· != op)
    let t ← IO.monoMsNow
    let accepted ← installCone env [ps] roots
    let declined ← installCone env [] roots
    let ms := (← IO.monoMsNow) - t
    match accepted, declined with
    | .ok n, .error why =>
      IO.eprintln s!"source-pin-gen: {op}: accepted with the variant ({n} installed declarations, \
        {ground.length} ground constants); without pins refused ({why.take 160}); {ms} ms"
    | .ok _, .ok _ =>
      IO.eprintln s!"source-pin-gen: {op}: accepted with the variant, but also without pins (no control)"
      bad := bad + 1
    | .error why, _ =>
      IO.eprintln s!"source-pin-gen: {op}: REFUSED with the variant: {why}"
      bad := bad + 1
  unless bad == 0 do return 1
  -- 4. share table, decoded back
  let (lines, roots) ← match encodePins ps with
    | .ok r => pure r
    | .error why => IO.eprintln s!"source-pin-gen: encoding failed: {why}"; return 1
  let table := "\n".intercalate lines.toList
  match decodePins ps.toolchain ("\n" ++ table ++ "\n") roots with
  | .ok decoded =>
    unless sameVariant decoded ps do
      IO.eprintln "source-pin-gen: the share table does not decode to the generated variant"
      return 1
  | .error why => IO.eprintln s!"source-pin-gen: decoding failed: {why}"; return 1
  let proofCount := (roots.toList.map (·.2.2.length)).foldl (· + ·) 0
  IO.eprintln s!"source-pin-gen: share table {lines.size} nodes, {proofCount} certificate proofs, decoded back equal"
  -- 5. output
  let opLines := roots.toList.map fun (n, pin, proofs) => s!"  ({n.quote}, {pin}, {proofs})"
  let text := s!"/-! # The pin-certified Nat operations' source-named pins and certificates (generated)

GENERATED by `source-pin-gen` (`Ix/CompileCert/SourcePinGenMain.lean`,
`Ix/CompileCert/SourcePinGen.lean`); do not edit. To regenerate:

{recipe}

One pin variant (`Ix.Kernel.NatOpPinSet`) of the eight pin-certified `Nat`
operations under Lean's own names, for the normalised source installation
(`Ix.CompileCert.SourceNormalizedInstallation`):

* the pins are the operations' Lean values, exported by the lane's
  `exportSourceExpr` (names by `sourceName`);
* the certificate proofs are the theorems of `IxC/Kernel/PinGen/Certs.lean` as
  Lean elaborated them (environment of `IxC.Kernel.PinGen.Certs`), exported by
  `exportSourceExpr`, with every constant outside the operation's Lean
  dependency cone, its certificate ground and the statements' machinery
  inlined, and beta, `let` and projection-of-constructor redexes reduced
  (`kernel-pin-gen`'s rule).

Every operation's source cone was accepted by the verified fold, through the
normalised source installation, with this variant (and refused without it)
when this file was generated. The fold takes its pin list as a parameter and
`Ix.Kernel.model_exists` holds at every list, so the data carries no trust.
`table` is a share table and `ops` its roots per operation, in `NatOpPinSet`
field order; the format and the decoder are in `IxC/Kernel/Ixon/Prelude.lean`. -/

namespace Ix.CompileCert.SourceNatOpPinData

def source : String := {s!"{Lean.versionString}; {env.constants.fold (fun n _ _ => n + 1) 0} constants".quote}

def toolchain : String := {ps.toolchain.quote}

def ops : Array (String × Nat × List Nat) := #[
{",\n".intercalate opLines}]

def table : String := r\"
{table}
\"

end Ix.CompileCert.SourceNatOpPinData
"
  IO.FS.writeFile output text
  IO.eprintln s!"source-pin-gen: wrote {output}; {(← IO.monoMsNow) - t0} ms"
  return 0

end Ix.CompileCert.SourcePinGen

def main (args : List String) : IO UInt32 := Ix.CompileCert.SourcePinGen.run args
