/-
Copyright (c) 2026 Argument Computer Corporation.
SPDX-License-Identifier: MIT OR Apache-2.0
-/

import Ix.Kernel.Ixon.Reader
import Ix.Kernel.Ixon.PinData
import Ix.Ixon.Canonical
import Ix.Kernel.Ixon.NatOpPinData
import Ix.Kernel.NatOpPinSet

/-! # The Ixon prelude and the pin table (decision D5)

Con-leche's built-in prelude (`Frontend/Prelude.lean`, not ported) is a
committed lean4export stream of twelve declarations, parsed at start-up and
put in front of every fold by `Frontend.preparePrelude`: the six pinned basis
blocks `Eq`, `Nat`, `PUnit`, `Empty`, `False` and the quotient package (the
four `Quot` constants and `Quot.sound`), plus `And` (pinned by design, for the
stuck-major rescue) and `Bool` (which the pin-certified Nat operations'
certificate statements are spelled over). Here the same twelve declarations
come from the Ixon records of the compiled Init: `PinData.prelude` holds
those records' canonical bytes, keyed by address (the inductive blocks, their
projection records and their recursor records, the four quotient records and
the `Quot.sound` axiom), generated by `Benchmarks/Kernel/PinGen.lean`
from `.lake/census/initstd.ixe`. They are decoded by the canonical decoder and
read by the same reader as every stream, so the prelude goes through no other
parser. A stream that declares any of them is checked on its own record
(`preparePrelude` moves the stream's copy to the front); the prelude's copy
fills in only where the stream has none.

`PinData.pins` is the pin table (`Ix.Kernel.IxonReader.Pin`), from the
same generator; see the reader's module docstring for what it may and may not
affect. `NatOpPinData` is the pin variant of the pin-certified `Nat`
operations, from the same generator and also from Ixon records only (below,
"The Nat-operation pins, from Ixon"). -/

namespace Ix.Kernel.IxonReader

open Ix.Kernel (ConstRef)

def nameOfComponents : List (String ⊕ Nat) → CName :=
  List.foldl (fun n c => match c with | .inl s => .str n s | .inr k => .num n k) .anonymous

def addressOfHex (s : String) : Option Address := do
  let b ← bytesOfHex s
  pure ⟨b⟩

/-- The committed pin table. An entry whose address does not parse is a
corrupted file, reported by `defaultPins`. -/
def pinTable : Except String (Array Pin) :=
  PinData.pins.mapM fun (cs, hex, i, c) => do
    let some b := addressOfHex hex | throw s!"pin table: bad address {hex}"
    let ref : ConstRef Address := if c == 0 then .member b i else .ctor b i (c - 1)
    pure ⟨ref, nameOfComponents cs⟩

/-- The committed level-parameter names. -/
def levelTable : Except String (Std.HashMap (ConstRef Address) (List CName)) :=
  PinData.levels.foldlM (init := {}) fun m (hex, i, c, ns) => do
    let some b := addressOfHex hex | throw s!"level table: bad address {hex}"
    let ref : ConstRef Address := if c == 0 then .member b i else .ctor b i (c - 1)
    pure (m.insert ref (ns.map nameOfComponents))

/-- The committed pin and level tables, the former checked (`pinMap`). -/
def defaultPins : Except String Pins := do
  pure { names := ← pinMap (← pinTable), levels := ← levelTable }

/-! ## The Nat-operation pins, from Ixon (plan v4 §2 "Pins")

Con-leche's pin-certified `Nat` operations (`div`, `mod`, `gcd`, `land`,
`lor`, `xor`, `shiftLeft`, `shiftRight`) take a pin variant
(`Ix.Kernel.NatOpPinSet`): per operation, the pinned defining expression the
stored value is compared with, and the certificate proofs of its pinned
recurrence statements. `NatOpPinData` is that variant generated from Ixon
records by `kernel-pin-gen` (`Benchmarks/Kernel/PinGen.lean`): the
pins are the operations' stored values in the compiled Init, read by this
reader; the proofs are the theorems of `Ix/Kernel/PinGen/Certs.lean` compiled
by the Ix compiler and read by this reader, with every constant outside the
operation's dependency cone, its certificate ground and the statements'
machinery inlined, as upstream's pinner does. The fold takes its pin list as
a parameter and `Ix.Kernel.model_exists` holds at every list, so neither the
data nor this decoder carries trust; they decide only whether the fast paths
are enabled.

**The table.** `NatOpPinData.table` is a share table, one node per line,
fields separated by single spaces. A reference is the index of an earlier
node: index 0 is `Name.anonymous`, index 1 is `Level.zero`, and line `k`
(from 0) is index `k + 2`. String payloads are percent-encoded UTF-8 (every
byte outside `[A-Za-z0-9._'!?-]` as `%XX`).

| line | node |
|---|---|
| `n p s` / `m p k` | `Name.str p s` / `Name.num p k` |
| `S u` / `M u v` / `I u v` / `P n` | `Level.succ` / `max` / `imax` / `param` |
| `B k` / `Y u` / `C n u…` / `A f a` | `Expr.bvar` / `sort` / `const` / `app` |
| `L t b` / `F t b` / `E t v b` | `lam` / `forallE` / `letE` (every binder `pw := .never`) |
| `N k` / `T s` / `J n i e` | a `Nat` literal / a `String` literal / `proj` |

`NatOpPinData.ops` lists, in `NatOpPinSet` field order, each operation's pin
and certificate-proof roots. -/

/-- One decoded share-table node. -/
inductive PinNode where
  | name (n : CName)
  | level (l : CLevel)
  | expr (e : CExpr)
  deriving Inhabited

/-- A hex digit's value. -/
def hexDigit (c : Char) : Option Nat :=
  if '0' ≤ c && c ≤ '9' then some (c.toNat - '0'.toNat)
  else if 'a' ≤ c && c ≤ 'f' then some (c.toNat - 'a'.toNat + 10)
  else if 'A' ≤ c && c ≤ 'F' then some (c.toNat - 'A'.toNat + 10)
  else none

/-- Undo the table's percent-encoding. -/
def percentDecode (s : String) : Except String String := do
  let cs := s.toList.toArray
  let mut bytes : ByteArray := .empty
  let mut i := 0
  for _ in [0:cs.size] do
    if h : i < cs.size then
      let c := cs[i]
      if c == '%' then
        let some hi := (cs[i + 1]?).bind hexDigit | throw s!"pin table: bad escape in {s}"
        let some lo := (cs[i + 2]?).bind hexDigit | throw s!"pin table: bad escape in {s}"
        bytes := bytes.push (hi * 16 + lo).toUInt8
        i := i + 3
      else
        bytes := bytes ++ c.toString.toUTF8
        i := i + 1
  match String.fromUTF8? bytes with
  | some r => pure r
  | none => throw s!"pin table: {s} is not UTF-8"

/-- Decode the share table. -/
def decodePinTable (text : String) : Except String (Array PinNode) := do
  let mut out : Array PinNode := #[.name .anonymous, .level .zero]
  for line in text.splitOn "\n" do
    if line.isEmpty then continue
    let fs := (line.splitOn " ").toArray
    let field (i : Nat) : Except String String :=
      match fs[i]? with
      | some f => pure f
      | none => throw s!"pin table: short line {line}"
    let num (i : Nat) : Except String Nat := do
      match (← field i).toNat? with
      | some k => pure k
      | none => throw s!"pin table: bad number in {line}"
    let node (i : Nat) : Except String PinNode := do
      match out[← num i]? with
      | some n => pure n
      | none => throw s!"pin table: forward reference in {line}"
    let nameAt (i : Nat) : Except String CName := do
      match ← node i with
      | .name n => pure n
      | _ => throw s!"pin table: not a name at field {i} of {line}"
    let levelAt (i : Nat) : Except String CLevel := do
      match ← node i with
      | .level l => pure l
      | _ => throw s!"pin table: not a level at field {i} of {line}"
    let exprAt (i : Nat) : Except String CExpr := do
      match ← node i with
      | .expr e => pure e
      | _ => throw s!"pin table: not an expression at field {i} of {line}"
    let n : PinNode ← match ← field 0 with
      | "n" => pure (.name (.str (← nameAt 1) (← percentDecode (← field 2))))
      | "m" => pure (.name (.num (← nameAt 1) (← num 2)))
      | "S" => pure (.level (.succ (← levelAt 1)))
      | "M" => pure (.level (.max (← levelAt 1) (← levelAt 2)))
      | "I" => pure (.level (.imax (← levelAt 1) (← levelAt 2)))
      | "P" => pure (.level (.param (← nameAt 1)))
      | "B" => pure (.expr (Ix.Kernel.Expr.mkBvar (← num 1)))
      | "Y" => pure (.expr (.sort (← levelAt 1)))
      | "C" => do
        let us ← ((List.range (fs.size - 2)).map (· + 2)).mapM levelAt
        pure (.expr (.const (← nameAt 1) us))
      | "A" => pure (.expr (.app (← exprAt 1) (← exprAt 2)))
      | "L" => pure (.expr (.lam (← exprAt 1) (← exprAt 2) ⟨.never⟩))
      | "F" => pure (.expr (.forallE (← exprAt 1) (← exprAt 2) ⟨.never⟩))
      | "E" => pure (.expr (.letE (← exprAt 1) (← exprAt 2) (← exprAt 3)))
      | "N" => pure (.expr (.lit (.natVal (← num 1))))
      | "T" => pure (.expr (.lit (.strVal (← percentDecode (← field 1)))))
      | "J" => pure (.expr (.proj (← nameAt 1) (← num 2) (← exprAt 3)))
      | t => throw s!"pin table: unknown node {t}"
    out := out.push n
  return out

/-- A pin variant from a decoded table and its per-operation roots (the
`NatOpPinSet` field order: `div`, `mod`, `gcd`, `land`, `lor`, `xor`,
`shiftLeft`, `shiftRight`). -/
def natOpPinSetOf (toolchain : String) (nodes : Array PinNode)
    (ops : Array (String × Nat × List Nat)) : Except String Ix.Kernel.NatOpPinSet := do
  let expr (i : Nat) : Except String CExpr :=
    match nodes[i]? with
    | some (.expr e) => pure e
    | _ => throw s!"pin table: root {i} is not an expression"
  let op (k : Nat) (name : String) : Except String (CExpr × List CExpr) := do
    let some (n, pin, proofs) := ops[k]? | throw s!"pin table: no entry for {name}"
    unless n == name do throw s!"pin table: entry {k} is {n}, expected {name}"
    pure (← expr pin, ← proofs.mapM expr)
  let (divPin, divProofs) ← op 0 "Nat.div"
  let (modPin, modProofs) ← op 1 "Nat.mod"
  let (gcdPin, gcdProofs) ← op 2 "Nat.gcd"
  let (landPin, landProofs) ← op 3 "Nat.land"
  let (lorPin, lorProofs) ← op 4 "Nat.lor"
  let (xorPin, xorProofs) ← op 5 "Nat.xor"
  let (shiftLeftPin, shiftLeftProofs) ← op 6 "Nat.shiftLeft"
  let (shiftRightPin, shiftRightProofs) ← op 7 "Nat.shiftRight"
  pure { toolchain, divPin, modPin, gcdPin, landPin, lorPin, xorPin, shiftLeftPin, shiftRightPin,
         divProofs, modProofs, gcdProofs, landProofs, lorProofs, xorProofs, shiftLeftProofs,
         shiftRightProofs }

/-- The committed pin variant, decoded; a failure is a corrupted committed
file, which the entry reports. -/
def builtinNatOpPins : Except String (List Ix.Kernel.NatOpPinSet) := do
  let nodes ← decodePinTable NatOpPinData.table
  pure [← natOpPinSetOf NatOpPinData.toolchain nodes NatOpPinData.ops]

/-- Generous per-record limits for the committed prelude records. -/
def preludeMaxBytes : Nat := 1 <<< 24
def preludeMaxUnivNodes : Nat := 1 <<< 20

/-- The committed prelude records, decoded canonically. -/
def preludeRecords : Except String (Array (Address × Ixon.Constant)) :=
  PinData.prelude.mapM fun (hex, bytes) => do
    let some a := addressOfHex hex | throw s!"prelude: bad address {hex}"
    let some b := bytesOfHex bytes | throw s!"prelude: bad bytes at {hex}"
    let c ← (Ixon.Canonical.deConstant preludeMaxBytes preludeMaxUnivNodes b).mapError
      (s!"prelude: record {hex}: " ++ ·)
    pure (a, c)

/-- The prelude: its records, their declarations, and the reader state after
them (the stream's reading continues from it). -/
structure Prelude where
  records : Array (Address × Ixon.Constant) := #[]
  ix : Ix.Kernel.Frontend.PreludeIx := {}
  state : State := {}

instance : Inhabited Prelude := ⟨{}⟩

/-- The reader context of `records` with the fallback store `fallback`.

The store is `storeOf records (storeOf fallback)` with both maps built here,
once: `storeOf` partially applied rebuilds its map at every lookup (it is
compiled at its full arity), which made reading quadratic in the number of
records (the 99,346 records of Init+Std did not finish reading in ten
minutes; they now read in 14 s). -/
def contextOf (pins : Pins) (records : Array (Address × Ixon.Constant))
    (blobs : List (Address × ByteArray)) (fallback : Array (Address × Ixon.Constant) := #[])
    (hint : ConstRef Address → Option Ix.Kernel.ReducibilityHint := fun _ => none) : Ctx :=
  let m := recordMap records
  let fm := recordMap fallback
  let store : Store := fun a => m[a]? <|> (fm[a]? <|> none)
  let blobMap : Std.HashMap Address ByteArray :=
    blobs.foldl (fun m (a, b) => if m.contains a then m else m.insert a b) {}
  let known : Std.HashSet Address := records.foldl (fun s (a, _) => s.insert a) {}
  let all := records ++ fallback.filter (fun (a, _) => !known.contains a)
  { store, blob := (blobMap[·]?), pins, index := buildIndex store pins.names all, hint,
    keys := keyNamesOf store pins.names all }

/-- Read prelude records under a pin table. -/
def readPrelude (pins : Pins)
    (records : Array (Address × Ixon.Constant)) : Except String Prelude := do
  let cx := contextOf pins records []
  match readRecords cx {} records with
  | .ok (state, decls) => pure ⟨records, ⟨decls⟩, state⟩
  | .error (e, i) => throw s!"prelude record {i}: {e}"

/-- The built-in prelude, under the committed pin table. A failure is a
corrupted committed file; the entry reports it rather than running with an
empty prelude. -/
def builtinPrelude : Except String Prelude := do
  readPrelude (← defaultPins) (← preludeRecords)

end Ix.Kernel.IxonReader
