version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
    # Create separate pull requests for major vs minor/patch version updates, as major bumps will likely introduce breaking changes and Dependabot will put each one in its own PR.
    groups:
      rust-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
