version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    allow:
      # Update both direct and indirect dependencies
      - dependency-type: "all"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
