/-
Copyright (c) 2026 Argument Computer Corporation.
SPDX-License-Identifier: MIT OR Apache-2.0
-/

import Ix.Kernel.ConLeche.Reader
import Ix.Kernel.ConLeche.PinData
import Ix.Ixon.Canonical
import ConLeche.Kernel.NatOpPins

/-! # The Ixon prelude and the pin table (decision D5)

Con-leche's built-in prelude (`Frontend/Prelude.lean`, not ported) is a
committed lean4export stream of twelve declarations, parsed at start-up and
put in front of every fold by `Frontend.preparePrelude`: the six pinned basis
blocks `Eq`, `Nat`, `PUnit`, `Empty`, `False` and the quotient package (the
four `Quot` constants and `Quot.sound`), plus `And` (pinned by design, for the
stuck-major rescue) and `Bool` (which the pin-certified Nat operations'
certificate statements are spelled over). Here the same twelve declarations
come from the Ixon records of the compiled Init: `PinData.prelude` holds
those records' canonical bytes, keyed by address (the inductive blocks, their
projection records and their recursor records, the four quotient records and
the `Quot.sound` axiom), generated by `Benchmarks/Kernel/ConLechePinGen.lean`
from `.lake/census/initstd.ixe`. They are decoded by the canonical decoder and
read by the same reader as every stream, so the prelude goes through no other
parser. A stream that declares any of them is checked on its own record
(`preparePrelude` moves the stream's copy to the front); the prelude's copy
fills in only where the stream has none.

`PinData.pins` is the pin table (`Ix.Kernel.ConLecheReader.Pin`), from the
same generator; see the reader's module docstring for what it may and may not
affect. -/

namespace Ix.Kernel.ConLecheReader

open Ix.Kernel (ConstRef)

def nameOfComponents : List (String ⊕ Nat) → CName :=
  List.foldl (fun n c => match c with | .inl s => .str n s | .inr k => .num n k) .anonymous

def addressOfHex (s : String) : Option Address := do
  let b ← bytesOfHex s
  pure ⟨b⟩

/-- The committed pin table. An entry whose address does not parse is a
corrupted file, reported by `defaultPins`. -/
def pinTable : Except String (Array Pin) :=
  PinData.pins.mapM fun (cs, hex, i, c) => do
    let some b := addressOfHex hex | throw s!"pin table: bad address {hex}"
    let ref : ConstRef Address := if c == 0 then .member b i else .ctor b i (c - 1)
    pure ⟨ref, nameOfComponents cs⟩

/-- The committed level-parameter names. -/
def levelTable : Except String (Std.HashMap (ConstRef Address) (List CName)) :=
  PinData.levels.foldlM (init := {}) fun m (hex, i, c, ns) => do
    let some b := addressOfHex hex | throw s!"level table: bad address {hex}"
    let ref : ConstRef Address := if c == 0 then .member b i else .ctor b i (c - 1)
    pure (m.insert ref (ns.map nameOfComponents))

/-- The committed pin and level tables, the former checked (`pinMap`). -/
def defaultPins : Except String Pins := do
  pure { names := ← pinMap (← pinTable), levels := ← levelTable }

/-! ## The Nat-operation pins in the reader's names

Con-leche's committed pin variants (`ConLeche.natOpPinSets`, the JSON dumps
spliced by `Kernel/NatOpPins.lean`) spell their pins and certificate proofs
with Lean names. Ixon content-addresses alpha-equivalent constants to one
record, so several of those names denote one Ixon constant (`HAdd.hAdd`,
`HMod.hMod`, `HDiv.hDiv`, … are one projection), which the reader can name
only once; and most of the others are read as `ix.…` names. `PinData.renames`
(generated with the table) maps each name the pins mention to the reader's
name of the constant it compiles to, and `ixonNatOpPins` is the committed
variants renamed through it (constants and projection type names). The fold
takes its pin list as a parameter and `ConLeche.model_exists` holds at every
list, so the renaming carries no trust; it decides only whether the
pin-certified operations' fast paths match. L4b's Ixon pinner replaces the
JSON dumps and this renaming with pins generated from the Ixon records. -/

/-- Rename constants and projection type names through `f`, sharing
preserved (one memoised walk of the DAG). -/
def renameExpr (f : CName → CName) (e : CExpr) : CExpr :=
  (go {} e).1
where
  go (memo : Std.HashMap CExpr CExpr) : CExpr → CExpr × Std.HashMap CExpr CExpr
    | .const n us => (.const (f n) us, memo)
    | .bvar i => (.bvar i, memo)
    | .sort u => (.sort u, memo)
    | .lit l => (.lit l, memo)
    | e =>
      match memo[e]? with
      | some r => (r, memo)
      | none =>
        let (r, memo) : CExpr × Std.HashMap CExpr CExpr := match e with
          | .fvar i ty => let (ty, memo) := go memo ty; (.fvar i ty, memo)
          | .app a b =>
            let (a, memo) := go memo a
            let (b, memo) := go memo b
            (.app a b, memo)
          | .lam ty b m =>
            let (ty, memo) := go memo ty
            let (b, memo) := go memo b
            (.lam ty b m, memo)
          | .forallE ty b m =>
            let (ty, memo) := go memo ty
            let (b, memo) := go memo b
            (.forallE ty b m, memo)
          | .letE ty v b =>
            let (ty, memo) := go memo ty
            let (v, memo) := go memo v
            let (b, memo) := go memo b
            (.letE ty v b, memo)
          | .proj s i x => let (x, memo) := go memo x; (.proj (f s) i x, memo)
          | e => (e, memo)
        (r, memo.insert e r)

def NatOpPinSet.rename (f : CName → CName) (ps : ConLeche.NatOpPinSet) : ConLeche.NatOpPinSet :=
  let r := renameExpr f
  { ps with
    divPin := r ps.divPin, modPin := r ps.modPin, gcdPin := r ps.gcdPin, landPin := r ps.landPin,
    lorPin := r ps.lorPin, xorPin := r ps.xorPin, shiftLeftPin := r ps.shiftLeftPin,
    shiftRightPin := r ps.shiftRightPin,
    divProofs := ps.divProofs.map r, modProofs := ps.modProofs.map r,
    gcdProofs := ps.gcdProofs.map r, landProofs := ps.landProofs.map r,
    lorProofs := ps.lorProofs.map r, xorProofs := ps.xorProofs.map r,
    shiftLeftProofs := ps.shiftLeftProofs.map r, shiftRightProofs := ps.shiftRightProofs.map r }

/-- The committed renaming of the pins' names. -/
def pinRenames : Std.HashMap CName CName :=
  PinData.renames.foldl (fun m (a, b) => m.insert (nameOfComponents a) (nameOfComponents b)) {}

/-- The pin variants under a renaming. -/
def renamePins (renames : Std.HashMap CName CName) : List ConLeche.NatOpPinSet :=
  ConLeche.natOpPinSets.map (NatOpPinSet.rename (fun n => renames.getD n n))

/-- The committed pin variants in the reader's names. -/
def ixonNatOpPins : List ConLeche.NatOpPinSet := renamePins pinRenames

/-- Generous per-record limits for the committed prelude records. -/
def preludeMaxBytes : Nat := 1 <<< 24
def preludeMaxUnivNodes : Nat := 1 <<< 20

/-- The committed prelude records, decoded canonically. -/
def preludeRecords : Except String (Array (Address × Ixon.Constant)) :=
  PinData.prelude.mapM fun (hex, bytes) => do
    let some a := addressOfHex hex | throw s!"prelude: bad address {hex}"
    let some b := bytesOfHex bytes | throw s!"prelude: bad bytes at {hex}"
    let c ← (Ixon.Canonical.deConstant preludeMaxBytes preludeMaxUnivNodes b).mapError
      (s!"prelude: record {hex}: " ++ ·)
    pure (a, c)

/-- The prelude: its records, their declarations, and the reader state after
them (the stream's reading continues from it). -/
structure Prelude where
  records : Array (Address × Ixon.Constant) := #[]
  ix : ConLeche.Frontend.PreludeIx := {}
  state : State := {}

instance : Inhabited Prelude := ⟨{}⟩

/-- The reader context of `records` with the fallback store `fallback`. -/
def contextOf (pins : Pins) (records : Array (Address × Ixon.Constant))
    (blobs : List (Address × ByteArray)) (fallback : Array (Address × Ixon.Constant) := #[])
    (hint : ConstRef Address → Option ConLeche.ReducibilityHint := fun _ => none) : Ctx :=
  let store := storeOf records (storeOf fallback)
  let blobMap : Std.HashMap Address ByteArray :=
    blobs.foldl (fun m (a, b) => if m.contains a then m else m.insert a b) {}
  let known : Std.HashSet Address := records.foldl (fun s (a, _) => s.insert a) {}
  let all := records ++ fallback.filter (fun (a, _) => !known.contains a)
  { store, blob := (blobMap[·]?), pins, index := buildIndex store pins.names all, hint }

/-- Read prelude records under a pin table. -/
def readPrelude (pins : Pins)
    (records : Array (Address × Ixon.Constant)) : Except String Prelude := do
  let cx := contextOf pins records []
  match readRecords cx {} records with
  | .ok (state, decls) => pure ⟨records, ⟨decls⟩, state⟩
  | .error (e, i) => throw s!"prelude record {i}: {e}"

/-- The built-in prelude, under the committed pin table. A failure is a
corrupted committed file; the entry reports it rather than running with an
empty prelude. -/
def builtinPrelude : Except String Prelude := do
  readPrelude (← defaultPins) (← preludeRecords)

end Ix.Kernel.ConLecheReader
