module
public import Ix.Aiur.Meta

/-!
# Keccak-256 in Aiur (value-based, wide permutation circuit)

Same algorithm/variant as `Ix/MultiStark/Keccak.lean` (Ethereum keccak-256:
pad `10*1`, rate 136, capacity 512) but shaped for the FFT cost model
(width x height x log2(height)): lanes and the 25-lane state are plain
values (no pointers, no memory traffic), the 24 rounds unroll into ONE
permutation circuit via `fold` (one row per keccak-f call), and rotations
are static bit recompositions (decompose once, recompose at compile-time
offsets) instead of runtime bit lists. theta's rotl-by-1 skips
decomposition entirely: `u8_add(b, b)` yields `(2b mod 256, msb)` and the
even low byte absorbs the neighbor's carry with a free field add.

Generated by a script (rho+pi is 24 distinct static bit wirings); the
pi/rho wiring is asserted against the MultiStark listing at generation
time.
-/

public section

namespace IxVM

-- The unrolled 24-round permutation elaborates to one deeply nested let
-- chain; the default recursion budget is not enough.
set_option maxRecDepth 65536 in
def keccak := ⟦
  /- # Test entrypoints -/

  pub fn keccak256_test() -> [[U8; 8]; 4] {
    let (idx, len) = io_get_info(0, [0]);
    let byte_stream = #read_byte_stream(0, idx, len);
    keccak256(byte_stream)
  }

  /- # Benchmark entrypoints -/

  pub fn keccak256_bench(num_hashes: G) -> G {
    let num_hashes_pred = num_hashes - 1;
    let key = [num_hashes_pred];
    let (idx, len) = io_get_info(0, key);
    let byte_stream = #read_byte_stream(0, idx, len);
    keccak256(byte_stream);
    match num_hashes_pred {
      0 => 0,
      _ => keccak256_bench(num_hashes_pred),
    }
  }

  /- # Sponge -/

  -- Pull one rate byte from the stream, injecting pad10*1 when the
  -- message is exhausted. `first_pad` is 1 until the first pad byte is
  -- emitted (which carries the 0x01 bit); position 135 carries 0x80
  -- (0x81 when both coincide). No store on the real-byte path — the
  -- block is consumed directly, not copied into a 136-node list.
  fn take_byte(stream: ByteStream, pos: G, first_pad: G) -> (U8, ByteStream, G) {
    match load(stream) {
      ListNode.Cons(b, rest) => (b, rest, first_pad),
      ListNode.Nil =>
        (u8_from_field_unsafe(first_pad + 128 * eq_zero(135 - pos)),
         store(ListNode.Nil), 0),
    }
  }

  -- Pull 8 consecutive rate bytes (one lane) from the stream, threading
  -- position and the pad flag. Factored out of absorb_blocks so the
  -- 136-byte walk is one reused circuit, not 136 inline lets in the
  -- toplevel AST (which overflows the elaborator).
  fn take_lane(stream: ByteStream, pos: G, first_pad: G) -> ([U8; 8], ByteStream, G) {
    let (b0, st, fp) = take_byte(stream, pos, first_pad);
    let (b1, st, fp) = take_byte(st, pos + 1, fp);
    let (b2, st, fp) = take_byte(st, pos + 2, fp);
    let (b3, st, fp) = take_byte(st, pos + 3, fp);
    let (b4, st, fp) = take_byte(st, pos + 4, fp);
    let (b5, st, fp) = take_byte(st, pos + 5, fp);
    let (b6, st, fp) = take_byte(st, pos + 6, fp);
    let (b7, st, fp) = take_byte(st, pos + 7, fp);
    ([b0, b1, b2, b3, b4, b5, b6, b7], st, fp)
  }

  -- Absorb one 136-byte rate block (17 lanes) directly from the stream
  -- into the state, permute, and recurse while whole real blocks keep
  -- filling (first_pad still 1 after 136 bytes). `first_pad` resets to 1
  -- per block: only a fully-real block recurses, so a fresh block never
  -- starts mid-pad.
  fn absorb_blocks(stream: ByteStream, s: [[U8; 8]; 25]) -> [[U8; 8]; 25] {
    let (rl0, st, fp) = take_lane(stream, 0, 1);
    let (rl1, st, fp) = take_lane(st, 8, fp);
    let (rl2, st, fp) = take_lane(st, 16, fp);
    let (rl3, st, fp) = take_lane(st, 24, fp);
    let (rl4, st, fp) = take_lane(st, 32, fp);
    let (rl5, st, fp) = take_lane(st, 40, fp);
    let (rl6, st, fp) = take_lane(st, 48, fp);
    let (rl7, st, fp) = take_lane(st, 56, fp);
    let (rl8, st, fp) = take_lane(st, 64, fp);
    let (rl9, st, fp) = take_lane(st, 72, fp);
    let (rl10, st, fp) = take_lane(st, 80, fp);
    let (rl11, st, fp) = take_lane(st, 88, fp);
    let (rl12, st, fp) = take_lane(st, 96, fp);
    let (rl13, st, fp) = take_lane(st, 104, fp);
    let (rl14, st, fp) = take_lane(st, 112, fp);
    let (rl15, st, fp) = take_lane(st, 120, fp);
    let (rl16, st, fp) = take_lane(st, 128, fp);
    let s = set(s, 0, [u8_xor(s[0][0], rl0[0]), u8_xor(s[0][1], rl0[1]), u8_xor(s[0][2], rl0[2]), u8_xor(s[0][3], rl0[3]), u8_xor(s[0][4], rl0[4]), u8_xor(s[0][5], rl0[5]), u8_xor(s[0][6], rl0[6]), u8_xor(s[0][7], rl0[7])]);
    let s = set(s, 1, [u8_xor(s[1][0], rl1[0]), u8_xor(s[1][1], rl1[1]), u8_xor(s[1][2], rl1[2]), u8_xor(s[1][3], rl1[3]), u8_xor(s[1][4], rl1[4]), u8_xor(s[1][5], rl1[5]), u8_xor(s[1][6], rl1[6]), u8_xor(s[1][7], rl1[7])]);
    let s = set(s, 2, [u8_xor(s[2][0], rl2[0]), u8_xor(s[2][1], rl2[1]), u8_xor(s[2][2], rl2[2]), u8_xor(s[2][3], rl2[3]), u8_xor(s[2][4], rl2[4]), u8_xor(s[2][5], rl2[5]), u8_xor(s[2][6], rl2[6]), u8_xor(s[2][7], rl2[7])]);
    let s = set(s, 3, [u8_xor(s[3][0], rl3[0]), u8_xor(s[3][1], rl3[1]), u8_xor(s[3][2], rl3[2]), u8_xor(s[3][3], rl3[3]), u8_xor(s[3][4], rl3[4]), u8_xor(s[3][5], rl3[5]), u8_xor(s[3][6], rl3[6]), u8_xor(s[3][7], rl3[7])]);
    let s = set(s, 4, [u8_xor(s[4][0], rl4[0]), u8_xor(s[4][1], rl4[1]), u8_xor(s[4][2], rl4[2]), u8_xor(s[4][3], rl4[3]), u8_xor(s[4][4], rl4[4]), u8_xor(s[4][5], rl4[5]), u8_xor(s[4][6], rl4[6]), u8_xor(s[4][7], rl4[7])]);
    let s = set(s, 5, [u8_xor(s[5][0], rl5[0]), u8_xor(s[5][1], rl5[1]), u8_xor(s[5][2], rl5[2]), u8_xor(s[5][3], rl5[3]), u8_xor(s[5][4], rl5[4]), u8_xor(s[5][5], rl5[5]), u8_xor(s[5][6], rl5[6]), u8_xor(s[5][7], rl5[7])]);
    let s = set(s, 6, [u8_xor(s[6][0], rl6[0]), u8_xor(s[6][1], rl6[1]), u8_xor(s[6][2], rl6[2]), u8_xor(s[6][3], rl6[3]), u8_xor(s[6][4], rl6[4]), u8_xor(s[6][5], rl6[5]), u8_xor(s[6][6], rl6[6]), u8_xor(s[6][7], rl6[7])]);
    let s = set(s, 7, [u8_xor(s[7][0], rl7[0]), u8_xor(s[7][1], rl7[1]), u8_xor(s[7][2], rl7[2]), u8_xor(s[7][3], rl7[3]), u8_xor(s[7][4], rl7[4]), u8_xor(s[7][5], rl7[5]), u8_xor(s[7][6], rl7[6]), u8_xor(s[7][7], rl7[7])]);
    let s = set(s, 8, [u8_xor(s[8][0], rl8[0]), u8_xor(s[8][1], rl8[1]), u8_xor(s[8][2], rl8[2]), u8_xor(s[8][3], rl8[3]), u8_xor(s[8][4], rl8[4]), u8_xor(s[8][5], rl8[5]), u8_xor(s[8][6], rl8[6]), u8_xor(s[8][7], rl8[7])]);
    let s = set(s, 9, [u8_xor(s[9][0], rl9[0]), u8_xor(s[9][1], rl9[1]), u8_xor(s[9][2], rl9[2]), u8_xor(s[9][3], rl9[3]), u8_xor(s[9][4], rl9[4]), u8_xor(s[9][5], rl9[5]), u8_xor(s[9][6], rl9[6]), u8_xor(s[9][7], rl9[7])]);
    let s = set(s, 10, [u8_xor(s[10][0], rl10[0]), u8_xor(s[10][1], rl10[1]), u8_xor(s[10][2], rl10[2]), u8_xor(s[10][3], rl10[3]), u8_xor(s[10][4], rl10[4]), u8_xor(s[10][5], rl10[5]), u8_xor(s[10][6], rl10[6]), u8_xor(s[10][7], rl10[7])]);
    let s = set(s, 11, [u8_xor(s[11][0], rl11[0]), u8_xor(s[11][1], rl11[1]), u8_xor(s[11][2], rl11[2]), u8_xor(s[11][3], rl11[3]), u8_xor(s[11][4], rl11[4]), u8_xor(s[11][5], rl11[5]), u8_xor(s[11][6], rl11[6]), u8_xor(s[11][7], rl11[7])]);
    let s = set(s, 12, [u8_xor(s[12][0], rl12[0]), u8_xor(s[12][1], rl12[1]), u8_xor(s[12][2], rl12[2]), u8_xor(s[12][3], rl12[3]), u8_xor(s[12][4], rl12[4]), u8_xor(s[12][5], rl12[5]), u8_xor(s[12][6], rl12[6]), u8_xor(s[12][7], rl12[7])]);
    let s = set(s, 13, [u8_xor(s[13][0], rl13[0]), u8_xor(s[13][1], rl13[1]), u8_xor(s[13][2], rl13[2]), u8_xor(s[13][3], rl13[3]), u8_xor(s[13][4], rl13[4]), u8_xor(s[13][5], rl13[5]), u8_xor(s[13][6], rl13[6]), u8_xor(s[13][7], rl13[7])]);
    let s = set(s, 14, [u8_xor(s[14][0], rl14[0]), u8_xor(s[14][1], rl14[1]), u8_xor(s[14][2], rl14[2]), u8_xor(s[14][3], rl14[3]), u8_xor(s[14][4], rl14[4]), u8_xor(s[14][5], rl14[5]), u8_xor(s[14][6], rl14[6]), u8_xor(s[14][7], rl14[7])]);
    let s = set(s, 15, [u8_xor(s[15][0], rl15[0]), u8_xor(s[15][1], rl15[1]), u8_xor(s[15][2], rl15[2]), u8_xor(s[15][3], rl15[3]), u8_xor(s[15][4], rl15[4]), u8_xor(s[15][5], rl15[5]), u8_xor(s[15][6], rl15[6]), u8_xor(s[15][7], rl15[7])]);
    let s = set(s, 16, [u8_xor(s[16][0], rl16[0]), u8_xor(s[16][1], rl16[1]), u8_xor(s[16][2], rl16[2]), u8_xor(s[16][3], rl16[3]), u8_xor(s[16][4], rl16[4]), u8_xor(s[16][5], rl16[5]), u8_xor(s[16][6], rl16[6]), u8_xor(s[16][7], rl16[7])]);
    let s2 = keccak_f(s);
    match fp {
      1 => absorb_blocks(st, s2),
      _ => s2,
    }
  }

  -- keccak-256: absorb into the zero state, squeeze lanes 0..3.
  fn keccak256(bytes: ByteStream) -> [[U8; 8]; 4] {
    let s = absorb_blocks(bytes, [[0u8; 8]; 25]);
    [s[0], s[1], s[2], s[3]]
  }

  /- # Byte-op helpers (all `@`-inlined into keccak_round). -/

  -- Bytewise XOR / AND of two lanes.
  fn xor8(a: [U8; 8], b: [U8; 8]) -> [U8; 8] {
    [u8_xor(a[0], b[0]), u8_xor(a[1], b[1]), u8_xor(a[2], b[2]), u8_xor(a[3], b[3]), u8_xor(a[4], b[4]), u8_xor(a[5], b[5]), u8_xor(a[6], b[6]), u8_xor(a[7], b[7])]
  }

  fn and8(a: [U8; 8], b: [U8; 8]) -> [U8; 8] {
    [u8_and(a[0], b[0]), u8_and(a[1], b[1]), u8_and(a[2], b[2]), u8_and(a[3], b[3]), u8_and(a[4], b[4]), u8_and(a[5], b[5]), u8_and(a[6], b[6]), u8_and(a[7], b[7])]
  }

  -- Bitwise NOT as the free recomposition 255 - b.
  fn not8(a: [U8; 8]) -> [U8; 8] {
    [u8_from_field_unsafe(255 - to_field(a[0])), u8_from_field_unsafe(255 - to_field(a[1])), u8_from_field_unsafe(255 - to_field(a[2])), u8_from_field_unsafe(255 - to_field(a[3])), u8_from_field_unsafe(255 - to_field(a[4])), u8_from_field_unsafe(255 - to_field(a[5])), u8_from_field_unsafe(255 - to_field(a[6])), u8_from_field_unsafe(255 - to_field(a[7]))]
  }

  -- chi lane: b0 ^ (~b1 & b2).
  fn chi_lane(b0: [U8; 8], b1: [U8; 8], b2: [U8; 8]) -> [U8; 8] {
    @xor8(b0, @and8(@not8(b1), b2))
  }

  -- theta's rotl-by-1 of a column parity, via the u8_add doubling trick:
  -- (b + b) = (2b mod 256, msb); the even low byte absorbs the neighbor's
  -- msb through a free field add.
  fn rotl1(l: [U8; 8]) -> [U8; 8] {
    let (a0, m0) = u8_add(l[0], l[0]);
    let (a1, m1) = u8_add(l[1], l[1]);
    let (a2, m2) = u8_add(l[2], l[2]);
    let (a3, m3) = u8_add(l[3], l[3]);
    let (a4, m4) = u8_add(l[4], l[4]);
    let (a5, m5) = u8_add(l[5], l[5]);
    let (a6, m6) = u8_add(l[6], l[6]);
    let (a7, m7) = u8_add(l[7], l[7]);
    [u8_from_field_unsafe(to_field(a0) + to_field(m7)), u8_from_field_unsafe(to_field(a1) + to_field(m0)), u8_from_field_unsafe(to_field(a2) + to_field(m1)), u8_from_field_unsafe(to_field(a3) + to_field(m2)), u8_from_field_unsafe(to_field(a4) + to_field(m3)), u8_from_field_unsafe(to_field(a5) + to_field(m4)), u8_from_field_unsafe(to_field(a6) + to_field(m5)), u8_from_field_unsafe(to_field(a7) + to_field(m6))]
  }

  /- # rho rotations: one `rotl_N` per distinct offset (bit recomposition;
     multiples of 8 are byte shuffles, others chain the u8_add / u8_shift
     tricks). All `@`-inlined. -/

  fn rotl_1(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[0], l[0]);
    let (a0_1, c0_1) = u8_add(l[1], l[1]);
    let (a0_2, c0_2) = u8_add(l[2], l[2]);
    let (a0_3, c0_3) = u8_add(l[3], l[3]);
    let (a0_4, c0_4) = u8_add(l[4], l[4]);
    let (a0_5, c0_5) = u8_add(l[5], l[5]);
    let (a0_6, c0_6) = u8_add(l[6], l[6]);
    let (a0_7, c0_7) = u8_add(l[7], l[7]);
    [u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6))]
  }

  fn rotl_2(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[0], l[0]);
    let (a0_1, c0_1) = u8_add(l[1], l[1]);
    let (a0_2, c0_2) = u8_add(l[2], l[2]);
    let (a0_3, c0_3) = u8_add(l[3], l[3]);
    let (a0_4, c0_4) = u8_add(l[4], l[4]);
    let (a0_5, c0_5) = u8_add(l[5], l[5]);
    let (a0_6, c0_6) = u8_add(l[6], l[6]);
    let (a0_7, c0_7) = u8_add(l[7], l[7]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    [u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6))]
  }

  fn rotl_3(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[0], l[0]);
    let (a0_1, c0_1) = u8_add(l[1], l[1]);
    let (a0_2, c0_2) = u8_add(l[2], l[2]);
    let (a0_3, c0_3) = u8_add(l[3], l[3]);
    let (a0_4, c0_4) = u8_add(l[4], l[4]);
    let (a0_5, c0_5) = u8_add(l[5], l[5]);
    let (a0_6, c0_6) = u8_add(l[6], l[6]);
    let (a0_7, c0_7) = u8_add(l[7], l[7]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    let (a2_0, c2_0) = u8_add(u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)));
    let (a2_1, c2_1) = u8_add(u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)));
    let (a2_2, c2_2) = u8_add(u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)));
    let (a2_3, c2_3) = u8_add(u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)));
    let (a2_4, c2_4) = u8_add(u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)));
    let (a2_5, c2_5) = u8_add(u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)));
    let (a2_6, c2_6) = u8_add(u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)));
    let (a2_7, c2_7) = u8_add(u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)));
    [u8_from_field_unsafe(to_field(a2_0) + to_field(c2_7)), u8_from_field_unsafe(to_field(a2_1) + to_field(c2_0)), u8_from_field_unsafe(to_field(a2_2) + to_field(c2_1)), u8_from_field_unsafe(to_field(a2_3) + to_field(c2_2)), u8_from_field_unsafe(to_field(a2_4) + to_field(c2_3)), u8_from_field_unsafe(to_field(a2_5) + to_field(c2_4)), u8_from_field_unsafe(to_field(a2_6) + to_field(c2_5)), u8_from_field_unsafe(to_field(a2_7) + to_field(c2_6))]
  }

  fn rotl_6(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[7]);
    let h0_1 = u8_shift_right(l[0]);
    let h0_2 = u8_shift_right(l[1]);
    let h0_3 = u8_shift_right(l[2]);
    let h0_4 = u8_shift_right(l[3]);
    let h0_5 = u8_shift_right(l[4]);
    let h0_6 = u8_shift_right(l[5]);
    let h0_7 = u8_shift_right(l[6]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[0]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[1]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[2]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[3]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[4]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[5]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[6]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[7]) - 2 * to_field(h0_0))));
    [u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[1]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))), u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[2]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))), u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[3]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))), u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[4]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))), u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[5]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))), u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[6]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))), u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[7]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))), u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[0]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))]
  }

  fn rotl_8(l: [U8; 8]) -> [U8; 8] {
    [l[7], l[0], l[1], l[2], l[3], l[4], l[5], l[6]]
  }

  fn rotl_10(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[7], l[7]);
    let (a0_1, c0_1) = u8_add(l[0], l[0]);
    let (a0_2, c0_2) = u8_add(l[1], l[1]);
    let (a0_3, c0_3) = u8_add(l[2], l[2]);
    let (a0_4, c0_4) = u8_add(l[3], l[3]);
    let (a0_5, c0_5) = u8_add(l[4], l[4]);
    let (a0_6, c0_6) = u8_add(l[5], l[5]);
    let (a0_7, c0_7) = u8_add(l[6], l[6]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    [u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6))]
  }

  fn rotl_14(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[6]);
    let h0_1 = u8_shift_right(l[7]);
    let h0_2 = u8_shift_right(l[0]);
    let h0_3 = u8_shift_right(l[1]);
    let h0_4 = u8_shift_right(l[2]);
    let h0_5 = u8_shift_right(l[3]);
    let h0_6 = u8_shift_right(l[4]);
    let h0_7 = u8_shift_right(l[5]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[7]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[0]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[1]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[2]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[3]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[4]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[5]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[6]) - 2 * to_field(h0_0))));
    [u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[0]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))), u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[1]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))), u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[2]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))), u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[3]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))), u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[4]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))), u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[5]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))), u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[6]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))), u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[7]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))]
  }

  fn rotl_15(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[6]);
    let h0_1 = u8_shift_right(l[7]);
    let h0_2 = u8_shift_right(l[0]);
    let h0_3 = u8_shift_right(l[1]);
    let h0_4 = u8_shift_right(l[2]);
    let h0_5 = u8_shift_right(l[3]);
    let h0_6 = u8_shift_right(l[4]);
    let h0_7 = u8_shift_right(l[5]);
    [u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[7]) - 2 * to_field(h0_1))), u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[0]) - 2 * to_field(h0_2))), u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[1]) - 2 * to_field(h0_3))), u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[2]) - 2 * to_field(h0_4))), u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[3]) - 2 * to_field(h0_5))), u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[4]) - 2 * to_field(h0_6))), u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[5]) - 2 * to_field(h0_7))), u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[6]) - 2 * to_field(h0_0)))]
  }

  fn rotl_18(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[6], l[6]);
    let (a0_1, c0_1) = u8_add(l[7], l[7]);
    let (a0_2, c0_2) = u8_add(l[0], l[0]);
    let (a0_3, c0_3) = u8_add(l[1], l[1]);
    let (a0_4, c0_4) = u8_add(l[2], l[2]);
    let (a0_5, c0_5) = u8_add(l[3], l[3]);
    let (a0_6, c0_6) = u8_add(l[4], l[4]);
    let (a0_7, c0_7) = u8_add(l[5], l[5]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    [u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6))]
  }

  fn rotl_20(l: [U8; 8]) -> [U8; 8] {
    let d0 = u8_bit_decomposition(l[0]);
    let d1 = u8_bit_decomposition(l[1]);
    let d2 = u8_bit_decomposition(l[2]);
    let d3 = u8_bit_decomposition(l[3]);
    let d4 = u8_bit_decomposition(l[4]);
    let d5 = u8_bit_decomposition(l[5]);
    let d6 = u8_bit_decomposition(l[6]);
    let d7 = u8_bit_decomposition(l[7]);
    [u8_from_field_unsafe(d5[4] + 2 * d5[5] + 4 * d5[6] + 8 * d5[7] + 16 * d6[0] + 32 * d6[1] + 64 * d6[2] + 128 * d6[3]), u8_from_field_unsafe(d6[4] + 2 * d6[5] + 4 * d6[6] + 8 * d6[7] + 16 * d7[0] + 32 * d7[1] + 64 * d7[2] + 128 * d7[3]), u8_from_field_unsafe(d7[4] + 2 * d7[5] + 4 * d7[6] + 8 * d7[7] + 16 * d0[0] + 32 * d0[1] + 64 * d0[2] + 128 * d0[3]), u8_from_field_unsafe(d0[4] + 2 * d0[5] + 4 * d0[6] + 8 * d0[7] + 16 * d1[0] + 32 * d1[1] + 64 * d1[2] + 128 * d1[3]), u8_from_field_unsafe(d1[4] + 2 * d1[5] + 4 * d1[6] + 8 * d1[7] + 16 * d2[0] + 32 * d2[1] + 64 * d2[2] + 128 * d2[3]), u8_from_field_unsafe(d2[4] + 2 * d2[5] + 4 * d2[6] + 8 * d2[7] + 16 * d3[0] + 32 * d3[1] + 64 * d3[2] + 128 * d3[3]), u8_from_field_unsafe(d3[4] + 2 * d3[5] + 4 * d3[6] + 8 * d3[7] + 16 * d4[0] + 32 * d4[1] + 64 * d4[2] + 128 * d4[3]), u8_from_field_unsafe(d4[4] + 2 * d4[5] + 4 * d4[6] + 8 * d4[7] + 16 * d5[0] + 32 * d5[1] + 64 * d5[2] + 128 * d5[3])]
  }

  fn rotl_21(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[5]);
    let h0_1 = u8_shift_right(l[6]);
    let h0_2 = u8_shift_right(l[7]);
    let h0_3 = u8_shift_right(l[0]);
    let h0_4 = u8_shift_right(l[1]);
    let h0_5 = u8_shift_right(l[2]);
    let h0_6 = u8_shift_right(l[3]);
    let h0_7 = u8_shift_right(l[4]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[6]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[7]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[0]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[1]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[2]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[3]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[4]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[5]) - 2 * to_field(h0_0))));
    let h2_0 = u8_shift_right(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[7]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))));
    let h2_1 = u8_shift_right(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[0]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))));
    let h2_2 = u8_shift_right(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[1]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))));
    let h2_3 = u8_shift_right(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[2]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))));
    let h2_4 = u8_shift_right(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[3]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))));
    let h2_5 = u8_shift_right(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[4]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))));
    let h2_6 = u8_shift_right(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[5]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))));
    let h2_7 = u8_shift_right(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[6]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0))));
    [u8_from_field_unsafe(to_field(h2_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[0]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2)))) - 2 * to_field(h2_1))), u8_from_field_unsafe(to_field(h2_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[1]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3)))) - 2 * to_field(h2_2))), u8_from_field_unsafe(to_field(h2_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[2]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4)))) - 2 * to_field(h2_3))), u8_from_field_unsafe(to_field(h2_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[3]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5)))) - 2 * to_field(h2_4))), u8_from_field_unsafe(to_field(h2_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[4]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6)))) - 2 * to_field(h2_5))), u8_from_field_unsafe(to_field(h2_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[5]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7)))) - 2 * to_field(h2_6))), u8_from_field_unsafe(to_field(h2_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[6]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))) - 2 * to_field(h2_7))), u8_from_field_unsafe(to_field(h2_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[7]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1)))) - 2 * to_field(h2_0)))]
  }

  fn rotl_25(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[5], l[5]);
    let (a0_1, c0_1) = u8_add(l[6], l[6]);
    let (a0_2, c0_2) = u8_add(l[7], l[7]);
    let (a0_3, c0_3) = u8_add(l[0], l[0]);
    let (a0_4, c0_4) = u8_add(l[1], l[1]);
    let (a0_5, c0_5) = u8_add(l[2], l[2]);
    let (a0_6, c0_6) = u8_add(l[3], l[3]);
    let (a0_7, c0_7) = u8_add(l[4], l[4]);
    [u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6))]
  }

  fn rotl_27(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[5], l[5]);
    let (a0_1, c0_1) = u8_add(l[6], l[6]);
    let (a0_2, c0_2) = u8_add(l[7], l[7]);
    let (a0_3, c0_3) = u8_add(l[0], l[0]);
    let (a0_4, c0_4) = u8_add(l[1], l[1]);
    let (a0_5, c0_5) = u8_add(l[2], l[2]);
    let (a0_6, c0_6) = u8_add(l[3], l[3]);
    let (a0_7, c0_7) = u8_add(l[4], l[4]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    let (a2_0, c2_0) = u8_add(u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)));
    let (a2_1, c2_1) = u8_add(u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)));
    let (a2_2, c2_2) = u8_add(u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)));
    let (a2_3, c2_3) = u8_add(u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)));
    let (a2_4, c2_4) = u8_add(u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)));
    let (a2_5, c2_5) = u8_add(u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)));
    let (a2_6, c2_6) = u8_add(u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)));
    let (a2_7, c2_7) = u8_add(u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)));
    [u8_from_field_unsafe(to_field(a2_0) + to_field(c2_7)), u8_from_field_unsafe(to_field(a2_1) + to_field(c2_0)), u8_from_field_unsafe(to_field(a2_2) + to_field(c2_1)), u8_from_field_unsafe(to_field(a2_3) + to_field(c2_2)), u8_from_field_unsafe(to_field(a2_4) + to_field(c2_3)), u8_from_field_unsafe(to_field(a2_5) + to_field(c2_4)), u8_from_field_unsafe(to_field(a2_6) + to_field(c2_5)), u8_from_field_unsafe(to_field(a2_7) + to_field(c2_6))]
  }

  fn rotl_28(l: [U8; 8]) -> [U8; 8] {
    let d0 = u8_bit_decomposition(l[0]);
    let d1 = u8_bit_decomposition(l[1]);
    let d2 = u8_bit_decomposition(l[2]);
    let d3 = u8_bit_decomposition(l[3]);
    let d4 = u8_bit_decomposition(l[4]);
    let d5 = u8_bit_decomposition(l[5]);
    let d6 = u8_bit_decomposition(l[6]);
    let d7 = u8_bit_decomposition(l[7]);
    [u8_from_field_unsafe(d4[4] + 2 * d4[5] + 4 * d4[6] + 8 * d4[7] + 16 * d5[0] + 32 * d5[1] + 64 * d5[2] + 128 * d5[3]), u8_from_field_unsafe(d5[4] + 2 * d5[5] + 4 * d5[6] + 8 * d5[7] + 16 * d6[0] + 32 * d6[1] + 64 * d6[2] + 128 * d6[3]), u8_from_field_unsafe(d6[4] + 2 * d6[5] + 4 * d6[6] + 8 * d6[7] + 16 * d7[0] + 32 * d7[1] + 64 * d7[2] + 128 * d7[3]), u8_from_field_unsafe(d7[4] + 2 * d7[5] + 4 * d7[6] + 8 * d7[7] + 16 * d0[0] + 32 * d0[1] + 64 * d0[2] + 128 * d0[3]), u8_from_field_unsafe(d0[4] + 2 * d0[5] + 4 * d0[6] + 8 * d0[7] + 16 * d1[0] + 32 * d1[1] + 64 * d1[2] + 128 * d1[3]), u8_from_field_unsafe(d1[4] + 2 * d1[5] + 4 * d1[6] + 8 * d1[7] + 16 * d2[0] + 32 * d2[1] + 64 * d2[2] + 128 * d2[3]), u8_from_field_unsafe(d2[4] + 2 * d2[5] + 4 * d2[6] + 8 * d2[7] + 16 * d3[0] + 32 * d3[1] + 64 * d3[2] + 128 * d3[3]), u8_from_field_unsafe(d3[4] + 2 * d3[5] + 4 * d3[6] + 8 * d3[7] + 16 * d4[0] + 32 * d4[1] + 64 * d4[2] + 128 * d4[3])]
  }

  fn rotl_36(l: [U8; 8]) -> [U8; 8] {
    let d0 = u8_bit_decomposition(l[0]);
    let d1 = u8_bit_decomposition(l[1]);
    let d2 = u8_bit_decomposition(l[2]);
    let d3 = u8_bit_decomposition(l[3]);
    let d4 = u8_bit_decomposition(l[4]);
    let d5 = u8_bit_decomposition(l[5]);
    let d6 = u8_bit_decomposition(l[6]);
    let d7 = u8_bit_decomposition(l[7]);
    [u8_from_field_unsafe(d3[4] + 2 * d3[5] + 4 * d3[6] + 8 * d3[7] + 16 * d4[0] + 32 * d4[1] + 64 * d4[2] + 128 * d4[3]), u8_from_field_unsafe(d4[4] + 2 * d4[5] + 4 * d4[6] + 8 * d4[7] + 16 * d5[0] + 32 * d5[1] + 64 * d5[2] + 128 * d5[3]), u8_from_field_unsafe(d5[4] + 2 * d5[5] + 4 * d5[6] + 8 * d5[7] + 16 * d6[0] + 32 * d6[1] + 64 * d6[2] + 128 * d6[3]), u8_from_field_unsafe(d6[4] + 2 * d6[5] + 4 * d6[6] + 8 * d6[7] + 16 * d7[0] + 32 * d7[1] + 64 * d7[2] + 128 * d7[3]), u8_from_field_unsafe(d7[4] + 2 * d7[5] + 4 * d7[6] + 8 * d7[7] + 16 * d0[0] + 32 * d0[1] + 64 * d0[2] + 128 * d0[3]), u8_from_field_unsafe(d0[4] + 2 * d0[5] + 4 * d0[6] + 8 * d0[7] + 16 * d1[0] + 32 * d1[1] + 64 * d1[2] + 128 * d1[3]), u8_from_field_unsafe(d1[4] + 2 * d1[5] + 4 * d1[6] + 8 * d1[7] + 16 * d2[0] + 32 * d2[1] + 64 * d2[2] + 128 * d2[3]), u8_from_field_unsafe(d2[4] + 2 * d2[5] + 4 * d2[6] + 8 * d2[7] + 16 * d3[0] + 32 * d3[1] + 64 * d3[2] + 128 * d3[3])]
  }

  fn rotl_39(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[3]);
    let h0_1 = u8_shift_right(l[4]);
    let h0_2 = u8_shift_right(l[5]);
    let h0_3 = u8_shift_right(l[6]);
    let h0_4 = u8_shift_right(l[7]);
    let h0_5 = u8_shift_right(l[0]);
    let h0_6 = u8_shift_right(l[1]);
    let h0_7 = u8_shift_right(l[2]);
    [u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[4]) - 2 * to_field(h0_1))), u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[5]) - 2 * to_field(h0_2))), u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[6]) - 2 * to_field(h0_3))), u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[7]) - 2 * to_field(h0_4))), u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[0]) - 2 * to_field(h0_5))), u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[1]) - 2 * to_field(h0_6))), u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[2]) - 2 * to_field(h0_7))), u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[3]) - 2 * to_field(h0_0)))]
  }

  fn rotl_41(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[3], l[3]);
    let (a0_1, c0_1) = u8_add(l[4], l[4]);
    let (a0_2, c0_2) = u8_add(l[5], l[5]);
    let (a0_3, c0_3) = u8_add(l[6], l[6]);
    let (a0_4, c0_4) = u8_add(l[7], l[7]);
    let (a0_5, c0_5) = u8_add(l[0], l[0]);
    let (a0_6, c0_6) = u8_add(l[1], l[1]);
    let (a0_7, c0_7) = u8_add(l[2], l[2]);
    [u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6))]
  }

  fn rotl_43(l: [U8; 8]) -> [U8; 8] {
    let (a0_0, c0_0) = u8_add(l[3], l[3]);
    let (a0_1, c0_1) = u8_add(l[4], l[4]);
    let (a0_2, c0_2) = u8_add(l[5], l[5]);
    let (a0_3, c0_3) = u8_add(l[6], l[6]);
    let (a0_4, c0_4) = u8_add(l[7], l[7]);
    let (a0_5, c0_5) = u8_add(l[0], l[0]);
    let (a0_6, c0_6) = u8_add(l[1], l[1]);
    let (a0_7, c0_7) = u8_add(l[2], l[2]);
    let (a1_0, c1_0) = u8_add(u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)), u8_from_field_unsafe(to_field(a0_0) + to_field(c0_7)));
    let (a1_1, c1_1) = u8_add(u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)), u8_from_field_unsafe(to_field(a0_1) + to_field(c0_0)));
    let (a1_2, c1_2) = u8_add(u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)), u8_from_field_unsafe(to_field(a0_2) + to_field(c0_1)));
    let (a1_3, c1_3) = u8_add(u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)), u8_from_field_unsafe(to_field(a0_3) + to_field(c0_2)));
    let (a1_4, c1_4) = u8_add(u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)), u8_from_field_unsafe(to_field(a0_4) + to_field(c0_3)));
    let (a1_5, c1_5) = u8_add(u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)), u8_from_field_unsafe(to_field(a0_5) + to_field(c0_4)));
    let (a1_6, c1_6) = u8_add(u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)), u8_from_field_unsafe(to_field(a0_6) + to_field(c0_5)));
    let (a1_7, c1_7) = u8_add(u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)), u8_from_field_unsafe(to_field(a0_7) + to_field(c0_6)));
    let (a2_0, c2_0) = u8_add(u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)), u8_from_field_unsafe(to_field(a1_0) + to_field(c1_7)));
    let (a2_1, c2_1) = u8_add(u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)), u8_from_field_unsafe(to_field(a1_1) + to_field(c1_0)));
    let (a2_2, c2_2) = u8_add(u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)), u8_from_field_unsafe(to_field(a1_2) + to_field(c1_1)));
    let (a2_3, c2_3) = u8_add(u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)), u8_from_field_unsafe(to_field(a1_3) + to_field(c1_2)));
    let (a2_4, c2_4) = u8_add(u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)), u8_from_field_unsafe(to_field(a1_4) + to_field(c1_3)));
    let (a2_5, c2_5) = u8_add(u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)), u8_from_field_unsafe(to_field(a1_5) + to_field(c1_4)));
    let (a2_6, c2_6) = u8_add(u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)), u8_from_field_unsafe(to_field(a1_6) + to_field(c1_5)));
    let (a2_7, c2_7) = u8_add(u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)), u8_from_field_unsafe(to_field(a1_7) + to_field(c1_6)));
    [u8_from_field_unsafe(to_field(a2_0) + to_field(c2_7)), u8_from_field_unsafe(to_field(a2_1) + to_field(c2_0)), u8_from_field_unsafe(to_field(a2_2) + to_field(c2_1)), u8_from_field_unsafe(to_field(a2_3) + to_field(c2_2)), u8_from_field_unsafe(to_field(a2_4) + to_field(c2_3)), u8_from_field_unsafe(to_field(a2_5) + to_field(c2_4)), u8_from_field_unsafe(to_field(a2_6) + to_field(c2_5)), u8_from_field_unsafe(to_field(a2_7) + to_field(c2_6))]
  }

  fn rotl_44(l: [U8; 8]) -> [U8; 8] {
    let d0 = u8_bit_decomposition(l[0]);
    let d1 = u8_bit_decomposition(l[1]);
    let d2 = u8_bit_decomposition(l[2]);
    let d3 = u8_bit_decomposition(l[3]);
    let d4 = u8_bit_decomposition(l[4]);
    let d5 = u8_bit_decomposition(l[5]);
    let d6 = u8_bit_decomposition(l[6]);
    let d7 = u8_bit_decomposition(l[7]);
    [u8_from_field_unsafe(d2[4] + 2 * d2[5] + 4 * d2[6] + 8 * d2[7] + 16 * d3[0] + 32 * d3[1] + 64 * d3[2] + 128 * d3[3]), u8_from_field_unsafe(d3[4] + 2 * d3[5] + 4 * d3[6] + 8 * d3[7] + 16 * d4[0] + 32 * d4[1] + 64 * d4[2] + 128 * d4[3]), u8_from_field_unsafe(d4[4] + 2 * d4[5] + 4 * d4[6] + 8 * d4[7] + 16 * d5[0] + 32 * d5[1] + 64 * d5[2] + 128 * d5[3]), u8_from_field_unsafe(d5[4] + 2 * d5[5] + 4 * d5[6] + 8 * d5[7] + 16 * d6[0] + 32 * d6[1] + 64 * d6[2] + 128 * d6[3]), u8_from_field_unsafe(d6[4] + 2 * d6[5] + 4 * d6[6] + 8 * d6[7] + 16 * d7[0] + 32 * d7[1] + 64 * d7[2] + 128 * d7[3]), u8_from_field_unsafe(d7[4] + 2 * d7[5] + 4 * d7[6] + 8 * d7[7] + 16 * d0[0] + 32 * d0[1] + 64 * d0[2] + 128 * d0[3]), u8_from_field_unsafe(d0[4] + 2 * d0[5] + 4 * d0[6] + 8 * d0[7] + 16 * d1[0] + 32 * d1[1] + 64 * d1[2] + 128 * d1[3]), u8_from_field_unsafe(d1[4] + 2 * d1[5] + 4 * d1[6] + 8 * d1[7] + 16 * d2[0] + 32 * d2[1] + 64 * d2[2] + 128 * d2[3])]
  }

  fn rotl_45(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[2]);
    let h0_1 = u8_shift_right(l[3]);
    let h0_2 = u8_shift_right(l[4]);
    let h0_3 = u8_shift_right(l[5]);
    let h0_4 = u8_shift_right(l[6]);
    let h0_5 = u8_shift_right(l[7]);
    let h0_6 = u8_shift_right(l[0]);
    let h0_7 = u8_shift_right(l[1]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[3]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[4]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[5]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[6]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[7]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[0]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[1]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[2]) - 2 * to_field(h0_0))));
    let h2_0 = u8_shift_right(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[4]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))));
    let h2_1 = u8_shift_right(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[5]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))));
    let h2_2 = u8_shift_right(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[6]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))));
    let h2_3 = u8_shift_right(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[7]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))));
    let h2_4 = u8_shift_right(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[0]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))));
    let h2_5 = u8_shift_right(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[1]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))));
    let h2_6 = u8_shift_right(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[2]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))));
    let h2_7 = u8_shift_right(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[3]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0))));
    [u8_from_field_unsafe(to_field(h2_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[5]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2)))) - 2 * to_field(h2_1))), u8_from_field_unsafe(to_field(h2_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[6]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3)))) - 2 * to_field(h2_2))), u8_from_field_unsafe(to_field(h2_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[7]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4)))) - 2 * to_field(h2_3))), u8_from_field_unsafe(to_field(h2_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[0]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5)))) - 2 * to_field(h2_4))), u8_from_field_unsafe(to_field(h2_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[1]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6)))) - 2 * to_field(h2_5))), u8_from_field_unsafe(to_field(h2_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[2]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7)))) - 2 * to_field(h2_6))), u8_from_field_unsafe(to_field(h2_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[3]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))) - 2 * to_field(h2_7))), u8_from_field_unsafe(to_field(h2_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[4]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1)))) - 2 * to_field(h2_0)))]
  }

  fn rotl_55(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[1]);
    let h0_1 = u8_shift_right(l[2]);
    let h0_2 = u8_shift_right(l[3]);
    let h0_3 = u8_shift_right(l[4]);
    let h0_4 = u8_shift_right(l[5]);
    let h0_5 = u8_shift_right(l[6]);
    let h0_6 = u8_shift_right(l[7]);
    let h0_7 = u8_shift_right(l[0]);
    [u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[2]) - 2 * to_field(h0_1))), u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[3]) - 2 * to_field(h0_2))), u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[4]) - 2 * to_field(h0_3))), u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[5]) - 2 * to_field(h0_4))), u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[6]) - 2 * to_field(h0_5))), u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[7]) - 2 * to_field(h0_6))), u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[0]) - 2 * to_field(h0_7))), u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[1]) - 2 * to_field(h0_0)))]
  }

  fn rotl_56(l: [U8; 8]) -> [U8; 8] {
    [l[1], l[2], l[3], l[4], l[5], l[6], l[7], l[0]]
  }

  fn rotl_61(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[0]);
    let h0_1 = u8_shift_right(l[1]);
    let h0_2 = u8_shift_right(l[2]);
    let h0_3 = u8_shift_right(l[3]);
    let h0_4 = u8_shift_right(l[4]);
    let h0_5 = u8_shift_right(l[5]);
    let h0_6 = u8_shift_right(l[6]);
    let h0_7 = u8_shift_right(l[7]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[1]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[2]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[3]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[4]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[5]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[6]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[7]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[0]) - 2 * to_field(h0_0))));
    let h2_0 = u8_shift_right(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[2]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))));
    let h2_1 = u8_shift_right(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[3]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))));
    let h2_2 = u8_shift_right(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[4]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))));
    let h2_3 = u8_shift_right(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[5]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))));
    let h2_4 = u8_shift_right(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[6]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))));
    let h2_5 = u8_shift_right(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[7]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))));
    let h2_6 = u8_shift_right(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[0]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))));
    let h2_7 = u8_shift_right(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[1]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0))));
    [u8_from_field_unsafe(to_field(h2_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[3]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2)))) - 2 * to_field(h2_1))), u8_from_field_unsafe(to_field(h2_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[4]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3)))) - 2 * to_field(h2_2))), u8_from_field_unsafe(to_field(h2_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[5]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4)))) - 2 * to_field(h2_3))), u8_from_field_unsafe(to_field(h2_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[6]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5)))) - 2 * to_field(h2_4))), u8_from_field_unsafe(to_field(h2_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[7]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6)))) - 2 * to_field(h2_5))), u8_from_field_unsafe(to_field(h2_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[0]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7)))) - 2 * to_field(h2_6))), u8_from_field_unsafe(to_field(h2_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[1]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))) - 2 * to_field(h2_7))), u8_from_field_unsafe(to_field(h2_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[2]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1)))) - 2 * to_field(h2_0)))]
  }

  fn rotl_62(l: [U8; 8]) -> [U8; 8] {
    let h0_0 = u8_shift_right(l[0]);
    let h0_1 = u8_shift_right(l[1]);
    let h0_2 = u8_shift_right(l[2]);
    let h0_3 = u8_shift_right(l[3]);
    let h0_4 = u8_shift_right(l[4]);
    let h0_5 = u8_shift_right(l[5]);
    let h0_6 = u8_shift_right(l[6]);
    let h0_7 = u8_shift_right(l[7]);
    let h1_0 = u8_shift_right(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[1]) - 2 * to_field(h0_1))));
    let h1_1 = u8_shift_right(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[2]) - 2 * to_field(h0_2))));
    let h1_2 = u8_shift_right(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[3]) - 2 * to_field(h0_3))));
    let h1_3 = u8_shift_right(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[4]) - 2 * to_field(h0_4))));
    let h1_4 = u8_shift_right(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[5]) - 2 * to_field(h0_5))));
    let h1_5 = u8_shift_right(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[6]) - 2 * to_field(h0_6))));
    let h1_6 = u8_shift_right(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[7]) - 2 * to_field(h0_7))));
    let h1_7 = u8_shift_right(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[0]) - 2 * to_field(h0_0))));
    [u8_from_field_unsafe(to_field(h1_0) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_1) + 128 * (to_field(l[2]) - 2 * to_field(h0_2)))) - 2 * to_field(h1_1))), u8_from_field_unsafe(to_field(h1_1) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_2) + 128 * (to_field(l[3]) - 2 * to_field(h0_3)))) - 2 * to_field(h1_2))), u8_from_field_unsafe(to_field(h1_2) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_3) + 128 * (to_field(l[4]) - 2 * to_field(h0_4)))) - 2 * to_field(h1_3))), u8_from_field_unsafe(to_field(h1_3) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_4) + 128 * (to_field(l[5]) - 2 * to_field(h0_5)))) - 2 * to_field(h1_4))), u8_from_field_unsafe(to_field(h1_4) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_5) + 128 * (to_field(l[6]) - 2 * to_field(h0_6)))) - 2 * to_field(h1_5))), u8_from_field_unsafe(to_field(h1_5) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_6) + 128 * (to_field(l[7]) - 2 * to_field(h0_7)))) - 2 * to_field(h1_6))), u8_from_field_unsafe(to_field(h1_6) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_7) + 128 * (to_field(l[0]) - 2 * to_field(h0_0)))) - 2 * to_field(h1_7))), u8_from_field_unsafe(to_field(h1_7) + 128 * (to_field(u8_from_field_unsafe(to_field(h0_0) + 128 * (to_field(l[1]) - 2 * to_field(h0_1)))) - 2 * to_field(h1_0)))]
  }

  /- # keccak-f[1600]: 24 rounds, each an inlined `@keccak_round` so all
     24 share one circuit (one row per permutation). -/

  fn keccak_f(s: [[U8; 8]; 25]) -> [[U8; 8]; 25] {
    let s = keccak_round(s, [0x01u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x82u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x8au8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x8bu8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x01u8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x81u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x09u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x8au8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x88u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x09u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x0au8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x8bu8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x8bu8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x89u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x03u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x02u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x0au8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]);
    let s = keccak_round(s, [0x0au8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x81u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x80u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8]);
    let s = keccak_round(s, [0x01u8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8]);
    keccak_round(s, [0x08u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8])
  }

  fn keccak_round(s: [[U8; 8]; 25], rc: [U8; 8]) -> [[U8; 8]; 25] {
    -- theta: column parities, then D[x] = C[x-1] ^ rotl1(C[x+1]).
    let c0 = @xor8(s[20], @xor8(s[15], @xor8(s[10], @xor8(s[5], s[0]))));
    let c1 = @xor8(s[21], @xor8(s[16], @xor8(s[11], @xor8(s[6], s[1]))));
    let c2 = @xor8(s[22], @xor8(s[17], @xor8(s[12], @xor8(s[7], s[2]))));
    let c3 = @xor8(s[23], @xor8(s[18], @xor8(s[13], @xor8(s[8], s[3]))));
    let c4 = @xor8(s[24], @xor8(s[19], @xor8(s[14], @xor8(s[9], s[4]))));
    let d0 = @xor8(c4, @rotl1(c1));
    let d1 = @xor8(c0, @rotl1(c2));
    let d2 = @xor8(c1, @rotl1(c3));
    let d3 = @xor8(c2, @rotl1(c4));
    let d4 = @xor8(c3, @rotl1(c0));
    let t0 = @xor8(s[0], d0);
    let t1 = @xor8(s[1], d1);
    let t2 = @xor8(s[2], d2);
    let t3 = @xor8(s[3], d3);
    let t4 = @xor8(s[4], d4);
    let t5 = @xor8(s[5], d0);
    let t6 = @xor8(s[6], d1);
    let t7 = @xor8(s[7], d2);
    let t8 = @xor8(s[8], d3);
    let t9 = @xor8(s[9], d4);
    let t10 = @xor8(s[10], d0);
    let t11 = @xor8(s[11], d1);
    let t12 = @xor8(s[12], d2);
    let t13 = @xor8(s[13], d3);
    let t14 = @xor8(s[14], d4);
    let t15 = @xor8(s[15], d0);
    let t16 = @xor8(s[16], d1);
    let t17 = @xor8(s[17], d2);
    let t18 = @xor8(s[18], d3);
    let t19 = @xor8(s[19], d4);
    let t20 = @xor8(s[20], d0);
    let t21 = @xor8(s[21], d1);
    let t22 = @xor8(s[22], d2);
    let t23 = @xor8(s[23], d3);
    let t24 = @xor8(s[24], d4);
    -- rho + pi: b[pi(src)] = rotl(t[src], rho(src)).
    let b0 = t0;
    let b10 = @rotl_1(t1);
    let b20 = @rotl_62(t2);
    let b5 = @rotl_28(t3);
    let b15 = @rotl_27(t4);
    let b16 = @rotl_36(t5);
    let b1 = @rotl_44(t6);
    let b11 = @rotl_6(t7);
    let b21 = @rotl_55(t8);
    let b6 = @rotl_20(t9);
    let b7 = @rotl_3(t10);
    let b17 = @rotl_10(t11);
    let b2 = @rotl_43(t12);
    let b12 = @rotl_25(t13);
    let b22 = @rotl_39(t14);
    let b23 = @rotl_41(t15);
    let b8 = @rotl_45(t16);
    let b18 = @rotl_15(t17);
    let b3 = @rotl_21(t18);
    let b13 = @rotl_8(t19);
    let b14 = @rotl_18(t20);
    let b24 = @rotl_2(t21);
    let b9 = @rotl_61(t22);
    let b19 = @rotl_56(t23);
    let b4 = @rotl_14(t24);
    -- chi.
    let e0 = @chi_lane(b0, b1, b2);
    let e1 = @chi_lane(b1, b2, b3);
    let e2 = @chi_lane(b2, b3, b4);
    let e3 = @chi_lane(b3, b4, b0);
    let e4 = @chi_lane(b4, b0, b1);
    let e5 = @chi_lane(b5, b6, b7);
    let e6 = @chi_lane(b6, b7, b8);
    let e7 = @chi_lane(b7, b8, b9);
    let e8 = @chi_lane(b8, b9, b5);
    let e9 = @chi_lane(b9, b5, b6);
    let e10 = @chi_lane(b10, b11, b12);
    let e11 = @chi_lane(b11, b12, b13);
    let e12 = @chi_lane(b12, b13, b14);
    let e13 = @chi_lane(b13, b14, b10);
    let e14 = @chi_lane(b14, b10, b11);
    let e15 = @chi_lane(b15, b16, b17);
    let e16 = @chi_lane(b16, b17, b18);
    let e17 = @chi_lane(b17, b18, b19);
    let e18 = @chi_lane(b18, b19, b15);
    let e19 = @chi_lane(b19, b15, b16);
    let e20 = @chi_lane(b20, b21, b22);
    let e21 = @chi_lane(b21, b22, b23);
    let e22 = @chi_lane(b22, b23, b24);
    let e23 = @chi_lane(b23, b24, b20);
    let e24 = @chi_lane(b24, b20, b21);
    -- iota.
    let f0 = @xor8(e0, rc);
    [f0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24]
  }
⟧

end IxVM

end
