module
public import Ix.Aiur.Meta

/-!
# Keccak-256 in Aiur (value-based, wide permutation circuit)

Same algorithm/variant as `Ix/MultiStark/Keccak.lean` (Ethereum keccak-256:
pad `10*1`, rate 136, capacity 512) but shaped for the FFT cost model
(width x height x log2(height)): lanes and the 25-lane state are plain
values (no pointers, no memory traffic), the 24 rounds unroll into ONE
permutation circuit via `fold` (one row per keccak-f call), and rotations
are static bit recompositions (decompose once, recompose at compile-time
offsets) instead of runtime bit lists. theta's rotl-by-1 skips
decomposition entirely: `u8_add(b, b)` yields `(2b mod 256, msb)` and the
even low byte absorbs the neighbor's carry with a free field add.

Generated by a script (rho+pi is 24 distinct static bit wirings); the
pi/rho wiring is asserted against the MultiStark listing at generation
time.
-/

public section

namespace IxVM

-- The unrolled 24-round permutation elaborates to one deeply nested let
-- chain; the default recursion budget is not enough.
set_option maxRecDepth 65536 in
def keccak := ⟦
  /- # Test entrypoints -/

  pub fn keccak256_test() -> [[U8; 8]; 4] {
    let (idx, len) = io_get_info(0, [0]);
    let byte_stream = #read_byte_stream(0, idx, len);
    keccak256(byte_stream)
  }

  /- # Benchmark entrypoints -/

  pub fn keccak256_bench(num_hashes: G) -> G {
    let num_hashes_pred = num_hashes - 1;
    let key = [num_hashes_pred];
    let (idx, len) = io_get_info(0, key);
    let byte_stream = #read_byte_stream(0, idx, len);
    keccak256(byte_stream);
    match num_hashes_pred {
      0 => 0,
      _ => keccak256_bench(num_hashes_pred),
    }
  }

  /- # Sponge -/

  -- Pad bytes for positions i..135 once the message is exhausted: `first`
  -- is 1 on the first pad position (0x01 bit), position 135 carries the
  -- 0x80 bit (0x81 when both land on 135).
  fn build_pad(i: G, first: G) -> ByteStream {
    match 136 - i {
      0 => store(ListNode.Nil),
      _ =>
        store(ListNode.Cons(u8_from_field_unsafe(first + 128 * eq_zero(135 - i)),
                            build_pad(i + 1, 0))),
    }
  }

  -- Take one 136-byte rate block from `stream` starting at position `i`.
  -- Returns (block, rest, full): full=1 iff 136 message bytes were consumed
  -- (padding not yet applied). An empty stream yields the all-padding block
  -- keccak appends when the message length is a multiple of 136.
  fn read_block(stream: ByteStream, i: G) -> (ByteStream, ByteStream, G) {
    match 136 - i {
      0 => (store(ListNode.Nil), stream, 1),
      _ => match load(stream) {
        ListNode.Cons(b, rest) =>
          let (blk, r, f) = read_block(rest, i + 1);
          (store(ListNode.Cons(b, blk)), r, f),
        ListNode.Nil => (build_pad(i, 1), store(ListNode.Nil), 0),
      },
    }
  }

  -- Extract lane bytes [b .. b+7] from the rate block (one `list_drop` to
  -- the first byte; the rest are successive tails).
  fn rate_lane(rate: ByteStream, b: G) -> [U8; 8] {
    let &ListNode.Cons(r0, t0) = list_drop(rate, b);
    let &ListNode.Cons(r1, t1) = t0;
    let &ListNode.Cons(r2, t2) = t1;
    let &ListNode.Cons(r3, t3) = t2;
    let &ListNode.Cons(r4, t4) = t3;
    let &ListNode.Cons(r5, t5) = t4;
    let &ListNode.Cons(r6, t6) = t5;
    let &ListNode.Cons(r7, _) = t6;
    [r0, r1, r2, r3, r4, r5, r6, r7]
  }

  -- XOR one 136-byte rate block into the first 17 lanes, then permute.
  fn absorb_one(s: [[U8; 8]; 25], rate: ByteStream) -> [[U8; 8]; 25] {
    let rl0 = rate_lane(rate, 0);
    let rl1 = rate_lane(rate, 8);
    let rl2 = rate_lane(rate, 16);
    let rl3 = rate_lane(rate, 24);
    let rl4 = rate_lane(rate, 32);
    let rl5 = rate_lane(rate, 40);
    let rl6 = rate_lane(rate, 48);
    let rl7 = rate_lane(rate, 56);
    let rl8 = rate_lane(rate, 64);
    let rl9 = rate_lane(rate, 72);
    let rl10 = rate_lane(rate, 80);
    let rl11 = rate_lane(rate, 88);
    let rl12 = rate_lane(rate, 96);
    let rl13 = rate_lane(rate, 104);
    let rl14 = rate_lane(rate, 112);
    let rl15 = rate_lane(rate, 120);
    let rl16 = rate_lane(rate, 128);
    let s = set(s, 0, [u8_xor(s[0][0], rl0[0]), u8_xor(s[0][1], rl0[1]), u8_xor(s[0][2], rl0[2]), u8_xor(s[0][3], rl0[3]), u8_xor(s[0][4], rl0[4]), u8_xor(s[0][5], rl0[5]), u8_xor(s[0][6], rl0[6]), u8_xor(s[0][7], rl0[7])]);
    let s = set(s, 1, [u8_xor(s[1][0], rl1[0]), u8_xor(s[1][1], rl1[1]), u8_xor(s[1][2], rl1[2]), u8_xor(s[1][3], rl1[3]), u8_xor(s[1][4], rl1[4]), u8_xor(s[1][5], rl1[5]), u8_xor(s[1][6], rl1[6]), u8_xor(s[1][7], rl1[7])]);
    let s = set(s, 2, [u8_xor(s[2][0], rl2[0]), u8_xor(s[2][1], rl2[1]), u8_xor(s[2][2], rl2[2]), u8_xor(s[2][3], rl2[3]), u8_xor(s[2][4], rl2[4]), u8_xor(s[2][5], rl2[5]), u8_xor(s[2][6], rl2[6]), u8_xor(s[2][7], rl2[7])]);
    let s = set(s, 3, [u8_xor(s[3][0], rl3[0]), u8_xor(s[3][1], rl3[1]), u8_xor(s[3][2], rl3[2]), u8_xor(s[3][3], rl3[3]), u8_xor(s[3][4], rl3[4]), u8_xor(s[3][5], rl3[5]), u8_xor(s[3][6], rl3[6]), u8_xor(s[3][7], rl3[7])]);
    let s = set(s, 4, [u8_xor(s[4][0], rl4[0]), u8_xor(s[4][1], rl4[1]), u8_xor(s[4][2], rl4[2]), u8_xor(s[4][3], rl4[3]), u8_xor(s[4][4], rl4[4]), u8_xor(s[4][5], rl4[5]), u8_xor(s[4][6], rl4[6]), u8_xor(s[4][7], rl4[7])]);
    let s = set(s, 5, [u8_xor(s[5][0], rl5[0]), u8_xor(s[5][1], rl5[1]), u8_xor(s[5][2], rl5[2]), u8_xor(s[5][3], rl5[3]), u8_xor(s[5][4], rl5[4]), u8_xor(s[5][5], rl5[5]), u8_xor(s[5][6], rl5[6]), u8_xor(s[5][7], rl5[7])]);
    let s = set(s, 6, [u8_xor(s[6][0], rl6[0]), u8_xor(s[6][1], rl6[1]), u8_xor(s[6][2], rl6[2]), u8_xor(s[6][3], rl6[3]), u8_xor(s[6][4], rl6[4]), u8_xor(s[6][5], rl6[5]), u8_xor(s[6][6], rl6[6]), u8_xor(s[6][7], rl6[7])]);
    let s = set(s, 7, [u8_xor(s[7][0], rl7[0]), u8_xor(s[7][1], rl7[1]), u8_xor(s[7][2], rl7[2]), u8_xor(s[7][3], rl7[3]), u8_xor(s[7][4], rl7[4]), u8_xor(s[7][5], rl7[5]), u8_xor(s[7][6], rl7[6]), u8_xor(s[7][7], rl7[7])]);
    let s = set(s, 8, [u8_xor(s[8][0], rl8[0]), u8_xor(s[8][1], rl8[1]), u8_xor(s[8][2], rl8[2]), u8_xor(s[8][3], rl8[3]), u8_xor(s[8][4], rl8[4]), u8_xor(s[8][5], rl8[5]), u8_xor(s[8][6], rl8[6]), u8_xor(s[8][7], rl8[7])]);
    let s = set(s, 9, [u8_xor(s[9][0], rl9[0]), u8_xor(s[9][1], rl9[1]), u8_xor(s[9][2], rl9[2]), u8_xor(s[9][3], rl9[3]), u8_xor(s[9][4], rl9[4]), u8_xor(s[9][5], rl9[5]), u8_xor(s[9][6], rl9[6]), u8_xor(s[9][7], rl9[7])]);
    let s = set(s, 10, [u8_xor(s[10][0], rl10[0]), u8_xor(s[10][1], rl10[1]), u8_xor(s[10][2], rl10[2]), u8_xor(s[10][3], rl10[3]), u8_xor(s[10][4], rl10[4]), u8_xor(s[10][5], rl10[5]), u8_xor(s[10][6], rl10[6]), u8_xor(s[10][7], rl10[7])]);
    let s = set(s, 11, [u8_xor(s[11][0], rl11[0]), u8_xor(s[11][1], rl11[1]), u8_xor(s[11][2], rl11[2]), u8_xor(s[11][3], rl11[3]), u8_xor(s[11][4], rl11[4]), u8_xor(s[11][5], rl11[5]), u8_xor(s[11][6], rl11[6]), u8_xor(s[11][7], rl11[7])]);
    let s = set(s, 12, [u8_xor(s[12][0], rl12[0]), u8_xor(s[12][1], rl12[1]), u8_xor(s[12][2], rl12[2]), u8_xor(s[12][3], rl12[3]), u8_xor(s[12][4], rl12[4]), u8_xor(s[12][5], rl12[5]), u8_xor(s[12][6], rl12[6]), u8_xor(s[12][7], rl12[7])]);
    let s = set(s, 13, [u8_xor(s[13][0], rl13[0]), u8_xor(s[13][1], rl13[1]), u8_xor(s[13][2], rl13[2]), u8_xor(s[13][3], rl13[3]), u8_xor(s[13][4], rl13[4]), u8_xor(s[13][5], rl13[5]), u8_xor(s[13][6], rl13[6]), u8_xor(s[13][7], rl13[7])]);
    let s = set(s, 14, [u8_xor(s[14][0], rl14[0]), u8_xor(s[14][1], rl14[1]), u8_xor(s[14][2], rl14[2]), u8_xor(s[14][3], rl14[3]), u8_xor(s[14][4], rl14[4]), u8_xor(s[14][5], rl14[5]), u8_xor(s[14][6], rl14[6]), u8_xor(s[14][7], rl14[7])]);
    let s = set(s, 15, [u8_xor(s[15][0], rl15[0]), u8_xor(s[15][1], rl15[1]), u8_xor(s[15][2], rl15[2]), u8_xor(s[15][3], rl15[3]), u8_xor(s[15][4], rl15[4]), u8_xor(s[15][5], rl15[5]), u8_xor(s[15][6], rl15[6]), u8_xor(s[15][7], rl15[7])]);
    let s = set(s, 16, [u8_xor(s[16][0], rl16[0]), u8_xor(s[16][1], rl16[1]), u8_xor(s[16][2], rl16[2]), u8_xor(s[16][3], rl16[3]), u8_xor(s[16][4], rl16[4]), u8_xor(s[16][5], rl16[5]), u8_xor(s[16][6], rl16[6]), u8_xor(s[16][7], rl16[7])]);
    keccak_f(s)
  }

  -- Absorb every rate block of the (padded) message into the state.
  fn absorb_blocks(stream: ByteStream, s: [[U8; 8]; 25]) -> [[U8; 8]; 25] {
    let (block, rest, full) = read_block(stream, 0);
    let s2 = absorb_one(s, block);
    match full {
      0 => s2,
      _ => absorb_blocks(rest, s2),
    }
  }

  -- keccak-256: absorb into the zero state, squeeze lanes 0..3.
  fn keccak256(bytes: ByteStream) -> [[U8; 8]; 4] {
    let s = absorb_blocks(bytes, [[0u8; 8]; 25]);
    [s[0], s[1], s[2], s[3]]
  }

  /- # keccak-f[1600]: 24 unrolled rounds of theta-rho-pi-chi-iota -/

  fn keccak_f(s: [[U8; 8]; 25]) -> [[U8; 8]; 25] {
    let RC = [
      [0x01u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x82u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x8au8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x8bu8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x01u8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8],
      [0x81u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x09u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x8au8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x88u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x09u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8],
      [0x0au8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8],
      [0x8bu8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8],
      [0x8bu8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x89u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x03u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x02u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x0au8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8],
      [0x0au8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x81u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x80u8, 0x80u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0x80u8],
      [0x01u8, 0u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0u8],
      [0x08u8, 0x80u8, 0u8, 0x80u8, 0u8, 0u8, 0u8, 0x80u8]
    ];
    fold(0 .. 24, s, |s, @i| keccak_rho_chi_iota(keccak_theta(s), RC[@i]))
  }

  -- One round, split into two circuits (theta | rho+pi+chi+iota), each of
  -- height 24 x permutations. A single fully-unrolled permutation circuit
  -- would be cheaper (no 200-column state re-input or 200 output aux per
  -- call, one row per permutation at a 24x shorter height's log2), but its
  -- ~7300-let macro-expanded body overflows the Lean elaborator's stack.
  -- Building the Source.Term programmatically would unlock it.
  fn keccak_theta(s: [[U8; 8]; 25]) -> [[U8; 8]; 25] {
      -- theta: column parities C[x] = xor of the 5 lanes in column x.
      let c0 = [
        u8_xor(s[20][0], u8_xor(s[15][0], u8_xor(s[10][0], u8_xor(s[5][0], s[0][0])))),
        u8_xor(s[20][1], u8_xor(s[15][1], u8_xor(s[10][1], u8_xor(s[5][1], s[0][1])))),
        u8_xor(s[20][2], u8_xor(s[15][2], u8_xor(s[10][2], u8_xor(s[5][2], s[0][2])))),
        u8_xor(s[20][3], u8_xor(s[15][3], u8_xor(s[10][3], u8_xor(s[5][3], s[0][3])))),
        u8_xor(s[20][4], u8_xor(s[15][4], u8_xor(s[10][4], u8_xor(s[5][4], s[0][4])))),
        u8_xor(s[20][5], u8_xor(s[15][5], u8_xor(s[10][5], u8_xor(s[5][5], s[0][5])))),
        u8_xor(s[20][6], u8_xor(s[15][6], u8_xor(s[10][6], u8_xor(s[5][6], s[0][6])))),
        u8_xor(s[20][7], u8_xor(s[15][7], u8_xor(s[10][7], u8_xor(s[5][7], s[0][7]))))
      ];
      let c1 = [
        u8_xor(s[21][0], u8_xor(s[16][0], u8_xor(s[11][0], u8_xor(s[6][0], s[1][0])))),
        u8_xor(s[21][1], u8_xor(s[16][1], u8_xor(s[11][1], u8_xor(s[6][1], s[1][1])))),
        u8_xor(s[21][2], u8_xor(s[16][2], u8_xor(s[11][2], u8_xor(s[6][2], s[1][2])))),
        u8_xor(s[21][3], u8_xor(s[16][3], u8_xor(s[11][3], u8_xor(s[6][3], s[1][3])))),
        u8_xor(s[21][4], u8_xor(s[16][4], u8_xor(s[11][4], u8_xor(s[6][4], s[1][4])))),
        u8_xor(s[21][5], u8_xor(s[16][5], u8_xor(s[11][5], u8_xor(s[6][5], s[1][5])))),
        u8_xor(s[21][6], u8_xor(s[16][6], u8_xor(s[11][6], u8_xor(s[6][6], s[1][6])))),
        u8_xor(s[21][7], u8_xor(s[16][7], u8_xor(s[11][7], u8_xor(s[6][7], s[1][7]))))
      ];
      let c2 = [
        u8_xor(s[22][0], u8_xor(s[17][0], u8_xor(s[12][0], u8_xor(s[7][0], s[2][0])))),
        u8_xor(s[22][1], u8_xor(s[17][1], u8_xor(s[12][1], u8_xor(s[7][1], s[2][1])))),
        u8_xor(s[22][2], u8_xor(s[17][2], u8_xor(s[12][2], u8_xor(s[7][2], s[2][2])))),
        u8_xor(s[22][3], u8_xor(s[17][3], u8_xor(s[12][3], u8_xor(s[7][3], s[2][3])))),
        u8_xor(s[22][4], u8_xor(s[17][4], u8_xor(s[12][4], u8_xor(s[7][4], s[2][4])))),
        u8_xor(s[22][5], u8_xor(s[17][5], u8_xor(s[12][5], u8_xor(s[7][5], s[2][5])))),
        u8_xor(s[22][6], u8_xor(s[17][6], u8_xor(s[12][6], u8_xor(s[7][6], s[2][6])))),
        u8_xor(s[22][7], u8_xor(s[17][7], u8_xor(s[12][7], u8_xor(s[7][7], s[2][7]))))
      ];
      let c3 = [
        u8_xor(s[23][0], u8_xor(s[18][0], u8_xor(s[13][0], u8_xor(s[8][0], s[3][0])))),
        u8_xor(s[23][1], u8_xor(s[18][1], u8_xor(s[13][1], u8_xor(s[8][1], s[3][1])))),
        u8_xor(s[23][2], u8_xor(s[18][2], u8_xor(s[13][2], u8_xor(s[8][2], s[3][2])))),
        u8_xor(s[23][3], u8_xor(s[18][3], u8_xor(s[13][3], u8_xor(s[8][3], s[3][3])))),
        u8_xor(s[23][4], u8_xor(s[18][4], u8_xor(s[13][4], u8_xor(s[8][4], s[3][4])))),
        u8_xor(s[23][5], u8_xor(s[18][5], u8_xor(s[13][5], u8_xor(s[8][5], s[3][5])))),
        u8_xor(s[23][6], u8_xor(s[18][6], u8_xor(s[13][6], u8_xor(s[8][6], s[3][6])))),
        u8_xor(s[23][7], u8_xor(s[18][7], u8_xor(s[13][7], u8_xor(s[8][7], s[3][7]))))
      ];
      let c4 = [
        u8_xor(s[24][0], u8_xor(s[19][0], u8_xor(s[14][0], u8_xor(s[9][0], s[4][0])))),
        u8_xor(s[24][1], u8_xor(s[19][1], u8_xor(s[14][1], u8_xor(s[9][1], s[4][1])))),
        u8_xor(s[24][2], u8_xor(s[19][2], u8_xor(s[14][2], u8_xor(s[9][2], s[4][2])))),
        u8_xor(s[24][3], u8_xor(s[19][3], u8_xor(s[14][3], u8_xor(s[9][3], s[4][3])))),
        u8_xor(s[24][4], u8_xor(s[19][4], u8_xor(s[14][4], u8_xor(s[9][4], s[4][4])))),
        u8_xor(s[24][5], u8_xor(s[19][5], u8_xor(s[14][5], u8_xor(s[9][5], s[4][5])))),
        u8_xor(s[24][6], u8_xor(s[19][6], u8_xor(s[14][6], u8_xor(s[9][6], s[4][6])))),
        u8_xor(s[24][7], u8_xor(s[19][7], u8_xor(s[14][7], u8_xor(s[9][7], s[4][7]))))
      ];
      -- rotl-by-1 of each C lane via the u8_add trick: (b + b) yields
      -- (2b mod 256, msb); the even low byte absorbs the neighbor byte's
      -- msb with a free field add.
      let (l0_0, m0_0) = u8_add(c0[0], c0[0]);
      let (l0_1, m0_1) = u8_add(c0[1], c0[1]);
      let (l0_2, m0_2) = u8_add(c0[2], c0[2]);
      let (l0_3, m0_3) = u8_add(c0[3], c0[3]);
      let (l0_4, m0_4) = u8_add(c0[4], c0[4]);
      let (l0_5, m0_5) = u8_add(c0[5], c0[5]);
      let (l0_6, m0_6) = u8_add(c0[6], c0[6]);
      let (l0_7, m0_7) = u8_add(c0[7], c0[7]);
      let r0 = [u8_from_field_unsafe(to_field(l0_0) + to_field(m0_7)), u8_from_field_unsafe(to_field(l0_1) + to_field(m0_0)), u8_from_field_unsafe(to_field(l0_2) + to_field(m0_1)), u8_from_field_unsafe(to_field(l0_3) + to_field(m0_2)), u8_from_field_unsafe(to_field(l0_4) + to_field(m0_3)), u8_from_field_unsafe(to_field(l0_5) + to_field(m0_4)), u8_from_field_unsafe(to_field(l0_6) + to_field(m0_5)), u8_from_field_unsafe(to_field(l0_7) + to_field(m0_6))];
      let (l1_0, m1_0) = u8_add(c1[0], c1[0]);
      let (l1_1, m1_1) = u8_add(c1[1], c1[1]);
      let (l1_2, m1_2) = u8_add(c1[2], c1[2]);
      let (l1_3, m1_3) = u8_add(c1[3], c1[3]);
      let (l1_4, m1_4) = u8_add(c1[4], c1[4]);
      let (l1_5, m1_5) = u8_add(c1[5], c1[5]);
      let (l1_6, m1_6) = u8_add(c1[6], c1[6]);
      let (l1_7, m1_7) = u8_add(c1[7], c1[7]);
      let r1 = [u8_from_field_unsafe(to_field(l1_0) + to_field(m1_7)), u8_from_field_unsafe(to_field(l1_1) + to_field(m1_0)), u8_from_field_unsafe(to_field(l1_2) + to_field(m1_1)), u8_from_field_unsafe(to_field(l1_3) + to_field(m1_2)), u8_from_field_unsafe(to_field(l1_4) + to_field(m1_3)), u8_from_field_unsafe(to_field(l1_5) + to_field(m1_4)), u8_from_field_unsafe(to_field(l1_6) + to_field(m1_5)), u8_from_field_unsafe(to_field(l1_7) + to_field(m1_6))];
      let (l2_0, m2_0) = u8_add(c2[0], c2[0]);
      let (l2_1, m2_1) = u8_add(c2[1], c2[1]);
      let (l2_2, m2_2) = u8_add(c2[2], c2[2]);
      let (l2_3, m2_3) = u8_add(c2[3], c2[3]);
      let (l2_4, m2_4) = u8_add(c2[4], c2[4]);
      let (l2_5, m2_5) = u8_add(c2[5], c2[5]);
      let (l2_6, m2_6) = u8_add(c2[6], c2[6]);
      let (l2_7, m2_7) = u8_add(c2[7], c2[7]);
      let r2 = [u8_from_field_unsafe(to_field(l2_0) + to_field(m2_7)), u8_from_field_unsafe(to_field(l2_1) + to_field(m2_0)), u8_from_field_unsafe(to_field(l2_2) + to_field(m2_1)), u8_from_field_unsafe(to_field(l2_3) + to_field(m2_2)), u8_from_field_unsafe(to_field(l2_4) + to_field(m2_3)), u8_from_field_unsafe(to_field(l2_5) + to_field(m2_4)), u8_from_field_unsafe(to_field(l2_6) + to_field(m2_5)), u8_from_field_unsafe(to_field(l2_7) + to_field(m2_6))];
      let (l3_0, m3_0) = u8_add(c3[0], c3[0]);
      let (l3_1, m3_1) = u8_add(c3[1], c3[1]);
      let (l3_2, m3_2) = u8_add(c3[2], c3[2]);
      let (l3_3, m3_3) = u8_add(c3[3], c3[3]);
      let (l3_4, m3_4) = u8_add(c3[4], c3[4]);
      let (l3_5, m3_5) = u8_add(c3[5], c3[5]);
      let (l3_6, m3_6) = u8_add(c3[6], c3[6]);
      let (l3_7, m3_7) = u8_add(c3[7], c3[7]);
      let r3 = [u8_from_field_unsafe(to_field(l3_0) + to_field(m3_7)), u8_from_field_unsafe(to_field(l3_1) + to_field(m3_0)), u8_from_field_unsafe(to_field(l3_2) + to_field(m3_1)), u8_from_field_unsafe(to_field(l3_3) + to_field(m3_2)), u8_from_field_unsafe(to_field(l3_4) + to_field(m3_3)), u8_from_field_unsafe(to_field(l3_5) + to_field(m3_4)), u8_from_field_unsafe(to_field(l3_6) + to_field(m3_5)), u8_from_field_unsafe(to_field(l3_7) + to_field(m3_6))];
      let (l4_0, m4_0) = u8_add(c4[0], c4[0]);
      let (l4_1, m4_1) = u8_add(c4[1], c4[1]);
      let (l4_2, m4_2) = u8_add(c4[2], c4[2]);
      let (l4_3, m4_3) = u8_add(c4[3], c4[3]);
      let (l4_4, m4_4) = u8_add(c4[4], c4[4]);
      let (l4_5, m4_5) = u8_add(c4[5], c4[5]);
      let (l4_6, m4_6) = u8_add(c4[6], c4[6]);
      let (l4_7, m4_7) = u8_add(c4[7], c4[7]);
      let r4 = [u8_from_field_unsafe(to_field(l4_0) + to_field(m4_7)), u8_from_field_unsafe(to_field(l4_1) + to_field(m4_0)), u8_from_field_unsafe(to_field(l4_2) + to_field(m4_1)), u8_from_field_unsafe(to_field(l4_3) + to_field(m4_2)), u8_from_field_unsafe(to_field(l4_4) + to_field(m4_3)), u8_from_field_unsafe(to_field(l4_5) + to_field(m4_4)), u8_from_field_unsafe(to_field(l4_6) + to_field(m4_5)), u8_from_field_unsafe(to_field(l4_7) + to_field(m4_6))];
      -- D[x] = C[x-1] ^ rotl1(C[x+1]); A'[x,y] = A[x,y] ^ D[x].
      let d0 = [u8_xor(c4[0], r1[0]), u8_xor(c4[1], r1[1]), u8_xor(c4[2], r1[2]), u8_xor(c4[3], r1[3]), u8_xor(c4[4], r1[4]), u8_xor(c4[5], r1[5]), u8_xor(c4[6], r1[6]), u8_xor(c4[7], r1[7])];
      let d1 = [u8_xor(c0[0], r2[0]), u8_xor(c0[1], r2[1]), u8_xor(c0[2], r2[2]), u8_xor(c0[3], r2[3]), u8_xor(c0[4], r2[4]), u8_xor(c0[5], r2[5]), u8_xor(c0[6], r2[6]), u8_xor(c0[7], r2[7])];
      let d2 = [u8_xor(c1[0], r3[0]), u8_xor(c1[1], r3[1]), u8_xor(c1[2], r3[2]), u8_xor(c1[3], r3[3]), u8_xor(c1[4], r3[4]), u8_xor(c1[5], r3[5]), u8_xor(c1[6], r3[6]), u8_xor(c1[7], r3[7])];
      let d3 = [u8_xor(c2[0], r4[0]), u8_xor(c2[1], r4[1]), u8_xor(c2[2], r4[2]), u8_xor(c2[3], r4[3]), u8_xor(c2[4], r4[4]), u8_xor(c2[5], r4[5]), u8_xor(c2[6], r4[6]), u8_xor(c2[7], r4[7])];
      let d4 = [u8_xor(c3[0], r0[0]), u8_xor(c3[1], r0[1]), u8_xor(c3[2], r0[2]), u8_xor(c3[3], r0[3]), u8_xor(c3[4], r0[4]), u8_xor(c3[5], r0[5]), u8_xor(c3[6], r0[6]), u8_xor(c3[7], r0[7])];
      let t0 = [u8_xor(s[0][0], d0[0]), u8_xor(s[0][1], d0[1]), u8_xor(s[0][2], d0[2]), u8_xor(s[0][3], d0[3]), u8_xor(s[0][4], d0[4]), u8_xor(s[0][5], d0[5]), u8_xor(s[0][6], d0[6]), u8_xor(s[0][7], d0[7])];
      let t1 = [u8_xor(s[1][0], d1[0]), u8_xor(s[1][1], d1[1]), u8_xor(s[1][2], d1[2]), u8_xor(s[1][3], d1[3]), u8_xor(s[1][4], d1[4]), u8_xor(s[1][5], d1[5]), u8_xor(s[1][6], d1[6]), u8_xor(s[1][7], d1[7])];
      let t2 = [u8_xor(s[2][0], d2[0]), u8_xor(s[2][1], d2[1]), u8_xor(s[2][2], d2[2]), u8_xor(s[2][3], d2[3]), u8_xor(s[2][4], d2[4]), u8_xor(s[2][5], d2[5]), u8_xor(s[2][6], d2[6]), u8_xor(s[2][7], d2[7])];
      let t3 = [u8_xor(s[3][0], d3[0]), u8_xor(s[3][1], d3[1]), u8_xor(s[3][2], d3[2]), u8_xor(s[3][3], d3[3]), u8_xor(s[3][4], d3[4]), u8_xor(s[3][5], d3[5]), u8_xor(s[3][6], d3[6]), u8_xor(s[3][7], d3[7])];
      let t4 = [u8_xor(s[4][0], d4[0]), u8_xor(s[4][1], d4[1]), u8_xor(s[4][2], d4[2]), u8_xor(s[4][3], d4[3]), u8_xor(s[4][4], d4[4]), u8_xor(s[4][5], d4[5]), u8_xor(s[4][6], d4[6]), u8_xor(s[4][7], d4[7])];
      let t5 = [u8_xor(s[5][0], d0[0]), u8_xor(s[5][1], d0[1]), u8_xor(s[5][2], d0[2]), u8_xor(s[5][3], d0[3]), u8_xor(s[5][4], d0[4]), u8_xor(s[5][5], d0[5]), u8_xor(s[5][6], d0[6]), u8_xor(s[5][7], d0[7])];
      let t6 = [u8_xor(s[6][0], d1[0]), u8_xor(s[6][1], d1[1]), u8_xor(s[6][2], d1[2]), u8_xor(s[6][3], d1[3]), u8_xor(s[6][4], d1[4]), u8_xor(s[6][5], d1[5]), u8_xor(s[6][6], d1[6]), u8_xor(s[6][7], d1[7])];
      let t7 = [u8_xor(s[7][0], d2[0]), u8_xor(s[7][1], d2[1]), u8_xor(s[7][2], d2[2]), u8_xor(s[7][3], d2[3]), u8_xor(s[7][4], d2[4]), u8_xor(s[7][5], d2[5]), u8_xor(s[7][6], d2[6]), u8_xor(s[7][7], d2[7])];
      let t8 = [u8_xor(s[8][0], d3[0]), u8_xor(s[8][1], d3[1]), u8_xor(s[8][2], d3[2]), u8_xor(s[8][3], d3[3]), u8_xor(s[8][4], d3[4]), u8_xor(s[8][5], d3[5]), u8_xor(s[8][6], d3[6]), u8_xor(s[8][7], d3[7])];
      let t9 = [u8_xor(s[9][0], d4[0]), u8_xor(s[9][1], d4[1]), u8_xor(s[9][2], d4[2]), u8_xor(s[9][3], d4[3]), u8_xor(s[9][4], d4[4]), u8_xor(s[9][5], d4[5]), u8_xor(s[9][6], d4[6]), u8_xor(s[9][7], d4[7])];
      let t10 = [u8_xor(s[10][0], d0[0]), u8_xor(s[10][1], d0[1]), u8_xor(s[10][2], d0[2]), u8_xor(s[10][3], d0[3]), u8_xor(s[10][4], d0[4]), u8_xor(s[10][5], d0[5]), u8_xor(s[10][6], d0[6]), u8_xor(s[10][7], d0[7])];
      let t11 = [u8_xor(s[11][0], d1[0]), u8_xor(s[11][1], d1[1]), u8_xor(s[11][2], d1[2]), u8_xor(s[11][3], d1[3]), u8_xor(s[11][4], d1[4]), u8_xor(s[11][5], d1[5]), u8_xor(s[11][6], d1[6]), u8_xor(s[11][7], d1[7])];
      let t12 = [u8_xor(s[12][0], d2[0]), u8_xor(s[12][1], d2[1]), u8_xor(s[12][2], d2[2]), u8_xor(s[12][3], d2[3]), u8_xor(s[12][4], d2[4]), u8_xor(s[12][5], d2[5]), u8_xor(s[12][6], d2[6]), u8_xor(s[12][7], d2[7])];
      let t13 = [u8_xor(s[13][0], d3[0]), u8_xor(s[13][1], d3[1]), u8_xor(s[13][2], d3[2]), u8_xor(s[13][3], d3[3]), u8_xor(s[13][4], d3[4]), u8_xor(s[13][5], d3[5]), u8_xor(s[13][6], d3[6]), u8_xor(s[13][7], d3[7])];
      let t14 = [u8_xor(s[14][0], d4[0]), u8_xor(s[14][1], d4[1]), u8_xor(s[14][2], d4[2]), u8_xor(s[14][3], d4[3]), u8_xor(s[14][4], d4[4]), u8_xor(s[14][5], d4[5]), u8_xor(s[14][6], d4[6]), u8_xor(s[14][7], d4[7])];
      let t15 = [u8_xor(s[15][0], d0[0]), u8_xor(s[15][1], d0[1]), u8_xor(s[15][2], d0[2]), u8_xor(s[15][3], d0[3]), u8_xor(s[15][4], d0[4]), u8_xor(s[15][5], d0[5]), u8_xor(s[15][6], d0[6]), u8_xor(s[15][7], d0[7])];
      let t16 = [u8_xor(s[16][0], d1[0]), u8_xor(s[16][1], d1[1]), u8_xor(s[16][2], d1[2]), u8_xor(s[16][3], d1[3]), u8_xor(s[16][4], d1[4]), u8_xor(s[16][5], d1[5]), u8_xor(s[16][6], d1[6]), u8_xor(s[16][7], d1[7])];
      let t17 = [u8_xor(s[17][0], d2[0]), u8_xor(s[17][1], d2[1]), u8_xor(s[17][2], d2[2]), u8_xor(s[17][3], d2[3]), u8_xor(s[17][4], d2[4]), u8_xor(s[17][5], d2[5]), u8_xor(s[17][6], d2[6]), u8_xor(s[17][7], d2[7])];
      let t18 = [u8_xor(s[18][0], d3[0]), u8_xor(s[18][1], d3[1]), u8_xor(s[18][2], d3[2]), u8_xor(s[18][3], d3[3]), u8_xor(s[18][4], d3[4]), u8_xor(s[18][5], d3[5]), u8_xor(s[18][6], d3[6]), u8_xor(s[18][7], d3[7])];
      let t19 = [u8_xor(s[19][0], d4[0]), u8_xor(s[19][1], d4[1]), u8_xor(s[19][2], d4[2]), u8_xor(s[19][3], d4[3]), u8_xor(s[19][4], d4[4]), u8_xor(s[19][5], d4[5]), u8_xor(s[19][6], d4[6]), u8_xor(s[19][7], d4[7])];
      let t20 = [u8_xor(s[20][0], d0[0]), u8_xor(s[20][1], d0[1]), u8_xor(s[20][2], d0[2]), u8_xor(s[20][3], d0[3]), u8_xor(s[20][4], d0[4]), u8_xor(s[20][5], d0[5]), u8_xor(s[20][6], d0[6]), u8_xor(s[20][7], d0[7])];
      let t21 = [u8_xor(s[21][0], d1[0]), u8_xor(s[21][1], d1[1]), u8_xor(s[21][2], d1[2]), u8_xor(s[21][3], d1[3]), u8_xor(s[21][4], d1[4]), u8_xor(s[21][5], d1[5]), u8_xor(s[21][6], d1[6]), u8_xor(s[21][7], d1[7])];
      let t22 = [u8_xor(s[22][0], d2[0]), u8_xor(s[22][1], d2[1]), u8_xor(s[22][2], d2[2]), u8_xor(s[22][3], d2[3]), u8_xor(s[22][4], d2[4]), u8_xor(s[22][5], d2[5]), u8_xor(s[22][6], d2[6]), u8_xor(s[22][7], d2[7])];
      let t23 = [u8_xor(s[23][0], d3[0]), u8_xor(s[23][1], d3[1]), u8_xor(s[23][2], d3[2]), u8_xor(s[23][3], d3[3]), u8_xor(s[23][4], d3[4]), u8_xor(s[23][5], d3[5]), u8_xor(s[23][6], d3[6]), u8_xor(s[23][7], d3[7])];
      let t24 = [u8_xor(s[24][0], d4[0]), u8_xor(s[24][1], d4[1]), u8_xor(s[24][2], d4[2]), u8_xor(s[24][3], d4[3]), u8_xor(s[24][4], d4[4]), u8_xor(s[24][5], d4[5]), u8_xor(s[24][6], d4[6]), u8_xor(s[24][7], d4[7])];
      [t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22, t23, t24]
  }

  fn keccak_rho_chi_iota(s: [[U8; 8]; 25], rc: [U8; 8]) -> [[U8; 8]; 25] {
      let t0 = s[0];
      let t1 = s[1];
      let t2 = s[2];
      let t3 = s[3];
      let t4 = s[4];
      let t5 = s[5];
      let t6 = s[6];
      let t7 = s[7];
      let t8 = s[8];
      let t9 = s[9];
      let t10 = s[10];
      let t11 = s[11];
      let t12 = s[12];
      let t13 = s[13];
      let t14 = s[14];
      let t15 = s[15];
      let t16 = s[16];
      let t17 = s[17];
      let t18 = s[18];
      let t19 = s[19];
      let t20 = s[20];
      let t21 = s[21];
      let t22 = s[22];
      let t23 = s[23];
      let t24 = s[24];
      -- rho + pi: b[pi(src)] = rotl(t[src], rho(src)).
      -- b0 = rotl(t0, 0): byte rotation only (free)
      let b0 = [t0[0], t0[1], t0[2], t0[3], t0[4], t0[5], t0[6], t0[7]];
      -- b10 = rotl(t1, 1) = byte-rotl 0 + bit-shl 1
      let d10_0 = u8_bit_decomposition(t1[0]);
      let d10_1 = u8_bit_decomposition(t1[1]);
      let d10_2 = u8_bit_decomposition(t1[2]);
      let d10_3 = u8_bit_decomposition(t1[3]);
      let d10_4 = u8_bit_decomposition(t1[4]);
      let d10_5 = u8_bit_decomposition(t1[5]);
      let d10_6 = u8_bit_decomposition(t1[6]);
      let d10_7 = u8_bit_decomposition(t1[7]);
      let b10 = [
        u8_from_field_unsafe(d10_7[7] + 2 * d10_0[0] + 4 * d10_0[1] + 8 * d10_0[2] + 16 * d10_0[3] + 32 * d10_0[4] + 64 * d10_0[5] + 128 * d10_0[6]),
        u8_from_field_unsafe(d10_0[7] + 2 * d10_1[0] + 4 * d10_1[1] + 8 * d10_1[2] + 16 * d10_1[3] + 32 * d10_1[4] + 64 * d10_1[5] + 128 * d10_1[6]),
        u8_from_field_unsafe(d10_1[7] + 2 * d10_2[0] + 4 * d10_2[1] + 8 * d10_2[2] + 16 * d10_2[3] + 32 * d10_2[4] + 64 * d10_2[5] + 128 * d10_2[6]),
        u8_from_field_unsafe(d10_2[7] + 2 * d10_3[0] + 4 * d10_3[1] + 8 * d10_3[2] + 16 * d10_3[3] + 32 * d10_3[4] + 64 * d10_3[5] + 128 * d10_3[6]),
        u8_from_field_unsafe(d10_3[7] + 2 * d10_4[0] + 4 * d10_4[1] + 8 * d10_4[2] + 16 * d10_4[3] + 32 * d10_4[4] + 64 * d10_4[5] + 128 * d10_4[6]),
        u8_from_field_unsafe(d10_4[7] + 2 * d10_5[0] + 4 * d10_5[1] + 8 * d10_5[2] + 16 * d10_5[3] + 32 * d10_5[4] + 64 * d10_5[5] + 128 * d10_5[6]),
        u8_from_field_unsafe(d10_5[7] + 2 * d10_6[0] + 4 * d10_6[1] + 8 * d10_6[2] + 16 * d10_6[3] + 32 * d10_6[4] + 64 * d10_6[5] + 128 * d10_6[6]),
        u8_from_field_unsafe(d10_6[7] + 2 * d10_7[0] + 4 * d10_7[1] + 8 * d10_7[2] + 16 * d10_7[3] + 32 * d10_7[4] + 64 * d10_7[5] + 128 * d10_7[6])
      ];
      -- b20 = rotl(t2, 62) = byte-rotl 7 + bit-shl 6
      let d20_0 = u8_bit_decomposition(t2[0]);
      let d20_1 = u8_bit_decomposition(t2[1]);
      let d20_2 = u8_bit_decomposition(t2[2]);
      let d20_3 = u8_bit_decomposition(t2[3]);
      let d20_4 = u8_bit_decomposition(t2[4]);
      let d20_5 = u8_bit_decomposition(t2[5]);
      let d20_6 = u8_bit_decomposition(t2[6]);
      let d20_7 = u8_bit_decomposition(t2[7]);
      let b20 = [
        u8_from_field_unsafe(d20_0[2] + 2 * d20_0[3] + 4 * d20_0[4] + 8 * d20_0[5] + 16 * d20_0[6] + 32 * d20_0[7] + 64 * d20_1[0] + 128 * d20_1[1]),
        u8_from_field_unsafe(d20_1[2] + 2 * d20_1[3] + 4 * d20_1[4] + 8 * d20_1[5] + 16 * d20_1[6] + 32 * d20_1[7] + 64 * d20_2[0] + 128 * d20_2[1]),
        u8_from_field_unsafe(d20_2[2] + 2 * d20_2[3] + 4 * d20_2[4] + 8 * d20_2[5] + 16 * d20_2[6] + 32 * d20_2[7] + 64 * d20_3[0] + 128 * d20_3[1]),
        u8_from_field_unsafe(d20_3[2] + 2 * d20_3[3] + 4 * d20_3[4] + 8 * d20_3[5] + 16 * d20_3[6] + 32 * d20_3[7] + 64 * d20_4[0] + 128 * d20_4[1]),
        u8_from_field_unsafe(d20_4[2] + 2 * d20_4[3] + 4 * d20_4[4] + 8 * d20_4[5] + 16 * d20_4[6] + 32 * d20_4[7] + 64 * d20_5[0] + 128 * d20_5[1]),
        u8_from_field_unsafe(d20_5[2] + 2 * d20_5[3] + 4 * d20_5[4] + 8 * d20_5[5] + 16 * d20_5[6] + 32 * d20_5[7] + 64 * d20_6[0] + 128 * d20_6[1]),
        u8_from_field_unsafe(d20_6[2] + 2 * d20_6[3] + 4 * d20_6[4] + 8 * d20_6[5] + 16 * d20_6[6] + 32 * d20_6[7] + 64 * d20_7[0] + 128 * d20_7[1]),
        u8_from_field_unsafe(d20_7[2] + 2 * d20_7[3] + 4 * d20_7[4] + 8 * d20_7[5] + 16 * d20_7[6] + 32 * d20_7[7] + 64 * d20_0[0] + 128 * d20_0[1])
      ];
      -- b5 = rotl(t3, 28) = byte-rotl 3 + bit-shl 4
      let d5_0 = u8_bit_decomposition(t3[0]);
      let d5_1 = u8_bit_decomposition(t3[1]);
      let d5_2 = u8_bit_decomposition(t3[2]);
      let d5_3 = u8_bit_decomposition(t3[3]);
      let d5_4 = u8_bit_decomposition(t3[4]);
      let d5_5 = u8_bit_decomposition(t3[5]);
      let d5_6 = u8_bit_decomposition(t3[6]);
      let d5_7 = u8_bit_decomposition(t3[7]);
      let b5 = [
        u8_from_field_unsafe(d5_4[4] + 2 * d5_4[5] + 4 * d5_4[6] + 8 * d5_4[7] + 16 * d5_5[0] + 32 * d5_5[1] + 64 * d5_5[2] + 128 * d5_5[3]),
        u8_from_field_unsafe(d5_5[4] + 2 * d5_5[5] + 4 * d5_5[6] + 8 * d5_5[7] + 16 * d5_6[0] + 32 * d5_6[1] + 64 * d5_6[2] + 128 * d5_6[3]),
        u8_from_field_unsafe(d5_6[4] + 2 * d5_6[5] + 4 * d5_6[6] + 8 * d5_6[7] + 16 * d5_7[0] + 32 * d5_7[1] + 64 * d5_7[2] + 128 * d5_7[3]),
        u8_from_field_unsafe(d5_7[4] + 2 * d5_7[5] + 4 * d5_7[6] + 8 * d5_7[7] + 16 * d5_0[0] + 32 * d5_0[1] + 64 * d5_0[2] + 128 * d5_0[3]),
        u8_from_field_unsafe(d5_0[4] + 2 * d5_0[5] + 4 * d5_0[6] + 8 * d5_0[7] + 16 * d5_1[0] + 32 * d5_1[1] + 64 * d5_1[2] + 128 * d5_1[3]),
        u8_from_field_unsafe(d5_1[4] + 2 * d5_1[5] + 4 * d5_1[6] + 8 * d5_1[7] + 16 * d5_2[0] + 32 * d5_2[1] + 64 * d5_2[2] + 128 * d5_2[3]),
        u8_from_field_unsafe(d5_2[4] + 2 * d5_2[5] + 4 * d5_2[6] + 8 * d5_2[7] + 16 * d5_3[0] + 32 * d5_3[1] + 64 * d5_3[2] + 128 * d5_3[3]),
        u8_from_field_unsafe(d5_3[4] + 2 * d5_3[5] + 4 * d5_3[6] + 8 * d5_3[7] + 16 * d5_4[0] + 32 * d5_4[1] + 64 * d5_4[2] + 128 * d5_4[3])
      ];
      -- b15 = rotl(t4, 27) = byte-rotl 3 + bit-shl 3
      let d15_0 = u8_bit_decomposition(t4[0]);
      let d15_1 = u8_bit_decomposition(t4[1]);
      let d15_2 = u8_bit_decomposition(t4[2]);
      let d15_3 = u8_bit_decomposition(t4[3]);
      let d15_4 = u8_bit_decomposition(t4[4]);
      let d15_5 = u8_bit_decomposition(t4[5]);
      let d15_6 = u8_bit_decomposition(t4[6]);
      let d15_7 = u8_bit_decomposition(t4[7]);
      let b15 = [
        u8_from_field_unsafe(d15_4[5] + 2 * d15_4[6] + 4 * d15_4[7] + 8 * d15_5[0] + 16 * d15_5[1] + 32 * d15_5[2] + 64 * d15_5[3] + 128 * d15_5[4]),
        u8_from_field_unsafe(d15_5[5] + 2 * d15_5[6] + 4 * d15_5[7] + 8 * d15_6[0] + 16 * d15_6[1] + 32 * d15_6[2] + 64 * d15_6[3] + 128 * d15_6[4]),
        u8_from_field_unsafe(d15_6[5] + 2 * d15_6[6] + 4 * d15_6[7] + 8 * d15_7[0] + 16 * d15_7[1] + 32 * d15_7[2] + 64 * d15_7[3] + 128 * d15_7[4]),
        u8_from_field_unsafe(d15_7[5] + 2 * d15_7[6] + 4 * d15_7[7] + 8 * d15_0[0] + 16 * d15_0[1] + 32 * d15_0[2] + 64 * d15_0[3] + 128 * d15_0[4]),
        u8_from_field_unsafe(d15_0[5] + 2 * d15_0[6] + 4 * d15_0[7] + 8 * d15_1[0] + 16 * d15_1[1] + 32 * d15_1[2] + 64 * d15_1[3] + 128 * d15_1[4]),
        u8_from_field_unsafe(d15_1[5] + 2 * d15_1[6] + 4 * d15_1[7] + 8 * d15_2[0] + 16 * d15_2[1] + 32 * d15_2[2] + 64 * d15_2[3] + 128 * d15_2[4]),
        u8_from_field_unsafe(d15_2[5] + 2 * d15_2[6] + 4 * d15_2[7] + 8 * d15_3[0] + 16 * d15_3[1] + 32 * d15_3[2] + 64 * d15_3[3] + 128 * d15_3[4]),
        u8_from_field_unsafe(d15_3[5] + 2 * d15_3[6] + 4 * d15_3[7] + 8 * d15_4[0] + 16 * d15_4[1] + 32 * d15_4[2] + 64 * d15_4[3] + 128 * d15_4[4])
      ];
      -- b16 = rotl(t5, 36) = byte-rotl 4 + bit-shl 4
      let d16_0 = u8_bit_decomposition(t5[0]);
      let d16_1 = u8_bit_decomposition(t5[1]);
      let d16_2 = u8_bit_decomposition(t5[2]);
      let d16_3 = u8_bit_decomposition(t5[3]);
      let d16_4 = u8_bit_decomposition(t5[4]);
      let d16_5 = u8_bit_decomposition(t5[5]);
      let d16_6 = u8_bit_decomposition(t5[6]);
      let d16_7 = u8_bit_decomposition(t5[7]);
      let b16 = [
        u8_from_field_unsafe(d16_3[4] + 2 * d16_3[5] + 4 * d16_3[6] + 8 * d16_3[7] + 16 * d16_4[0] + 32 * d16_4[1] + 64 * d16_4[2] + 128 * d16_4[3]),
        u8_from_field_unsafe(d16_4[4] + 2 * d16_4[5] + 4 * d16_4[6] + 8 * d16_4[7] + 16 * d16_5[0] + 32 * d16_5[1] + 64 * d16_5[2] + 128 * d16_5[3]),
        u8_from_field_unsafe(d16_5[4] + 2 * d16_5[5] + 4 * d16_5[6] + 8 * d16_5[7] + 16 * d16_6[0] + 32 * d16_6[1] + 64 * d16_6[2] + 128 * d16_6[3]),
        u8_from_field_unsafe(d16_6[4] + 2 * d16_6[5] + 4 * d16_6[6] + 8 * d16_6[7] + 16 * d16_7[0] + 32 * d16_7[1] + 64 * d16_7[2] + 128 * d16_7[3]),
        u8_from_field_unsafe(d16_7[4] + 2 * d16_7[5] + 4 * d16_7[6] + 8 * d16_7[7] + 16 * d16_0[0] + 32 * d16_0[1] + 64 * d16_0[2] + 128 * d16_0[3]),
        u8_from_field_unsafe(d16_0[4] + 2 * d16_0[5] + 4 * d16_0[6] + 8 * d16_0[7] + 16 * d16_1[0] + 32 * d16_1[1] + 64 * d16_1[2] + 128 * d16_1[3]),
        u8_from_field_unsafe(d16_1[4] + 2 * d16_1[5] + 4 * d16_1[6] + 8 * d16_1[7] + 16 * d16_2[0] + 32 * d16_2[1] + 64 * d16_2[2] + 128 * d16_2[3]),
        u8_from_field_unsafe(d16_2[4] + 2 * d16_2[5] + 4 * d16_2[6] + 8 * d16_2[7] + 16 * d16_3[0] + 32 * d16_3[1] + 64 * d16_3[2] + 128 * d16_3[3])
      ];
      -- b1 = rotl(t6, 44) = byte-rotl 5 + bit-shl 4
      let d1_0 = u8_bit_decomposition(t6[0]);
      let d1_1 = u8_bit_decomposition(t6[1]);
      let d1_2 = u8_bit_decomposition(t6[2]);
      let d1_3 = u8_bit_decomposition(t6[3]);
      let d1_4 = u8_bit_decomposition(t6[4]);
      let d1_5 = u8_bit_decomposition(t6[5]);
      let d1_6 = u8_bit_decomposition(t6[6]);
      let d1_7 = u8_bit_decomposition(t6[7]);
      let b1 = [
        u8_from_field_unsafe(d1_2[4] + 2 * d1_2[5] + 4 * d1_2[6] + 8 * d1_2[7] + 16 * d1_3[0] + 32 * d1_3[1] + 64 * d1_3[2] + 128 * d1_3[3]),
        u8_from_field_unsafe(d1_3[4] + 2 * d1_3[5] + 4 * d1_3[6] + 8 * d1_3[7] + 16 * d1_4[0] + 32 * d1_4[1] + 64 * d1_4[2] + 128 * d1_4[3]),
        u8_from_field_unsafe(d1_4[4] + 2 * d1_4[5] + 4 * d1_4[6] + 8 * d1_4[7] + 16 * d1_5[0] + 32 * d1_5[1] + 64 * d1_5[2] + 128 * d1_5[3]),
        u8_from_field_unsafe(d1_5[4] + 2 * d1_5[5] + 4 * d1_5[6] + 8 * d1_5[7] + 16 * d1_6[0] + 32 * d1_6[1] + 64 * d1_6[2] + 128 * d1_6[3]),
        u8_from_field_unsafe(d1_6[4] + 2 * d1_6[5] + 4 * d1_6[6] + 8 * d1_6[7] + 16 * d1_7[0] + 32 * d1_7[1] + 64 * d1_7[2] + 128 * d1_7[3]),
        u8_from_field_unsafe(d1_7[4] + 2 * d1_7[5] + 4 * d1_7[6] + 8 * d1_7[7] + 16 * d1_0[0] + 32 * d1_0[1] + 64 * d1_0[2] + 128 * d1_0[3]),
        u8_from_field_unsafe(d1_0[4] + 2 * d1_0[5] + 4 * d1_0[6] + 8 * d1_0[7] + 16 * d1_1[0] + 32 * d1_1[1] + 64 * d1_1[2] + 128 * d1_1[3]),
        u8_from_field_unsafe(d1_1[4] + 2 * d1_1[5] + 4 * d1_1[6] + 8 * d1_1[7] + 16 * d1_2[0] + 32 * d1_2[1] + 64 * d1_2[2] + 128 * d1_2[3])
      ];
      -- b11 = rotl(t7, 6) = byte-rotl 0 + bit-shl 6
      let d11_0 = u8_bit_decomposition(t7[0]);
      let d11_1 = u8_bit_decomposition(t7[1]);
      let d11_2 = u8_bit_decomposition(t7[2]);
      let d11_3 = u8_bit_decomposition(t7[3]);
      let d11_4 = u8_bit_decomposition(t7[4]);
      let d11_5 = u8_bit_decomposition(t7[5]);
      let d11_6 = u8_bit_decomposition(t7[6]);
      let d11_7 = u8_bit_decomposition(t7[7]);
      let b11 = [
        u8_from_field_unsafe(d11_7[2] + 2 * d11_7[3] + 4 * d11_7[4] + 8 * d11_7[5] + 16 * d11_7[6] + 32 * d11_7[7] + 64 * d11_0[0] + 128 * d11_0[1]),
        u8_from_field_unsafe(d11_0[2] + 2 * d11_0[3] + 4 * d11_0[4] + 8 * d11_0[5] + 16 * d11_0[6] + 32 * d11_0[7] + 64 * d11_1[0] + 128 * d11_1[1]),
        u8_from_field_unsafe(d11_1[2] + 2 * d11_1[3] + 4 * d11_1[4] + 8 * d11_1[5] + 16 * d11_1[6] + 32 * d11_1[7] + 64 * d11_2[0] + 128 * d11_2[1]),
        u8_from_field_unsafe(d11_2[2] + 2 * d11_2[3] + 4 * d11_2[4] + 8 * d11_2[5] + 16 * d11_2[6] + 32 * d11_2[7] + 64 * d11_3[0] + 128 * d11_3[1]),
        u8_from_field_unsafe(d11_3[2] + 2 * d11_3[3] + 4 * d11_3[4] + 8 * d11_3[5] + 16 * d11_3[6] + 32 * d11_3[7] + 64 * d11_4[0] + 128 * d11_4[1]),
        u8_from_field_unsafe(d11_4[2] + 2 * d11_4[3] + 4 * d11_4[4] + 8 * d11_4[5] + 16 * d11_4[6] + 32 * d11_4[7] + 64 * d11_5[0] + 128 * d11_5[1]),
        u8_from_field_unsafe(d11_5[2] + 2 * d11_5[3] + 4 * d11_5[4] + 8 * d11_5[5] + 16 * d11_5[6] + 32 * d11_5[7] + 64 * d11_6[0] + 128 * d11_6[1]),
        u8_from_field_unsafe(d11_6[2] + 2 * d11_6[3] + 4 * d11_6[4] + 8 * d11_6[5] + 16 * d11_6[6] + 32 * d11_6[7] + 64 * d11_7[0] + 128 * d11_7[1])
      ];
      -- b21 = rotl(t8, 55) = byte-rotl 6 + bit-shl 7
      let d21_0 = u8_bit_decomposition(t8[0]);
      let d21_1 = u8_bit_decomposition(t8[1]);
      let d21_2 = u8_bit_decomposition(t8[2]);
      let d21_3 = u8_bit_decomposition(t8[3]);
      let d21_4 = u8_bit_decomposition(t8[4]);
      let d21_5 = u8_bit_decomposition(t8[5]);
      let d21_6 = u8_bit_decomposition(t8[6]);
      let d21_7 = u8_bit_decomposition(t8[7]);
      let b21 = [
        u8_from_field_unsafe(d21_1[1] + 2 * d21_1[2] + 4 * d21_1[3] + 8 * d21_1[4] + 16 * d21_1[5] + 32 * d21_1[6] + 64 * d21_1[7] + 128 * d21_2[0]),
        u8_from_field_unsafe(d21_2[1] + 2 * d21_2[2] + 4 * d21_2[3] + 8 * d21_2[4] + 16 * d21_2[5] + 32 * d21_2[6] + 64 * d21_2[7] + 128 * d21_3[0]),
        u8_from_field_unsafe(d21_3[1] + 2 * d21_3[2] + 4 * d21_3[3] + 8 * d21_3[4] + 16 * d21_3[5] + 32 * d21_3[6] + 64 * d21_3[7] + 128 * d21_4[0]),
        u8_from_field_unsafe(d21_4[1] + 2 * d21_4[2] + 4 * d21_4[3] + 8 * d21_4[4] + 16 * d21_4[5] + 32 * d21_4[6] + 64 * d21_4[7] + 128 * d21_5[0]),
        u8_from_field_unsafe(d21_5[1] + 2 * d21_5[2] + 4 * d21_5[3] + 8 * d21_5[4] + 16 * d21_5[5] + 32 * d21_5[6] + 64 * d21_5[7] + 128 * d21_6[0]),
        u8_from_field_unsafe(d21_6[1] + 2 * d21_6[2] + 4 * d21_6[3] + 8 * d21_6[4] + 16 * d21_6[5] + 32 * d21_6[6] + 64 * d21_6[7] + 128 * d21_7[0]),
        u8_from_field_unsafe(d21_7[1] + 2 * d21_7[2] + 4 * d21_7[3] + 8 * d21_7[4] + 16 * d21_7[5] + 32 * d21_7[6] + 64 * d21_7[7] + 128 * d21_0[0]),
        u8_from_field_unsafe(d21_0[1] + 2 * d21_0[2] + 4 * d21_0[3] + 8 * d21_0[4] + 16 * d21_0[5] + 32 * d21_0[6] + 64 * d21_0[7] + 128 * d21_1[0])
      ];
      -- b6 = rotl(t9, 20) = byte-rotl 2 + bit-shl 4
      let d6_0 = u8_bit_decomposition(t9[0]);
      let d6_1 = u8_bit_decomposition(t9[1]);
      let d6_2 = u8_bit_decomposition(t9[2]);
      let d6_3 = u8_bit_decomposition(t9[3]);
      let d6_4 = u8_bit_decomposition(t9[4]);
      let d6_5 = u8_bit_decomposition(t9[5]);
      let d6_6 = u8_bit_decomposition(t9[6]);
      let d6_7 = u8_bit_decomposition(t9[7]);
      let b6 = [
        u8_from_field_unsafe(d6_5[4] + 2 * d6_5[5] + 4 * d6_5[6] + 8 * d6_5[7] + 16 * d6_6[0] + 32 * d6_6[1] + 64 * d6_6[2] + 128 * d6_6[3]),
        u8_from_field_unsafe(d6_6[4] + 2 * d6_6[5] + 4 * d6_6[6] + 8 * d6_6[7] + 16 * d6_7[0] + 32 * d6_7[1] + 64 * d6_7[2] + 128 * d6_7[3]),
        u8_from_field_unsafe(d6_7[4] + 2 * d6_7[5] + 4 * d6_7[6] + 8 * d6_7[7] + 16 * d6_0[0] + 32 * d6_0[1] + 64 * d6_0[2] + 128 * d6_0[3]),
        u8_from_field_unsafe(d6_0[4] + 2 * d6_0[5] + 4 * d6_0[6] + 8 * d6_0[7] + 16 * d6_1[0] + 32 * d6_1[1] + 64 * d6_1[2] + 128 * d6_1[3]),
        u8_from_field_unsafe(d6_1[4] + 2 * d6_1[5] + 4 * d6_1[6] + 8 * d6_1[7] + 16 * d6_2[0] + 32 * d6_2[1] + 64 * d6_2[2] + 128 * d6_2[3]),
        u8_from_field_unsafe(d6_2[4] + 2 * d6_2[5] + 4 * d6_2[6] + 8 * d6_2[7] + 16 * d6_3[0] + 32 * d6_3[1] + 64 * d6_3[2] + 128 * d6_3[3]),
        u8_from_field_unsafe(d6_3[4] + 2 * d6_3[5] + 4 * d6_3[6] + 8 * d6_3[7] + 16 * d6_4[0] + 32 * d6_4[1] + 64 * d6_4[2] + 128 * d6_4[3]),
        u8_from_field_unsafe(d6_4[4] + 2 * d6_4[5] + 4 * d6_4[6] + 8 * d6_4[7] + 16 * d6_5[0] + 32 * d6_5[1] + 64 * d6_5[2] + 128 * d6_5[3])
      ];
      -- b7 = rotl(t10, 3) = byte-rotl 0 + bit-shl 3
      let d7_0 = u8_bit_decomposition(t10[0]);
      let d7_1 = u8_bit_decomposition(t10[1]);
      let d7_2 = u8_bit_decomposition(t10[2]);
      let d7_3 = u8_bit_decomposition(t10[3]);
      let d7_4 = u8_bit_decomposition(t10[4]);
      let d7_5 = u8_bit_decomposition(t10[5]);
      let d7_6 = u8_bit_decomposition(t10[6]);
      let d7_7 = u8_bit_decomposition(t10[7]);
      let b7 = [
        u8_from_field_unsafe(d7_7[5] + 2 * d7_7[6] + 4 * d7_7[7] + 8 * d7_0[0] + 16 * d7_0[1] + 32 * d7_0[2] + 64 * d7_0[3] + 128 * d7_0[4]),
        u8_from_field_unsafe(d7_0[5] + 2 * d7_0[6] + 4 * d7_0[7] + 8 * d7_1[0] + 16 * d7_1[1] + 32 * d7_1[2] + 64 * d7_1[3] + 128 * d7_1[4]),
        u8_from_field_unsafe(d7_1[5] + 2 * d7_1[6] + 4 * d7_1[7] + 8 * d7_2[0] + 16 * d7_2[1] + 32 * d7_2[2] + 64 * d7_2[3] + 128 * d7_2[4]),
        u8_from_field_unsafe(d7_2[5] + 2 * d7_2[6] + 4 * d7_2[7] + 8 * d7_3[0] + 16 * d7_3[1] + 32 * d7_3[2] + 64 * d7_3[3] + 128 * d7_3[4]),
        u8_from_field_unsafe(d7_3[5] + 2 * d7_3[6] + 4 * d7_3[7] + 8 * d7_4[0] + 16 * d7_4[1] + 32 * d7_4[2] + 64 * d7_4[3] + 128 * d7_4[4]),
        u8_from_field_unsafe(d7_4[5] + 2 * d7_4[6] + 4 * d7_4[7] + 8 * d7_5[0] + 16 * d7_5[1] + 32 * d7_5[2] + 64 * d7_5[3] + 128 * d7_5[4]),
        u8_from_field_unsafe(d7_5[5] + 2 * d7_5[6] + 4 * d7_5[7] + 8 * d7_6[0] + 16 * d7_6[1] + 32 * d7_6[2] + 64 * d7_6[3] + 128 * d7_6[4]),
        u8_from_field_unsafe(d7_6[5] + 2 * d7_6[6] + 4 * d7_6[7] + 8 * d7_7[0] + 16 * d7_7[1] + 32 * d7_7[2] + 64 * d7_7[3] + 128 * d7_7[4])
      ];
      -- b17 = rotl(t11, 10) = byte-rotl 1 + bit-shl 2
      let d17_0 = u8_bit_decomposition(t11[0]);
      let d17_1 = u8_bit_decomposition(t11[1]);
      let d17_2 = u8_bit_decomposition(t11[2]);
      let d17_3 = u8_bit_decomposition(t11[3]);
      let d17_4 = u8_bit_decomposition(t11[4]);
      let d17_5 = u8_bit_decomposition(t11[5]);
      let d17_6 = u8_bit_decomposition(t11[6]);
      let d17_7 = u8_bit_decomposition(t11[7]);
      let b17 = [
        u8_from_field_unsafe(d17_6[6] + 2 * d17_6[7] + 4 * d17_7[0] + 8 * d17_7[1] + 16 * d17_7[2] + 32 * d17_7[3] + 64 * d17_7[4] + 128 * d17_7[5]),
        u8_from_field_unsafe(d17_7[6] + 2 * d17_7[7] + 4 * d17_0[0] + 8 * d17_0[1] + 16 * d17_0[2] + 32 * d17_0[3] + 64 * d17_0[4] + 128 * d17_0[5]),
        u8_from_field_unsafe(d17_0[6] + 2 * d17_0[7] + 4 * d17_1[0] + 8 * d17_1[1] + 16 * d17_1[2] + 32 * d17_1[3] + 64 * d17_1[4] + 128 * d17_1[5]),
        u8_from_field_unsafe(d17_1[6] + 2 * d17_1[7] + 4 * d17_2[0] + 8 * d17_2[1] + 16 * d17_2[2] + 32 * d17_2[3] + 64 * d17_2[4] + 128 * d17_2[5]),
        u8_from_field_unsafe(d17_2[6] + 2 * d17_2[7] + 4 * d17_3[0] + 8 * d17_3[1] + 16 * d17_3[2] + 32 * d17_3[3] + 64 * d17_3[4] + 128 * d17_3[5]),
        u8_from_field_unsafe(d17_3[6] + 2 * d17_3[7] + 4 * d17_4[0] + 8 * d17_4[1] + 16 * d17_4[2] + 32 * d17_4[3] + 64 * d17_4[4] + 128 * d17_4[5]),
        u8_from_field_unsafe(d17_4[6] + 2 * d17_4[7] + 4 * d17_5[0] + 8 * d17_5[1] + 16 * d17_5[2] + 32 * d17_5[3] + 64 * d17_5[4] + 128 * d17_5[5]),
        u8_from_field_unsafe(d17_5[6] + 2 * d17_5[7] + 4 * d17_6[0] + 8 * d17_6[1] + 16 * d17_6[2] + 32 * d17_6[3] + 64 * d17_6[4] + 128 * d17_6[5])
      ];
      -- b2 = rotl(t12, 43) = byte-rotl 5 + bit-shl 3
      let d2_0 = u8_bit_decomposition(t12[0]);
      let d2_1 = u8_bit_decomposition(t12[1]);
      let d2_2 = u8_bit_decomposition(t12[2]);
      let d2_3 = u8_bit_decomposition(t12[3]);
      let d2_4 = u8_bit_decomposition(t12[4]);
      let d2_5 = u8_bit_decomposition(t12[5]);
      let d2_6 = u8_bit_decomposition(t12[6]);
      let d2_7 = u8_bit_decomposition(t12[7]);
      let b2 = [
        u8_from_field_unsafe(d2_2[5] + 2 * d2_2[6] + 4 * d2_2[7] + 8 * d2_3[0] + 16 * d2_3[1] + 32 * d2_3[2] + 64 * d2_3[3] + 128 * d2_3[4]),
        u8_from_field_unsafe(d2_3[5] + 2 * d2_3[6] + 4 * d2_3[7] + 8 * d2_4[0] + 16 * d2_4[1] + 32 * d2_4[2] + 64 * d2_4[3] + 128 * d2_4[4]),
        u8_from_field_unsafe(d2_4[5] + 2 * d2_4[6] + 4 * d2_4[7] + 8 * d2_5[0] + 16 * d2_5[1] + 32 * d2_5[2] + 64 * d2_5[3] + 128 * d2_5[4]),
        u8_from_field_unsafe(d2_5[5] + 2 * d2_5[6] + 4 * d2_5[7] + 8 * d2_6[0] + 16 * d2_6[1] + 32 * d2_6[2] + 64 * d2_6[3] + 128 * d2_6[4]),
        u8_from_field_unsafe(d2_6[5] + 2 * d2_6[6] + 4 * d2_6[7] + 8 * d2_7[0] + 16 * d2_7[1] + 32 * d2_7[2] + 64 * d2_7[3] + 128 * d2_7[4]),
        u8_from_field_unsafe(d2_7[5] + 2 * d2_7[6] + 4 * d2_7[7] + 8 * d2_0[0] + 16 * d2_0[1] + 32 * d2_0[2] + 64 * d2_0[3] + 128 * d2_0[4]),
        u8_from_field_unsafe(d2_0[5] + 2 * d2_0[6] + 4 * d2_0[7] + 8 * d2_1[0] + 16 * d2_1[1] + 32 * d2_1[2] + 64 * d2_1[3] + 128 * d2_1[4]),
        u8_from_field_unsafe(d2_1[5] + 2 * d2_1[6] + 4 * d2_1[7] + 8 * d2_2[0] + 16 * d2_2[1] + 32 * d2_2[2] + 64 * d2_2[3] + 128 * d2_2[4])
      ];
      -- b12 = rotl(t13, 25) = byte-rotl 3 + bit-shl 1
      let d12_0 = u8_bit_decomposition(t13[0]);
      let d12_1 = u8_bit_decomposition(t13[1]);
      let d12_2 = u8_bit_decomposition(t13[2]);
      let d12_3 = u8_bit_decomposition(t13[3]);
      let d12_4 = u8_bit_decomposition(t13[4]);
      let d12_5 = u8_bit_decomposition(t13[5]);
      let d12_6 = u8_bit_decomposition(t13[6]);
      let d12_7 = u8_bit_decomposition(t13[7]);
      let b12 = [
        u8_from_field_unsafe(d12_4[7] + 2 * d12_5[0] + 4 * d12_5[1] + 8 * d12_5[2] + 16 * d12_5[3] + 32 * d12_5[4] + 64 * d12_5[5] + 128 * d12_5[6]),
        u8_from_field_unsafe(d12_5[7] + 2 * d12_6[0] + 4 * d12_6[1] + 8 * d12_6[2] + 16 * d12_6[3] + 32 * d12_6[4] + 64 * d12_6[5] + 128 * d12_6[6]),
        u8_from_field_unsafe(d12_6[7] + 2 * d12_7[0] + 4 * d12_7[1] + 8 * d12_7[2] + 16 * d12_7[3] + 32 * d12_7[4] + 64 * d12_7[5] + 128 * d12_7[6]),
        u8_from_field_unsafe(d12_7[7] + 2 * d12_0[0] + 4 * d12_0[1] + 8 * d12_0[2] + 16 * d12_0[3] + 32 * d12_0[4] + 64 * d12_0[5] + 128 * d12_0[6]),
        u8_from_field_unsafe(d12_0[7] + 2 * d12_1[0] + 4 * d12_1[1] + 8 * d12_1[2] + 16 * d12_1[3] + 32 * d12_1[4] + 64 * d12_1[5] + 128 * d12_1[6]),
        u8_from_field_unsafe(d12_1[7] + 2 * d12_2[0] + 4 * d12_2[1] + 8 * d12_2[2] + 16 * d12_2[3] + 32 * d12_2[4] + 64 * d12_2[5] + 128 * d12_2[6]),
        u8_from_field_unsafe(d12_2[7] + 2 * d12_3[0] + 4 * d12_3[1] + 8 * d12_3[2] + 16 * d12_3[3] + 32 * d12_3[4] + 64 * d12_3[5] + 128 * d12_3[6]),
        u8_from_field_unsafe(d12_3[7] + 2 * d12_4[0] + 4 * d12_4[1] + 8 * d12_4[2] + 16 * d12_4[3] + 32 * d12_4[4] + 64 * d12_4[5] + 128 * d12_4[6])
      ];
      -- b22 = rotl(t14, 39) = byte-rotl 4 + bit-shl 7
      let d22_0 = u8_bit_decomposition(t14[0]);
      let d22_1 = u8_bit_decomposition(t14[1]);
      let d22_2 = u8_bit_decomposition(t14[2]);
      let d22_3 = u8_bit_decomposition(t14[3]);
      let d22_4 = u8_bit_decomposition(t14[4]);
      let d22_5 = u8_bit_decomposition(t14[5]);
      let d22_6 = u8_bit_decomposition(t14[6]);
      let d22_7 = u8_bit_decomposition(t14[7]);
      let b22 = [
        u8_from_field_unsafe(d22_3[1] + 2 * d22_3[2] + 4 * d22_3[3] + 8 * d22_3[4] + 16 * d22_3[5] + 32 * d22_3[6] + 64 * d22_3[7] + 128 * d22_4[0]),
        u8_from_field_unsafe(d22_4[1] + 2 * d22_4[2] + 4 * d22_4[3] + 8 * d22_4[4] + 16 * d22_4[5] + 32 * d22_4[6] + 64 * d22_4[7] + 128 * d22_5[0]),
        u8_from_field_unsafe(d22_5[1] + 2 * d22_5[2] + 4 * d22_5[3] + 8 * d22_5[4] + 16 * d22_5[5] + 32 * d22_5[6] + 64 * d22_5[7] + 128 * d22_6[0]),
        u8_from_field_unsafe(d22_6[1] + 2 * d22_6[2] + 4 * d22_6[3] + 8 * d22_6[4] + 16 * d22_6[5] + 32 * d22_6[6] + 64 * d22_6[7] + 128 * d22_7[0]),
        u8_from_field_unsafe(d22_7[1] + 2 * d22_7[2] + 4 * d22_7[3] + 8 * d22_7[4] + 16 * d22_7[5] + 32 * d22_7[6] + 64 * d22_7[7] + 128 * d22_0[0]),
        u8_from_field_unsafe(d22_0[1] + 2 * d22_0[2] + 4 * d22_0[3] + 8 * d22_0[4] + 16 * d22_0[5] + 32 * d22_0[6] + 64 * d22_0[7] + 128 * d22_1[0]),
        u8_from_field_unsafe(d22_1[1] + 2 * d22_1[2] + 4 * d22_1[3] + 8 * d22_1[4] + 16 * d22_1[5] + 32 * d22_1[6] + 64 * d22_1[7] + 128 * d22_2[0]),
        u8_from_field_unsafe(d22_2[1] + 2 * d22_2[2] + 4 * d22_2[3] + 8 * d22_2[4] + 16 * d22_2[5] + 32 * d22_2[6] + 64 * d22_2[7] + 128 * d22_3[0])
      ];
      -- b23 = rotl(t15, 41) = byte-rotl 5 + bit-shl 1
      let d23_0 = u8_bit_decomposition(t15[0]);
      let d23_1 = u8_bit_decomposition(t15[1]);
      let d23_2 = u8_bit_decomposition(t15[2]);
      let d23_3 = u8_bit_decomposition(t15[3]);
      let d23_4 = u8_bit_decomposition(t15[4]);
      let d23_5 = u8_bit_decomposition(t15[5]);
      let d23_6 = u8_bit_decomposition(t15[6]);
      let d23_7 = u8_bit_decomposition(t15[7]);
      let b23 = [
        u8_from_field_unsafe(d23_2[7] + 2 * d23_3[0] + 4 * d23_3[1] + 8 * d23_3[2] + 16 * d23_3[3] + 32 * d23_3[4] + 64 * d23_3[5] + 128 * d23_3[6]),
        u8_from_field_unsafe(d23_3[7] + 2 * d23_4[0] + 4 * d23_4[1] + 8 * d23_4[2] + 16 * d23_4[3] + 32 * d23_4[4] + 64 * d23_4[5] + 128 * d23_4[6]),
        u8_from_field_unsafe(d23_4[7] + 2 * d23_5[0] + 4 * d23_5[1] + 8 * d23_5[2] + 16 * d23_5[3] + 32 * d23_5[4] + 64 * d23_5[5] + 128 * d23_5[6]),
        u8_from_field_unsafe(d23_5[7] + 2 * d23_6[0] + 4 * d23_6[1] + 8 * d23_6[2] + 16 * d23_6[3] + 32 * d23_6[4] + 64 * d23_6[5] + 128 * d23_6[6]),
        u8_from_field_unsafe(d23_6[7] + 2 * d23_7[0] + 4 * d23_7[1] + 8 * d23_7[2] + 16 * d23_7[3] + 32 * d23_7[4] + 64 * d23_7[5] + 128 * d23_7[6]),
        u8_from_field_unsafe(d23_7[7] + 2 * d23_0[0] + 4 * d23_0[1] + 8 * d23_0[2] + 16 * d23_0[3] + 32 * d23_0[4] + 64 * d23_0[5] + 128 * d23_0[6]),
        u8_from_field_unsafe(d23_0[7] + 2 * d23_1[0] + 4 * d23_1[1] + 8 * d23_1[2] + 16 * d23_1[3] + 32 * d23_1[4] + 64 * d23_1[5] + 128 * d23_1[6]),
        u8_from_field_unsafe(d23_1[7] + 2 * d23_2[0] + 4 * d23_2[1] + 8 * d23_2[2] + 16 * d23_2[3] + 32 * d23_2[4] + 64 * d23_2[5] + 128 * d23_2[6])
      ];
      -- b8 = rotl(t16, 45) = byte-rotl 5 + bit-shl 5
      let d8_0 = u8_bit_decomposition(t16[0]);
      let d8_1 = u8_bit_decomposition(t16[1]);
      let d8_2 = u8_bit_decomposition(t16[2]);
      let d8_3 = u8_bit_decomposition(t16[3]);
      let d8_4 = u8_bit_decomposition(t16[4]);
      let d8_5 = u8_bit_decomposition(t16[5]);
      let d8_6 = u8_bit_decomposition(t16[6]);
      let d8_7 = u8_bit_decomposition(t16[7]);
      let b8 = [
        u8_from_field_unsafe(d8_2[3] + 2 * d8_2[4] + 4 * d8_2[5] + 8 * d8_2[6] + 16 * d8_2[7] + 32 * d8_3[0] + 64 * d8_3[1] + 128 * d8_3[2]),
        u8_from_field_unsafe(d8_3[3] + 2 * d8_3[4] + 4 * d8_3[5] + 8 * d8_3[6] + 16 * d8_3[7] + 32 * d8_4[0] + 64 * d8_4[1] + 128 * d8_4[2]),
        u8_from_field_unsafe(d8_4[3] + 2 * d8_4[4] + 4 * d8_4[5] + 8 * d8_4[6] + 16 * d8_4[7] + 32 * d8_5[0] + 64 * d8_5[1] + 128 * d8_5[2]),
        u8_from_field_unsafe(d8_5[3] + 2 * d8_5[4] + 4 * d8_5[5] + 8 * d8_5[6] + 16 * d8_5[7] + 32 * d8_6[0] + 64 * d8_6[1] + 128 * d8_6[2]),
        u8_from_field_unsafe(d8_6[3] + 2 * d8_6[4] + 4 * d8_6[5] + 8 * d8_6[6] + 16 * d8_6[7] + 32 * d8_7[0] + 64 * d8_7[1] + 128 * d8_7[2]),
        u8_from_field_unsafe(d8_7[3] + 2 * d8_7[4] + 4 * d8_7[5] + 8 * d8_7[6] + 16 * d8_7[7] + 32 * d8_0[0] + 64 * d8_0[1] + 128 * d8_0[2]),
        u8_from_field_unsafe(d8_0[3] + 2 * d8_0[4] + 4 * d8_0[5] + 8 * d8_0[6] + 16 * d8_0[7] + 32 * d8_1[0] + 64 * d8_1[1] + 128 * d8_1[2]),
        u8_from_field_unsafe(d8_1[3] + 2 * d8_1[4] + 4 * d8_1[5] + 8 * d8_1[6] + 16 * d8_1[7] + 32 * d8_2[0] + 64 * d8_2[1] + 128 * d8_2[2])
      ];
      -- b18 = rotl(t17, 15) = byte-rotl 1 + bit-shl 7
      let d18_0 = u8_bit_decomposition(t17[0]);
      let d18_1 = u8_bit_decomposition(t17[1]);
      let d18_2 = u8_bit_decomposition(t17[2]);
      let d18_3 = u8_bit_decomposition(t17[3]);
      let d18_4 = u8_bit_decomposition(t17[4]);
      let d18_5 = u8_bit_decomposition(t17[5]);
      let d18_6 = u8_bit_decomposition(t17[6]);
      let d18_7 = u8_bit_decomposition(t17[7]);
      let b18 = [
        u8_from_field_unsafe(d18_6[1] + 2 * d18_6[2] + 4 * d18_6[3] + 8 * d18_6[4] + 16 * d18_6[5] + 32 * d18_6[6] + 64 * d18_6[7] + 128 * d18_7[0]),
        u8_from_field_unsafe(d18_7[1] + 2 * d18_7[2] + 4 * d18_7[3] + 8 * d18_7[4] + 16 * d18_7[5] + 32 * d18_7[6] + 64 * d18_7[7] + 128 * d18_0[0]),
        u8_from_field_unsafe(d18_0[1] + 2 * d18_0[2] + 4 * d18_0[3] + 8 * d18_0[4] + 16 * d18_0[5] + 32 * d18_0[6] + 64 * d18_0[7] + 128 * d18_1[0]),
        u8_from_field_unsafe(d18_1[1] + 2 * d18_1[2] + 4 * d18_1[3] + 8 * d18_1[4] + 16 * d18_1[5] + 32 * d18_1[6] + 64 * d18_1[7] + 128 * d18_2[0]),
        u8_from_field_unsafe(d18_2[1] + 2 * d18_2[2] + 4 * d18_2[3] + 8 * d18_2[4] + 16 * d18_2[5] + 32 * d18_2[6] + 64 * d18_2[7] + 128 * d18_3[0]),
        u8_from_field_unsafe(d18_3[1] + 2 * d18_3[2] + 4 * d18_3[3] + 8 * d18_3[4] + 16 * d18_3[5] + 32 * d18_3[6] + 64 * d18_3[7] + 128 * d18_4[0]),
        u8_from_field_unsafe(d18_4[1] + 2 * d18_4[2] + 4 * d18_4[3] + 8 * d18_4[4] + 16 * d18_4[5] + 32 * d18_4[6] + 64 * d18_4[7] + 128 * d18_5[0]),
        u8_from_field_unsafe(d18_5[1] + 2 * d18_5[2] + 4 * d18_5[3] + 8 * d18_5[4] + 16 * d18_5[5] + 32 * d18_5[6] + 64 * d18_5[7] + 128 * d18_6[0])
      ];
      -- b3 = rotl(t18, 21) = byte-rotl 2 + bit-shl 5
      let d3_0 = u8_bit_decomposition(t18[0]);
      let d3_1 = u8_bit_decomposition(t18[1]);
      let d3_2 = u8_bit_decomposition(t18[2]);
      let d3_3 = u8_bit_decomposition(t18[3]);
      let d3_4 = u8_bit_decomposition(t18[4]);
      let d3_5 = u8_bit_decomposition(t18[5]);
      let d3_6 = u8_bit_decomposition(t18[6]);
      let d3_7 = u8_bit_decomposition(t18[7]);
      let b3 = [
        u8_from_field_unsafe(d3_5[3] + 2 * d3_5[4] + 4 * d3_5[5] + 8 * d3_5[6] + 16 * d3_5[7] + 32 * d3_6[0] + 64 * d3_6[1] + 128 * d3_6[2]),
        u8_from_field_unsafe(d3_6[3] + 2 * d3_6[4] + 4 * d3_6[5] + 8 * d3_6[6] + 16 * d3_6[7] + 32 * d3_7[0] + 64 * d3_7[1] + 128 * d3_7[2]),
        u8_from_field_unsafe(d3_7[3] + 2 * d3_7[4] + 4 * d3_7[5] + 8 * d3_7[6] + 16 * d3_7[7] + 32 * d3_0[0] + 64 * d3_0[1] + 128 * d3_0[2]),
        u8_from_field_unsafe(d3_0[3] + 2 * d3_0[4] + 4 * d3_0[5] + 8 * d3_0[6] + 16 * d3_0[7] + 32 * d3_1[0] + 64 * d3_1[1] + 128 * d3_1[2]),
        u8_from_field_unsafe(d3_1[3] + 2 * d3_1[4] + 4 * d3_1[5] + 8 * d3_1[6] + 16 * d3_1[7] + 32 * d3_2[0] + 64 * d3_2[1] + 128 * d3_2[2]),
        u8_from_field_unsafe(d3_2[3] + 2 * d3_2[4] + 4 * d3_2[5] + 8 * d3_2[6] + 16 * d3_2[7] + 32 * d3_3[0] + 64 * d3_3[1] + 128 * d3_3[2]),
        u8_from_field_unsafe(d3_3[3] + 2 * d3_3[4] + 4 * d3_3[5] + 8 * d3_3[6] + 16 * d3_3[7] + 32 * d3_4[0] + 64 * d3_4[1] + 128 * d3_4[2]),
        u8_from_field_unsafe(d3_4[3] + 2 * d3_4[4] + 4 * d3_4[5] + 8 * d3_4[6] + 16 * d3_4[7] + 32 * d3_5[0] + 64 * d3_5[1] + 128 * d3_5[2])
      ];
      -- b13 = rotl(t19, 8): byte rotation only (free)
      let b13 = [t19[7], t19[0], t19[1], t19[2], t19[3], t19[4], t19[5], t19[6]];
      -- b14 = rotl(t20, 18) = byte-rotl 2 + bit-shl 2
      let d14_0 = u8_bit_decomposition(t20[0]);
      let d14_1 = u8_bit_decomposition(t20[1]);
      let d14_2 = u8_bit_decomposition(t20[2]);
      let d14_3 = u8_bit_decomposition(t20[3]);
      let d14_4 = u8_bit_decomposition(t20[4]);
      let d14_5 = u8_bit_decomposition(t20[5]);
      let d14_6 = u8_bit_decomposition(t20[6]);
      let d14_7 = u8_bit_decomposition(t20[7]);
      let b14 = [
        u8_from_field_unsafe(d14_5[6] + 2 * d14_5[7] + 4 * d14_6[0] + 8 * d14_6[1] + 16 * d14_6[2] + 32 * d14_6[3] + 64 * d14_6[4] + 128 * d14_6[5]),
        u8_from_field_unsafe(d14_6[6] + 2 * d14_6[7] + 4 * d14_7[0] + 8 * d14_7[1] + 16 * d14_7[2] + 32 * d14_7[3] + 64 * d14_7[4] + 128 * d14_7[5]),
        u8_from_field_unsafe(d14_7[6] + 2 * d14_7[7] + 4 * d14_0[0] + 8 * d14_0[1] + 16 * d14_0[2] + 32 * d14_0[3] + 64 * d14_0[4] + 128 * d14_0[5]),
        u8_from_field_unsafe(d14_0[6] + 2 * d14_0[7] + 4 * d14_1[0] + 8 * d14_1[1] + 16 * d14_1[2] + 32 * d14_1[3] + 64 * d14_1[4] + 128 * d14_1[5]),
        u8_from_field_unsafe(d14_1[6] + 2 * d14_1[7] + 4 * d14_2[0] + 8 * d14_2[1] + 16 * d14_2[2] + 32 * d14_2[3] + 64 * d14_2[4] + 128 * d14_2[5]),
        u8_from_field_unsafe(d14_2[6] + 2 * d14_2[7] + 4 * d14_3[0] + 8 * d14_3[1] + 16 * d14_3[2] + 32 * d14_3[3] + 64 * d14_3[4] + 128 * d14_3[5]),
        u8_from_field_unsafe(d14_3[6] + 2 * d14_3[7] + 4 * d14_4[0] + 8 * d14_4[1] + 16 * d14_4[2] + 32 * d14_4[3] + 64 * d14_4[4] + 128 * d14_4[5]),
        u8_from_field_unsafe(d14_4[6] + 2 * d14_4[7] + 4 * d14_5[0] + 8 * d14_5[1] + 16 * d14_5[2] + 32 * d14_5[3] + 64 * d14_5[4] + 128 * d14_5[5])
      ];
      -- b24 = rotl(t21, 2) = byte-rotl 0 + bit-shl 2
      let d24_0 = u8_bit_decomposition(t21[0]);
      let d24_1 = u8_bit_decomposition(t21[1]);
      let d24_2 = u8_bit_decomposition(t21[2]);
      let d24_3 = u8_bit_decomposition(t21[3]);
      let d24_4 = u8_bit_decomposition(t21[4]);
      let d24_5 = u8_bit_decomposition(t21[5]);
      let d24_6 = u8_bit_decomposition(t21[6]);
      let d24_7 = u8_bit_decomposition(t21[7]);
      let b24 = [
        u8_from_field_unsafe(d24_7[6] + 2 * d24_7[7] + 4 * d24_0[0] + 8 * d24_0[1] + 16 * d24_0[2] + 32 * d24_0[3] + 64 * d24_0[4] + 128 * d24_0[5]),
        u8_from_field_unsafe(d24_0[6] + 2 * d24_0[7] + 4 * d24_1[0] + 8 * d24_1[1] + 16 * d24_1[2] + 32 * d24_1[3] + 64 * d24_1[4] + 128 * d24_1[5]),
        u8_from_field_unsafe(d24_1[6] + 2 * d24_1[7] + 4 * d24_2[0] + 8 * d24_2[1] + 16 * d24_2[2] + 32 * d24_2[3] + 64 * d24_2[4] + 128 * d24_2[5]),
        u8_from_field_unsafe(d24_2[6] + 2 * d24_2[7] + 4 * d24_3[0] + 8 * d24_3[1] + 16 * d24_3[2] + 32 * d24_3[3] + 64 * d24_3[4] + 128 * d24_3[5]),
        u8_from_field_unsafe(d24_3[6] + 2 * d24_3[7] + 4 * d24_4[0] + 8 * d24_4[1] + 16 * d24_4[2] + 32 * d24_4[3] + 64 * d24_4[4] + 128 * d24_4[5]),
        u8_from_field_unsafe(d24_4[6] + 2 * d24_4[7] + 4 * d24_5[0] + 8 * d24_5[1] + 16 * d24_5[2] + 32 * d24_5[3] + 64 * d24_5[4] + 128 * d24_5[5]),
        u8_from_field_unsafe(d24_5[6] + 2 * d24_5[7] + 4 * d24_6[0] + 8 * d24_6[1] + 16 * d24_6[2] + 32 * d24_6[3] + 64 * d24_6[4] + 128 * d24_6[5]),
        u8_from_field_unsafe(d24_6[6] + 2 * d24_6[7] + 4 * d24_7[0] + 8 * d24_7[1] + 16 * d24_7[2] + 32 * d24_7[3] + 64 * d24_7[4] + 128 * d24_7[5])
      ];
      -- b9 = rotl(t22, 61) = byte-rotl 7 + bit-shl 5
      let d9_0 = u8_bit_decomposition(t22[0]);
      let d9_1 = u8_bit_decomposition(t22[1]);
      let d9_2 = u8_bit_decomposition(t22[2]);
      let d9_3 = u8_bit_decomposition(t22[3]);
      let d9_4 = u8_bit_decomposition(t22[4]);
      let d9_5 = u8_bit_decomposition(t22[5]);
      let d9_6 = u8_bit_decomposition(t22[6]);
      let d9_7 = u8_bit_decomposition(t22[7]);
      let b9 = [
        u8_from_field_unsafe(d9_0[3] + 2 * d9_0[4] + 4 * d9_0[5] + 8 * d9_0[6] + 16 * d9_0[7] + 32 * d9_1[0] + 64 * d9_1[1] + 128 * d9_1[2]),
        u8_from_field_unsafe(d9_1[3] + 2 * d9_1[4] + 4 * d9_1[5] + 8 * d9_1[6] + 16 * d9_1[7] + 32 * d9_2[0] + 64 * d9_2[1] + 128 * d9_2[2]),
        u8_from_field_unsafe(d9_2[3] + 2 * d9_2[4] + 4 * d9_2[5] + 8 * d9_2[6] + 16 * d9_2[7] + 32 * d9_3[0] + 64 * d9_3[1] + 128 * d9_3[2]),
        u8_from_field_unsafe(d9_3[3] + 2 * d9_3[4] + 4 * d9_3[5] + 8 * d9_3[6] + 16 * d9_3[7] + 32 * d9_4[0] + 64 * d9_4[1] + 128 * d9_4[2]),
        u8_from_field_unsafe(d9_4[3] + 2 * d9_4[4] + 4 * d9_4[5] + 8 * d9_4[6] + 16 * d9_4[7] + 32 * d9_5[0] + 64 * d9_5[1] + 128 * d9_5[2]),
        u8_from_field_unsafe(d9_5[3] + 2 * d9_5[4] + 4 * d9_5[5] + 8 * d9_5[6] + 16 * d9_5[7] + 32 * d9_6[0] + 64 * d9_6[1] + 128 * d9_6[2]),
        u8_from_field_unsafe(d9_6[3] + 2 * d9_6[4] + 4 * d9_6[5] + 8 * d9_6[6] + 16 * d9_6[7] + 32 * d9_7[0] + 64 * d9_7[1] + 128 * d9_7[2]),
        u8_from_field_unsafe(d9_7[3] + 2 * d9_7[4] + 4 * d9_7[5] + 8 * d9_7[6] + 16 * d9_7[7] + 32 * d9_0[0] + 64 * d9_0[1] + 128 * d9_0[2])
      ];
      -- b19 = rotl(t23, 56): byte rotation only (free)
      let b19 = [t23[1], t23[2], t23[3], t23[4], t23[5], t23[6], t23[7], t23[0]];
      -- b4 = rotl(t24, 14) = byte-rotl 1 + bit-shl 6
      let d4_0 = u8_bit_decomposition(t24[0]);
      let d4_1 = u8_bit_decomposition(t24[1]);
      let d4_2 = u8_bit_decomposition(t24[2]);
      let d4_3 = u8_bit_decomposition(t24[3]);
      let d4_4 = u8_bit_decomposition(t24[4]);
      let d4_5 = u8_bit_decomposition(t24[5]);
      let d4_6 = u8_bit_decomposition(t24[6]);
      let d4_7 = u8_bit_decomposition(t24[7]);
      let b4 = [
        u8_from_field_unsafe(d4_6[2] + 2 * d4_6[3] + 4 * d4_6[4] + 8 * d4_6[5] + 16 * d4_6[6] + 32 * d4_6[7] + 64 * d4_7[0] + 128 * d4_7[1]),
        u8_from_field_unsafe(d4_7[2] + 2 * d4_7[3] + 4 * d4_7[4] + 8 * d4_7[5] + 16 * d4_7[6] + 32 * d4_7[7] + 64 * d4_0[0] + 128 * d4_0[1]),
        u8_from_field_unsafe(d4_0[2] + 2 * d4_0[3] + 4 * d4_0[4] + 8 * d4_0[5] + 16 * d4_0[6] + 32 * d4_0[7] + 64 * d4_1[0] + 128 * d4_1[1]),
        u8_from_field_unsafe(d4_1[2] + 2 * d4_1[3] + 4 * d4_1[4] + 8 * d4_1[5] + 16 * d4_1[6] + 32 * d4_1[7] + 64 * d4_2[0] + 128 * d4_2[1]),
        u8_from_field_unsafe(d4_2[2] + 2 * d4_2[3] + 4 * d4_2[4] + 8 * d4_2[5] + 16 * d4_2[6] + 32 * d4_2[7] + 64 * d4_3[0] + 128 * d4_3[1]),
        u8_from_field_unsafe(d4_3[2] + 2 * d4_3[3] + 4 * d4_3[4] + 8 * d4_3[5] + 16 * d4_3[6] + 32 * d4_3[7] + 64 * d4_4[0] + 128 * d4_4[1]),
        u8_from_field_unsafe(d4_4[2] + 2 * d4_4[3] + 4 * d4_4[4] + 8 * d4_4[5] + 16 * d4_4[6] + 32 * d4_4[7] + 64 * d4_5[0] + 128 * d4_5[1]),
        u8_from_field_unsafe(d4_5[2] + 2 * d4_5[3] + 4 * d4_5[4] + 8 * d4_5[5] + 16 * d4_5[6] + 32 * d4_5[7] + 64 * d4_6[0] + 128 * d4_6[1])
      ];
      -- chi: e[x,y] = b[x,y] ^ (~b[x+1,y] & b[x+2,y]); NOT is the free
      -- recomposition 255 - b.
      let e0 = [u8_xor(b0[0], u8_and(u8_from_field_unsafe(255 - to_field(b1[0])), b2[0])), u8_xor(b0[1], u8_and(u8_from_field_unsafe(255 - to_field(b1[1])), b2[1])), u8_xor(b0[2], u8_and(u8_from_field_unsafe(255 - to_field(b1[2])), b2[2])), u8_xor(b0[3], u8_and(u8_from_field_unsafe(255 - to_field(b1[3])), b2[3])), u8_xor(b0[4], u8_and(u8_from_field_unsafe(255 - to_field(b1[4])), b2[4])), u8_xor(b0[5], u8_and(u8_from_field_unsafe(255 - to_field(b1[5])), b2[5])), u8_xor(b0[6], u8_and(u8_from_field_unsafe(255 - to_field(b1[6])), b2[6])), u8_xor(b0[7], u8_and(u8_from_field_unsafe(255 - to_field(b1[7])), b2[7]))];
      let e1 = [u8_xor(b1[0], u8_and(u8_from_field_unsafe(255 - to_field(b2[0])), b3[0])), u8_xor(b1[1], u8_and(u8_from_field_unsafe(255 - to_field(b2[1])), b3[1])), u8_xor(b1[2], u8_and(u8_from_field_unsafe(255 - to_field(b2[2])), b3[2])), u8_xor(b1[3], u8_and(u8_from_field_unsafe(255 - to_field(b2[3])), b3[3])), u8_xor(b1[4], u8_and(u8_from_field_unsafe(255 - to_field(b2[4])), b3[4])), u8_xor(b1[5], u8_and(u8_from_field_unsafe(255 - to_field(b2[5])), b3[5])), u8_xor(b1[6], u8_and(u8_from_field_unsafe(255 - to_field(b2[6])), b3[6])), u8_xor(b1[7], u8_and(u8_from_field_unsafe(255 - to_field(b2[7])), b3[7]))];
      let e2 = [u8_xor(b2[0], u8_and(u8_from_field_unsafe(255 - to_field(b3[0])), b4[0])), u8_xor(b2[1], u8_and(u8_from_field_unsafe(255 - to_field(b3[1])), b4[1])), u8_xor(b2[2], u8_and(u8_from_field_unsafe(255 - to_field(b3[2])), b4[2])), u8_xor(b2[3], u8_and(u8_from_field_unsafe(255 - to_field(b3[3])), b4[3])), u8_xor(b2[4], u8_and(u8_from_field_unsafe(255 - to_field(b3[4])), b4[4])), u8_xor(b2[5], u8_and(u8_from_field_unsafe(255 - to_field(b3[5])), b4[5])), u8_xor(b2[6], u8_and(u8_from_field_unsafe(255 - to_field(b3[6])), b4[6])), u8_xor(b2[7], u8_and(u8_from_field_unsafe(255 - to_field(b3[7])), b4[7]))];
      let e3 = [u8_xor(b3[0], u8_and(u8_from_field_unsafe(255 - to_field(b4[0])), b0[0])), u8_xor(b3[1], u8_and(u8_from_field_unsafe(255 - to_field(b4[1])), b0[1])), u8_xor(b3[2], u8_and(u8_from_field_unsafe(255 - to_field(b4[2])), b0[2])), u8_xor(b3[3], u8_and(u8_from_field_unsafe(255 - to_field(b4[3])), b0[3])), u8_xor(b3[4], u8_and(u8_from_field_unsafe(255 - to_field(b4[4])), b0[4])), u8_xor(b3[5], u8_and(u8_from_field_unsafe(255 - to_field(b4[5])), b0[5])), u8_xor(b3[6], u8_and(u8_from_field_unsafe(255 - to_field(b4[6])), b0[6])), u8_xor(b3[7], u8_and(u8_from_field_unsafe(255 - to_field(b4[7])), b0[7]))];
      let e4 = [u8_xor(b4[0], u8_and(u8_from_field_unsafe(255 - to_field(b0[0])), b1[0])), u8_xor(b4[1], u8_and(u8_from_field_unsafe(255 - to_field(b0[1])), b1[1])), u8_xor(b4[2], u8_and(u8_from_field_unsafe(255 - to_field(b0[2])), b1[2])), u8_xor(b4[3], u8_and(u8_from_field_unsafe(255 - to_field(b0[3])), b1[3])), u8_xor(b4[4], u8_and(u8_from_field_unsafe(255 - to_field(b0[4])), b1[4])), u8_xor(b4[5], u8_and(u8_from_field_unsafe(255 - to_field(b0[5])), b1[5])), u8_xor(b4[6], u8_and(u8_from_field_unsafe(255 - to_field(b0[6])), b1[6])), u8_xor(b4[7], u8_and(u8_from_field_unsafe(255 - to_field(b0[7])), b1[7]))];
      let e5 = [u8_xor(b5[0], u8_and(u8_from_field_unsafe(255 - to_field(b6[0])), b7[0])), u8_xor(b5[1], u8_and(u8_from_field_unsafe(255 - to_field(b6[1])), b7[1])), u8_xor(b5[2], u8_and(u8_from_field_unsafe(255 - to_field(b6[2])), b7[2])), u8_xor(b5[3], u8_and(u8_from_field_unsafe(255 - to_field(b6[3])), b7[3])), u8_xor(b5[4], u8_and(u8_from_field_unsafe(255 - to_field(b6[4])), b7[4])), u8_xor(b5[5], u8_and(u8_from_field_unsafe(255 - to_field(b6[5])), b7[5])), u8_xor(b5[6], u8_and(u8_from_field_unsafe(255 - to_field(b6[6])), b7[6])), u8_xor(b5[7], u8_and(u8_from_field_unsafe(255 - to_field(b6[7])), b7[7]))];
      let e6 = [u8_xor(b6[0], u8_and(u8_from_field_unsafe(255 - to_field(b7[0])), b8[0])), u8_xor(b6[1], u8_and(u8_from_field_unsafe(255 - to_field(b7[1])), b8[1])), u8_xor(b6[2], u8_and(u8_from_field_unsafe(255 - to_field(b7[2])), b8[2])), u8_xor(b6[3], u8_and(u8_from_field_unsafe(255 - to_field(b7[3])), b8[3])), u8_xor(b6[4], u8_and(u8_from_field_unsafe(255 - to_field(b7[4])), b8[4])), u8_xor(b6[5], u8_and(u8_from_field_unsafe(255 - to_field(b7[5])), b8[5])), u8_xor(b6[6], u8_and(u8_from_field_unsafe(255 - to_field(b7[6])), b8[6])), u8_xor(b6[7], u8_and(u8_from_field_unsafe(255 - to_field(b7[7])), b8[7]))];
      let e7 = [u8_xor(b7[0], u8_and(u8_from_field_unsafe(255 - to_field(b8[0])), b9[0])), u8_xor(b7[1], u8_and(u8_from_field_unsafe(255 - to_field(b8[1])), b9[1])), u8_xor(b7[2], u8_and(u8_from_field_unsafe(255 - to_field(b8[2])), b9[2])), u8_xor(b7[3], u8_and(u8_from_field_unsafe(255 - to_field(b8[3])), b9[3])), u8_xor(b7[4], u8_and(u8_from_field_unsafe(255 - to_field(b8[4])), b9[4])), u8_xor(b7[5], u8_and(u8_from_field_unsafe(255 - to_field(b8[5])), b9[5])), u8_xor(b7[6], u8_and(u8_from_field_unsafe(255 - to_field(b8[6])), b9[6])), u8_xor(b7[7], u8_and(u8_from_field_unsafe(255 - to_field(b8[7])), b9[7]))];
      let e8 = [u8_xor(b8[0], u8_and(u8_from_field_unsafe(255 - to_field(b9[0])), b5[0])), u8_xor(b8[1], u8_and(u8_from_field_unsafe(255 - to_field(b9[1])), b5[1])), u8_xor(b8[2], u8_and(u8_from_field_unsafe(255 - to_field(b9[2])), b5[2])), u8_xor(b8[3], u8_and(u8_from_field_unsafe(255 - to_field(b9[3])), b5[3])), u8_xor(b8[4], u8_and(u8_from_field_unsafe(255 - to_field(b9[4])), b5[4])), u8_xor(b8[5], u8_and(u8_from_field_unsafe(255 - to_field(b9[5])), b5[5])), u8_xor(b8[6], u8_and(u8_from_field_unsafe(255 - to_field(b9[6])), b5[6])), u8_xor(b8[7], u8_and(u8_from_field_unsafe(255 - to_field(b9[7])), b5[7]))];
      let e9 = [u8_xor(b9[0], u8_and(u8_from_field_unsafe(255 - to_field(b5[0])), b6[0])), u8_xor(b9[1], u8_and(u8_from_field_unsafe(255 - to_field(b5[1])), b6[1])), u8_xor(b9[2], u8_and(u8_from_field_unsafe(255 - to_field(b5[2])), b6[2])), u8_xor(b9[3], u8_and(u8_from_field_unsafe(255 - to_field(b5[3])), b6[3])), u8_xor(b9[4], u8_and(u8_from_field_unsafe(255 - to_field(b5[4])), b6[4])), u8_xor(b9[5], u8_and(u8_from_field_unsafe(255 - to_field(b5[5])), b6[5])), u8_xor(b9[6], u8_and(u8_from_field_unsafe(255 - to_field(b5[6])), b6[6])), u8_xor(b9[7], u8_and(u8_from_field_unsafe(255 - to_field(b5[7])), b6[7]))];
      let e10 = [u8_xor(b10[0], u8_and(u8_from_field_unsafe(255 - to_field(b11[0])), b12[0])), u8_xor(b10[1], u8_and(u8_from_field_unsafe(255 - to_field(b11[1])), b12[1])), u8_xor(b10[2], u8_and(u8_from_field_unsafe(255 - to_field(b11[2])), b12[2])), u8_xor(b10[3], u8_and(u8_from_field_unsafe(255 - to_field(b11[3])), b12[3])), u8_xor(b10[4], u8_and(u8_from_field_unsafe(255 - to_field(b11[4])), b12[4])), u8_xor(b10[5], u8_and(u8_from_field_unsafe(255 - to_field(b11[5])), b12[5])), u8_xor(b10[6], u8_and(u8_from_field_unsafe(255 - to_field(b11[6])), b12[6])), u8_xor(b10[7], u8_and(u8_from_field_unsafe(255 - to_field(b11[7])), b12[7]))];
      let e11 = [u8_xor(b11[0], u8_and(u8_from_field_unsafe(255 - to_field(b12[0])), b13[0])), u8_xor(b11[1], u8_and(u8_from_field_unsafe(255 - to_field(b12[1])), b13[1])), u8_xor(b11[2], u8_and(u8_from_field_unsafe(255 - to_field(b12[2])), b13[2])), u8_xor(b11[3], u8_and(u8_from_field_unsafe(255 - to_field(b12[3])), b13[3])), u8_xor(b11[4], u8_and(u8_from_field_unsafe(255 - to_field(b12[4])), b13[4])), u8_xor(b11[5], u8_and(u8_from_field_unsafe(255 - to_field(b12[5])), b13[5])), u8_xor(b11[6], u8_and(u8_from_field_unsafe(255 - to_field(b12[6])), b13[6])), u8_xor(b11[7], u8_and(u8_from_field_unsafe(255 - to_field(b12[7])), b13[7]))];
      let e12 = [u8_xor(b12[0], u8_and(u8_from_field_unsafe(255 - to_field(b13[0])), b14[0])), u8_xor(b12[1], u8_and(u8_from_field_unsafe(255 - to_field(b13[1])), b14[1])), u8_xor(b12[2], u8_and(u8_from_field_unsafe(255 - to_field(b13[2])), b14[2])), u8_xor(b12[3], u8_and(u8_from_field_unsafe(255 - to_field(b13[3])), b14[3])), u8_xor(b12[4], u8_and(u8_from_field_unsafe(255 - to_field(b13[4])), b14[4])), u8_xor(b12[5], u8_and(u8_from_field_unsafe(255 - to_field(b13[5])), b14[5])), u8_xor(b12[6], u8_and(u8_from_field_unsafe(255 - to_field(b13[6])), b14[6])), u8_xor(b12[7], u8_and(u8_from_field_unsafe(255 - to_field(b13[7])), b14[7]))];
      let e13 = [u8_xor(b13[0], u8_and(u8_from_field_unsafe(255 - to_field(b14[0])), b10[0])), u8_xor(b13[1], u8_and(u8_from_field_unsafe(255 - to_field(b14[1])), b10[1])), u8_xor(b13[2], u8_and(u8_from_field_unsafe(255 - to_field(b14[2])), b10[2])), u8_xor(b13[3], u8_and(u8_from_field_unsafe(255 - to_field(b14[3])), b10[3])), u8_xor(b13[4], u8_and(u8_from_field_unsafe(255 - to_field(b14[4])), b10[4])), u8_xor(b13[5], u8_and(u8_from_field_unsafe(255 - to_field(b14[5])), b10[5])), u8_xor(b13[6], u8_and(u8_from_field_unsafe(255 - to_field(b14[6])), b10[6])), u8_xor(b13[7], u8_and(u8_from_field_unsafe(255 - to_field(b14[7])), b10[7]))];
      let e14 = [u8_xor(b14[0], u8_and(u8_from_field_unsafe(255 - to_field(b10[0])), b11[0])), u8_xor(b14[1], u8_and(u8_from_field_unsafe(255 - to_field(b10[1])), b11[1])), u8_xor(b14[2], u8_and(u8_from_field_unsafe(255 - to_field(b10[2])), b11[2])), u8_xor(b14[3], u8_and(u8_from_field_unsafe(255 - to_field(b10[3])), b11[3])), u8_xor(b14[4], u8_and(u8_from_field_unsafe(255 - to_field(b10[4])), b11[4])), u8_xor(b14[5], u8_and(u8_from_field_unsafe(255 - to_field(b10[5])), b11[5])), u8_xor(b14[6], u8_and(u8_from_field_unsafe(255 - to_field(b10[6])), b11[6])), u8_xor(b14[7], u8_and(u8_from_field_unsafe(255 - to_field(b10[7])), b11[7]))];
      let e15 = [u8_xor(b15[0], u8_and(u8_from_field_unsafe(255 - to_field(b16[0])), b17[0])), u8_xor(b15[1], u8_and(u8_from_field_unsafe(255 - to_field(b16[1])), b17[1])), u8_xor(b15[2], u8_and(u8_from_field_unsafe(255 - to_field(b16[2])), b17[2])), u8_xor(b15[3], u8_and(u8_from_field_unsafe(255 - to_field(b16[3])), b17[3])), u8_xor(b15[4], u8_and(u8_from_field_unsafe(255 - to_field(b16[4])), b17[4])), u8_xor(b15[5], u8_and(u8_from_field_unsafe(255 - to_field(b16[5])), b17[5])), u8_xor(b15[6], u8_and(u8_from_field_unsafe(255 - to_field(b16[6])), b17[6])), u8_xor(b15[7], u8_and(u8_from_field_unsafe(255 - to_field(b16[7])), b17[7]))];
      let e16 = [u8_xor(b16[0], u8_and(u8_from_field_unsafe(255 - to_field(b17[0])), b18[0])), u8_xor(b16[1], u8_and(u8_from_field_unsafe(255 - to_field(b17[1])), b18[1])), u8_xor(b16[2], u8_and(u8_from_field_unsafe(255 - to_field(b17[2])), b18[2])), u8_xor(b16[3], u8_and(u8_from_field_unsafe(255 - to_field(b17[3])), b18[3])), u8_xor(b16[4], u8_and(u8_from_field_unsafe(255 - to_field(b17[4])), b18[4])), u8_xor(b16[5], u8_and(u8_from_field_unsafe(255 - to_field(b17[5])), b18[5])), u8_xor(b16[6], u8_and(u8_from_field_unsafe(255 - to_field(b17[6])), b18[6])), u8_xor(b16[7], u8_and(u8_from_field_unsafe(255 - to_field(b17[7])), b18[7]))];
      let e17 = [u8_xor(b17[0], u8_and(u8_from_field_unsafe(255 - to_field(b18[0])), b19[0])), u8_xor(b17[1], u8_and(u8_from_field_unsafe(255 - to_field(b18[1])), b19[1])), u8_xor(b17[2], u8_and(u8_from_field_unsafe(255 - to_field(b18[2])), b19[2])), u8_xor(b17[3], u8_and(u8_from_field_unsafe(255 - to_field(b18[3])), b19[3])), u8_xor(b17[4], u8_and(u8_from_field_unsafe(255 - to_field(b18[4])), b19[4])), u8_xor(b17[5], u8_and(u8_from_field_unsafe(255 - to_field(b18[5])), b19[5])), u8_xor(b17[6], u8_and(u8_from_field_unsafe(255 - to_field(b18[6])), b19[6])), u8_xor(b17[7], u8_and(u8_from_field_unsafe(255 - to_field(b18[7])), b19[7]))];
      let e18 = [u8_xor(b18[0], u8_and(u8_from_field_unsafe(255 - to_field(b19[0])), b15[0])), u8_xor(b18[1], u8_and(u8_from_field_unsafe(255 - to_field(b19[1])), b15[1])), u8_xor(b18[2], u8_and(u8_from_field_unsafe(255 - to_field(b19[2])), b15[2])), u8_xor(b18[3], u8_and(u8_from_field_unsafe(255 - to_field(b19[3])), b15[3])), u8_xor(b18[4], u8_and(u8_from_field_unsafe(255 - to_field(b19[4])), b15[4])), u8_xor(b18[5], u8_and(u8_from_field_unsafe(255 - to_field(b19[5])), b15[5])), u8_xor(b18[6], u8_and(u8_from_field_unsafe(255 - to_field(b19[6])), b15[6])), u8_xor(b18[7], u8_and(u8_from_field_unsafe(255 - to_field(b19[7])), b15[7]))];
      let e19 = [u8_xor(b19[0], u8_and(u8_from_field_unsafe(255 - to_field(b15[0])), b16[0])), u8_xor(b19[1], u8_and(u8_from_field_unsafe(255 - to_field(b15[1])), b16[1])), u8_xor(b19[2], u8_and(u8_from_field_unsafe(255 - to_field(b15[2])), b16[2])), u8_xor(b19[3], u8_and(u8_from_field_unsafe(255 - to_field(b15[3])), b16[3])), u8_xor(b19[4], u8_and(u8_from_field_unsafe(255 - to_field(b15[4])), b16[4])), u8_xor(b19[5], u8_and(u8_from_field_unsafe(255 - to_field(b15[5])), b16[5])), u8_xor(b19[6], u8_and(u8_from_field_unsafe(255 - to_field(b15[6])), b16[6])), u8_xor(b19[7], u8_and(u8_from_field_unsafe(255 - to_field(b15[7])), b16[7]))];
      let e20 = [u8_xor(b20[0], u8_and(u8_from_field_unsafe(255 - to_field(b21[0])), b22[0])), u8_xor(b20[1], u8_and(u8_from_field_unsafe(255 - to_field(b21[1])), b22[1])), u8_xor(b20[2], u8_and(u8_from_field_unsafe(255 - to_field(b21[2])), b22[2])), u8_xor(b20[3], u8_and(u8_from_field_unsafe(255 - to_field(b21[3])), b22[3])), u8_xor(b20[4], u8_and(u8_from_field_unsafe(255 - to_field(b21[4])), b22[4])), u8_xor(b20[5], u8_and(u8_from_field_unsafe(255 - to_field(b21[5])), b22[5])), u8_xor(b20[6], u8_and(u8_from_field_unsafe(255 - to_field(b21[6])), b22[6])), u8_xor(b20[7], u8_and(u8_from_field_unsafe(255 - to_field(b21[7])), b22[7]))];
      let e21 = [u8_xor(b21[0], u8_and(u8_from_field_unsafe(255 - to_field(b22[0])), b23[0])), u8_xor(b21[1], u8_and(u8_from_field_unsafe(255 - to_field(b22[1])), b23[1])), u8_xor(b21[2], u8_and(u8_from_field_unsafe(255 - to_field(b22[2])), b23[2])), u8_xor(b21[3], u8_and(u8_from_field_unsafe(255 - to_field(b22[3])), b23[3])), u8_xor(b21[4], u8_and(u8_from_field_unsafe(255 - to_field(b22[4])), b23[4])), u8_xor(b21[5], u8_and(u8_from_field_unsafe(255 - to_field(b22[5])), b23[5])), u8_xor(b21[6], u8_and(u8_from_field_unsafe(255 - to_field(b22[6])), b23[6])), u8_xor(b21[7], u8_and(u8_from_field_unsafe(255 - to_field(b22[7])), b23[7]))];
      let e22 = [u8_xor(b22[0], u8_and(u8_from_field_unsafe(255 - to_field(b23[0])), b24[0])), u8_xor(b22[1], u8_and(u8_from_field_unsafe(255 - to_field(b23[1])), b24[1])), u8_xor(b22[2], u8_and(u8_from_field_unsafe(255 - to_field(b23[2])), b24[2])), u8_xor(b22[3], u8_and(u8_from_field_unsafe(255 - to_field(b23[3])), b24[3])), u8_xor(b22[4], u8_and(u8_from_field_unsafe(255 - to_field(b23[4])), b24[4])), u8_xor(b22[5], u8_and(u8_from_field_unsafe(255 - to_field(b23[5])), b24[5])), u8_xor(b22[6], u8_and(u8_from_field_unsafe(255 - to_field(b23[6])), b24[6])), u8_xor(b22[7], u8_and(u8_from_field_unsafe(255 - to_field(b23[7])), b24[7]))];
      let e23 = [u8_xor(b23[0], u8_and(u8_from_field_unsafe(255 - to_field(b24[0])), b20[0])), u8_xor(b23[1], u8_and(u8_from_field_unsafe(255 - to_field(b24[1])), b20[1])), u8_xor(b23[2], u8_and(u8_from_field_unsafe(255 - to_field(b24[2])), b20[2])), u8_xor(b23[3], u8_and(u8_from_field_unsafe(255 - to_field(b24[3])), b20[3])), u8_xor(b23[4], u8_and(u8_from_field_unsafe(255 - to_field(b24[4])), b20[4])), u8_xor(b23[5], u8_and(u8_from_field_unsafe(255 - to_field(b24[5])), b20[5])), u8_xor(b23[6], u8_and(u8_from_field_unsafe(255 - to_field(b24[6])), b20[6])), u8_xor(b23[7], u8_and(u8_from_field_unsafe(255 - to_field(b24[7])), b20[7]))];
      let e24 = [u8_xor(b24[0], u8_and(u8_from_field_unsafe(255 - to_field(b20[0])), b21[0])), u8_xor(b24[1], u8_and(u8_from_field_unsafe(255 - to_field(b20[1])), b21[1])), u8_xor(b24[2], u8_and(u8_from_field_unsafe(255 - to_field(b20[2])), b21[2])), u8_xor(b24[3], u8_and(u8_from_field_unsafe(255 - to_field(b20[3])), b21[3])), u8_xor(b24[4], u8_and(u8_from_field_unsafe(255 - to_field(b20[4])), b21[4])), u8_xor(b24[5], u8_and(u8_from_field_unsafe(255 - to_field(b20[5])), b21[5])), u8_xor(b24[6], u8_and(u8_from_field_unsafe(255 - to_field(b20[6])), b21[6])), u8_xor(b24[7], u8_and(u8_from_field_unsafe(255 - to_field(b20[7])), b21[7]))];
      -- iota: xor the round constant into lane (0,0).
      let f0 = [u8_xor(e0[0], rc[0]), u8_xor(e0[1], rc[1]), u8_xor(e0[2], rc[2]), u8_xor(e0[3], rc[3]), u8_xor(e0[4], rc[4]), u8_xor(e0[5], rc[5]), u8_xor(e0[6], rc[6]), u8_xor(e0[7], rc[7])];
      [f0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24]
  }
⟧

end IxVM

end
