use crate::{
  CanonicalR1csV1, ConstraintPhase, LinearCombination, R1csBuilder, R1csError,
  Variable, Witness,
};
use ark_bls12_381::Fr;
use ark_ff::{AdditiveGroup, Field};
use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, OnceLock};

pub const F128_BITS: usize = 128;

/// Canonical little-endian bit wires for one Flock `GF(2^128)` element.
///
/// The basis is the polynomial basis used by GHASH: bit `i` is the
/// coefficient of `x^i`, reduced modulo `x^128 + x^7 + x^2 + x + 1`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct F128VariablesV1 {
  value: [u8; 16],
  bit_variables: [Variable; F128_BITS],
}

impl F128VariablesV1 {
  pub const fn value(&self) -> &[u8; 16] {
    &self.value
  }

  pub const fn bit_variables(&self) -> &[Variable; F128_BITS] {
    &self.bit_variables
  }

  pub(crate) const fn from_constrained_bits(
    value: [u8; 16],
    bit_variables: [Variable; F128_BITS],
  ) -> Self {
    Self { value, bit_variables }
  }
}

/// Build a standalone multiplication relation in the exact Flock field.
pub fn build_f128_multiplication_r1cs(
  left: [u8; 16],
  right: [u8; 16],
  phase: ConstraintPhase,
) -> Result<(CanonicalR1csV1, Witness, F128VariablesV1), R1csError> {
  let mut builder = R1csBuilder::new();
  let left = alloc_f128_private(&mut builder, left, phase)?;
  let right = alloc_f128_private(&mut builder, right, phase)?;
  let output = constrain_f128_multiply(&mut builder, &left, &right, phase)?;
  let (r1cs, witness) = builder.finish()?;
  Ok((r1cs, witness, output))
}

/// Allocate a bit-decomposed private `GF(2^128)` value.
pub fn alloc_f128_private(
  builder: &mut R1csBuilder,
  value: [u8; 16],
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let bits = value_bits(&value)
    .into_iter()
    .map(|value| alloc_checked_bit(builder, value, phase))
    .collect::<Result<Vec<_>, _>>()?;
  export_variables(builder, value, bits, phase)
}

pub(crate) fn alloc_f128_constant(
  builder: &mut R1csBuilder,
  value: [u8; 16],
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let variables = alloc_f128_private(builder, value, phase)?;
  enforce_f128_equal_constant(builder, &variables, value, phase);
  Ok(variables)
}

/// Reinterpret a 128-by-128 bit matrix by swapping its axes.
///
/// This is wiring, not advice: output bit `i` of element `b` is literally
/// input element `i`'s bit `b`, matching Flock's TensorAlgebra transpose.
pub(crate) fn transpose_f128_variables(
  values: &[F128VariablesV1],
) -> Result<Vec<F128VariablesV1>, R1csError> {
  if values.len() != F128_BITS {
    return Err(R1csError::InternalShape);
  }
  (0..F128_BITS)
    .map(|source_bit| {
      let mut value = [0u8; 16];
      for (output_bit, input) in values.iter().enumerate() {
        if value_bits(input.value())[source_bit] {
          value[output_bit / 8] |= 1 << (output_bit % 8);
        }
      }
      let bit_variables = core::array::from_fn(|output_bit| {
        values[output_bit].bit_variables()[source_bit]
      });
      Ok(F128VariablesV1::from_constrained_bits(value, bit_variables))
    })
    .collect()
}

/// Constrain characteristic-two addition (bitwise XOR).
pub fn constrain_f128_add(
  builder: &mut R1csBuilder,
  left: &F128VariablesV1,
  right: &F128VariablesV1,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let left_bits = import_variables(left);
  let right_bits = import_variables(right);
  let bits = left_bits
    .iter()
    .zip(&right_bits)
    .map(|(left, right)| xor2(builder, left, right, phase))
    .collect::<Result<Vec<_>, _>>()?;
  export_variables(builder, xor_values(left.value, right.value), bits, phase)
}

/// Constrain multiplication modulo `x^128 + x^7 + x^2 + x + 1`.
///
/// The multiplication tensor is generated by a flattened seven-level
/// Karatsuba recursion. Only its 2,187 leaf products become AND constraints;
/// reconstruction and polynomial reduction are parity constraints. This is
/// materially smaller than the 16,384 products in a schoolbook bit circuit.
pub fn constrain_f128_multiply(
  builder: &mut R1csBuilder,
  left: &F128VariablesV1,
  right: &F128VariablesV1,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let left_bits = import_variables(left);
  let right_bits = import_variables(right);
  let plan = karatsuba_plan();
  let mut left_signals = left_bits.to_vec();
  let mut right_signals = right_bits.to_vec();
  for &(low, high) in &plan.xor_pairs {
    left_signals.push(xor2(
      builder,
      &left_signals[low],
      &left_signals[high],
      phase,
    )?);
    right_signals.push(xor2(
      builder,
      &right_signals[low],
      &right_signals[high],
      phase,
    )?);
  }
  let products = plan
    .leaf_signals
    .iter()
    .map(|&signal| {
      and(builder, &left_signals[signal], &right_signals[signal], phase)
    })
    .collect::<Result<Vec<_>, _>>()?;

  let mut bits = Vec::with_capacity(F128_BITS);
  for terms in &plan.output_terms {
    let inputs =
      terms.iter().map(|&term| products[term].clone()).collect::<Vec<_>>();
    bits.push(xor_many(builder, &inputs, phase)?);
  }
  let value = multiply_values(left.value, right.value);
  debug_assert_eq!(wire_values(&bits), value_bits(&value));
  export_variables(builder, value, bits, phase)
}

/// Constrain multiplication by a shape-time constant as one binary-linear
/// map, avoiding the bilinear Karatsuba tensor used for two witness values.
pub fn constrain_f128_multiply_constant(
  builder: &mut R1csBuilder,
  value: &F128VariablesV1,
  constant: [u8; 16],
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  if constant == [0; 16] {
    return alloc_f128_constant(builder, [0; 16], phase);
  }
  if constant == one_value() {
    return Ok(value.clone());
  }
  let plan = constant_multiplication_plan(constant);
  constrain_binary_linear_map(builder, value, &plan, phase)
}

/// Constrain the Frobenius map `x -> x^(2^power)` in `GF(2^128)`.
///
/// Frobenius is binary-linear, so every power is a fixed XOR network over
/// the already canonical input bits. Powers are reduced modulo 128.
pub fn constrain_f128_frobenius(
  builder: &mut R1csBuilder,
  value: &F128VariablesV1,
  power: usize,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let power = power % F128_BITS;
  if power == 0 {
    return Ok(value.clone());
  }
  constrain_binary_linear_map(builder, value, &frobenius_plans()[power], phase)
}

/// Witness and constrain a nonzero multiplicative inverse.
pub fn constrain_f128_inverse(
  builder: &mut R1csBuilder,
  value: &F128VariablesV1,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let inverse_value = inverse_value(value.value)
    .ok_or(R1csError::NonInvertibleBinaryFieldElement)?;
  let inverse = alloc_f128_private(builder, inverse_value, phase)?;
  let product = constrain_f128_multiply(builder, value, &inverse, phase)?;
  enforce_f128_equal_constant(builder, &product, one_value(), phase);
  Ok(inverse)
}

/// Enforce equality using the injective 128-bit integer packing into Fr.
pub fn enforce_f128_equal(
  builder: &mut R1csBuilder,
  left: &F128VariablesV1,
  right: &F128VariablesV1,
  phase: ConstraintPhase,
) {
  builder.enforce_zero(
    phase,
    packed_f128_variables(left).minus(&packed_f128_variables(right)),
  );
}

pub(crate) fn enforce_f128_equal_constant(
  builder: &mut R1csBuilder,
  value: &F128VariablesV1,
  expected: [u8; 16],
  phase: ConstraintPhase,
) {
  let packed = u128::from_le_bytes(expected);
  let low = u64::try_from(packed & u128::from(u64::MAX))
    .expect("masked value fits u64");
  let high = u64::try_from(packed >> 64).expect("upper half fits u64");
  let expected =
    Fr::from(low) + Fr::from(high) * Fr::from(u128::from(1u64) << 64);
  builder.enforce_zero(
    phase,
    packed_f128_variables(value)
      .minus(&LinearCombination::from_constant(expected)),
  );
}

pub(crate) fn packed_f128_variables(
  value: &F128VariablesV1,
) -> LinearCombination {
  let mut coefficient = Fr::ONE;
  let terms = value.bit_variables.iter().copied().map(|variable| {
    let term = (variable, coefficient);
    coefficient.double_in_place();
    term
  });
  LinearCombination::from_terms(terms)
}

#[derive(Clone, Debug)]
struct BitWire {
  value: bool,
  expression: LinearCombination,
  variable: Option<Variable>,
  constant: bool,
}

impl BitWire {
  fn constant(value: bool) -> Self {
    Self {
      value,
      expression: LinearCombination::from_constant(Fr::from(u64::from(value))),
      variable: None,
      constant: true,
    }
  }

  fn not(&self) -> Self {
    Self {
      value: !self.value,
      expression: LinearCombination::one().minus(&self.expression),
      variable: None,
      constant: self.constant,
    }
  }
}

fn alloc_checked_bit(
  builder: &mut R1csBuilder,
  value: bool,
  phase: ConstraintPhase,
) -> Result<BitWire, R1csError> {
  let variable = builder.alloc_private(Fr::from(u64::from(value)))?;
  builder.enforce_boolean(phase, variable);
  Ok(BitWire {
    value,
    expression: LinearCombination::from_variable(variable),
    variable: Some(variable),
    constant: false,
  })
}

fn alloc_derived_bit(
  builder: &mut R1csBuilder,
  value: bool,
) -> Result<BitWire, R1csError> {
  let variable = builder.alloc_private(Fr::from(u64::from(value)))?;
  Ok(BitWire {
    value,
    expression: LinearCombination::from_variable(variable),
    variable: Some(variable),
    constant: false,
  })
}

fn materialize_bit(
  builder: &mut R1csBuilder,
  bit: &BitWire,
  phase: ConstraintPhase,
) -> Result<BitWire, R1csError> {
  if bit.variable.is_some() {
    return Ok(bit.clone());
  }
  let output = alloc_derived_bit(builder, bit.value)?;
  builder.enforce_zero(phase, output.expression.clone().minus(&bit.expression));
  Ok(output)
}

fn xor2(
  builder: &mut R1csBuilder,
  left: &BitWire,
  right: &BitWire,
  phase: ConstraintPhase,
) -> Result<BitWire, R1csError> {
  if left.constant {
    return Ok(if left.value { right.not() } else { right.clone() });
  }
  if right.constant {
    return Ok(if right.value { left.not() } else { left.clone() });
  }
  let output = alloc_derived_bit(builder, left.value ^ right.value)?;
  let inverse_two = Fr::from(2u64).inverse().expect("two is invertible in Fr");
  builder.enforce(
    phase,
    left.expression.clone(),
    right.expression.clone(),
    left
      .expression
      .clone()
      .plus(&right.expression)
      .minus(&output.expression)
      .scale(inverse_two),
  );
  Ok(output)
}

fn and(
  builder: &mut R1csBuilder,
  left: &BitWire,
  right: &BitWire,
  phase: ConstraintPhase,
) -> Result<BitWire, R1csError> {
  if (left.constant && !left.value) || (right.constant && !right.value) {
    return Ok(BitWire::constant(false));
  }
  if left.constant && left.value {
    return Ok(right.clone());
  }
  if right.constant && right.value {
    return Ok(left.clone());
  }
  let output = alloc_derived_bit(builder, left.value & right.value)?;
  builder.enforce(
    phase,
    left.expression.clone(),
    right.expression.clone(),
    output.expression.clone(),
  );
  Ok(output)
}

fn xor_many(
  builder: &mut R1csBuilder,
  inputs: &[BitWire],
  phase: ConstraintPhase,
) -> Result<BitWire, R1csError> {
  let true_constants =
    inputs.iter().filter(|input| input.constant && input.value).count();
  let mut live =
    inputs.iter().filter(|input| !input.constant).cloned().collect::<Vec<_>>();
  let toggle = true_constants & 1 == 1;
  if live.is_empty() {
    return Ok(BitWire::constant(toggle));
  }
  if live.len() <= 4 {
    let first = live.remove(0);
    let result = live
      .into_iter()
      .try_fold(first, |left, right| xor2(builder, &left, &right, phase))?;
    return Ok(if toggle { result.not() } else { result });
  }

  let ones =
    live.iter().filter(|input| input.value).count() + usize::from(toggle);
  let output = alloc_checked_bit(builder, ones & 1 == 1, phase)?;
  let quotient = ones / 2;
  let maximum_quotient = (live.len() + usize::from(toggle)) / 2;
  let quotient_bits =
    usize::try_from(usize::BITS - maximum_quotient.leading_zeros())
      .expect("bit width fits usize");
  let quotient_wires = (0..quotient_bits)
    .map(|bit| alloc_checked_bit(builder, (quotient >> bit) & 1 == 1, phase))
    .collect::<Result<Vec<_>, _>>()?;

  let mut terms = Vec::with_capacity(live.len() + quotient_wires.len() + 2);
  if toggle {
    terms.push((Variable::ONE, Fr::ONE));
  }
  for input in &live {
    terms.extend(input.expression.terms().iter().copied());
  }
  terms.extend(
    output
      .expression
      .terms()
      .iter()
      .map(|&(variable, coefficient)| (variable, -coefficient)),
  );
  let mut coefficient = Fr::from(2u64);
  for bit in &quotient_wires {
    terms.extend(
      bit
        .expression
        .terms()
        .iter()
        .map(|&(variable, value)| (variable, -(value * coefficient))),
    );
    coefficient.double_in_place();
  }
  builder.enforce_zero(phase, LinearCombination::from_terms(terms));
  Ok(output)
}

type TermSet = Vec<usize>;

struct KaratsubaPlan {
  xor_pairs: Vec<(usize, usize)>,
  leaf_signals: Vec<usize>,
  output_terms: Vec<TermSet>,
}

fn karatsuba_plan() -> &'static KaratsubaPlan {
  static PLAN: OnceLock<KaratsubaPlan> = OnceLock::new();
  PLAN.get_or_init(|| {
    let mut xor_pairs = Vec::new();
    let mut leaf_signals = Vec::new();
    let inputs = (0..F128_BITS).collect::<Vec<_>>();
    let mut coefficients =
      karatsuba_plan_terms(&inputs, &mut xor_pairs, &mut leaf_signals);
    debug_assert_eq!(coefficients.len(), 2 * F128_BITS - 1);

    // Descending reduction is literal polynomial long division in
    // characteristic two: x^128 = x^7 + x^2 + x + 1.
    for degree in (F128_BITS..coefficients.len()).rev() {
      let high = core::mem::take(&mut coefficients[degree]);
      for shift in [0usize, 1, 2, 7] {
        xor_term_set(&mut coefficients[degree - F128_BITS + shift], &high);
      }
    }
    KaratsubaPlan {
      xor_pairs,
      leaf_signals,
      output_terms: coefficients.into_iter().take(F128_BITS).collect(),
    }
  })
}

fn karatsuba_plan_terms(
  signals: &[usize],
  xor_pairs: &mut Vec<(usize, usize)>,
  leaf_signals: &mut Vec<usize>,
) -> Vec<TermSet> {
  debug_assert!(signals.len().is_power_of_two());
  if signals.len() == 1 {
    let index = leaf_signals.len();
    leaf_signals.push(signals[0]);
    return vec![vec![index]];
  }

  let half = signals.len() / 2;
  let (low_signals, high_signals) = signals.split_at(half);
  let sum_signals = low_signals
    .iter()
    .zip(high_signals)
    .map(|(&low, &high)| {
      let output = F128_BITS + xor_pairs.len();
      xor_pairs.push((low, high));
      output
    })
    .collect::<Vec<_>>();

  let low = karatsuba_plan_terms(low_signals, xor_pairs, leaf_signals);
  let high = karatsuba_plan_terms(high_signals, xor_pairs, leaf_signals);
  let sum = karatsuba_plan_terms(&sum_signals, xor_pairs, leaf_signals);
  let mut middle = sum;
  for index in 0..middle.len() {
    xor_term_set(&mut middle[index], &low[index]);
    xor_term_set(&mut middle[index], &high[index]);
  }

  let mut output = vec![Vec::new(); 2 * signals.len() - 1];
  for (index, terms) in low.iter().enumerate() {
    xor_term_set(&mut output[index], terms);
  }
  for (index, terms) in middle.iter().enumerate() {
    xor_term_set(&mut output[index + half], terms);
  }
  for (index, terms) in high.iter().enumerate() {
    xor_term_set(&mut output[index + 2 * half], terms);
  }
  output
}

fn xor_term_set(target: &mut TermSet, source: &[usize]) {
  let left = core::mem::take(target);
  let mut output = Vec::with_capacity(left.len() + source.len());
  let (mut left_index, mut right_index) = (0usize, 0usize);
  while left_index < left.len() || right_index < source.len() {
    match (left.get(left_index), source.get(right_index)) {
      (Some(&left_value), Some(&right_value)) if left_value == right_value => {
        left_index += 1;
        right_index += 1;
      },
      (Some(&left_value), Some(&right_value)) if left_value < right_value => {
        output.push(left_value);
        left_index += 1;
      },
      (Some(_), Some(&right_value)) => {
        output.push(right_value);
        right_index += 1;
      },
      (Some(&left_value), None) => {
        output.push(left_value);
        left_index += 1;
      },
      (None, Some(&right_value)) => {
        output.push(right_value);
        right_index += 1;
      },
      (None, None) => break,
    }
  }
  *target = output;
}

#[derive(Clone)]
struct BinaryLinearMapPlan {
  basis_images: Vec<[u8; 16]>,
  output_inputs: Vec<Vec<usize>>,
}

fn constrain_binary_linear_map(
  builder: &mut R1csBuilder,
  value: &F128VariablesV1,
  plan: &BinaryLinearMapPlan,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  if plan.basis_images.len() != F128_BITS
    || plan.output_inputs.len() != F128_BITS
  {
    return Err(R1csError::InternalShape);
  }
  let inputs = import_variables(value);
  let output_bits = plan
    .output_inputs
    .iter()
    .map(|sources| {
      let terms = sources
        .iter()
        .map(|&source| {
          inputs.get(source).cloned().ok_or(R1csError::InternalShape)
        })
        .collect::<Result<Vec<_>, _>>()?;
      xor_many(builder, &terms, phase)
    })
    .collect::<Result<Vec<_>, _>>()?;
  let input_value_bits = value_bits(value.value());
  let expected = input_value_bits
    .iter()
    .zip(&plan.basis_images)
    .filter(|(bit, _)| **bit)
    .fold([0u8; 16], |accumulator, (_, image)| xor_values(accumulator, *image));
  debug_assert_eq!(wire_values(&output_bits), value_bits(&expected));
  export_variables(builder, expected, output_bits, phase)
}

fn plan_from_basis_images(basis_images: Vec<[u8; 16]>) -> BinaryLinearMapPlan {
  debug_assert_eq!(basis_images.len(), F128_BITS);
  let image_bits = basis_images.iter().map(value_bits).collect::<Vec<_>>();
  let output_inputs = (0..F128_BITS)
    .map(|output_bit| {
      image_bits
        .iter()
        .enumerate()
        .filter_map(|(input_bit, bits)| bits[output_bit].then_some(input_bit))
        .collect()
    })
    .collect();
  BinaryLinearMapPlan { basis_images, output_inputs }
}

fn constant_multiplication_plan(
  constant: [u8; 16],
) -> Arc<BinaryLinearMapPlan> {
  static PLANS: OnceLock<Mutex<BTreeMap<[u8; 16], Arc<BinaryLinearMapPlan>>>> =
    OnceLock::new();
  let plans = PLANS.get_or_init(|| Mutex::new(BTreeMap::new()));
  if let Some(plan) =
    plans.lock().expect("linear-map cache lock").get(&constant)
  {
    return Arc::clone(plan);
  }
  let basis_images = (0..F128_BITS)
    .map(|bit| multiply_values(bit_basis_value(bit), constant))
    .collect();
  let plan = Arc::new(plan_from_basis_images(basis_images));
  Arc::clone(
    plans
      .lock()
      .expect("linear-map cache lock")
      .entry(constant)
      .or_insert(plan),
  )
}

fn frobenius_plans() -> &'static [BinaryLinearMapPlan] {
  static PLANS: OnceLock<Vec<BinaryLinearMapPlan>> = OnceLock::new();
  PLANS.get_or_init(|| {
    let mut images = (0..F128_BITS).map(bit_basis_value).collect::<Vec<_>>();
    let mut plans = Vec::with_capacity(F128_BITS);
    for _ in 0..F128_BITS {
      plans.push(plan_from_basis_images(images.clone()));
      for image in &mut images {
        *image = multiply_values(*image, *image);
      }
    }
    plans
  })
}

fn bit_basis_value(bit: usize) -> [u8; 16] {
  let mut value = [0u8; 16];
  value[bit / 8] = 1 << (bit % 8);
  value
}

fn import_variables(value: &F128VariablesV1) -> [BitWire; F128_BITS] {
  let bits = value_bits(&value.value);
  core::array::from_fn(|index| BitWire {
    value: bits[index],
    expression: LinearCombination::from_variable(value.bit_variables[index]),
    variable: Some(value.bit_variables[index]),
    constant: false,
  })
}

fn export_variables(
  builder: &mut R1csBuilder,
  value: [u8; 16],
  bits: Vec<BitWire>,
  phase: ConstraintPhase,
) -> Result<F128VariablesV1, R1csError> {
  let bits: [BitWire; F128_BITS] =
    bits.try_into().map_err(|_| R1csError::InternalShape)?;
  let bit_variables = bits
    .iter()
    .map(|bit| materialize_bit(builder, bit, phase))
    .collect::<Result<Vec<_>, _>>()?
    .into_iter()
    .map(|bit| bit.variable.ok_or(R1csError::InternalShape))
    .collect::<Result<Vec<_>, _>>()?
    .try_into()
    .map_err(|_| R1csError::InternalShape)?;
  Ok(F128VariablesV1::from_constrained_bits(value, bit_variables))
}

fn value_bits(value: &[u8; 16]) -> [bool; F128_BITS] {
  core::array::from_fn(|bit| (value[bit / 8] >> (bit % 8)) & 1 == 1)
}

fn wire_values(bits: &[BitWire]) -> [bool; F128_BITS] {
  core::array::from_fn(|index| bits[index].value)
}

fn xor_values(left: [u8; 16], right: [u8; 16]) -> [u8; 16] {
  core::array::from_fn(|index| left[index] ^ right[index])
}

pub(crate) fn native_f128_add(left: [u8; 16], right: [u8; 16]) -> [u8; 16] {
  xor_values(left, right)
}

fn one_value() -> [u8; 16] {
  let mut one = [0u8; 16];
  one[0] = 1;
  one
}

fn multiply_values(left: [u8; 16], right: [u8; 16]) -> [u8; 16] {
  let left = u128::from_le_bytes(left);
  let right = u128::from_le_bytes(right);
  let left_low =
    u64::try_from(left & u128::from(u64::MAX)).expect("masked value fits u64");
  let left_high = u64::try_from(left >> 64).expect("upper half fits u64");
  let right_low =
    u64::try_from(right & u128::from(u64::MAX)).expect("masked value fits u64");
  let right_high = u64::try_from(right >> 64).expect("upper half fits u64");
  let p00 = carryless_mul64(left_low, right_low);
  let p01 = carryless_mul64(left_low, right_high);
  let p10 = carryless_mul64(left_high, right_low);
  let p11 = carryless_mul64(left_high, right_high);
  let low64 = |value: u128| {
    u64::try_from(value & u128::from(u64::MAX)).expect("masked value fits u64")
  };
  let high64 =
    |value: u128| u64::try_from(value >> 64).expect("upper half fits u64");
  let r0 = low64(p00);
  let r1 = high64(p00) ^ low64(p01) ^ low64(p10);
  let r2 = high64(p01) ^ high64(p10) ^ low64(p11);
  let r3 = high64(p11);
  reduce_ghash(r0, r1, r2, r3)
}

pub(crate) fn native_f128_multiply(
  left: [u8; 16],
  right: [u8; 16],
) -> [u8; 16] {
  multiply_values(left, right)
}

fn carryless_mul64(left: u64, right: u64) -> u128 {
  let mut product = 0u128;
  for bit in 0..64 {
    if (left >> bit) & 1 == 1 {
      product ^= u128::from(right) << bit;
    }
  }
  product
}

fn reduce_ghash(r0: u64, r1: u64, r2: u64, r3: u64) -> [u8; 16] {
  let shift1_low = r2 << 1;
  let shift1_high = (r3 << 1) | (r2 >> 63);
  let shift2_low = r2 << 2;
  let shift2_high = (r3 << 2) | (r2 >> 62);
  let shift7_low = r2 << 7;
  let shift7_high = (r3 << 7) | (r2 >> 57);
  let folded_low = r2 ^ shift1_low ^ shift2_low ^ shift7_low;
  let folded_high = r3 ^ shift1_high ^ shift2_high ^ shift7_high;
  let overflow = (r3 >> 63) ^ (r3 >> 62) ^ (r3 >> 57);
  let correction =
    overflow ^ (overflow << 1) ^ (overflow << 2) ^ (overflow << 7);
  let value = u128::from(r0 ^ folded_low ^ correction)
    | (u128::from(r1 ^ folded_high) << 64);
  value.to_le_bytes()
}

fn inverse_value(value: [u8; 16]) -> Option<[u8; 16]> {
  if value == [0; 16] {
    return None;
  }
  // x^(2^128 - 2): bits 1..127 of the exponent are all one.
  let mut result = one_value();
  let mut power = value;
  for bit in 0..128 {
    if bit != 0 {
      result = multiply_values(result, power);
    }
    power = multiply_values(power, power);
  }
  Some(result)
}

pub(crate) fn native_f128_inverse(value: [u8; 16]) -> Option<[u8; 16]> {
  inverse_value(value)
}

#[cfg(test)]
mod tests {
  use super::*;

  fn value(low: u64, high: u64) -> [u8; 16] {
    (u128::from(low) | (u128::from(high) << 64)).to_le_bytes()
  }

  #[test]
  fn native_multiplication_matches_polynomial_oracle() {
    fn oracle(left: [u8; 16], right: [u8; 16]) -> [u8; 16] {
      let left = value_bits(&left);
      let right = value_bits(&right);
      let mut product = [false; 255];
      for (left_index, &left_bit) in left.iter().enumerate() {
        for (right_index, &right_bit) in right.iter().enumerate() {
          product[left_index + right_index] ^= left_bit & right_bit;
        }
      }
      for degree in (128..255).rev() {
        if product[degree] {
          product[degree] = false;
          for shift in [0usize, 1, 2, 7] {
            product[degree - 128 + shift] ^= true;
          }
        }
      }
      let mut output = [0u8; 16];
      for (bit, &set) in product[..128].iter().enumerate() {
        output[bit / 8] |= u8::from(set) << (bit % 8);
      }
      output
    }

    let vectors = [
      (value(0, 0), value(7, 9)),
      (value(1, 0), value(u64::MAX, u64::MAX)),
      (value(2, 0), value(0, 1u64 << 63)),
      (
        value(0x0123_4567_89ab_cdef, 0xfedc_ba98_7654_3210),
        value(0x0f1e_2d3c_4b5a_6978, 0x8877_6655_4433_2211),
      ),
    ];
    for (left, right) in vectors {
      assert_eq!(multiply_values(left, right), oracle(left, right));
    }
  }

  #[test]
  fn multiplication_relation_is_sound_and_value_independent() {
    let left = value(0x0123_4567_89ab_cdef, 0xfedc_ba98_7654_3210);
    let right = value(0x0f1e_2d3c_4b5a_6978, 0x8877_6655_4433_2211);
    let (first, mut witness, output) =
      build_f128_multiplication_r1cs(left, right, ConstraintPhase::Zerocheck)
        .unwrap();
    let census = first.census();
    assert_eq!(census.private_variables, 7_793);
    assert_eq!(census.constraints, 7_921);
    assert_eq!(census.nonzero_terms, 108_480);
    assert_eq!(*output.value(), multiply_values(left, right));
    first.check(&witness).unwrap();
    let bit = output.bit_variables()[0];
    let wrong = !value_bits(output.value())[0];
    witness.set(bit, Fr::from(u64::from(wrong))).unwrap();
    assert!(first.check(&witness).is_err());

    let (second, _, _) = build_f128_multiplication_r1cs(
      value(3, 5),
      value(7, 11),
      ConstraintPhase::Zerocheck,
    )
    .unwrap();
    assert_eq!(first.digest(), second.digest());
    assert_eq!(first.census(), second.census());
  }

  #[test]
  fn addition_and_inversion_satisfy_field_identities() {
    let mut builder = R1csBuilder::new();
    let left = alloc_f128_private(
      &mut builder,
      value(0x55aa, 0x1234),
      ConstraintPhase::Lincheck,
    )
    .unwrap();
    let right = alloc_f128_private(
      &mut builder,
      value(0x0f0f, 0xabcd),
      ConstraintPhase::Lincheck,
    )
    .unwrap();
    let sum = constrain_f128_add(
      &mut builder,
      &left,
      &right,
      ConstraintPhase::Lincheck,
    )
    .unwrap();
    assert_eq!(*sum.value(), xor_values(left.value, right.value));
    let inverse =
      constrain_f128_inverse(&mut builder, &left, ConstraintPhase::Lincheck)
        .unwrap();
    assert_eq!(multiply_values(left.value, *inverse.value()), one_value());
    let (r1cs, witness) = builder.finish().unwrap();
    r1cs.check(&witness).unwrap();
  }

  #[test]
  fn zero_has_no_constrained_inverse() {
    let mut builder = R1csBuilder::new();
    let zero =
      alloc_f128_private(&mut builder, [0; 16], ConstraintPhase::Pcs).unwrap();
    assert_eq!(
      constrain_f128_inverse(&mut builder, &zero, ConstraintPhase::Pcs),
      Err(R1csError::NonInvertibleBinaryFieldElement),
    );
  }

  #[test]
  fn constant_multiplication_and_frobenius_are_linear_maps() {
    let input = value(0x0123_4567_89ab_cdef, 0xfedc_ba98_7654_3210);
    let constant = value(0x0f1e_2d3c_4b5a_6978, 0x8877_6655_4433_2211);
    let mut builder = R1csBuilder::new();
    let input_variables =
      alloc_f128_private(&mut builder, input, ConstraintPhase::Pcs).unwrap();
    let product = constrain_f128_multiply_constant(
      &mut builder,
      &input_variables,
      constant,
      ConstraintPhase::Pcs,
    )
    .unwrap();
    let power = constrain_f128_frobenius(
      &mut builder,
      &input_variables,
      17,
      ConstraintPhase::Pcs,
    )
    .unwrap();
    assert_eq!(*product.value(), multiply_values(input, constant));
    let expected_power =
      (0..17).fold(input, |value, _| multiply_values(value, value));
    assert_eq!(*power.value(), expected_power);
    let (r1cs, witness) = builder.finish().unwrap();
    r1cs.check(&witness).unwrap();
  }
}
