import Ix.Tc.Verify.Check.BlockAcceptance

/-!
# Oracle-free one-family generated-recursor admission

Lean4Lean's current public generation certificate covers one inductive family
at a time. Such a transaction has two distinct physical Ix blocks:

* the family/constructor block advances the certified Theory environment; and
* the separately ingressed generated-recursor block is admitted only after its
  already-installed type, equations, and iota patterns have been checked.

This module packages that common two-stage shape without choosing a future
environment, constructing an `InductiveOracle`, or pretending that a mutual
declaration is a sequence of singleton declarations.
-/

namespace Ix.Tc

/-- Complete semantic evidence for the two physical blocks generated by one
certified inductive family. Freshness of the recursor is stated in the
family-accepted world, so the second stage is necessarily disjoint from the
first and cannot re-admit an already trusted member. -/
structure OneFamilyRecursorCertificate (trProj : RawProjRel)
    (world : VerifyWorld)
    (familyBlock : KId .anon) (familyMembers : Array (KId .anon))
    (recursorBlock : KId .anon) (recursorMembers : Array (KId .anon))
    (afterVEnv : Lean4Lean.VEnv) : Prop where
  family :
    SemanticBlockTransitionCertificate trProj world familyBlock familyMembers
      .inductive' afterVEnv
  recursor :
    ExistingSemanticBlockCertificate trProj family.admittedWorld recursorBlock
      recursorMembers .recursor

namespace OneFamilyRecursorCertificate

/-- Intermediate world after the family/constructor block is admitted. -/
def familyWorld {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) : VerifyWorld :=
  certificate.family.admittedWorld

/-- Final world after the separately owned generated-recursor block is also
admitted. -/
def admittedWorld {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) : VerifyWorld :=
  certificate.recursor.admittedWorld

/-- The first stage is the exact explicit Theory transition. -/
theorem familyAdmission {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv)
    (trusted : TrustedCatalogRel trProj world) :
    AtomicBlockAdmission trProj world certificate.familyWorld familyBlock
      familyMembers .inductive' :=
  certificate.family.admit trusted

/-- The second stage consumes the trusted catalog produced by the family
stage and admits only semantic entries already present in `afterVEnv`. -/
theorem recursorAdmission {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv)
    (trusted : TrustedCatalogRel trProj world) :
    AtomicBlockAdmission trProj certificate.familyWorld
      certificate.admittedWorld recursorBlock recursorMembers .recursor :=
  certificate.recursor.admit
    (certificate.familyAdmission trusted).trustedCatalog

/-- Both stages compose to one monotone world extension. -/
theorem le_admittedWorld {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) :
    world ≤ certificate.admittedWorld :=
  VerifyWorld.LE.trans certificate.family.le_admittedWorld
    certificate.recursor.le_admittedWorld

/-- The final trust delta is exactly the generated-recursor members followed
by the family members and the original trusted set. -/
theorem trusted_iff {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv)
    (id : KId .anon) :
    certificate.admittedWorld.trusted id ↔
      id ∈ recursorMembers ∨ id ∈ familyMembers ∨ world.trusted id :=
  Iff.rfl

@[simp] theorem admittedWorld_venv {trProj : RawProjRel}
    {world : VerifyWorld} {familyBlock : KId .anon}
    {familyMembers : Array (KId .anon)} {recursorBlock : KId .anon}
    {recursorMembers : Array (KId .anon)} {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) :
    certificate.admittedWorld.venv = afterVEnv :=
  rfl

@[simp] theorem admittedWorld_catalog {trProj : RawProjRel}
    {world : VerifyWorld} {familyBlock : KId .anon}
    {familyMembers : Array (KId .anon)} {recursorBlock : KId .anon}
    {recursorMembers : Array (KId .anon)} {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) :
    certificate.admittedWorld.catalog = world.catalog :=
  rfl

@[simp] theorem admittedWorld_blocks {trProj : RawProjRel}
    {world : VerifyWorld} {familyBlock : KId .anon}
    {familyMembers : Array (KId .anon)} {recursorBlock : KId .anon}
    {recursorMembers : Array (KId .anon)} {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) :
    certificate.admittedWorld.blocks = world.blocks :=
  rfl

@[simp] theorem admittedWorld_nameOf {trProj : RawProjRel}
    {world : VerifyWorld} {familyBlock : KId .anon}
    {familyMembers : Array (KId .anon)} {recursorBlock : KId .anon}
    {recursorMembers : Array (KId .anon)} {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) :
    certificate.admittedWorld.nameOf = world.nameOf :=
  rfl

/-- Reusable semantic closure of one certified family and its generated
recursor. It records acceptance of both exact physical blocks in the final
world, not only the two intermediate promotion witnesses. -/
structure AtomicClosure {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv) : Prop where
  familyAdmission :
    AtomicBlockAdmission trProj world certificate.familyWorld familyBlock
      familyMembers .inductive'
  recursorAdmission :
    AtomicBlockAdmission trProj certificate.familyWorld
      certificate.admittedWorld recursorBlock recursorMembers .recursor
  familyAccepted : certificate.admittedWorld.AcceptedBlock familyBlock
  recursorAccepted : certificate.admittedWorld.AcceptedBlock recursorBlock

/-- Close both stages from the original world's trusted-catalog relation. -/
theorem atomicClosure {trProj : RawProjRel} {world : VerifyWorld}
    {familyBlock : KId .anon} {familyMembers : Array (KId .anon)}
    {recursorBlock : KId .anon} {recursorMembers : Array (KId .anon)}
    {afterVEnv : Lean4Lean.VEnv}
    (certificate : OneFamilyRecursorCertificate trProj world familyBlock
      familyMembers recursorBlock recursorMembers afterVEnv)
    (trusted : TrustedCatalogRel trProj world) :
    certificate.AtomicClosure := by
  let familyAdmission := certificate.familyAdmission trusted
  let recursorAdmission := certificate.recursorAdmission trusted
  exact
    { familyAdmission := familyAdmission
      recursorAdmission := recursorAdmission
      familyAccepted :=
        familyAdmission.accepted.mono recursorAdmission.promotion.le
      recursorAccepted := recursorAdmission.accepted }

end OneFamilyRecursorCertificate

end Ix.Tc
