/-
  image-gen: the pure image generator (`Ix.Compile.Image`) on the prototype's
  fifteen retained prototype sub-cases (`Tests/Ix/Compile/Image/`), with
  Lean's kernel as the oracle.

  Fixtures: `Tests/Ix/Compile/Image/C*.lean` are the prototype's case files
  without its commands: each declares a source block (`Ck.Src`) with its user
  functions and the prototype's hand-written canonical block (`Ck.Can`). They
  are elaborated at run time (`getFileEnvCore`) and are in no Lake library.

  Per sub-case, in a scratch environment grown with `addDecl` (every
  declaration through Lean's kernel, `Elab.async false`):

  * **G** the canonical form from Pass 1 (`canonBlock Rules.phaseA`) and the
    canonical declarations from it (`ImageSpec.ofBlock`), declared as
    `Ck.Gen.*`: the kernel generates their recursors, whose types are the
    generator's input (in the compiler, Pass 2's recursors);
  * **T** the images of every Lean recursor of the block, generated by the
    pure function, added as definitions `Ck.View.*.rec` (38 expected);
  * **I** every computation rule over the image, as generated, by `Eq.refl`
    (62 expected);
  * **CMP** each image and rule statement against the prototype's
    `buildTransport` / `iotaStatements` on the hand-written `Ck.Can`, after
    renaming `Gen` to `Can`: equal, equal up to level normalisation, or
    different (logged);
  * **V/L** the prototype's view: every other source constant copied over
    the images under renaming (`copyAll`), as PRO did;
  * **B1** the prototype's transport-inlined normal forms `f._N` and
    `f._N = f` by `Eq.refl` (45 expected);
  * **H** the call-site form: every definition of the view whose value has
    a full application of an image is rewritten with `Image.inline` (the
    development, hereditary substitution) into `f._H`, which must type-check
    with `f`'s type and satisfy `f._H = f` by `Eq.refl`;
  * the two ablations of PRO as negative controls: `C4b-naive` (head
    recursor first: the rule `A2.rec_1.iota_node` must be rejected) and
    `C8-nolift` (no lift: all three images must be rejected).

  Logs (eliminator choices, images, differences): `out/image-gen/<case>.log`;
  every verdict: `out/image-gen/results.tsv`.

  Invoked as `lake test -- image-gen`.
-/
import Lean
import Ix.Compile.Canon
import Ix.Compile.Image
import Ix.CanonM
import Ix.Meta
import Tests.Ix.Compile.ImageProto

open Lean Meta

namespace Tests.Ix.Compile.Image

open _root_.Ix.Compile.Image (GenOptions ImageSpec Naming Image imagesOfBlock)

/-! ## Conversions between Lean's and Ix's terms (test side only) -/

def toLeanName : _root_.Ix.Name → Lean.Name
  | .anonymous _ => .anonymous
  | .str p s _ => .str (toLeanName p) s
  | .num p n _ => .num (toLeanName p) n

def ixName (n : Lean.Name) : _root_.Ix.Name := _root_.Ix.Name.fromLeanName n

def toIx (c : ConstantInfo) : _root_.Ix.ConstantInfo := (_root_.Ix.CanonM.canonConst c).run' {}
def toIxExpr (e : Expr) : _root_.Ix.Expr := (_root_.Ix.CanonM.canonExpr e).run' {}
def toLeanExpr (e : _root_.Ix.Expr) : Expr := (_root_.Ix.CanonM.uncanonExpr e).run' {}

/-- The generator's view of a Lean environment. -/
def ixLookup (env : Environment) (n : _root_.Ix.Name) : Option _root_.Ix.ConstantInfo :=
  let n' := toLeanName n
  -- the nested auxiliary recursors the kernel generates for a raw `addDecl` are in the kernel
  -- environment only (Lean 4.34.1: `Environment.find?` misses them)
  ((env.find? n').orElse fun _ => env.toKernelEnv.find? n').map toIx

/-! ## Cases -/

structure Case where
  name : String
  /-- `Ck` (source block `Ck.Src`, prototype's canonical block `Ck.Can`). -/
  ns : Lean.Name
  /-- The prototype's hand map, source member ↦ `Ck.Can` member. -/
  hand : Array (Lean.Name × Lean.Name)
  users : Array Lean.Name
  /-- B1 bridges: view names relative to `Ck.View`. -/
  nf : Array Lean.Name
  opts : GenOptions := {}
  /-- An ablation reuses its base case's canonical blocks and only builds
  images into its own view namespace. -/
  ablationOf : Option Lean.Name := none
  viewNs? : Option Lean.Name := none

def Case.srcNs (c : Case) : Lean.Name := c.ns ++ `Src
def Case.canNs (c : Case) : Lean.Name := c.ns ++ `Can
def Case.genNs (c : Case) : Lean.Name := (c.ablationOf.getD c.ns) ++ `Gen
def Case.viewNs (c : Case) : Lean.Name := c.viewNs?.getD (c.ns ++ `View)

def pairs (ns : Lean.Name) (xs : List (Lean.Name × Lean.Name)) : Array (Lean.Name × Lean.Name) :=
  xs.toArray.map fun (a, b) => (ns ++ `Src ++ a, ns ++ `Can ++ b)

def files : Array (String × Array Case) := #[
  ("Tests/Ix/Compile/Image/C1Perm.lean", #[
    { name := "C1", ns := `C1, hand := pairs `C1 [(`Odd, `Odd), (`Even, `Even)]
      users := #[`Odd.toNat, `Even.toNat, `three, `Even.isZero, `Even.viaRec]
      nf := #[`Odd.toNat, `Even.toNat, `Even.isZero, `Even.viaRec] }]),
  ("Tests/Ix/Compile/Image/C2Split.lean", #[
    { name := "C2", ns := `C2, hand := pairs `C2 [(`A, `A), (`B, `B)]
      users := #[`A.len, `len2, `A.cnt, `B.cnt, `cnt1, `A.isNil, `A.viaRec]
      nf := #[`A.len, `A.cnt, `B.cnt, `A.isNil, `A.viaRec] },
    { name := "C2b", ns := `C2b, hand := pairs `C2b [(`A, `A), (`B, `B)]
      users := #[`A.len, `B.size], nf := #[`A.len, `B.size] }]),
  ("Tests/Ix/Compile/Image/C3PropSplit.lean", #[
    { name := "C3", ns := `C3, hand := pairs `C3 [(`P1, `P1), (`P2, `P2)]
      users := #[`p1, `p2], nf := #[`p1, `p2] },
    { name := "C3b", ns := `C3b, hand := pairs `C3b [(`Q1, `X), (`Q2, `X)]
      users := #[`q1, `q2], nf := #[`q1, `q2] }]),
  ("Tests/Ix/Compile/Image/C4Evap.lean", #[
    { name := "C4", ns := `C4, hand := pairs `C4 [(`A, `A), (`B, `B)]
      users := #[`useRec, `useRec1, `rawRec1, `useBelow1, `useBrecOn1, `A.size, `sizeL, `B.size,
        `size_ex, `useRec_ex, `A.isMk]
      nf := #[`useRec, `useRec1, `A.size, `sizeL, `B.size, `A.isMk, `useBrecOn1] },
    { name := "C4b", ns := `C4b, hand := pairs `C4b [(`A2, `A2), (`B2, `B2)]
      users := #[`A2.isMk, `A2.cnt, `roseCnt, `listCnt, `B2.cnt, `cnt_ex, `rawRec, `rawRec2]
      nf := #[`A2.isMk, `A2.cnt, `roseCnt] },
    { name := "C4b-naive", ns := `C4b, hand := pairs `C4b [(`A2, `A2), (`B2, `B2)]
      users := #[], nf := #[], opts := { naiveElim := true }
      ablationOf := some `C4b, viewNs? := some `Abl.C4b.View }]),
  ("Tests/Ix/Compile/Image/C5Collapse.lean", #[
    { name := "C5", ns := `C5, hand := pairs `C5 [(`A, `X), (`B, `X)]
      users := #[`f, `f_ab, `A.f, `B.g, `fg_ab, `fg_bab, `A.h, `B.k, `A.isNil, `B.isNil]
      nf := #[`f, `A.f, `B.g, `A.h, `B.k, `A.isNil, `B.isNil] }]),
  ("Tests/Ix/Compile/Image/C6NestedCollapse.lean", #[
    { name := "C6", ns := `C6, hand := pairs `C6 [(`A, `X), (`B, `X)]
      users := #[`r, `rb, `r1, `t, `A.size, `B.size, `sizeL, `sizeLA, `A.w, `B.w, `wL, `wLA,
        `size_ex, `w_ex]
      nf := #[`A.size, `B.size, `sizeL] }]),
  ("Tests/Ix/Compile/Image/C7IndPred.lean", #[
    { name := "C7", ns := `C7, hand := pairs `C7 [(`P, `X), (`Q, `X)]
      users := #[`p_cases, `P.toQ, `Q.toP], nf := #[`P.toQ] },
    { name := "C7b", ns := `C7b, hand := pairs `C7b [(`EvenP, `EvenP), (`OddP, `OddP), (`R, `R)]
      users := #[`EvenP.toR, `OddP.toR, `EvenP.two], nf := #[`EvenP.toR] }]),
  ("Tests/Ix/Compile/Image/C8Collapse3.lean", #[
    { name := "C8", ns := `C8, hand := pairs `C8 [(`A, `X), (`B, `X), (`C, `C)]
      users := #[`A.f, `B.f, `C.f, `f_ex, `A.h, `B.h, `C.h, `viaRec, `viaRec_ex, `C.isE]
      nf := #[`C.f, `C.h, `C.isE] },
    { name := "C8b", ns := `C8b, hand := pairs `C8b [(`A, `X), (`B, `X), (`C, `X)]
      users := #[`A.f, `B.f, `C.f, `f_ex, `viaRec, `viaRec_ex, `B.isZ], nf := #[`A.f, `B.isZ] },
    { name := "C8-nolift", ns := `C8, hand := pairs `C8 [(`A, `X), (`B, `X), (`C, `C)]
      users := #[], nf := #[], opts := { noLift := true }
      ablationOf := some `C8, viewNs? := some `Abl.C8.View }]),
  ("Tests/Ix/Compile/Image/C9Params.lean", #[
    { name := "C9", ns := `C9, hand := pairs `C9 [(`A, `A), (`B, `B)]
      users := #[`A.depth, `A.isNil, `depth_ex], nf := #[`A.depth, `A.isNil] },
    { name := "C9b", ns := `C9b, hand := pairs `C9b [(`A, `X), (`B, `X)]
      users := #[`A.f, `B.g, `f_ex, `viaRec], nf := #[`A.f] }])]

/-! ## Helpers -/

open Tests.Ix.Compile.ImageProto (record appendLog addAndRecord)

def pp (e : Expr) : CoreM String := do
  return toString (← (Meta.ppExpr e).run')

def normLevels (e : Expr) : Expr :=
  e.replace fun
    | .sort l => some (.sort l.normalize)
    | .const n ls => some (.const n (ls.map (·.normalize)))
    | _ => none

def renameConsts (m : Std.HashMap Lean.Name Lean.Name) (e : Expr) : Expr :=
  e.replace fun
    | .const n ls => some (.const ((m.get? n).getD n) ls)
    | _ => none

/-- The prototype's spec for a case: source ↦ `tyMap`, constructors by
position. -/
def protoSpec (c : Case) (tyMap : Array (Lean.Name × Lean.Name)) (canNs : Lean.Name) :
    CoreM ImageProto.Spec := do
  let mut ctorMap := #[]
  for (a, b) in tyMap do
    let ia ← getConstInfoInduct a
    let ib ← getConstInfoInduct b
    for (ca, cb) in ia.ctors.zip ib.ctors do ctorMap := ctorMap.push (ca, cb)
  return { caseName := c.name, srcNs := c.srcNs, viewNs := c.viewNs, canNs, tyMap, ctorMap,
           users := c.users }

/-- Full applications of image constants replaced by their inline forms;
`none` when the term has none. -/
partial def inlineImages (imgs : Std.HashMap _root_.Ix.Name Image) (e : _root_.Ix.Expr) :
    Except String (Option _root_.Ix.Expr) := do
  let rec go (e : _root_.Ix.Expr) : Except String (_root_.Ix.Expr × Bool) := do
    match e with
    | .app .. =>
      let (h, args) := _root_.Ix.Compile.Canon.getAppFnArgs e
      let mut args' := #[]
      let mut ch := false
      for a in args do
        let (a', c) ← go a
        args' := args'.push a'
        ch := ch || c
      match h with
      | .const n us _ =>
        match imgs.get? n with
        | some img =>
          match ← img.inline us args' with
          | some r => return (r, true)
          | none => return (_root_.Ix.Compile.Canon.mkAppN h args', ch)
        | none => return (_root_.Ix.Compile.Canon.mkAppN h args', ch)
      | _ =>
        let (h', c) ← go h
        return (_root_.Ix.Compile.Canon.mkAppN h' args', ch || c)
    | .lam n t b bi _ =>
      let (t', c1) ← go t
      let (b', c2) ← go b
      return (_root_.Ix.Expr.mkLam n t' b' bi, c1 || c2)
    | .forallE n t b bi _ =>
      let (t', c1) ← go t
      let (b', c2) ← go b
      return (_root_.Ix.Expr.mkForallE n t' b' bi, c1 || c2)
    | .letE n t v b nd _ =>
      let (t', c1) ← go t
      let (v', c2) ← go v
      let (b', c3) ← go b
      return (_root_.Ix.Expr.mkLetE n t' v' b' nd, c1 || c2 || c3)
    | .proj s i x _ =>
      let (x', c) ← go x
      return (_root_.Ix.Expr.mkProj s i x', c)
    | .mdata md x _ =>
      let (x', c) ← go x
      return (_root_.Ix.Expr.mkMData md x', c)
    | e => return (e, false)
  let (e', c) ← go e
  return if c then some e' else none

/-! ## One case -/

def runCase (c : Case) : CoreM Unit := do
  let log := appendLog c.name
  let srcIx := ixName c.srcNs
  let genIx := ixName c.genNs
  let viewIx := ixName c.viewNs
  -- equation lemmas of the user definitions become part of the view (as PRO)
  for u in c.users do
    let n := c.srcNs ++ u
    if let some (.defnInfo _) := (← getEnv).find? n then
      try
        discard <| (Meta.getEqnsFor? n).run'
        discard <| (Meta.getUnfoldEqnFor? n).run'
      catch e => log s!"eqns for {n}: {← e.toMessageData.toString}"
  let some (first, _) := c.hand[0]? | throwError "case without members"
  let all := (← getConstInfoInduct first).all
  -- Pass 1
  let cenv := _root_.Ix.Compile.Canon.Env.ofSource {
    source := { consts := {}, fallback? := some {
      index := (← getEnv).constants.toList.foldl
        (fun m (n, ci) => m.insert (ixName n) (n, ci)) {}
      fetch := fun (_, ci) => some (toIx ci) } }
    addr? := fun n => some (Address.blake3 n.pretty.toUTF8) }
  let block ← match _root_.Ix.Compile.Canon.canonBlock _root_.Ix.Compile.Canon.Rules.phaseA cenv
      (all.toArray.map ixName) with
    | .ok b => pure b
    | .error e => throwError "canonBlock: {e}"
  let comps := block.components.map fun cc => cc.classes.map (·.map (·.pretty))
  log s!"=== Pass 1 (phaseA): components/classes {comps}; change {reprStr block.change}; \
    member order address-decided: {block.memberOrderAddrDecided}"
  let naming : Naming := {
    ind := fun _ _ rep => _root_.Ix.Compile.Canon.nameReplacePrefix rep srcIx genIx
    img := fun r => _root_.Ix.Compile.Canon.nameReplacePrefix r srcIx viewIx }
  let spec ← match ImageSpec.ofBlock naming (ixLookup (← getEnv)) block with
    | .ok s => pure s
    | .error e => throwError "ImageSpec.ofBlock: {e}"
  let genMap : Array (Lean.Name × Lean.Name) := all.toArray.map fun s =>
    (s, toLeanName ((spec.tyMap.get? (ixName s)).getD (ixName s)))
  let hspec ← protoSpec c c.hand c.canNs
  -- G: the canonical declarations
  if c.ablationOf.isNone then
    for d in spec.decls do
      let types := d.types.toList.map fun ty =>
        { name := toLeanName ty.name, type := toLeanExpr ty.type
          ctors := ty.ctors.toList.map fun k =>
            { name := toLeanName k.name, type := toLeanExpr k.type : Constructor } : InductiveType }
      let decl := Declaration.inductDecl (d.levelParams.toList.map toLeanName) d.numParams types
        d.isUnsafe
      let nm := types.head!.name
      log s!"=== canonical block {types.map (·.name)} (component {d.comp})"
      for ty in types do
        log s!"  {ty.name} : {← pp ty.type}"
        for k in ty.ctors do log s!"    {k.name} : {← pp k.type}"
      discard <| addAndRecord hspec "G" decl nm
      -- the kernel's recursors of the canonical block: the generator's `recTy` input
      for (rn, rc) in (← getEnv).constants.toList do
        if let .recInfo rv := rc then
          if types.any (fun ty => rv.all.contains ty.name) then
            log s!"  recursor {rn} : {← pp rv.type}"
  let vspec ← if c.ablationOf.isSome then pure hspec else protoSpec c genMap c.genNs
  -- T, I: images and computation rules
  let imgs ← match imagesOfBlock c.opts (ixLookup (← getEnv)) spec (ixName first) with
    | .ok xs => pure xs
    | .error e => do
      record c.name "T" (toString first) "BUILD-FAIL" e
      pure #[]
  let mut toCan : Std.HashMap Lean.Name Lean.Name := {}
  for (s, can) in c.hand do
    let gen := (genMap.find? (·.1 == s)).map (·.2) |>.getD s
    toCan := toCan.insert gen can
    toCan := toCan.insert (gen ++ `rec) (can ++ `rec)
    for j in [1:10] do
      toCan := toCan.insert (gen.str s!"rec_{j}") (can.str s!"rec_{j}")
    if let some (.inductInfo gi) := (← getEnv).find? gen then
      let ci ← getConstInfoInduct can
      for (a, b) in gi.ctors.zip ci.ctors do toCan := toCan.insert a b
  -- is Pass 1's canonical form the prototype's hand-written one (same partition, same order)?
  let mut canonSame := all.all fun a => all.all fun b =>
    let g := fun x => (genMap.find? (·.1 == x)).map (·.2)
    let h := fun x => (c.hand.find? (·.1 == x)).map (·.2)
    (g a == g b) == (h a == h b)
  if c.ablationOf.isNone then
    for d in spec.decls do
      let cans := d.types.toList.map fun ty => (toCan.get? (toLeanName ty.name)).getD .anonymous
      match (← getEnv).find? cans.head! with
      | some (.inductInfo iv) => canonSame := canonSame && iv.all == cans
      | _ => canonSame := false
  if !canonSame then
    log s!"--- Pass 1's canonical form differs from the prototype's hand-written block: \
      generated {genMap.map (·.2)} vs hand {c.hand.map (·.2)}"
  for img in imgs do
    let n := toLeanName img.name
    let lps := img.levelParams.toList.map toLeanName
    let value := toLeanExpr img.value
    let type := toLeanExpr img.type
    log s!"=== image {n} (of {toLeanName img.leanRec}, arity {img.arity})\n\
      {String.intercalate "\n" (img.log.toList.map ("  " ++ ·))}\n{← pp value}"
    discard <| addAndRecord vspec "T" (.defnDecl {
      name := n, levelParams := lps, type, value, hints := .abbrev, safety := .safe }) n
    -- CMP: against the prototype's transport on the hand-written block
    if c.ablationOf.isNone then
      try
        let (pv, _) ← (ImageProto.buildTransport hspec (toLeanName img.leanRec)).run'
        let mine := renameConsts toCan value
        if mine == pv then record c.name "CMP:image" n.toString "EQUAL" ""
        else if normLevels mine == normLevels pv then
          record c.name "CMP:image" n.toString "EQUAL-LEVELS" ""
        else
          record c.name "CMP:image" n.toString (if canonSame then "DIFFERENT" else "CANON-DIFF")
            s!"see {c.name}.log"
          log s!"--- DIFFERENT from the prototype: {n}\n  generated (renamed): {← pp mine}\n  \
            prototype:           {← pp pv}"
        let stmts ← (ImageProto.iotaStatements hspec (toLeanName img.leanRec)).run'
        for (rule, (pn, pty, _)) in img.rules.zip stmts do
          let mine := renameConsts toCan (toLeanExpr rule.type)
          let v := if mine == pty then "EQUAL"
            else if normLevels mine == normLevels pty then "EQUAL-LEVELS"
            else if canonSame then "DIFFERENT" else "CANON-DIFF"
          record c.name "CMP:rule" pn.toString v ""
          if v == "DIFFERENT" then
            log s!"--- DIFFERENT rule {pn}\n  generated (renamed): {← pp mine}\n  prototype: {← pp pty}"
      catch e =>
        record c.name "CMP:image" n.toString "PROTO-FAIL" (← e.toMessageData.toString)
  -- I: the computation rules, once every image is declared (the right-hand sides call them)
  for img in imgs do
    for rule in img.rules do
      discard <| addAndRecord vspec "I" (.thmDecl {
        name := toLeanName rule.name, levelParams := img.levelParams.toList.map toLeanName
        type := toLeanExpr rule.type, value := toLeanExpr rule.proof }) (toLeanName rule.name)
  if c.ablationOf.isSome then return
  -- V/L: the prototype's view over the images
  ImageProto.copyAll vspec
  -- B1: transport-inlined normal forms (PRO's #bridge_nf)
  for f in c.nf do
    let vf := c.viewNs ++ f
    let vci ← getConstInfo vf
    let nfV ← ImageProto.nf vspec (ImageProto.valueOf vci)
    let nN := vf ++ `_N
    let ok ← addAndRecord vspec "B1:nf-def" (.defnDecl {
      name := nN, levelParams := vci.levelParams, type := vci.type, value := nfV
      hints := .opaque, safety := .safe }) nN
    if ok then
      let lv := vci.levelParams.map mkLevelParam
      let (ty, pf) ← (do
        let eq ← mkEq (.const nN lv) (.const vf lv)
        return (eq, ← mkEqRefl (.const nN lv))).run'
      discard <| addAndRecord vspec "B1:rfl" (.thmDecl {
        name := vf ++ `bridge_nf, levelParams := vci.levelParams, type := ty, value := pf })
        (vf ++ `bridge_nf)
  -- H: the call-site form (inline at full applications, developed)
  let imgMap : Std.HashMap _root_.Ix.Name Image := imgs.foldl (fun m i => m.insert i.name i) {}
  let viewDefs := (← getEnv).constants.toList.filterMap fun (n, ci) =>
    match ci with
    | .defnInfo d =>
      if c.viewNs.isPrefixOf n && d.safety == .safe && !imgMap.contains (ixName n) then some d
      else none
    | _ => none
  for d in viewDefs.toArray.qsort (fun a b => Name.quickLt a.name b.name) do
    match inlineImages imgMap (toIxExpr d.value) with
    | .error e => record c.name "H:def" d.name.toString "BUILD-FAIL" e
    | .ok none => pure ()
    | .ok (some v) =>
      let nH := d.name ++ `_H
      let ok ← addAndRecord vspec "H:def" (.defnDecl {
        name := nH, levelParams := d.levelParams, type := d.type, value := toLeanExpr v
        hints := .opaque, safety := .safe }) nH
      if ok then
        let lv := d.levelParams.map mkLevelParam
        let (ty, pf) ← (do
          let eq ← mkEq (.const nH lv) (.const d.name lv)
          return (eq, ← mkEqRefl (.const nH lv))).run'
        discard <| addAndRecord vspec "H:rfl" (.thmDecl {
          name := d.name ++ `bridge_H, levelParams := d.levelParams, type := ty, value := pf })
          (d.name ++ `bridge_H)

/-! ## The development on small terms (Q10) -/

/-- `instantiate f args` against the expected developed term: hereditary β, projection of a
constructor and η at the substituted variable; the user's own redexes and recursor applications
(never ι) left alone. -/
def devChecks : Array (String × Bool) :=
  let ty := mkConst `Nat
  let a := mkConst `a
  let b := mkConst `b
  let g := mkConst `g
  let h := mkConst `h
  let z := mkConst `z
  let lam (n : Lean.Name) (body : Expr) : Expr := .lam n ty body .default
  let dev (f : Expr) (args : Array Expr) : Option Expr :=
    match _root_.Ix.Compile.Image.instantiate (toIxExpr f) (args.map toIxExpr) with
    | .ok e => some (toLeanExpr e)
    | .error _ => none
  let pair := mkAppN (mkConst ``PProd.mk [1, 1]) #[ty, ty, a, b]
  let natRec := fun (m : Expr) => mkAppN (mkConst ``Nat.rec [1]) #[m, z, h, mkApp (mkConst ``Nat.succ) a]
  #[("β, hereditary: (λ m. m a) (λ x. x) = a",
      dev (lam `m (mkApp (.bvar 0) a)) #[lam `x (.bvar 0)] == some a),
    ("β, two levels: (λ m. m (λ y. y) b) (λ k x. k x) = b",
      dev (lam `m (mkAppN (.bvar 0) #[lam `y (.bvar 0), b]))
        #[lam `k (lam `x (mkApp (.bvar 1) (.bvar 0)))] == some b),
    ("projection: (λ p. p.1) ⟨a, b⟩ = a",
      dev (lam `p (.proj ``PProd 0 (.bvar 0))) #[pair] == some a),
    ("η at the substituted variable: (λ m. λ y. m y) g = g",
      dev (lam `m (lam `y (mkApp (.bvar 1) (.bvar 0)))) #[g] == some g),
    ("the user's η-redex is kept: (λ m. λ y. m y) (λ x. h x) = λ y. h y",
      dev (lam `m (lam `y (mkApp (.bvar 1) (.bvar 0)))) #[lam `x (mkApp h (.bvar 0))]
        == some (lam `y (mkApp h (.bvar 0)))),
    ("a redex already in the body is kept: (λ m. (λ w. w) m) g = (λ w. w) g",
      dev (lam `m (mkApp (lam `w (.bvar 0)) (.bvar 0))) #[g] == some (mkApp (lam `w (.bvar 0)) g)),
    ("never ι: (λ m. Nat.rec m z h (succ a)) (λ x. x) keeps the recursor",
      dev (lam `m (natRec (.bvar 0))) #[lam `x (.bvar 0)] == some (natRec (lam `x (.bvar 0)))),
    ("extra arguments stay applied: (λ m. m) g a = g a",
      dev (lam `m (.bvar 0)) #[g, a] == some (mkApp g a))]

/-! ## Optional: the view closures as `.ixe`, for the certified checker -/

/-- Every constant reachable from `seeds`, with the constructors and recursors of each inductive
(the checker declines a block without its recursor). -/
partial def closure (env : Environment) (seeds : List Lean.Name) : Array (Lean.Name × ConstantInfo) :=
  let find := fun n => (env.find? n).orElse fun _ => env.toKernelEnv.find? n
  let rec go (todo : List Lean.Name) (seen : NameSet) (acc : Array (Lean.Name × ConstantInfo)) :=
    match todo with
    | [] => acc
    | n :: rest =>
      if seen.contains n then go rest seen acc else
      let seen := seen.insert n
      match find n with
      | none => go rest seen acc
      | some ci =>
        let extra : List Lean.Name := match ci with
          | .inductInfo iv =>
            iv.ctors ++ iv.all.map (· ++ `rec) ++
              (List.range iv.numNested).map fun i => iv.all.head! |>.str s!"rec_{i + 1}"
          | .ctorInfo cv => [cv.induct]
          | .recInfo rv => rv.all
          | _ => []
        go (ci.getUsedConstantsAsSet.toList ++ extra ++ rest) seen (acc.push (n, ci))
  go seeds {} #[]

/-- Compile the view and canonical constants of a fixture's cases with the Rust compiler into
`out/image-gen/<stem>.ixe` (run `kernel-check-ixe` on it afterwards). -/
def dumpIxe (env : Environment) (stem : String) (cases : Array Case) : IO String := do
  let nss := cases.filter (·.ablationOf.isNone) |>.map fun c => (c.viewNs, c.genNs)
  let seeds := env.constants.toList.filterMap fun (n, ci) =>
    if nss.any (fun (v, g) => v.isPrefixOf n || g.isPrefixOf n) && !(ci matches .axiomInfo _) then
      some n else none
  let consts := (closure env seeds).toList
  let consts ← IO.ofExcept <| _root_.Ix.Compile.prepareRegisteredConstants env consts
  let path := s!"out/image-gen/{stem}.ixe"
  let status ← _root_.Ix.CompileM.rsCompileEnvBytesFFI consts path true
  return s!"{stem}: {seeds.length} seeds, {consts.length} constants, {status.bytes} bytes, \
    {status.ungrounded.size} ungrounded"

/-! ## The suite -/

def countRows (rows : Array ImageProto.Row) (p : ImageProto.Row → Bool) : Nat :=
  (rows.filter p).size

def run : IO UInt32 := do
  ImageProto.rowsRef.set #[]
  ImageProto.logRef.set #[]
  let mut failures : Array String := #[]
  for (path, cases) in files do
    try
      let env ← getFileEnv path
      let ctx : Core.Context := { fileName := path, fileMap := default, maxHeartbeats := 0 }
      let (_, st) ← (do
          for c in cases do
            try runCase c
            catch e => record c.name "CASE" c.name "ERROR" (← e.toMessageData.toString)
        : CoreM Unit).toIO ctx { env }
      if (← IO.getEnv "IMAGE_GEN_IXE").isSome then
        IO.FS.createDirAll "out/image-gen"
        let stem := (System.FilePath.mk path).fileStem.getD path
        IO.println s!"[image-gen] ixe {← dumpIxe st.env stem cases}"
    catch e => failures := failures.push s!"{path}: {e}"
  let rows ← ImageProto.rowsRef.get
  let logs ← ImageProto.logRef.get
  IO.FS.createDirAll "out/image-gen"
  IO.FS.writeFile "out/image-gen/results.tsv" <| String.join <| rows.toList.map fun r =>
    s!"{r.case}\t{r.tag}\t{r.name}\t{r.verdict}\t{r.msg}\n"
  let caseNames := files.foldl (fun acc (_, cs) => acc ++ cs.map (·.name)) #[]
  for cn in caseNames do
    IO.FS.writeFile s!"out/image-gen/{cn}.log" <| String.join <|
      (logs.filter (·.1 == cn)).toList.map (·.2 ++ "\n")
  -- per-case table
  let tags := #["G", "T", "I", "CMP:image", "CMP:rule", "V:def", "V:thm", "V:ind", "L:def",
    "L:thm", "B1:rfl", "H:def", "H:rfl"]
  IO.println s!"[image-gen] case        {String.intercalate " " (tags.toList.map (·.take 9 |>.toString))}"
  for cn in caseNames do
    let cr := rows.filter (·.case == cn)
    let cells := tags.map fun t =>
      let all := cr.filter (·.tag == t)
      let ok := all.filter fun r => r.verdict == "ACCEPT" || r.verdict == "EQUAL"
      if all.isEmpty then "-" else s!"{ok.size}/{all.size}"
    IO.println s!"[image-gen] {cn}  {String.intercalate " " cells.toList}"
  for r in rows do
    if r.verdict != "ACCEPT" && r.verdict != "EQUAL" then
      IO.println s!"[image-gen] {r.case} {r.tag} {r.name}: {r.verdict} {(r.msg.take 400).toString}"
  -- expectations
  let main := rows.filter fun r => !r.case.endsWith "-naive" && !r.case.endsWith "-nolift"
  let acc := fun (t : String) => countRows main fun r => r.tag == t && r.verdict == "ACCEPT"
  let tot := fun (t : String) => countRows main fun r => r.tag == t
  let check := fun (fs : Array String) (ok : Bool) (msg : String) => if ok then fs else fs.push msg
  failures := check failures (acc "T" == 38 && tot "T" == 38) s!"images {acc "T"}/{tot "T"}, want 38/38"
  failures := check failures (acc "I" == 62 && tot "I" == 62) s!"rules {acc "I"}/{tot "I"}, want 62/62"
  failures := check failures (acc "B1:rfl" == 45 && tot "B1:rfl" == 45)
    s!"B1 bridges {acc "B1:rfl"}/{tot "B1:rfl"}, want 45/45"
  failures := check failures (acc "G" == tot "G" && tot "G" > 0) s!"canonical blocks {acc "G"}/{tot "G"}"
  failures := check failures (acc "H:rfl" == tot "H:def" && acc "H:def" == tot "H:def")
    s!"call-site forms {acc "H:def"}/{acc "H:rfl"}/{tot "H:def"}"
  let rej := fun (cn t : String) => countRows rows fun r => r.case == cn && r.tag == t && r.verdict == "REJECT"
  failures := check failures (rej "C8-nolift" "T" == 3) s!"C8-nolift: {rej "C8-nolift" "T"} images rejected, want 3"
  failures := check failures ((rows.filter fun r => r.case == "C4b-naive" && r.tag == "I" &&
      r.verdict == "REJECT" && (r.name.endsWith "rec_1.iota_node")).size == 1)
    "C4b-naive: A2.rec_1.iota_node not rejected"
  for r in main do
    if (r.tag.startsWith "CMP" && r.verdict != "EQUAL" && r.verdict != "EQUAL-LEVELS" &&
        r.verdict != "CANON-DIFF") then
      failures := failures.push s!"{r.case} {r.tag} {r.name}: {r.verdict} (unclassified)"
  for r in main do
    if r.verdict == "REJECT" || r.verdict == "BUILD-FAIL" || r.verdict == "ERROR" then
      failures := failures.push s!"{r.case} {r.tag} {r.name}: {r.verdict}"
  let eq := fun (t v : String) => countRows main fun r => r.tag == t && r.verdict == v
  IO.println s!"[image-gen] totals: images {acc "T"}/{tot "T"}, rules {acc "I"}/{tot "I"}, \
    B1 {acc "B1:rfl"}/{tot "B1:rfl"}, view {acc "V:def" + acc "V:thm" + acc "V:ind" + acc "V:opaque"
      + acc "V:ax" + acc "L:def" + acc "L:thm"}/{tot "V:def" + tot "V:thm" + tot "V:ind" + tot "V:opaque"
      + tot "V:ax" + tot "L:def" + tot "L:thm"}, call-site forms {acc "H:def"}+{acc "H:rfl"}/{tot "H:def"}"
  IO.println s!"[image-gen] vs prototype: images EQUAL {eq "CMP:image" "EQUAL"}, EQUAL-LEVELS \
    {eq "CMP:image" "EQUAL-LEVELS"}, CANON-DIFF {eq "CMP:image" "CANON-DIFF"}, DIFFERENT \
    {eq "CMP:image" "DIFFERENT"}; rules EQUAL {eq "CMP:rule" "EQUAL"}, EQUAL-LEVELS \
    {eq "CMP:rule" "EQUAL-LEVELS"}, CANON-DIFF {eq "CMP:rule" "CANON-DIFF"}, DIFFERENT \
    {eq "CMP:rule" "DIFFERENT"}"
  let devOk := devChecks.filter (·.2)
  IO.println s!"[image-gen] development: {devOk.size}/{devChecks.size}"
  for (msg, ok) in devChecks do
    if !ok then failures := failures.push s!"development: {msg}"
  IO.println s!"[image-gen] {failures.size} failures"
  for f in failures do IO.println s!"[image-gen] FAIL {f}"
  return if failures.isEmpty then 0 else 1

end Tests.Ix.Compile.Image
