/-
  opt-census (M7 L3-def): the definitional passes' theorems on the `pass3`
  fixtures (`Ix/CompileCert/Opt/**`, `plans/review2/M7-L3-def.md` §1.7).

  Per compile unit (the `pass3` suite's units, compiled in-process by the Lean
  pipeline under Pass 3, the default), with every changed block's view built
  afresh as `dev-census` does:

  1. **the core against the executable** (refactor R-2): every constant that
     mentions a head is rewritten by the executable (`Translate.rewriteConstM`,
     with its tables and records) and by the table-free core the theorems are
     about (`Ix.CompileCert.Opt.rewriteConstP`, at a Lean name); their
     erasures (`Ix.CompileCert.Conv.er`) must be equal, and the two must fail
     together;
  2. **the shapes are within Lean's ranges** (`Ix.CompileCert.Opt.ShapesWF`):
     every shape of every block's recursors;
  3. **the Def 3.5 bodies** (`RecOnBody`, the `CasesOnBody` frame): Lean's
     `x.recOn` of a changed block is `λ ps ms is t mins. x.rec ps ms mins is t`
     and Lean's `x.casesOn` is `λ ps motive is t mins. x.rec ps M⃗ N⃗ is t`;
     Pass 2's `ρ.recOn` (regenerated by `Ix.AuxGen.generateRecOn` from the
     canonical recursor) is the same construction over `ρ` (`IxRecOnLaw`);
  4. **coverage**: the passes that fire at the occurrences of the inputs
     (the engine at every full application of a head, before rewriting);
  5. **the core copies against the executables** (`AuxGenCopies`, design
     D-3): the original arbitrary-HashMap `batchAbstract` compatibility
     entry point against `Ix.CompileCert.Opt.batchAbstractP`, over every
     telescope opened from the inputs' types and values. The production
     binder builders now use structural NameTable lookup; their focused
     forged-cache and ordinary-name controls are in `aux-gen-unit`.

  Run with: `lake test -- --ignored opt-census` (`OPT_CENSUS_ONLY` restricts
  the units: comma-separated stems, `twins`, `corpus`).
-/
import Tests.Ix.Compile.Pass3
import Ix.CompileCert.Opt
import Ix.CompileCert.Opt.AuxCore

open Lean (Environment)

namespace Tests.Ix.Compile.OptCensus

open _root_.Ix (Name Level Expr ConstantInfo RecursorVal)
open _root_.Ix.CompileCert.Conv (Tm er)
open _root_.Ix.Compile.Canon (getAppFnArgs mkAppN)

/-! ## Erased terms: equality -/

partial def tmEq : Tm → Tm → Bool
  | .bvar i, .bvar j => i == j
  | .fvar a, .fvar b => a == b
  | .mvar a, .mvar b => a == b
  | .sort u, .sort v => u == v
  | .const a us, .const b vs => a == b && us == vs
  | .app f a, .app g b => tmEq f g && tmEq a b
  | .lam t b, .lam t' b' => tmEq t t' && tmEq b b'
  | .pi t b, .pi t' b' => tmEq t t' && tmEq b b'
  | .letE t v b, .letE t' v' b' => tmEq t t' && tmEq v v' && tmEq b b'
  | .lit l, .lit l' => l == l'
  | .proj s i e, .proj s' i' e' => s == s' && i == i' && tmEq e e'
  | _, _ => false

/-- The expressions of a constant, erased: its type, then its value or its rules' right-hand sides. -/
def ciTms (ci : ConstantInfo) : List Tm :=
  let ty := er ci.getCnst.type
  match ci with
  | .defnInfo v => [ty, er v.value]
  | .thmInfo v => [ty, er v.value]
  | .opaqueInfo v => [ty, er v.value]
  | .recInfo v => ty :: v.rules.toList.map (er ·.rhs)
  | _ => [ty]

def tmsEq (a b : List Tm) : Bool := a.length == b.length && (a.zip b).all fun (x, y) => tmEq x y

/-! ## Decidable forms of the Def 3.5 bodies -/

/-- Strip `n` leading λs of an erased term. -/
def stripLamsTm : Nat → Tm → Option Tm
  | 0, t => some t
  | n + 1, .lam _ b => stripLamsTm n b
  | _, _ => none

/-- The spine of an erased application. -/
def spineTm : Tm → Tm × List Tm
  | .app f a => let (h, as) := spineTm f; (h, as ++ [a])
  | t => (t, [])

/-- `RecOnBody c us np nm nmin ni v`, decided. -/
def recOnBodyB (c : Name) (us : Array Level) (np nm nmin ni : Nat) (v : Tm) : Bool :=
  let ar := np + nm + nmin + ni + 1
  match stripLamsTm ar v with
  | none => false
  | some body =>
    tmEq body (Tm.appN (.const c us)
      ((_root_.Ix.CompileCert.Opt.recOnIdx np nm nmin ni).map fun p => .bvar (ar - 1 - p)))

/-- The frame of `CasesOnBody c us np ni nc M N v` (the slots `M`, `N` arbitrary), decided: the
parameters, indices and major in place, `nm` motive and `nmin` minor slots. -/
def casesOnFrameB (c : Name) (us : Array Level) (np nm nmin ni nc : Nat) (v : Tm) : Bool :=
  match stripLamsTm (np + 1 + ni + 1 + nc) v with
  | none => false
  | some body =>
    let (h, args) := spineTm body
    let tv := fun p => Tm.bvar (np + 1 + ni + 1 + nc - 1 - p)
    tmEq h (.const c us) && args.length == np + nm + nmin + ni + 1 &&
      (List.range np).all (fun i => tmEq (args.getD i (.bvar 0)) (tv i)) &&
      (List.range (ni + 1)).all (fun i => tmEq (args.getD (np + nm + nmin + i) (.bvar 0)) (tv (np + 1 + i)))

/-! ## One unit -/

structure UnitResult where
  /-- Constants compared, equal, failing together. -/
  compared : Nat := 0
  equal : Nat := 0
  bothFail : Nat := 0
  shapes : Nat := 0
  recOns : Nat := 0
  casesOns : Nat := 0
  ixRecOns : Nat := 0
  firings : Std.HashMap String Nat := {}
  copies : Nat := 0
  problems : Array String := #[]
  refused : Nat := 0

def UnitResult.merge (a b : UnitResult) : UnitResult :=
  { compared := a.compared + b.compared, equal := a.equal + b.equal, bothFail := a.bothFail + b.bothFail,
    shapes := a.shapes + b.shapes, recOns := a.recOns + b.recOns, casesOns := a.casesOns + b.casesOns,
    ixRecOns := a.ixRecOns + b.ixRecOns, copies := a.copies + b.copies,
    firings := b.firings.fold (fun m k v => m.insert k (m.getD k 0 + v)) a.firings,
    problems := a.problems ++ b.problems, refused := a.refused + b.refused }

/-- The full applications of heads in an expression (before rewriting). -/
partial def occurrences (heads : Std.HashMap Name Name) (arity : Name → Option Nat) :
    Expr → Array (Name × Array Level × Array Expr)
  | e@(.app ..) | e@(.const ..) =>
    let (h, args) := getAppFnArgs e
    let inner := args.foldl (fun acc a => acc ++ occurrences heads arity a) #[]
    match h with
    | .const n us _ =>
      if heads.contains n && (arity n).any (· ≤ args.size) then inner.push (n, us, args) else inner
    | _ => inner ++ occurrences heads arity h
  | .lam _ t b _ _ | .forallE _ t b _ _ => occurrences heads arity t ++ occurrences heads arity b
  | .letE _ t v b _ _ => occurrences heads arity t ++ occurrences heads arity v ++ occurrences heads arity b
  | .proj _ _ x _ | .mdata _ x _ => occurrences heads arity x
  | _ => #[]

/-- The original arbitrary-HashMap compatibility map from telescope variables to positions. -/
def fvarMapOf (decls : Array _root_.Ix.AuxGen.LocalDecl) : Std.HashMap Name Nat :=
  decls.zipIdx.foldl (fun m (b, i) => m.insert b.fvarName i) {}

/-- Compatibility-entry abstractions over the telescope opened from `e`: (checked, differing). -/
def copyChecks (e : Expr) : Nat × Nat :=
  let (_, decls, body) := match e with
    | .lam .. => _root_.Ix.AuxGen.lambdaTelescope e 4096 "oc" 0
    | _ => _root_.Ix.AuxGen.forallTelescope e 4096 "oc" 0
  let m := fvarMapOf decls
  let pairs := (body, decls.size) :: (decls.toList.zipIdx.map fun (d, j) => (d.domain, j))
  pairs.foldl (fun (c, bad) (x, j) =>
    (c + 1, if _root_.Ix.AuxGen.batchAbstract x m j 0 == _root_.Ix.CompileCert.Opt.batchAbstractP x m j 0
      then bad else bad + 1)) (0, 0)

def levelParamsOf (c : ConstantInfo) : Array Level := c.getCnst.levelParams.map Level.mkParam

def runCompiled (cenv : _root_.Ix.CompileM.CompileEnv) : UnitResult := Id.run do
  let mut res : UnitResult := {}
  if cenv.p3Heads.isEmpty then return res
  let inp := _root_.Ix.Compile.Pass.viewInput cenv
  let mut views : Std.HashMap Name _root_.Ix.Compile.Pass.BlockView := {}
  for (key, all) in cenv.p3Blocks do
    match _root_.Ix.Compile.Pass.buildView inp all with
    | .ok v => views := views.insert key v
    | .error e => res := { res with problems := res.problems.push s!"view {key.pretty}: {e}" }
  let blocks := _root_.Ix.Compile.Pass.optBlocks cenv views
  let env : _root_.Ix.Compile.Pass.Opt.OptEnv :=
    { ienv := cenv.env, resolves := fun n => (_root_.Ix.Compile.Pass.resolveAddr cenv n).isSome
      blockOf := fun h => (cenv.p3Heads.get? h).bind blocks.get?
      addrOf := _root_.Ix.Compile.Pass.resolveAddr cenv
      ixForm? := _root_.Ix.Compile.Pass.ixFormOf cenv }
  -- 2. the shapes; 3. the Def 3.5 bodies
  for (_, b) in blocks do
    for (r, s) in b.shapes do
      res := { res with shapes := res.shapes + 1 }
      unless s.motiveSrc.all (· < s.nm) && (s.minorSrc.filterMap id).all (· < s.nmin) do
        res := { res with problems := res.problems.push s!"shape of {r.pretty}: out of Lean's ranges" }
      -- Lean's `x.recOn` and `x.casesOn` over `x.rec` (when `r` is `x.rec`)
      if let .str x "rec" _ := r then
        let recOn := Name.mkStr x "recOn"
        if let some ci@(.defnInfo d) := cenv.env.get? recOn then
          res := { res with recOns := res.recOns + 1 }
          unless recOnBodyB r (levelParamsOf ci) s.np s.nm s.nmin s.ni (er d.value) do
            res := { res with problems := res.problems.push s!"{recOn.pretty}: not mkRecOn over {r.pretty}" }
        let casesOn := Name.mkStr x "casesOn"
        if let (some ci@(.defnInfo d), some (.inductInfo iv)) := (cenv.env.get? casesOn, cenv.env.get? x) then
          res := { res with casesOns := res.casesOns + 1 }
          unless casesOnFrameB r (levelParamsOf ci) s.np s.nm s.nmin s.ni iv.ctors.size (er d.value) do
            res := { res with problems := res.problems.push s!"{casesOn.pretty}: not mkCasesOn's frame over {r.pretty}" }
      -- Pass 2's `ρ.recOn` over `ρ`
      if let some ixRecOn := _root_.Ix.Compile.Pass.Opt.ixAuxOf s.ixRec .kRecOn then
        if env.resolves ixRecOn then
          if let some rv := b.ixRecs.get? s.ixRec then
            match _root_.Ix.AuxGen.generateRecOn ixRecOn { rv with cnst := { rv.cnst with name := s.ixRec } } with
            | some d =>
              res := { res with ixRecOns := res.ixRecOns + 1 }
              let ls := d.levelParams.map Level.mkParam
              unless recOnBodyB s.ixRec ls s.np s.motiveSrc.size s.minorSrc.size s.ni (er d.value) do
                res := { res with problems := res.problems.push s!"{ixRecOn.pretty}: not mkRecOn over {s.ixRec.pretty}" }
            | none => pure ()
  -- 1. the core against the executable; 4. coverage
  let table := _root_.Ix.Compile.Pass.expansionTable cenv views
  let lookup := _root_.Ix.Compile.Pass.expansionLookupIn table cenv views
  let opt := _root_.Ix.Compile.Pass.optLookup cenv blocks
  let arity : Name → Option Nat := fun n => match lookup n with
    | .ok (some x) => some x.arity
    | _ => none
  for (n, ci) in cenv.env.consts do
    if (_root_.Ix.Compile.Pass.headsIn cenv.p3Heads ci).isEmpty then continue
    let exec := (_root_.Ix.Compile.Pass.rewriteConstM lookup ci).run { base := 0, opt? := opt }
    let core := _root_.Ix.CompileCert.Opt.rewriteConstP lookup opt false ci
    res := { res with compared := res.compared + 1 }
    match exec, core with
    | .ok (x, _), .ok y =>
      if tmsEq (ciTms x) (ciTms y) then res := { res with equal := res.equal + 1 }
      else res := { res with problems := res.problems.push s!"rewrite {n.pretty}: core and executable differ" }
    | .error _, .error _ =>
      if cenv.ungrounded.contains n then res := { res with refused := res.refused + 1 }
      else res := { res with bothFail := res.bothFail + 1 }
    | .ok _, .error e => res := { res with problems := res.problems.push s!"rewrite {n.pretty}: only the core fails: {e}" }
    | .error e, .ok _ => res := { res with problems := res.problems.push s!"rewrite {n.pretty}: only the executable fails: {e}" }
    let roots := match ci with
      | .defnInfo v => #[ci.getCnst.type, v.value]
      | .thmInfo v => #[ci.getCnst.type, v.value]
      | .opaqueInfo v => #[ci.getCnst.type, v.value]
      | _ => #[ci.getCnst.type]
    for root in roots do
      let (c, bad) := copyChecks root
      res := { res with copies := res.copies + c }
      if bad > 0 then
        res := { res with problems := res.problems.push s!"copies {n.pretty}: batchAbstract and its copy differ ({bad})" }
      for (h, us, args) in occurrences cenv.p3Heads arity root do
        if let some (nm, _, _) := _root_.Ix.Compile.Pass.Opt.engineFull env { head := h, us, args } then
          res := { res with firings := res.firings.insert nm (res.firings.getD nm 0 + 1) }
  return res

def summary (name : String) (r : UnitResult) : Array String := Id.run do
  let mut out : Array String := #[]
  let fs := r.firings.toArray.qsort (fun a b => a.1 < b.1)
  out := out.push s!"{name}: rewritten constants={r.compared} core=executable={r.equal} both-fail={r.bothFail} refused-by-the-compile={r.refused} shapes={r.shapes} recOn={r.recOns} casesOn={r.casesOns} ixRecOn={r.ixRecOns} copies={r.copies} firings={fs.toList}"
  for p in r.problems do out := out.push s!"{name}: PROBLEM {p}"
  return out

def run (env : Environment) : IO UInt32 := do
  let only := ((← IO.getEnv "OPT_CENSUS_ONLY").map (·.splitOn ",")).getD []
  let want := fun (s : String) => only.isEmpty || only.contains s
  let mut all : UnitResult := {}
  let mut units := 0
  let files := Tests.Ix.Compile.Pass3.auxCertFiles ++ Tests.Ix.Compile.Pass3.protoFiles ++
    Tests.Ix.Compile.Pass3.passFiles ++ Tests.Ix.Compile.Pass3.pjPassFiles
  let mut work : Array (String × IO Tests.Ix.Compile.Pass3.CUnit) := #[]
  for p in files do
    let stem := (System.FilePath.mk p).fileStem.getD p
    if want stem && !Tests.Ix.Compile.Pass3.leanRejects.contains stem then
      work := work.push (stem, Tests.Ix.Compile.Pass3.unitOfFile p)
  if want "twins" then
    work := work.push ("twins", do
      let (seeds, _) := Tests.Ix.Compile.Twins.familyClosure env Tests.Ix.Compile.Twins.allFamilies
      pure { name := "twins", env, seeds, closure := Tests.Ix.Compile.Pass3.closureOf env seeds.toList })
  if want "corpus" then
    work := work.push ("corpus", do
      let closure := Tests.Ix.Compile.Pass3.closureOf env ((validateAuxClosure env).map (·.1))
      pure { name := "corpus", env, seeds := (closure.map (·.1)).toArray, closure })
  for (stem, mk) in work do
    try
      let u ← mk
      let on ← Tests.Ix.Compile.Pass3.compileUnit u
      let r := runCompiled on.cenv
      units := units + 1
      for l in summary stem r do IO.println s!"[opt-census] {l}"
      all := all.merge { r with problems := r.problems.map (s!"{stem}: " ++ ·) }
    catch e =>
      IO.println s!"[opt-census] {stem}: compile refused ({(toString e).take 160})"
  for l in summary "TOTAL" all do IO.println s!"[opt-census] {l}"
  IO.println s!"[opt-census] {units} units, {all.compared} constants, {all.problems.size} problem(s)"
  return if all.problems.isEmpty && units > 0 then 0 else 1

end Tests.Ix.Compile.OptCensus
