/-
  aux-oracle: Lean's own auxiliaries against Ix's regenerated ones (Phase A
  §5.3; design document §4.7).

  For every block twin family (`Tests.Ix.Compile.Twins`: the oracle
  experiment's pairs, the prototype's cases, the library twins generated by
  `Tests.Ix.Compile.Oracle.Gen`, and `UnivSplit`), the reference
  presentation `T` is the canonical one, whose auxiliaries were built by
  Lean's own constructions (the `inductive` elaborator, or `Gen.twinBlock`
  replaying it). For each auxiliary `t` of `T` (`rec`, `rec_N`, `casesOn`,
  `recOn`, `below`, `below_N`, `brecOn`, `brecOn_N`, `.go`, `.eq`,
  `noConfusionType`, `noConfusion`, `ctorIdx`, `ctorElim`, `_sizeOf_N`, …)
  and each auxiliary `o` of the original presentation `O` that the name map
  sends to `t`:

  - `lean(t)`: Lean's own form of `t` compiled through `ix compile-lean`,
    i.e. `Named.original` when the compiler regenerated `t`, else `t`'s
    address;
  - `ix(o)`: the auxiliary Ix regenerated for `O`.

  The oracle requires `ix(o) = lean(t)` byte for byte. Every exception is
  classified, and the suite passes when every exception is in an expected
  class: the six split differences of §4.7 ((a) universe list, (b) existence
  for the Lean block, (c) `noConfusion` enumeration form, (d) the `sizeOf`
  family, (e)/(f) surgery), plus `PACKAGING`, Ix's one-block-per-kind
  packaging of a mutual block's auxiliaries (§2.8, D6: `ix(o) = ix(t)`, and
  `ix(t)` is a projection into a block of several members while Lean's form
  is compiled as its own constant, so the two are not comparable by address
  until D6). Class (f) also takes the open audit defects of a fixture at
  this head (WB-B1 `FieldBelow`, WB `RecAlias`), with the defect id.
  A constant absent on one side is class (b).

  Also checked: that `T` is in Ix's canonical order (in every Lean block of
  `T`, the `iPrj` indices of the members increase), which the oracle
  presupposes; a non-canonical `T` fails the suite.

  Run with: `lake test -- --ignored aux-oracle`.
-/
import Tests.Ix.Compile.Twins
import Tests.Ix.Compile.Oracle.Lib

open Lean Tests.Ix.Compile.Twins

namespace Tests.Ix.Compile.Oracle

/-- Generated-name suffixes (`Gen.familyNames`). -/
def genSuffix (s : String) : Bool :=
  ["rec", "casesOn", "recOn", "below", "brecOn", "go", "eq", "noConfusionType", "noConfusion",
    "ctorIdx", "ctorElim", "ctorElimType", "_sizeOf_inst", "inj", "injEq", "sizeOf_spec", "elim",
    ].contains s
  || s.startsWith "rec_" || s.startsWith "below_" || s.startsWith "brecOn_"
  || s.startsWith "_sizeOf_"

/-- An auxiliary of an inductive family: a name whose components after the
    longest prefix naming an inductive or a constructor are all generated. -/
def isAux (env : Environment) (n : Name) : Bool :=
  let rec go (p : Name) (sfx : List String) : Bool :=
    match p with
    | .str q s =>
      let here := match env.find? p with
        | some (.inductInfo _) | some (.ctorInfo _) => !sfx.isEmpty && sfx.all genSuffix
        | _ => false
      here || go q (s :: sfx)
    | _ => false
  match env.find? n with
  | some (.inductInfo _) | some (.ctorInfo _) => false
  | _ => go n []

def kindOf (env : Ixon.Env) (a : Address) : String :=
  match env.getConst? a with
  | some c => match c.info with
    | .defn _ => "defn" | .recr _ => "recr" | .axio _ => "axio" | .quot _ => "quot"
    | .cPrj _ => "cPrj" | .rPrj _ => "rPrj" | .iPrj _ => "iPrj" | .dPrj _ => "dPrj"
    | .muts ms => s!"muts{ms.size}"
  | none => "absent"

/-- The member count of the block a projection points into (`none` for a
    constant that is not a projection). -/
def projBlockSize (env : Ixon.Env) (a : Address) : Option Nat := do
  let c ← env.getConst? a
  let blk ← match c.info with
    | .cPrj p => some p.block | .rPrj p => some p.block | .iPrj p => some p.block
    | .dPrj p => some p.block | _ => none
  match (← env.getConst? blk).info with
  | .muts ms => some ms.size
  | _ => none

/-- The position of an inductive in its Ix block (`iPrj` index). -/
def iPrjIdx (env : Ixon.Env) (a : Address) : Option Nat := do
  match (← env.getConst? a).info with
  | .iPrj p => some p.idx.toNat
  | _ => none

/-- The expected class of an exception, from the auxiliary's name and the
    two Lean constants. -/
def classify (env : Environment) (t o : Option Name) (sameIx packaged : Bool) : String :=
  let last := match t.orElse fun _ => o with
    | some n => match n with | .str _ s => s | _ => ""
    | none => ""
  let lps (n? : Option Name) : Option Nat := n?.bind fun n => (env.find? n).map (·.levelParams.length)
  if t.isNone || o.isNone then "(b)"
  else if lps t != lps o then "(a)"
  else if last == "noConfusion" || last == "noConfusionType" then "(c)"
  else if last.startsWith "_sizeOf_" || last == "sizeOf_spec" then "(d)"
  else if sameIx && packaged then "PACKAGING"
  else "UNEXPECTED"

structure Row where
  family : Name
  aux : Name
  cls : String
  detail : String

/-- One family: the rows of every exception, and the number compared. -/
def oracleFamily (env : Environment) (ixon : Ixon.Env) (f : Family) : IO (Nat × Array Row) := do
  let some a := f.pres.head? | return (0, #[])
  let some b := f.pres[1]? | return (0, #[])
  let addr (n : Name) : Option Address := ixon.getAddr? (Ix.Name.fromLeanName n)
  let named (n : Name) := ixon.named.get? (Ix.Name.fromLeanName n)
  let lean (n : Name) : Option Address := match named n with
    | some nm => some (nm.original.map (·.1) |>.getD nm.addr)
    | none => none
  let rel (n : Name) : Name := n.replacePrefix a.ns .anonymous
  let ca := (presConsts env a).filter (isAux env ·.1)
  let cb := (presConsts env b).filter (isAux env ·.1)
  let mapB := mapInto a b
  let mut rows : Array Row := #[]
  let mut n := 0
  let mut hit : Std.HashSet Name := {}
  for (o, _) in cb do
    let t := mapB o
    if !(ca.any (·.1 == t)) then
      rows := rows.push
        { family := f.fixture, aux := rel t, cls := classify env none (some o) false false,
          detail := s!"only in {b.id}" }
      continue
    hit := hit.insert t
    n := n + 1
    if addr o == lean t then continue
    let sameIx := addr o == addr t
    let packaged := match addr t, lean t with
      | some x, some y => x != y && (projBlockSize ixon x).getD 0 > 1
      | _, _ => false
    let cls := classify env (some t) (some o) sameIx packaged
    -- UnivSplit: the split member keeps the block's universe list, and the
    -- users of its recursor follow (§4.7 (a))
    let cls := if cls == "UNEXPECTED" && f.fixture.getString! == "UnivSplit" then "(a)" else cls
    -- open audit defects of the fixture itself at this head (§4.7 (f) extended):
    -- a user constant named `below` taken for an auxiliary (WB-B1, FieldBelow;
    -- fixed by A0), the Prop `below` over a reducible alias (WB RecAlias)
    let cls := if cls != "UNEXPECTED" then cls else match f.fixture.getString! with
      | "FieldBelow" => "(f) WB-B1"
      | "RecAlias" => "(f) WB-RecAlias"
      | _ => cls
    let k (x : Option Address) : String := (x.map (kindOf ixon)).getD "-"
    rows := rows.push
      { family := f.fixture, aux := rel t, cls,
        detail := s!"ix({b.id}) {k (addr o)} {(addr o).map toString |>.getD "-" |>.take 12}, \
lean({a.id}) {k (lean t)} {(lean t).map toString |>.getD "-" |>.take 12}, \
ix({a.id}) {k (addr t)}{if sameIx then " (= ix(" ++ b.id ++ "))" else ""}" }
  for (t, _) in ca do
    if !hit.contains t then
      rows := rows.push
        { family := f.fixture, aux := rel t, cls := classify env (some t) none false false,
          detail := s!"only in {a.id}" }
  return (n, rows)

/-- The oracle families: every block and library twin family, and
    `UnivSplit` (§4.7 (a)). -/
def oracleFamilies : List Family :=
  (allFamilies.filter (·.kind != .clique)) ++
  [{ fixture := `Tests.Ix.Compile.Twins.Repro.UnivSplit, kind := .block
     pres := [{ id := "twin", ns := `Tests.Ix.Compile.Twins.Repro.Twin.Tw.UnivSplit },
              { id := "orig", ns := `Tests.Ix.Compile.Twins.Repro.Orig.UnivSplit }] }]

def run : IO UInt32 := do
  let env ← get_env!
  let families := oracleFamilies
  let (seeds, closure) := familyClosure env families
  IO.println s!"[aux-oracle] {families.length} families, {seeds.size} fixture constants, \
{closure.length} in the closure"
  let out ← leanCompile env closure
  let mut failures ← refusalCheck "aux-oracle" (closure.foldl (init := {}) fun s (x, _) => s.insert x)
    (out.cenv.ungrounded.toList.map fun (x, e) => (x.pretty, e))
  let mut total := 0
  let mut byClass : Std.HashMap String Nat := {}
  for f in families do
    let (n, rows) ← oracleFamily env out.env f
    total := total + n
    -- the canonical presentation's recursors as Lean made them
    let some a := f.pres.head? | continue
    -- the oracle presupposes that `T` is canonical: in every Lean block of
    -- `T`, Ix keeps the members in Lean's order (`iPrj` indices increase)
    let idx (x : Name) : Option Nat :=
      (out.env.getAddr? (Ix.Name.fromLeanName x)).bind (iPrjIdx out.env ·)
    let notCanon := (presConsts env a).filterMap fun (_, ci) => match ci with
      | .inductInfo v =>
        let is := v.all.map idx
        if v.all.head? == some ci.name && is.all Option.isSome &&
            !(is.zip is.tail).all (fun (x, y) => x.getD 0 ≤ y.getD 0)
        then some (v.all.map (·.replacePrefix a.ns .anonymous), is.map (·.getD 0)) else none
      | _ => none
    IO.println s!"[aux-oracle] {f.fixture.getString!}: {n} compared, {rows.size} exceptions\
{if notCanon.isEmpty then s!"; {a.id} canonical" else s!"; {a.id} NOT canonical: {notCanon.toList}"}"
    failures := failures + notCanon.size
    for r in rows do
      byClass := byClass.insert r.cls ((byClass.getD r.cls 0) + 1)
      IO.println s!"[aux-oracle]   {r.cls} {r.aux}: {r.detail}"
      if r.cls == "UNEXPECTED" then failures := failures + 1
  IO.println s!"[aux-oracle] {total} auxiliaries compared; exceptions by class: \
{byClass.toList.map fun (c, k) => s!"{c} {k}"}"
  IO.println s!"[aux-oracle] {if failures == 0 then "PASS" else s!"FAIL ({failures})"}"
  return if failures == 0 then 0 else 1

end Tests.Ix.Compile.Oracle
