// Copyright (c) 2026 Argument Computer Corporation.
// SPDX-License-Identifier: MIT OR Apache-2.0

use multi_stark::p3_field::PrimeCharacteristicRing;
use rustc_hash::FxHashMap;

use crate::{
  G,
  bytecode::{CallComponent, Ctrl, Op, Toplevel},
};

/// Ranks and positive call-order gaps are below 2^48. Their sum is below
/// 2^49, well below the Goldilocks modulus, so an AIR equality cannot wrap.
pub(crate) const RANK_BYTES: usize = 6;
pub(crate) const RANK_BOUND: u64 = 1 << (8 * RANK_BYTES);
pub(crate) const RANK_LOOKUPS: usize = RANK_BYTES / 2;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum CallRank {
  Zero,
  Bound,
  Ordered,
}

pub(crate) fn row_uses_rank(
  components: &[CallComponent],
  function: usize,
) -> bool {
  components.is_empty() || components[function].ranked
}

/// Used only after the component certificate has been checked. A boundary
/// call still binds a ranked callee's return, without imposing a rank gap.
pub(crate) fn call_rank(
  components: &[CallComponent],
  parent: usize,
  child: usize,
) -> CallRank {
  if components.is_empty() {
    CallRank::Ordered
  } else if !components[child].ranked {
    CallRank::Zero
  } else if components[parent].order == components[child].order {
    CallRank::Ordered
  } else {
    CallRank::Bound
  }
}

impl Toplevel {
  /// Check the certificate from the actual constrained bytecode edges,
  /// including branches, defaults and shared continuations. Every cycle
  /// must stay within one component. Internal edges retain ranks or are
  /// self-edges with an independently checked unit-counter certificate.
  pub fn validate_call_components(&self) -> Result<(), &'static str> {
    if self.call_components.is_empty() {
      return Ok(());
    }
    if self.call_components.len() != self.functions.len() {
      return Err("call component count differs from function count");
    }
    if self
      .call_components
      .iter()
      .any(|component| component.order >= self.functions.len())
    {
      return Err("call component order exceeds function count");
    }
    for (index, function) in self.functions.iter().enumerate() {
      if !function.constrained {
        continue;
      }
      let parent = self.call_components[index];
      let mut blocks = vec![&function.body];
      let mut counter_valid = None;
      while let Some(block) = blocks.pop() {
        for op in &block.ops {
          if let Op::Call(child, _, _, false) = op {
            let child_index = *child;
            let Some(child) = self.call_components.get(child_index) else {
              return Err("call component refers to a missing function");
            };
            let counter_edge = index == child_index
              && !parent.ranked
              && !child.ranked
              && *counter_valid.get_or_insert_with(|| {
                crate::unit_counter::has_unit_counter(index, function)
              });
            if !(parent.order < child.order
              || (parent.order == child.order && parent.ranked && child.ranked)
              || counter_edge)
            {
              return Err("call violates the static component order");
            }
          }
        }
        match &block.ctrl {
          Ctrl::Return(..) | Ctrl::Yield(..) => {},
          Ctrl::Match(_, branches, fallback) => {
            blocks.extend(branches.values());
            blocks.extend(fallback.as_deref());
          },
          Ctrl::MatchContinue(_, branches, fallback, _, _, _, continuation) => {
            blocks.extend(branches.values());
            blocks.extend(fallback.as_deref());
            blocks.push(continuation);
          },
        }
      }
    }
    Ok(())
  }
}

/// Extra byte-table queries generated by call-order witnesses. Each worker
/// accumulates locally; the prover merges these before building Bytes2.
pub(crate) type RankRanges = FxHashMap<[u8; 2], G>;

pub(crate) fn merge_ranges(
  mut left: RankRanges,
  right: RankRanges,
) -> RankRanges {
  for (pair, count) in right {
    *left.entry(pair).or_insert(G::ZERO) += count;
  }
  left
}
