// Copyright (c) 2026 Argument Computer Corporation.
// SPDX-License-Identifier: MIT OR Apache-2.0

use multi_stark::p3_field::PrimeCharacteristicRing;
use rustc_hash::FxHashMap;

use crate::G;

/// Ranks and positive call-order gaps are below 2^48. Their sum is below
/// 2^49, well below the Goldilocks modulus, so an AIR equality cannot wrap.
pub(crate) const RANK_BYTES: usize = 6;
pub(crate) const RANK_BOUND: u64 = 1 << (8 * RANK_BYTES);
pub(crate) const RANK_LOOKUPS: usize = RANK_BYTES / 2;

/// Extra byte-table queries generated by call-order witnesses. Each worker
/// accumulates locally; the prover merges these before building Bytes2.
pub(crate) type RankRanges = FxHashMap<[u8; 2], G>;

pub(crate) fn merge_ranges(
  mut left: RankRanges,
  right: RankRanges,
) -> RankRanges {
  for (pair, count) in right {
    *left.entry(pair).or_insert(G::ZERO) += count;
  }
  left
}
