use multi_stark::p3_field::{PrimeCharacteristicRing, PrimeField64};
use rustc_hash::FxHashMap;
use std::collections::hash_map::Entry;

use crate::{
  FxIndexMap, G,
  bytecode::{Block, Ctrl, FunIdx, Function, Op, Toplevel},
  gadgets::{
    AiurGadget,
    bytes1::{Bytes1, Bytes1Op, Bytes1Queries},
    bytes2::{Bytes2, Bytes2Op, Bytes2Queries},
  },
  querymap::QueryMap,
};

pub struct QueryRecord {
  pub function_queries: Vec<QueryMap>,
  pub memory_queries: FxIndexMap<usize, QueryMap>,
  pub bytes1_queries: Bytes1Queries,
  pub bytes2_queries: Bytes2Queries,
}

impl QueryRecord {
  pub fn new(toplevel: &Toplevel) -> Self {
    let function_queries = toplevel
      .functions
      .iter()
      .map(|f| QueryMap::new(f.layout.input_size))
      .collect();
    let memory_queries = toplevel
      .memory_sizes
      .iter()
      .map(|width| (*width, QueryMap::new(*width)))
      .collect();
    let bytes1_queries = Bytes1Queries::new();
    let bytes2_queries = Bytes2Queries::new();
    Self { function_queries, memory_queries, bytes1_queries, bytes2_queries }
  }
}

pub struct IOKeyInfo {
  pub idx: usize,
  pub len: usize,
}

pub struct IOBuffer {
  /// Per-channel data arenas. `idx` slots into `data[&channel]`.
  pub data: FxHashMap<G, Vec<G>>,
  /// Channel-keyed info map; same `key` on different channels resolves
  /// to distinct `IOKeyInfo`.
  pub map: FxHashMap<(G, Vec<G>), IOKeyInfo>,
}

impl IOBuffer {
  #[inline]
  pub fn get_info(
    &self,
    channel: G,
    key: &[G],
  ) -> Result<&IOKeyInfo, ExecError> {
    self.map.get(&(channel, key.to_vec())).ok_or(ExecError::InvalidIOKey)
  }
  fn set_info(
    &mut self,
    channel: G,
    key: Vec<G>,
    idx: usize,
    len: usize,
  ) -> Result<(), ExecError> {
    let Entry::Vacant(e) = self.map.entry((channel, key)) else {
      return Err(ExecError::IOMappingAlreadySet);
    };
    e.insert(IOKeyInfo { idx, len });
    Ok(())
  }
  #[inline]
  pub fn read(
    &self,
    channel: G,
    idx: usize,
    len: usize,
  ) -> Result<&[G], ExecError> {
    let empty: &[G] = &[];
    let arena = self.data.get(&channel).map_or(empty, |v| v.as_slice());
    arena
      .get(idx..idx.saturating_add(len))
      .ok_or(ExecError::IOReadOutOfBounds { idx, len })
  }
  fn write(&mut self, channel: G, data: impl Iterator<Item = G>) {
    self.data.entry(channel).or_default().extend(data)
  }
}

/// Errors raised by Aiur bytecode execution. Mirrors the panic/assert sites
/// in `Function::execute` so callers (tests, kernel-arena runner) can
/// distinguish recoverable rejections (`AssertEq`, `MatchNoCase`) from
/// genuine bytecode bugs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExecError {
  NotEntryFunction(FunIdx),
  InvalidMemorySize(usize),
  UnboundPointer {
    ptr: u64,
    size: usize,
  },
  PointerTooLarge(u64),
  IndexTooLarge(u64),
  U32OutOfRange(u64),
  U8RangeCheckFailed(u64),
  UnconstrainedBigUintDivModFailed(String),
  AssertEqLengthMismatch {
    lhs: usize,
    rhs: usize,
  },
  AssertEqMismatch {
    lhs: u64,
    rhs: u64,
  },
  MatchNoCase(u64),
  NoContinuation,
  StackNotEmpty,
  InvalidIOKey,
  IOMappingAlreadySet,
  IOReadOutOfBounds {
    idx: usize,
    len: usize,
  },
  /// Dispatched a `fun_idx` that the codegen'd kernel doesn't know.
  /// Generated by `execute_generated` in `crate::ix::aiur_ixvm`.
  InvalidFunIdx(usize),
}

impl std::fmt::Display for ExecError {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    match self {
      Self::NotEntryFunction(idx) => {
        write!(f, "cannot execute non-entry function {idx}")
      },
      Self::InvalidMemorySize(s) => write!(f, "invalid memory size {s}"),
      Self::UnboundPointer { ptr, size } => {
        write!(f, "unbound pointer {ptr} for memory size {size}")
      },
      Self::PointerTooLarge(p) => write!(f, "pointer {p} too large for usize"),
      Self::IndexTooLarge(i) => write!(f, "index {i} too large for usize"),
      Self::U32OutOfRange(v) => write!(f, "value {v} out of u32 range"),
      Self::U8RangeCheckFailed(v) => {
        write!(f, "value {v} out of u8 range [0, 256)")
      },
      Self::UnconstrainedBigUintDivModFailed(msg) => {
        write!(f, "unconstrained_big_uint_div_mod failed: {msg}")
      },
      Self::AssertEqLengthMismatch { lhs, rhs } => {
        write!(f, "assert_eq length mismatch: lhs={lhs}, rhs={rhs}")
      },
      Self::AssertEqMismatch { lhs, rhs } => {
        write!(f, "assert_eq mismatch: {lhs} != {rhs}")
      },
      Self::MatchNoCase(v) => write!(f, "no match case for value {v}"),
      Self::NoContinuation => write!(f, "yield without continuation"),
      Self::StackNotEmpty => {
        write!(f, "exec entries stack not empty at return")
      },
      Self::InvalidIOKey => write!(f, "invalid IO key"),
      Self::IOMappingAlreadySet => write!(f, "IO mapping already set for key"),
      Self::IOReadOutOfBounds { idx, len } => {
        write!(f, "IO read out of bounds: idx={idx}, len={len}")
      },
      Self::InvalidFunIdx(idx) => write!(f, "invalid fun_idx {idx}"),
    }
  }
}

impl std::error::Error for ExecError {}

/// Gated by `IX_AIUR_QUERY_STATS=1`: dump per-function query-map sizes
/// during/after execution so RAM blowups can be attributed to specific
/// Aiur functions (indices resolve to names via the Lean
/// `CompiledToplevel`). Heaviest maps first, by retained G elements.
static QUERY_STATS: std::sync::LazyLock<bool> =
  std::sync::LazyLock::new(|| {
    std::env::var_os("IX_AIUR_QUERY_STATS").is_some()
  });

fn dump_query_stats(record: &QueryRecord, tag: &str) {
  let mut rows: Vec<(usize, usize, usize)> = record
    .function_queries
    .iter()
    .enumerate()
    .map(|(i, m)| (i, m.len(), m.retained_elems()))
    .filter(|(_, n, _)| *n > 0)
    .collect();
  rows.sort_by(|a, b| b.2.cmp(&a.2));
  let total_entries: usize = rows.iter().map(|r| r.1).sum();
  let total_elems: usize = rows.iter().map(|r| r.2).sum();
  eprintln!(
    "[aiur-stats {tag}] function_queries: {total_entries} entries, \
     {total_elems} G-elems; top maps:"
  );
  for (i, n, e) in rows.iter().take(30) {
    eprintln!("  fn{i:<4} entries={n:<12} g_elems={e}");
  }
  let mem: Vec<String> = record
    .memory_queries
    .iter()
    .map(|(w, m)| format!("w{w}={}", m.len()))
    .collect();
  eprintln!("[aiur-stats {tag}] memory entries: {}", mem.join(" "));
}

impl Toplevel {
  pub fn execute(
    &self,
    fun_idx: FunIdx,
    args: Vec<G>,
    io_buffer: &mut IOBuffer,
  ) -> Result<(QueryRecord, Vec<G>), ExecError> {
    if !self.functions[fun_idx].entry {
      return Err(ExecError::NotEntryFunction(fun_idx));
    }
    let mut record = QueryRecord::new(self);
    let function = &self.functions[fun_idx];
    let output =
      function.execute(fun_idx, args, self, &mut record, io_buffer)?;
    if *QUERY_STATS {
      dump_query_stats(&record, "final");
    }
    Ok((record, output))
  }
}

enum ExecEntry<'a> {
  Op(&'a Op),
  Ctrl(&'a Ctrl),
}

struct CallerState {
  fun_idx: FunIdx,
  map: Vec<G>,
  unconstrained: bool,
  continuation_depth: usize,
}

struct ContinuationState<'a> {
  block: &'a Block,
  map_len: usize,
}

impl Function {
  fn execute(
    &self,
    mut fun_idx: FunIdx,
    mut map: Vec<G>,
    toplevel: &Toplevel,
    record: &mut QueryRecord,
    io_buffer: &mut IOBuffer,
  ) -> Result<Vec<G>, ExecError> {
    let mut exec_entries_stack = vec![];
    let mut callers_states_stack = vec![];
    let mut continuation_stack: Vec<ContinuationState<'_>> = vec![];
    macro_rules! push_block_exec_entries {
      ($block:expr) => {
        exec_entries_stack.push(ExecEntry::Ctrl(&$block.ctrl));
        exec_entries_stack.extend($block.ops.iter().rev().map(ExecEntry::Op));
      };
    }
    push_block_exec_entries!(&self.body);
    let mut unconstrained = false;
    let mut stats_ops: u64 = 0;
    while let Some(exec_entry) = exec_entries_stack.pop() {
      if *QUERY_STATS {
        stats_ops += 1;
        if stats_ops.is_multiple_of(1 << 31) {
          dump_query_stats(record, &format!("ops={stats_ops}"));
        }
      }
      match exec_entry {
        ExecEntry::Op(Op::Const(c)) => map.push(*c),
        ExecEntry::Op(Op::Add(a, b)) => {
          let a = map[*a];
          let b = map[*b];
          map.push(a + b);
        },
        ExecEntry::Op(Op::Sub(a, b)) => {
          let a = map[*a];
          let b = map[*b];
          map.push(a - b);
        },
        ExecEntry::Op(Op::Mul(a, b)) => {
          let a = map[*a];
          let b = map[*b];
          map.push(a * b);
        },
        ExecEntry::Op(Op::EqZero(a)) => {
          let a = map[*a];
          map.push(G::from_bool(a == G::ZERO));
        },
        ExecEntry::Op(Op::Call(callee_idx, args, _, op_unconstrained)) => {
          let args: Vec<G> = args.iter().map(|i| map[*i]).collect();
          if let Some(result) =
            record.function_queries[*callee_idx].get_mut(&args)
          {
            if !unconstrained && !op_unconstrained {
              *result.multiplicity += G::ONE;
            }
            map.extend_from_slice(result.output);
          } else {
            let saved_map = std::mem::replace(&mut map, args);
            callers_states_stack.push(CallerState {
              fun_idx,
              map: saved_map,
              unconstrained,
              continuation_depth: continuation_stack.len(),
            });
            fun_idx = *callee_idx;
            unconstrained = unconstrained || *op_unconstrained;
            push_block_exec_entries!(&toplevel.functions[fun_idx].body);
          }
        },
        ExecEntry::Op(Op::Store(values)) => {
          let values = values.iter().map(|v| map[*v]).collect::<Vec<_>>();
          let size = values.len();
          let memory_queries = record
            .memory_queries
            .get_mut(&size)
            .ok_or(ExecError::InvalidMemorySize(size))?;
          if let Some(result) = memory_queries.get_mut(&values) {
            if !unconstrained {
              *result.multiplicity += G::ONE;
            }
            map.extend_from_slice(result.output);
          } else {
            let ptr = G::from_usize(memory_queries.len());
            memory_queries.insert(
              &values,
              &[ptr],
              G::from_bool(!unconstrained),
            );
            map.push(ptr);
          }
        },
        ExecEntry::Op(Op::Load(size, ptr)) => {
          let memory_queries = record
            .memory_queries
            .get_mut(size)
            .ok_or(ExecError::InvalidMemorySize(*size))?;
          let ptr = &map[*ptr];
          let ptr_u64 = ptr.as_canonical_u64();
          let ptr_usize = usize::try_from(ptr_u64)
            .ok()
            .ok_or(ExecError::PointerTooLarge(ptr_u64))?;
          let (args, multiplicity) = memory_queries
            .get_index_mut(ptr_usize)
            .ok_or(ExecError::UnboundPointer { ptr: ptr_u64, size: *size })?;
          if !unconstrained {
            *multiplicity += G::ONE;
          }
          map.extend_from_slice(args);
        },
        ExecEntry::Op(Op::AssertEq(xs, ys)) => {
          if xs.len() != ys.len() {
            return Err(ExecError::AssertEqLengthMismatch {
              lhs: xs.len(),
              rhs: ys.len(),
            });
          }
          for (x, y) in xs.iter().zip(ys) {
            let lhs = map[*x];
            let rhs = map[*y];
            if lhs != rhs {
              return Err(ExecError::AssertEqMismatch {
                lhs: lhs.as_canonical_u64(),
                rhs: rhs.as_canonical_u64(),
              });
            }
          }
        },
        ExecEntry::Op(Op::IOGetInfo(channel, key)) => {
          let channel = map[*channel];
          let key = key.iter().map(|v| map[*v]).collect::<Vec<_>>();
          let IOKeyInfo { idx, len } = io_buffer.get_info(channel, &key)?;
          map.push(G::from_usize(*idx));
          map.push(G::from_usize(*len));
        },
        ExecEntry::Op(Op::IOSetInfo(channel, key, idx, len)) => {
          let channel = map[*channel];
          let key = key.iter().map(|v| map[*v]).collect::<Vec<_>>();
          let get = |x: &usize| {
            let v = map[*x].as_canonical_u64();
            usize::try_from(v).ok().ok_or(ExecError::IndexTooLarge(v))
          };
          io_buffer.set_info(channel, key, get(idx)?, get(len)?)?;
        },
        ExecEntry::Op(Op::IORead(channel, idx, len)) => {
          let channel = map[*channel];
          let idx_val = map[*idx].as_canonical_u64();
          let idx = usize::try_from(idx_val)
            .ok()
            .ok_or(ExecError::IndexTooLarge(idx_val))?;
          let data = io_buffer.read(channel, idx, *len)?.to_vec();
          map.extend(data);
        },
        ExecEntry::Op(Op::IOWrite(channel, data)) => {
          let channel = map[*channel];
          io_buffer.write(channel, data.iter().map(|v| map[*v]))
        },
        ExecEntry::Op(Op::U8BitDecomposition(byte)) => {
          if unconstrained {
            map.extend(Bytes1::bit_decompose(&map[*byte]));
          } else {
            bytes1_execute(
              *byte,
              &Bytes1Op::BitDecomposition,
              &mut map,
              record,
            );
          }
        },
        ExecEntry::Op(Op::U8ShiftLeft(byte)) => {
          if unconstrained {
            map.push(Bytes1::shift_left(&map[*byte]));
          } else {
            bytes1_execute(*byte, &Bytes1Op::ShiftLeft, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8ShiftRight(byte)) => {
          if unconstrained {
            map.push(Bytes1::shift_right(&map[*byte]));
          } else {
            bytes1_execute(*byte, &Bytes1Op::ShiftRight, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8Xor(i, j)) => {
          if unconstrained {
            map.push(Bytes2::xor(&map[*i], &map[*j]));
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::Xor, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8Add(i, j)) => {
          // The add gadget yields only the low byte; the carry is derived
          // and pushed separately so the op still produces `(low, carry)`.
          let (_r, o) = Bytes2::add(&map[*i], &map[*j]);
          if unconstrained {
            map.push(Bytes2::add(&map[*i], &map[*j]).0);
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::Add, &mut map, record);
          }
          map.push(o);
        },
        ExecEntry::Op(Op::U8Mul(i, j)) => {
          if unconstrained {
            let (lo, hi) = Bytes2::mul(&map[*i], &map[*j]);
            map.extend([lo, hi]);
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::Mul, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8Sub(i, j)) => {
          // The sub gadget yields only the low byte; the borrow is derived
          // and pushed separately so the op still produces `(low, borrow)`.
          let (_r, u) = Bytes2::sub(&map[*i], &map[*j]);
          if unconstrained {
            map.push(Bytes2::sub(&map[*i], &map[*j]).0);
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::Sub, &mut map, record);
          }
          map.push(u);
        },
        ExecEntry::Op(Op::U8And(i, j)) => {
          if unconstrained {
            map.push(Bytes2::and(&map[*i], &map[*j]));
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::And, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8Or(i, j)) => {
          if unconstrained {
            map.push(Bytes2::or(&map[*i], &map[*j]));
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::Or, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8LessThan(i, j)) => {
          if unconstrained {
            map.push(Bytes2::less_than(&map[*i], &map[*j]));
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::LessThan, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U32LessThan(x_idx, y_idx)) => {
          let a_val = map[*x_idx].as_canonical_u64();
          let b_val = map[*y_idx].as_canonical_u64();
          let a_u32 =
            u32::try_from(a_val).ok().ok_or(ExecError::U32OutOfRange(a_val))?;
          let b_u32 =
            u32::try_from(b_val).ok().ok_or(ExecError::U32OutOfRange(b_val))?;
          let result = G::from_bool(a_u32 < b_u32);
          map.push(result);
          if !unconstrained {
            let x_bytes = a_u32.to_le_bytes();
            let z_bytes = b_u32.to_le_bytes();
            let c_u32 = b_u32.wrapping_sub(a_u32).wrapping_sub(1);
            let y_bytes = c_u32.to_le_bytes();
            // Bump range-check queries for byte pairs
            for (i, j) in [
              (x_bytes[0], x_bytes[1]),
              (x_bytes[2], x_bytes[3]),
              (y_bytes[0], y_bytes[1]),
              (y_bytes[2], y_bytes[3]),
              (z_bytes[0], z_bytes[1]),
              (z_bytes[2], z_bytes[3]),
            ] {
              record
                .bytes2_queries
                .bump_range_check(&G::from_u8(i), &G::from_u8(j));
            }
          }
        },
        ExecEntry::Op(Op::U8ChainRotr7(i, j)) => {
          if unconstrained {
            let (o0, o1, o2) = Bytes2::chain_rotr7(&map[*i], &map[*j]);
            map.extend([o0, o1, o2]);
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::ChainRotr7, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8ChainRotr4(i, j)) => {
          if unconstrained {
            let (o0, o1, o2) = Bytes2::chain_rotr4(&map[*i], &map[*j]);
            map.extend([o0, o1, o2]);
          } else {
            bytes2_execute(*i, *j, &Bytes2Op::ChainRotr4, &mut map, record);
          }
        },
        ExecEntry::Op(Op::U8RangeCheck(i, j)) => {
          // No `map.push`: the two `u8` outputs alias the inputs `i`, `j`.
          // Records a range-check query so the byte-chip lookup is satisfied.
          if !unconstrained {
            let (vi, vj) = (map[*i], map[*j]);
            let (bi, bj) = (vi.as_canonical_u64(), vj.as_canonical_u64());
            if bi >= 256 {
              return Err(ExecError::U8RangeCheckFailed(bi));
            }
            if bj >= 256 {
              return Err(ExecError::U8RangeCheckFailed(bj));
            }
            record.bytes2_queries.bump_range_check(&vi, &vj);
          }
        },
        ExecEntry::Op(Op::UnconstrainedBigUintDivMod(a_idx, b_idx)) => {
          // Unconstrained hint for klimbs-style LE byte division. Inputs are
          // pointers to `List<U64>` (in memory[10]) values storing `a` and
          // `b` as little-endian u64 limbs (each limb's 8 bytes are stored
          // tag-then-bytes within memory[10] per the standard Aiur enum
          // layout: `[tag, b0..b7, next_ptr]`). The op walks both lists,
          // computes `q = a / b` and `r = a % b` via `num_bigint::BigUint`,
          // and rebuilds the result lists in memory[10] with multiplicity 0
          // (unconstrained). Returns the two new head pointers. The caller
          // is responsible for verifying `q * b + r == a` and `r < b` in
          // constrained code.
          //
          // The `memory[10]` channel is chosen because the standard Aiur
          // layout for a tagged enum with a `(U64, &Self)` constructor is
          // `tag(1) + U64(8) + ptr(1) = 10` G values.
          let a_ptr = map[*a_idx];
          let b_ptr = map[*b_idx];
          let a_limbs = read_klimbs_u64(&record.memory_queries, a_ptr)
            .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
          let b_limbs = read_klimbs_u64(&record.memory_queries, b_ptr)
            .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
          let a_big = klimbs_u64_to_biguint(&a_limbs);
          let b_big = klimbs_u64_to_biguint(&b_limbs);
          let (q_big, r_big) = if b_big == num_bigint::BigUint::ZERO {
            (num_bigint::BigUint::ZERO, a_big.clone())
          } else {
            (&a_big / &b_big, &a_big % &b_big)
          };
          let q_limbs = biguint_to_klimbs_u64(&q_big);
          let r_limbs = biguint_to_klimbs_u64(&r_big);
          let q_ptr = build_klimbs_u64(&mut record.memory_queries, &q_limbs)
            .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
          let r_ptr = build_klimbs_u64(&mut record.memory_queries, &r_limbs)
            .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
          map.push(q_ptr);
          map.push(r_ptr);
        },
        ExecEntry::Op(Op::Debug(label, idxs)) => match idxs {
          None => println!("{label}"),
          Some(idxs) => {
            let parts: Vec<_> =
              idxs.iter().map(|idx| map[*idx].to_string()).collect();
            let parts_joined = parts.join(", ");
            println!("{label}: {parts_joined}");
          },
        },
        ExecEntry::Ctrl(Ctrl::Match(val_idx, cases, default)) => {
          let val = &map[*val_idx];
          if let Some(block) = cases.get(val) {
            push_block_exec_entries!(block);
          } else {
            let default = default
              .as_ref()
              .ok_or_else(|| ExecError::MatchNoCase(val.as_canonical_u64()))?;
            push_block_exec_entries!(default);
          }
        },
        ExecEntry::Ctrl(Ctrl::MatchContinue(
          val_idx,
          cases,
          default,
          _output_size,
          _shared_aux,
          _shared_lookups,
          continuation,
        )) => {
          continuation_stack.push(ContinuationState {
            block: continuation,
            map_len: map.len(),
          });
          let val = &map[*val_idx];
          if let Some(block) = cases.get(val) {
            push_block_exec_entries!(block);
          } else {
            let default = default
              .as_ref()
              .ok_or_else(|| ExecError::MatchNoCase(val.as_canonical_u64()))?;
            push_block_exec_entries!(default);
          }
        },
        ExecEntry::Ctrl(Ctrl::Yield(_, output)) => {
          let cont =
            continuation_stack.pop().ok_or(ExecError::NoContinuation)?;
          let yielded: Vec<G> = output.iter().map(|&v| map[v]).collect();
          map.truncate(cont.map_len);
          map.extend(yielded);
          push_block_exec_entries!(cont.block);
        },
        ExecEntry::Ctrl(Ctrl::Return(_, output)) => {
          // Register the query.
          let input_size = toplevel.functions[fun_idx].layout.input_size;
          let output = output.iter().map(|i| map[*i]).collect::<Vec<_>>();
          record.function_queries[fun_idx].insert(
            &map[..input_size],
            &output,
            G::from_bool(!unconstrained),
          );
          if let Some(CallerState {
            fun_idx: caller_idx,
            map: caller_map,
            unconstrained: caller_unconstrained,
            continuation_depth,
          }) = callers_states_stack.pop()
          {
            continuation_stack.truncate(continuation_depth);
            fun_idx = caller_idx;
            map = caller_map;
            map.extend(output);
            unconstrained = caller_unconstrained;
          } else {
            continuation_stack.clear();
            if !exec_entries_stack.is_empty() {
              return Err(ExecError::StackNotEmpty);
            }
            map = output;
            break;
          }
        },
      }
    }
    Ok(map)
  }
}

pub fn bytes1_execute(
  byte: usize,
  op: &Bytes1Op,
  map: &mut Vec<G>,
  record: &mut QueryRecord,
) {
  map.extend(Bytes1.execute(op, &[map[byte]], record));
}

pub fn bytes2_execute(
  i: usize,
  j: usize,
  op: &Bytes2Op,
  map: &mut Vec<G>,
  record: &mut QueryRecord,
) {
  map.extend(Bytes2.execute(op, &[map[i], map[j]], record));
}

// ============================================================================
// Per-op value-returning helpers for the codegen'd kernel.
//
// The interpreter routes byte ops through `bytes{1,2}_execute(idx, op,
// &mut Vec<G>, record)` which `extends` the Vec with the gadget's
// output. The codegen'd kernel doesn't keep a `Vec<G>` value stack
// (every Aiur ValIdx is a real Rust local), so the wrappers below let
// it consume gadget outputs as fixed-size arrays / tuples / single Gs
// without an allocating Vec<G> per op.
//
// Each helper bumps the same `bytes{1,2}_queries` channel as the
// interpreter's `Bytes{1,2}::execute` arm, so QueryRecord parity is
// preserved bit-for-bit.
// ============================================================================

#[inline]
pub fn bytes1_bit_decompose_value(byte: G, record: &mut QueryRecord) -> [G; 8] {
  record.bytes1_queries.bump_bit_decomposition(&byte);
  let byte_u64 = byte.as_canonical_u64();
  [
    G::from_bool(byte_u64 & 1 == 1),
    G::from_bool(byte_u64 >> 1 & 1 == 1),
    G::from_bool(byte_u64 >> 2 & 1 == 1),
    G::from_bool(byte_u64 >> 3 & 1 == 1),
    G::from_bool(byte_u64 >> 4 & 1 == 1),
    G::from_bool(byte_u64 >> 5 & 1 == 1),
    G::from_bool(byte_u64 >> 6 & 1 == 1),
    G::from_bool(byte_u64 >> 7 & 1 == 1),
  ]
}

/// IxVM kernel doesn't emit `Op::U8ShiftLeft` today; kept for codegen
/// of other toplevels that might.
#[inline]
#[allow(dead_code)]
pub fn bytes1_shift_left_value(byte: G, record: &mut QueryRecord) -> G {
  record.bytes1_queries.bump_shift_left(&byte);
  Bytes1::shift_left(&byte)
}

/// IxVM kernel doesn't emit `Op::U8ShiftRight` today; kept for
/// codegen of other toplevels.
#[inline]
#[allow(dead_code)]
pub fn bytes1_shift_right_value(byte: G, record: &mut QueryRecord) -> G {
  record.bytes1_queries.bump_shift_right(&byte);
  Bytes1::shift_right(&byte)
}

#[inline]
pub fn bytes2_xor_value(a: G, b: G, record: &mut QueryRecord) -> G {
  record.bytes2_queries.bump_xor(&a, &b);
  Bytes2::xor(&a, &b)
}

#[inline]
pub fn bytes2_and_value(a: G, b: G, record: &mut QueryRecord) -> G {
  record.bytes2_queries.bump_and(&a, &b);
  Bytes2::and(&a, &b)
}

#[inline]
pub fn bytes2_or_value(a: G, b: G, record: &mut QueryRecord) -> G {
  record.bytes2_queries.bump_or(&a, &b);
  Bytes2::or(&a, &b)
}

#[inline]
pub fn bytes2_less_than_value(a: G, b: G, record: &mut QueryRecord) -> G {
  record.bytes2_queries.bump_less_than(&a, &b);
  Bytes2::less_than(&a, &b)
}

/// IxVM kernel doesn't emit `Op::U8Mul` today; kept for codegen of
/// other toplevels.
#[inline]
#[allow(dead_code)]
pub fn bytes2_mul_value(a: G, b: G, record: &mut QueryRecord) -> (G, G) {
  record.bytes2_queries.bump_mul(&a, &b);
  Bytes2::mul(&a, &b)
}

#[inline]
pub fn bytes2_chain_rotr7_value(
  a: G,
  b: G,
  record: &mut QueryRecord,
) -> (G, G, G) {
  record.bytes2_queries.bump_chain_rotr7(&a, &b);
  Bytes2::chain_rotr7(&a, &b)
}

#[inline]
pub fn bytes2_chain_rotr4_value(
  a: G,
  b: G,
  record: &mut QueryRecord,
) -> (G, G, G) {
  record.bytes2_queries.bump_chain_rotr4(&a, &b);
  Bytes2::chain_rotr4(&a, &b)
}

/// Bumps `bytes2_queries.add` and returns the full `(low, carry)`
/// pair. The constrained-mode gadget only LOOKUPS `low` from the
/// chip; carry is derived natively. The codegen path uses this
/// helper so the add gadget runs exactly once.
#[inline]
pub fn bytes2_add_value(a: G, b: G, record: &mut QueryRecord) -> (G, G) {
  record.bytes2_queries.bump_add(&a, &b);
  Bytes2::add(&a, &b)
}

#[inline]
pub fn bytes2_sub_value(a: G, b: G, record: &mut QueryRecord) -> (G, G) {
  record.bytes2_queries.bump_sub(&a, &b);
  Bytes2::sub(&a, &b)
}

/// Re-exports for the codegen'd kernel (`ix::aiur_ixvm`). The generated
/// code names these as `aiur::execute::*`; we re-export them `pub` here
/// so an external `ix` crate can see them. `CodegenBytes1Op` and
/// `CodegenBytes2Op` aren't re-exported here because the generated
/// kernel no longer references them (per-op value helpers above
/// replaced the byte-op enum dispatch).
pub use crate::gadgets::bytes1::Bytes1 as CodegenBytes1;
pub use crate::gadgets::bytes2::Bytes2 as CodegenBytes2;

/// Helper extracted for the codegen'd kernel: compute the unconstrained
/// BigUint div-mod and return `(q_ptr, r_ptr)`. Same side effects on
/// `record.memory_queries` as the inlined `Op::UnconstrainedBigUintDivMod`
/// arm in the interpreter.
pub fn unconstrained_big_uint_div_mod_helper(
  a_ptr: G,
  b_ptr: G,
  record: &mut QueryRecord,
) -> Result<(G, G), ExecError> {
  let a_limbs = read_klimbs_u64(&record.memory_queries, a_ptr)
    .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
  let b_limbs = read_klimbs_u64(&record.memory_queries, b_ptr)
    .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
  let a_big = klimbs_u64_to_biguint(&a_limbs);
  let b_big = klimbs_u64_to_biguint(&b_limbs);
  let (q_big, r_big) = if b_big == num_bigint::BigUint::ZERO {
    (num_bigint::BigUint::ZERO, a_big.clone())
  } else {
    (&a_big / &b_big, &a_big % &b_big)
  };
  let q_limbs = biguint_to_klimbs_u64(&q_big);
  let r_limbs = biguint_to_klimbs_u64(&r_big);
  let q_ptr = build_klimbs_u64(&mut record.memory_queries, &q_limbs)
    .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
  let r_ptr = build_klimbs_u64(&mut record.memory_queries, &r_limbs)
    .map_err(ExecError::UnconstrainedBigUintDivModFailed)?;
  Ok((q_ptr, r_ptr))
}

/// Walk a `List<U64>` chain from `head_ptr` in `memory[10]`, returning the
/// u64 limbs in head-first order. Each memory[10] entry is the standard Aiur
/// tagged-enum layout: `[tag, byte0..byte7, next_ptr]`. `tag == 0` = Nil
/// (terminator), `tag == 1` = Cons. Bytes are LE within the u64.
fn read_klimbs_u64(
  memory: &FxIndexMap<usize, QueryMap>,
  head_ptr: G,
) -> Result<Vec<u64>, String> {
  let queries = memory.get(&10).ok_or_else(|| {
    "memory[10] channel not registered (no List<U64> in program?)".to_string()
  })?;
  let mut limbs: Vec<u64> = Vec::new();
  let mut ptr = head_ptr;
  loop {
    let ptr_u64 = ptr.as_canonical_u64();
    let ptr_idx = usize::try_from(ptr_u64)
      .map_err(|_e| format!("ptr {ptr_u64} too large for usize"))?;
    let (key, _) = queries.get_index(ptr_idx).ok_or_else(|| {
      format!("unbound ptr {ptr_u64} in memory[10] (walking List<U64>)")
    })?;
    let tag = key[0].as_canonical_u64();
    // `enum ListNode { Cons, Nil }` in Ix/IxVM/Core.lean — Cons is the
    // first variant (tag 0), Nil the second (tag 1).
    if tag == 1 {
      return Ok(limbs);
    }
    if tag != 0 {
      return Err(format!(
        "List<U64> walk: unexpected tag {tag} (expected 0=Cons, 1=Nil)"
      ));
    }
    let mut limb_bytes = [0u8; 8];
    for k in 0..8 {
      let b = key[1 + k].as_canonical_u64();
      if b >= 256 {
        return Err(format!("limb byte {b} out of u8 range"));
      }
      limb_bytes[k] = u8::try_from(b).expect("range-checked above");
    }
    limbs.push(u64::from_le_bytes(limb_bytes));
    ptr = key[9];
  }
}

/// Treat `limbs` as a little-endian sequence of 64-bit limbs and convert to
/// a `BigUint`. Aiur's `klimbs_normalize` strips trailing zero limbs but a
/// non-normalized input still produces the correct value via `from_bytes_le`.
fn klimbs_u64_to_biguint(limbs: &[u64]) -> num_bigint::BigUint {
  let mut bytes: Vec<u8> = Vec::with_capacity(limbs.len() * 8);
  for limb in limbs {
    bytes.extend_from_slice(&limb.to_le_bytes());
  }
  num_bigint::BigUint::from_bytes_le(&bytes)
}

/// Convert a `BigUint` to LE-u64 limbs. The output is non-padded (trailing
/// limbs that would all be zero are omitted), matching `klimbs_normalize`'s
/// canonical form so the Aiur kernel's subsequent equality checks compare
/// equal forms without round-trip discrepancies.
fn biguint_to_klimbs_u64(n: &num_bigint::BigUint) -> Vec<u64> {
  if n == &num_bigint::BigUint::ZERO {
    return Vec::new();
  }
  let mut bytes = n.to_bytes_le();
  while !bytes.len().is_multiple_of(8) {
    bytes.push(0);
  }
  bytes
    .chunks_exact(8)
    .map(|c| {
      let mut a = [0u8; 8];
      a.copy_from_slice(c);
      u64::from_le_bytes(a)
    })
    .collect()
}

/// Build a `List<U64>` chain in `memory[10]` from `limbs` (head-first order)
/// and return the head pointer. Each entry is inserted with multiplicity 0
/// (unconstrained); subsequent constrained `Load`s by the kernel will bump
/// the multiplicity. Content-addressed via `QueryMap::get_mut`, so repeated
/// identical sub-tails share storage.
fn build_klimbs_u64(
  memory: &mut FxIndexMap<usize, QueryMap>,
  limbs: &[u64],
) -> Result<G, String> {
  let queries = memory.get_mut(&10).ok_or_else(|| {
    "memory[10] channel not registered (no List<U64> in program?)".to_string()
  })?;
  // Find or insert the Nil ptr (tag = 1, padded payload all zero).
  let nil_key: Vec<G> =
    std::iter::once(G::ONE).chain((0..9).map(|_| G::ZERO)).collect();
  let mut tail_ptr = if let Some(out) = queries.get_mut(&nil_key) {
    out.output[0]
  } else {
    let ptr = G::from_usize(queries.len());
    queries.insert(&nil_key, &[ptr], G::ZERO);
    ptr
  };
  // Walk limbs in REVERSE so each Cons points at the previously-built tail.
  for limb in limbs.iter().rev() {
    let bytes = limb.to_le_bytes();
    let mut key: Vec<G> = Vec::with_capacity(10);
    key.push(G::ZERO); // Cons tag (first variant of ListNode‹U64›)
    for b in &bytes {
      key.push(G::from_u8(*b));
    }
    key.push(tail_ptr);
    tail_ptr = if let Some(out) = queries.get_mut(&key) {
      out.output[0]
    } else {
      let ptr = G::from_usize(queries.len());
      queries.insert(&key, &[ptr], G::ZERO);
      ptr
    };
  }
  Ok(tail_ptr)
}
