//! Compilation of aux_gen-generated constants into Ixon blocks.
//!
//! This module handles two related tasks:
//!
//! 1. **`compile_aux_block`**: Takes a set of `MutConst` values (recursors,
//!    definitions, inductives) generated by aux_gen and compiles them into an
//!    Ixon mutual block with projections, reusing the same sort/compile/register
//!    pipeline as `compile_mutual` in the parent module.
//!
//! 2. **`generate_and_compile_aux_recursors`**: Orchestrates the full aux_gen
//!    pipeline: generates canonical patches (recursors, `.below`, `.brecOn`),
//!    then compiles each phase's output via `compile_aux_block`.

use std::sync::Arc;

use rustc_hash::FxHashMap;

use lean_ffi::nat::Nat;

use crate::ix::address::Address;
use crate::ix::compile::aux_gen::below::BelowIndc;
use crate::ix::compile::aux_gen::brecon::BRecOnDef;
use crate::ix::compile::aux_gen::recursor;
use crate::ix::compile::aux_gen::{self, PatchedConstant};
use crate::ix::compile::{
  BlockCache, CompileState, compile_definition, compile_inductive,
  compile_mutual_block, compile_recursor, sort_consts,
};
use crate::ix::env::{
  ConstantInfo as LeanConstantInfo, ConstantVal, ConstructorVal,
  DefinitionSafety, Env as LeanEnv, Name,
};
use crate::ix::ixon::{
  CompileError,
  constant::{
    Constant, ConstantInfo, ConstructorProj, DefKind, DefinitionProj,
    InductiveProj, MutConst as IxonMutConst, RecursorProj,
  },
  env::Named,
  metadata::ConstantMeta,
  univ::Univ,
};
use crate::ix::mutual::{Def, Ind, MutConst};

// ===========================================================================
// compile_aux_block
// ===========================================================================

/// Compile a set of aux_gen-produced constants into an Ixon mutual block.
///
/// This is the aux_gen analogue of `compile_mutual` in the parent module:
/// it sorts constants into equivalence classes, compiles each representative,
/// creates the mutual block, and registers projections + names.
///
/// Compiled constants are registered in `stt.aux_name_to_addr` (not
/// `stt.name_to_addr`) so they don't interfere with the scheduler's
/// dependency tracking. The scheduler's promotion path in `env.rs` moves
/// them to `name_to_addr` when the block is processed.
pub(crate) fn compile_aux_block(
  aux_consts: &[MutConst],
  lean_env: &Arc<LeanEnv>,
  stt: &CompileState,
) -> Result<(), CompileError> {
  if aux_consts.is_empty() {
    return Ok(());
  }
  let mut cache = BlockCache::default();

  // Sort into equivalence classes (same algorithm as compile_mutual).
  let refs: Vec<&MutConst> = aux_consts.iter().collect();
  let sorted_classes = sort_consts(&refs, &mut cache, stt)?;
  let mut_ctx = MutConst::ctx(&sorted_classes);

  // Compile each representative per class.
  let mut ixon_mutuals = Vec::new();
  let mut all_metas: FxHashMap<Name, ConstantMeta> = FxHashMap::default();

  for class in &sorted_classes {
    let mut rep_pushed = false;
    for cnst in class {
      match cnst {
        MutConst::Recr(rec) => {
          let (data, meta) = compile_recursor(rec, &mut_ctx, &mut cache, stt)?;
          if !rep_pushed {
            ixon_mutuals.push(IxonMutConst::Recr(data));
            rep_pushed = true;
          }
          all_metas.insert(rec.cnst.name.clone(), meta);
        },
        MutConst::Defn(def) => {
          let (data, meta) =
            compile_definition(def, &mut_ctx, &mut cache, stt)?;
          if !rep_pushed {
            ixon_mutuals.push(IxonMutConst::Defn(data));
            rep_pushed = true;
          }
          all_metas.insert(def.name.clone(), meta);
        },
        MutConst::Indc(ind) => {
          let (data, meta, ctor_metas) =
            compile_inductive(ind, &mut_ctx, &mut cache, stt)?;
          if !rep_pushed {
            ixon_mutuals.push(IxonMutConst::Indc(data));
            rep_pushed = true;
          }
          all_metas.insert(ind.ind.cnst.name.clone(), meta);
          for (ctor, cm) in ind.ctors.iter().zip(ctor_metas) {
            all_metas.insert(ctor.cnst.name.clone(), cm);
          }
        },
      }
    }
  }

  // Compile the mutual block.
  let name_refs = cache.build_name_refs();
  let block_refs: Vec<Address> = cache.refs.iter().cloned().collect();
  let block_univs: Vec<Arc<Univ>> = cache.univs.iter().cloned().collect();
  let name_str = aux_consts[0].name().pretty();
  let compiled = compile_mutual_block(
    ixon_mutuals,
    block_refs,
    block_univs,
    Some(&name_str),
  );
  let block_addr = compiled.addr.clone();
  stt.env.store_const(block_addr.clone(), compiled.constant);

  // Register projections for each constant, same pattern as compile_mutual.
  // Collect names for batched pending-queue push (one lock acquisition).
  let mut pending_names: Vec<Name> = Vec::new();

  let singleton = sorted_classes.len() == 1
    && !aux_consts.iter().any(|c| matches!(c, MutConst::Indc(_)));

  if singleton {
    // Single non-inductive class: register directly with block_addr.
    for cnst in &sorted_classes[0] {
      let n = cnst.name();
      let meta = all_metas.remove(&n).unwrap_or_default();
      stt.env.register_name(
        n.clone(),
        Named::new(block_addr.clone(), meta).with_name_refs(name_refs.clone()),
      );
      stt.aux_name_to_addr.insert(n.clone(), block_addr.clone());
      stt.aux_gen_extra_names.insert(n.clone());
      pending_names.push(n);
    }
  } else {
    // Multi-class or inductive: create projections per member.
    for (idx, class) in sorted_classes.iter().enumerate() {
      let idx = idx as u64;
      for cnst in class {
        let n = cnst.name();
        let meta = all_metas.get(&n).cloned().unwrap_or_default();

        match cnst {
          MutConst::Indc(ind) => {
            // Inductive projection
            let indc_proj = Constant::new(ConstantInfo::IPrj(InductiveProj {
              idx,
              block: block_addr.clone(),
            }));
            let proj_addr = content_address(&indc_proj);
            stt.env.store_const(proj_addr.clone(), indc_proj);
            stt.env.register_name(
              n.clone(),
              Named::new(proj_addr.clone(), meta)
                .with_name_refs(name_refs.clone()),
            );
            stt.aux_name_to_addr.insert(n.clone(), proj_addr.clone());
            stt.aux_gen_extra_names.insert(n.clone());
            pending_names.push(n);

            // Constructor projections
            for (cidx, ctor) in ind.ctors.iter().enumerate() {
              let ctor_meta =
                all_metas.get(&ctor.cnst.name).cloned().unwrap_or_default();
              let ctor_proj =
                Constant::new(ConstantInfo::CPrj(ConstructorProj {
                  idx,
                  cidx: cidx as u64,
                  block: block_addr.clone(),
                }));
              let ctor_addr = content_address(&ctor_proj);
              stt.env.store_const(ctor_addr.clone(), ctor_proj);
              stt.env.register_name(
                ctor.cnst.name.clone(),
                Named::new(ctor_addr.clone(), ctor_meta)
                  .with_name_refs(name_refs.clone()),
              );
              stt
                .aux_name_to_addr
                .insert(ctor.cnst.name.clone(), ctor_addr.clone());
              stt.aux_gen_extra_names.insert(ctor.cnst.name.clone());
              pending_names.push(ctor.cnst.name.clone());
            }
          },
          MutConst::Recr(_) => {
            let proj = Constant::new(ConstantInfo::RPrj(RecursorProj {
              idx,
              block: block_addr.clone(),
            }));
            let proj_addr = content_address(&proj);
            stt.env.store_const(proj_addr.clone(), proj);
            stt.env.register_name(
              n.clone(),
              Named::new(proj_addr.clone(), meta)
                .with_name_refs(name_refs.clone()),
            );
            stt.aux_name_to_addr.insert(n.clone(), proj_addr);
            stt.aux_gen_extra_names.insert(n.clone());
            pending_names.push(n);
          },
          MutConst::Defn(_) => {
            let proj = Constant::new(ConstantInfo::DPrj(DefinitionProj {
              idx,
              block: block_addr.clone(),
            }));
            let proj_addr = content_address(&proj);
            stt.env.store_const(proj_addr.clone(), proj);
            stt.env.register_name(
              n.clone(),
              Named::new(proj_addr.clone(), meta)
                .with_name_refs(name_refs.clone()),
            );
            stt.aux_name_to_addr.insert(n.clone(), proj_addr);
            stt.aux_gen_extra_names.insert(n.clone());
            pending_names.push(n);
          },
        }
      }
    }
  }

  // Batch-push to pending queue (single lock acquisition).
  if !pending_names.is_empty() {
    stt.aux_gen_pending.lock().unwrap().extend(pending_names);
  }

  // Ingress all registered aux constants into the kernel environment.
  for cnst in aux_consts {
    crate::ix::compile::aux_gen::expr_utils::ensure_in_kenv(
      &cnst.name(),
      lean_env.as_ref(),
      stt,
    );
  }

  Ok(())
}

/// Compute the content-addressed hash for a Constant.
fn content_address(constant: &Constant) -> Address {
  let mut bytes = Vec::new();
  constant.put(&mut bytes);
  Address::hash(&bytes)
}

// ===========================================================================
// generate_and_compile_aux_recursors
// ===========================================================================

/// Generate and compile auxiliary constants for an alpha-collapsed inductive
/// block.
///
/// Called from `compile_mutual` after projections are registered. Runs the
/// full aux_gen pipeline:
///
/// 1. Generate patches (recursors, `.below`, `.brecOn`)
/// 2. Compile recursors
/// 3. Compile `.below` inductives (Prop) or definitions (Type)
/// 4. Compile `.below.rec` (for Prop `.below` inductives)
/// 5. Compile `.brecOn` in batched order (`.go`, main, `.eq`)
///
/// Only runs for inductive blocks. Non-inductive mutual blocks return
/// immediately.
pub(crate) fn generate_and_compile_aux_recursors(
  cs: &[MutConst],
  class_names: &[Vec<Name>],
  lean_env: &Arc<LeanEnv>,
  stt: &CompileState,
) -> Result<(), CompileError> {
  // Guard: only run for blocks containing inductives.
  let is_inductive_block = cs.iter().any(|c| matches!(c, MutConst::Indc(_)));
  if !is_inductive_block {
    return Ok(());
  }

  let aux_total_start = std::time::Instant::now();
  let block_label = class_names
    .first()
    .and_then(|c| c.first())
    .map(|n| n.pretty())
    .unwrap_or_default();

  // Phase 1: Generate patches. Errors here indicate a bug in aux_gen
  // (the input has already been validated by sort_consts and the compile
  // loop), so we propagate rather than swallow.
  let t0 = std::time::Instant::now();
  let patches =
    aux_gen::generate_aux_patches(class_names, cs, lean_env, stt, &stt.kctx)?;
  let gen_elapsed = t0.elapsed();
  if patches.is_empty() {
    return Ok(());
  }
  // Phase 2: Compile canonical recursors.
  let t1 = std::time::Instant::now();
  let rec_consts: Vec<MutConst> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::Rec(r) => Some(MutConst::Recr(r.clone())),
      _ => None,
    })
    .collect();
  if !rec_consts.is_empty() {
    compile_aux_block(&rec_consts, lean_env, stt)?;
  }
  let rec_elapsed = t1.elapsed();
  // Phase 2b: Compile .casesOn definitions.
  // casesOn wraps .rec and must be compiled after .rec but before .brecOn
  // (because .brecOn.eq references casesOn).
  let t2 = std::time::Instant::now();
  let cases_on_defs: Vec<MutConst> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::CasesOn(d) => Some(MutConst::Defn(Def {
        name: d.name.clone(),
        level_params: d.level_params.clone(),
        typ: d.typ.clone(),
        kind: DefKind::Definition,
        value: d.value.clone(),
        hints: crate::ix::env::ReducibilityHints::Abbrev,
        safety: DefinitionSafety::Safe,
        all: vec![],
      })),
      _ => None,
    })
    .collect();
  if !cases_on_defs.is_empty() {
    compile_aux_block(&cases_on_defs, lean_env, stt)?;
  }
  let cases_elapsed = t2.elapsed();

  // Phase 2c: Compile .recOn definitions (arg-reordered .rec wrapper).
  // recOn wraps .rec and must be compiled after .rec.
  let t3 = std::time::Instant::now();
  let rec_on_defs: Vec<MutConst> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::RecOn(d) => Some(MutConst::Defn(Def {
        name: d.name.clone(),
        level_params: d.level_params.clone(),
        typ: d.typ.clone(),
        kind: DefKind::Definition,
        value: d.value.clone(),
        hints: crate::ix::env::ReducibilityHints::Abbrev,
        safety: DefinitionSafety::Safe,
        all: vec![],
      })),
      _ => None,
    })
    .collect();
  if !rec_on_defs.is_empty() {
    compile_aux_block(&rec_on_defs, lean_env, stt)?;
  }
  let rec_on_elapsed = t3.elapsed();
  // Phase 3: Compile .below inductives (Prop-level).
  // Collect all .below names first for the mutual `all` field.
  let t4 = std::time::Instant::now();
  let all_below_names: Vec<Name> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::BelowIndc(bi) => Some(bi.name.clone()),
      _ => None,
    })
    .collect();
  let below_indcs: Vec<MutConst> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::BelowIndc(bi) => {
        Some(below_indc_to_mut_const(bi, &all_below_names))
      },
      _ => None,
    })
    .collect();
  if !below_indcs.is_empty() {
    compile_aux_block(&below_indcs, lean_env, stt)?;
    // Note: constructor names are already correctly set by rename_below_indc
    // during alias patching. register_below_ctor_aliases was removed because
    // it created spurious cross-aliases (e.g., Z.below.x for alpha-collapsed
    // blocks) that don't exist in the Lean environment.
  }

  // Phase 4: Compile .below definitions (Type-level).
  let below_defs: Vec<MutConst> = patches
    .iter()
    .filter_map(|(_, p)| match p {
      PatchedConstant::BelowDef(d) => Some(MutConst::Defn(Def {
        name: d.name.clone(),
        level_params: d.level_params.clone(),
        typ: d.typ.clone(),
        kind: DefKind::Definition,
        value: d.value.clone(),
        hints: crate::ix::env::ReducibilityHints::Abbrev,
        safety: DefinitionSafety::Safe,
        all: vec![],
      })),
      _ => None,
    })
    .collect();
  if !below_defs.is_empty() {
    compile_aux_block(&below_defs, lean_env, stt)?;
  }
  let below_elapsed = t4.elapsed();

  // Phase 5: Compile .below.rec (for Prop-level .below inductives).
  let t5 = std::time::Instant::now();
  if !below_indcs.is_empty() {
    compile_below_recursors(&below_indcs, lean_env, stt)?;
  }
  let below_rec_elapsed = t5.elapsed();

  // Phase 6: Compile .brecOn in 3 batches (.go first, main second, .eq last).
  let t6 = std::time::Instant::now();
  for batch in 0..3u8 {
    let defs: Vec<MutConst> = patches
      .iter()
      .filter_map(|(_, p)| match p {
        PatchedConstant::BRecOn(d) if brecon_batch(&d.name) == batch => {
          Some(brecon_to_mut_const(d))
        },
        _ => None,
      })
      .collect();
    if !defs.is_empty() {
      compile_aux_block(&defs, lean_env, stt)?;
    }
  }
  let brecon_elapsed = t6.elapsed();

  // Note: `.noConfusion`, `.noConfusionType`, `.ctor.noConfusion`, `.ctorIdx`,
  // `.ctorElim*`, `.ctor.inj*`, `._sizeOf_*`, etc. are **not** regenerated.
  // Their bodies only invoke `.casesOn` (never `.rec`), and `.casesOn`'s
  // public binder arity is invariant under alpha collapse. Compiling the
  // original Lean values as-is produces correct Ixon — they resolve to our
  // regenerated `.casesOn` at address-resolution time. The validate-aux
  // roundtrip test confirms this empirically (0 mismatches across 25k+
  // constants, including these auxiliaries for alpha-collapsed multi-ctor
  // blocks). See the aux_gen.rs module docs for the full rationale.

  let total = aux_total_start.elapsed();
  if *crate::ix::compile::IX_TIMING && total.as_secs_f32() > 0.5 {
    eprintln!(
      "[aux_gen] {:?} total={:.2}s gen={:.2}s rec={:.2}s cases={:.2}s recOn={:.2}s below={:.2}s belowRec={:.2}s brecon={:.2}s patches={}",
      block_label,
      total.as_secs_f32(),
      gen_elapsed.as_secs_f32(),
      rec_elapsed.as_secs_f32(),
      cases_elapsed.as_secs_f32(),
      rec_on_elapsed.as_secs_f32(),
      below_elapsed.as_secs_f32(),
      below_rec_elapsed.as_secs_f32(),
      brecon_elapsed.as_secs_f32(),
      patches.len(),
    );
  }
  Ok(())
}

// ===========================================================================
// Helpers
// ===========================================================================

/// Convert a `BelowIndc` (aux_gen output) to a `MutConst::Indc`.
/// `all_below_names` lists all `.below` inductives in the mutual block,
/// needed for the `all` field so `.below.rec` sees the full mutual structure.
fn below_indc_to_mut_const(
  bi: &BelowIndc,
  all_below_names: &[Name],
) -> MutConst {
  let ctor_vals: Vec<ConstructorVal> = bi
    .ctors
    .iter()
    .enumerate()
    .map(|(ci, c)| ConstructorVal {
      cnst: ConstantVal {
        name: c.name.clone(),
        level_params: bi.level_params.clone(),
        typ: c.typ.clone(),
      },
      induct: bi.name.clone(),
      cidx: Nat::from(ci as u64),
      num_params: Nat::from(c.n_params as u64),
      num_fields: Nat::from(c.n_fields as u64),
      is_unsafe: false,
    })
    .collect();

  MutConst::Indc(Ind {
    ind: crate::ix::env::InductiveVal {
      cnst: ConstantVal {
        name: bi.name.clone(),
        level_params: bi.level_params.clone(),
        typ: bi.typ.clone(),
      },
      num_params: Nat::from(bi.n_params as u64),
      // .below has original indices + 1 (the major premise)
      num_indices: Nat::from(bi.n_indices as u64),
      all: all_below_names.to_vec(),
      ctors: bi.ctors.iter().map(|c| c.name.clone()).collect(),
      is_rec: true,
      is_unsafe: false,
      // Propagate reflexivity from the parent: a `.below` built from a
      // reflexive parent has higher-order recursive IH fields of its own
      // (`∀ ys, I.below ... (h ys)`). Hardcoding `false` here silently
      // diverges from Lean's auto-generated `.below` content hash for
      // inductives like `Acc` and `Lean.Order.iterates`.
      is_reflexive: bi.is_reflexive,
      num_nested: Nat::from(0u64),
    },
    ctors: ctor_vals,
  })
}

/// Convert a `BRecOnDef` to a `MutConst::Defn`.
fn brecon_to_mut_const(d: &BRecOnDef) -> MutConst {
  MutConst::Defn(Def {
    name: d.name.clone(),
    level_params: d.level_params.clone(),
    typ: d.typ.clone(),
    kind: DefKind::Theorem,
    value: d.value.clone(),
    hints: crate::ix::env::ReducibilityHints::Abbrev,
    safety: DefinitionSafety::Safe,
    all: vec![],
  })
}

/// Determine which batch a `.brecOn` definition belongs to.
///
/// Batch 0: `.brecOn.go` (must compile first, `.brecOn` references it)
/// Batch 1: `.brecOn` (the main definition)
/// Batch 2: `.brecOn.eq` (proof of unfolding equation, references `.brecOn`)
fn brecon_batch(name: &Name) -> u8 {
  match name.last_str() {
    Some("go") => 0,
    Some("eq") => 2,
    _ => 1,
  }
}

/// Compile `.below.rec` recursors for Prop-level `.below` inductives.
///
/// Augments the lean_env with the `.below` inductives and their constructors
/// (since they don't exist in the original environment), then generates
/// canonical recursors for ALL `.below` inductives as one mutual block.
fn compile_below_recursors(
  below_indcs: &[MutConst],
  lean_env: &Arc<LeanEnv>,
  stt: &CompileState,
) -> Result<(), CompileError> {
  // Build a small overlay with just the .below inductives + ctors.
  // These don't exist in the original lean_env, but generate_canonical_recursors
  // needs to look them up as class representatives. Using an overlay avoids
  // cloning the full ~197k-entry environment.
  let mut overlay: LeanEnv = LeanEnv::default();
  for c in below_indcs {
    if let MutConst::Indc(ind) = c {
      overlay.insert(
        ind.ind.cnst.name.clone(),
        LeanConstantInfo::InductInfo(ind.ind.clone()),
      );
      for ctor in &ind.ctors {
        overlay.insert(
          ctor.cnst.name.clone(),
          LeanConstantInfo::CtorInfo(ctor.clone()),
        );
      }
    }
  }

  // Generate recursors for all .below inductives as ONE mutual block.
  // Each .below goes in its own class, matching the structure of the
  // original Lean .below.rec (which is a mutual recursor over all .below types).
  let classes: Vec<Vec<Name>> = below_indcs
    .iter()
    .filter_map(|c| match c {
      MutConst::Indc(ind) => Some(vec![ind.ind.cnst.name.clone()]),
      _ => None,
    })
    .collect();

  if classes.is_empty() {
    return Ok(());
  }

  let mut below_recs: Vec<MutConst> = Vec::new();
  let (recs, _) = recursor::generate_canonical_recursors_with_overlay(
    &classes,
    lean_env,
    Some(&overlay),
    None,
    stt,
    &stt.kctx,
  )?;
  for (_, rec) in recs {
    below_recs.push(MutConst::Recr(rec));
  }

  if !below_recs.is_empty() {
    compile_aux_block(&below_recs, lean_env, stt)?;
  }
  Ok(())
}
