module
public import Ix.Aiur.Meta

/-!
# Evaluation domain: two-adic multiplicative cosets

The trace domain of a circuit of size 2^L is the order-2^L subgroup
(shift = 1) of the inner field's two-adic group, generated by
`two_adic_gen(L)` — Rust's `EvaluationDomain`/`LagrangeSelectors`
(`Radix2Coset`, shared by the FRI and KZG configs). Written against the
field interface (`val_*`/`ext_*`): `two_adic_gen`, `pow2`, the vanishing
polynomial `trace_vanishing`, and the Lagrange selectors at a point
`trace_selectors` (`is_first_row`, `is_last_row`, `is_transition`,
`inv_vanishing`).
-/

public section

namespace MultiStark

def twoAdicDomain := ⟦
  -- ==========================================================================
  -- OOD evaluation domain math (`TwoAdicMultiplicativeCoset`, Goldilocks).
  -- The trace domain for a circuit of size 2^L is the order-2^L subgroup H
  -- (shift = 1) generated by `two_adic_gen(L)`.
  -- ==========================================================================

  -- e^(2^k) in the extension field.
  fn ext_exp_pow2(e: Ext, k: G) -> Ext {
    match k {
      0 => e,
      _ => ext_exp_pow2(ext_mul(e, e), k - 1),
    }
  }

  -- `two_adic_generator(bits)` — a primitive 2^bits root of unity in
  -- Goldilocks, derived by repeated squaring from the maximal (2^32)
  -- generator: `g_k = g_{k+1}^2` (matches Plonky3's TWO_ADIC_GENERATORS
  -- table, checked value-by-value). The 33-arm table cost 32 default-arm
  -- aux + 33 selectors; the chain is one short memoized circuit — the
  -- first call materialises ≤ 32 rows, every later call is a cache hit.
  -- Callers must keep `bits ≤ 32` (guarded where `bits` comes from proof
  -- advice: log_degrees in `ood_loop`, log_gmax in `pcs_verify`);
  -- an unguarded larger value would recurse without a base case.
  fn two_adic_gen(bits: G) -> Val {
    match bits {
      0  => .VAL_ONE,
      32 => .VAL_TWO_ADIC_ROOT,
      _  =>
        let g = two_adic_gen(bits + 1);
        val_mul(g, g),
    }
  }

  -- Vanishing polynomial of the trace domain (shift = 1, size 2^L) at point ζ:
  -- `Z_H(ζ) = ζ^(2^L) - 1`.
  fn trace_vanishing(zeta: Ext, l: G) -> Ext {
    ext_sub(ext_exp_pow2(zeta, l), .EXT_ONE)
  }

  -- Lagrange selectors at ζ for the trace domain (shift = 1), mirroring
  -- `domain.rs::selectors_at_point`:
  --   is_first_row   = Z_H(ζ) / (ζ - 1)
  --   is_last_row    = Z_H(ζ) / (ζ - g⁻¹)
  --   is_transition  = ζ - g⁻¹
  --   inv_vanishing  = 1 / Z_H(ζ)
  -- where g = two_adic_gen(L) is the subgroup generator.
  -- 2^l as an inner-field value (l is a small log-height).
  fn pow2(l: G) -> Val {
    match l {
      0 => .VAL_ONE,
      _ => val_mul(.VAL_TWO, pow2(l - 1)),
    }
  }

  fn trace_selectors(zeta: Ext, l: G) -> (Ext, Ext, Ext, Ext) {
    let zh = @trace_vanishing(zeta, l);
    let ginv = val_inverse(two_adic_gen(l));
    let is_first = ext_div(zh, ext_sub(zeta, .EXT_ONE));
    let is_last = ext_div(zh, ext_sub(zeta, [ginv, .VAL_ZERO]));
    let is_trans = ext_sub(zeta, [ginv, .VAL_ZERO]);
    let inv_van = ext_inverse(zh);
    (is_first, is_last, is_trans, inv_van)
  }
⟧

end MultiStark

end
