module

/-!
Circuit-grouping data for the recursive-verifier toplevel, applied wherever
it is compiled for proving or verifying (see
`CompiledToplevel.groupFunctions`). Empty = no grouping: every constrained
function keeps its singleton circuit. Fill from measured workload
statistics; a stale grouping stays sound (grouping never affects
semantics), only less efficient.
-/

public section

namespace MultiStark

-- Width-first partition, profiled on the IxVM-scale recursion workload
-- (see the cold-band PR discussion): the 12 tall (height >= ~300k rows),
-- narrow (width 12..48) circuits get their own band so the 10M-row bulk
-- never pays the cold band's merged width; everything else non-blake3
-- shares one band; the blake3 compression pair stays its own
-- all-branchless k = 2 group (folding it in drops lookups to k = 1 and
-- explodes stage 2). Measured widths: tall 73, cold 635, blake3 1566
-- (total 2,501 vs 10,946 ungrouped). Real-workload model (calibrated to
-- 1%): total FFT proxy 9.4e11 -> ~3.8e11, largest circuit 7.7e11 -> 1.7e11.
def verifierColdGroups : Array (String × Array String) := #[
  ("verifier_tall", #[
    "ro_fold",
    "blake3_compress_chunks",
    "read_vk_u8",
    "rows_pop",
    "read_u64_vec_n",
    "list_length.Ptr.ListNode.U8_8_4",
    "lanes_to_gl",
    "gl_val",
    "gl_lt_p",
    "gl_to_bytes",
    "select_rows",
    "read_vk_u16",
  ]),
  ("verifier_cold", #[
    "from_ext_basis",
    "prep_count",
    "read_merkle_cap_at",
    "read_vk_tag",
    "gl_inverse",
    "trace_vanishing",
    "flatten_u64",
    "ext_is_zero",
    "recon_evals",
    "opt_commit_cap",
    "pow2",
    "list_is_empty.U8",
    "prep_onto",
    "read_active",
    "read_batch_opening",
    "read_batch_opening_vec",
    "read_claims",
    "read_commit_phase_step_vec",
    "read_digest_vec_at",
    "read_ext_vec",
    "read_ext_vec_vec",
    "read_merkle_cap_vec",
    "read_one_claim",
    "read_opened_round",
    "read_query_proof",
    "read_query_proof_vec",
    "read_u64_vec",
    "read_u64_vec_vec",
    "read_vk_u16_limb",
    "snoc_cap",
    "eg_inverse",
    "list_lookup.U8",
    "ood_fold",
    "list_lookup.BatchOpening",
    "read_commit_phase_step",
    "read_commitments",
    "read_count_at",
    "read_preprocessed",
    "read_sys_lookup",
    "bits_to_num",
    "lookup_groups_count",
    "pad_block",
    "read_u8",
    "ro_x",
    "assert_bits",
    "list_length.BatchOpening",
    "list_lookup.SysNode",
    "list_concat.U8",
    "list_drop.G",
    "list_length.CommitPhaseProofStep",
    "log_degrees_onto",
    "obs_log_arities",
    "points_onto",
    "rev_onto",
    "round_onto",
    "b3_w4_onto",
    "ext_exp_pow2",
    "heights_all",
    "list_drop.BatchOpening",
    "ood_prep_rows",
    "read_active_n",
    "read_claims_n",
    "read_count",
    "read_ext_vec_vec_n",
    "read_field",
    "read_merkle_cap_vec_n",
    "read_node_ids_n",
    "read_opened_round_n",
    "read_opt_commit",
    "read_u64_vec_vec_n",
    "read_vk_u32_limb",
    "take_bits",
    "claims_onto",
    "list_length.Bucket",
    "read_batch_opening_vec_n",
    "read_ext_vec_n",
    "read_query_proof_vec_n",
    "read_sys_lookups_n",
    "snoc_b8",
    "build_buckets",
    "exp_by_bits",
    "has_height",
    "list_drop.SysNode",
    "list_length.SysCircuit",
    "read_commit_phase_step_vec_n",
    "read_opt_idx_n",
    "relaxed_u64_succ",
    "u64_is_zero",
    "read_nodes_n",
    "ch_sample_bits",
    "circ_has_height",
    "last_acc_is_zero",
    "list_length.U8_8",
    "heights_prep",
    "limbs_onto",
    "list_concat.U8_8",
    "read_claim_vals_n",
    "reconstruct_ext_row",
    "select_active_prep",
    "assert_blowup_zero",
    "open_2pt_mat",
    "pair_mul",
    "read_fri_proof",
    "build_publics",
    "claims_acc",
    "claims_each_onto",
    "cons8",
    "read_ext_at",
    "read_u64",
    "read_vk_u64",
    "ri_apply",
    "seed_tag_onto",
    "ch_sample_ext",
    "pcs_check_witness",
    "quotient_eval",
    "select_active_circuits",
    "fingerprint_vals",
    "list_length_u64.Ptr.ListNode.U8_8",
    "trace_selectors",
    "rollin",
    "b3_to_digest",
    "bucket_update",
    "ch_sample_field",
    "open_batch_2pt",
    "heights_max",
    "open_quotient",
    "ch_sample8",
    "fri_fold2",
    "list_length_u64.U8_8",
    "read_digest_at",
    "accs_onto",
    "open_prep",
    "read_system",
    "verify",
    "fold_roots",
    "quotient_degree_of",
    "open_prep_batch",
    "list_lookup.U8_8_4",
    "logup_fingerprint",
    "read_node",
    "read_proof",
    "digest_onto",
    "query_loop",
    "read_vk_digest",
    "cap_onto",
    "list_drop.U8_8_4",
    "read_digest_vec_at_n",
    "read_vk_cap_n",
    "eval_at",
    "b3_flatten_onto",
    "flatten2",
    "ch_sample_byte",
    "pcs_betas",
    "two_adic_gen",
    "verify_query",
    "cons_shape7",
    "leaf_hash_at",
    "ood_verify",
    "mmcs_root",
    "mmcs_verify",
    "b3_rows",
    "blake3",
    "read_sys_circuits_n",
    "ood_composition",
    "pcs_fri_verify",
    "read_sys_params",
    "digest_eq",
    "sample8_bits",
    "verify_one_query",
    "read_sys_circuit",
    "compress_ordered",
    "ood_loop",
    "inject_maybe",
    "logup_steps_fold",
    "fiat_shamir",
    "mmcs_compress",
    "blake3_finish",
    "mmcs_fold",
    "blake3_compress_block",
    "blake3_compress_layer",
    "blake3_next_layer",
    "bytes_to_block",
    "verify_multi_stark_proof",
    "b3_rows_chunks",
  ]),
  ("verifier_blake3", #[
    "blake3_compress_inner_j",
    "blake3_compress",
  ]),
]

end MultiStark

end
