import Ix.Tc.Verify.Audit.Basic
import Ix.Ixby
import Ix.Ixby.Aiur.Objects.Operands

/-!
# IxBy theorem trust manifest

Run with `lake build --wfail Ix.Ixby.Audit`. This audit is deliberately not
imported by the pure `Ix.Ixby` API or by the host proving adapter.

The exact allowances below cover all 314 source-authored public theorems
in the current logical/reference and object-parser proof modules. Only
`propext`, `Classical.choice`, and `Quot.sound` are permitted: no upstream,
native, pending, or sorry allowances. Updating a proof's exact dependency set
requires an explicit manifest change.

The complementary source-module scan also rejects nonstandard axioms in
private/generated/unlisted theorems, and rejects new global axioms even when
no manifest root uses them. Its scope is the imported IxBy proof surface;
new proof modules must be imported here to join that surface.

The reused audit helper is a Lean-only leaf module; it imports no checker
proofs, compiler verification, or proving FFI. These checks audit logical
dependencies, not the separate native/compiler/AIR soundness obligations.
-/

namespace Ix.Ixby.Audit

open Lean Lean.Elab.Command Ix.Tc.Verify.Audit

private def standard : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
private def noChoice : Array Lean.Name := #[``propext, ``Quot.sound]

private def withAxioms (axioms : Array Lean.Name) (names : Array Lean.Name) : Array RootAllowance :=
  names.map fun root => { root, standardAxioms := axioms }

private def roots : Array RootAllowance :=
  withAxioms standard #[
    ``AiurBackend.Objects.Admission.checked_advice_call,
    ``AiurBackend.Objects.Admission.checked_advice_eval,
    ``AiurBackend.Objects.Admission.checked_advice_head_reject,
    ``AiurBackend.Objects.Admission.checked_extended_load,
    ``AiurBackend.Objects.Admission.checked_load_admission,
    ``AiurBackend.Objects.Admission.checked_load_call,
    ``AiurBackend.Objects.Admission.checked_load_eval,
    ``AiurBackend.Objects.Admission.checked_load_limit_reject,
    ``AiurBackend.Objects.Admission.extend_advice_metadata,
    ``AiurBackend.Objects.Admission.extend_advice_slice,
    ``AiurBackend.Objects.Admission.load_u32_limit,
    ``AiurBackend.Objects.Admission.loaded_declarations,
    ``AiurBackend.Objects.Admission.store_advice_io,
    ``AiurBackend.Objects.Admission.store_advice_map,
    ``AiurBackend.Objects.Admission.store_advice_other_bucket,
    ``AiurBackend.Objects.Admission.store_advice_prefix,
    ``AiurBackend.Objects.Admission.store_advice_preserves,
    ``AiurBackend.Objects.Admission.store_advice_size,
    ``AiurBackend.Objects.Admission.store_advice_stream,
    ``AiurBackend.Objects.CodeHeaders.checked_block_continuation,
    ``AiurBackend.Objects.CodeHeaders.checked_block_header,
    ``AiurBackend.Objects.CodeHeaders.checked_block_header_reject,
    ``AiurBackend.Objects.CodeHeaders.checked_empty_list,
    ``AiurBackend.Objects.CodeHeaders.checked_function_continuation,
    ``AiurBackend.Objects.CodeHeaders.checked_function_count,
    ``AiurBackend.Objects.CodeHeaders.checked_function_header,
    ``AiurBackend.Objects.CodeHeaders.checked_function_header_reject,
    ``AiurBackend.Objects.CodeHeaders.checked_program_headers,
    ``AiurBackend.Objects.CodeHeaders.checked_program_headers_success,
    ``AiurBackend.Objects.CodeHeaders.count_state_registers,
    ``AiurBackend.Objects.CodeHeaders.function_count_valid_iff,
    ``AiurBackend.Objects.CodeHeaders.function_header_valid_iff,
    ``AiurBackend.Objects.CodeHeaders.loaded_program_headers,
    ``AiurBackend.Objects.CodeHeaders.u32_upper_exact,
    ``AiurBackend.Objects.Declarations.checked_declaration_header,
    ``AiurBackend.Objects.Declarations.checked_declarations_call,
    ``AiurBackend.Objects.Declarations.checked_declarations_eval,
    ``AiurBackend.Objects.Declarations.checked_declarations_reject,
    ``AiurBackend.Objects.Declarations.checked_declarations_table,
    ``AiurBackend.Objects.Declarations.declaration_cell_decoded,
    ``AiurBackend.Objects.Declarations.declaration_codec,
    ``AiurBackend.Objects.Declarations.declaration_decoded,
    ``AiurBackend.Objects.Declarations.declaration_fields,
    ``AiurBackend.Objects.Declarations.field_u32_limit,
    ``AiurBackend.Objects.Declarations.store_declarations_io,
    ``AiurBackend.Objects.Declarations.store_declarations_map,
    ``AiurBackend.Objects.Declarations.store_declarations_prefix,
    ``AiurBackend.Objects.Declarations.store_declarations_preserves,
    ``AiurBackend.Objects.Declarations.store_declarations_size,
    ``AiurBackend.Objects.Declarations.store_declarations_table,
    ``AiurBackend.Objects.Declarations.valid_cons,
    ``AiurBackend.Objects.Equality.checked_id_eq_call,
    ``AiurBackend.Objects.Equality.id_eq_call,
    ``AiurBackend.Objects.Equality.id_eq_eval,
    ``AiurBackend.Objects.Equality.id_eq_semantic,
    ``AiurBackend.Objects.Equality.raw_decode_injective,
    ``AiurBackend.Objects.Equality.raw_semantic_eq,
    ``AiurBackend.Objects.Identity.checked_id_reader_call,
    ``AiurBackend.Objects.Identity.checked_id_reader_prefix,
    ``AiurBackend.Objects.Identity.checked_id_reader_sound,
    ``AiurBackend.Objects.Identity.decode_id_words,
    ``AiurBackend.Objects.Identity.inline_word_eval,
    ``AiurBackend.Objects.Identity.inline_word_prefix,
    ``AiurBackend.Objects.Identity.run_ops_append,
    ``AiurBackend.Objects.Identity.run_ops_list,
    ``AiurBackend.Objects.Identity.word_bytes_prepend,
    ``AiurBackend.Objects.Identity.word_field_bound,
    ``AiurBackend.Objects.Identity.word_field_codec,
    ``AiurBackend.Objects.Identity.word_indices_bound,
    ``AiurBackend.Objects.Identity.words_digest_exact,
    ``AiurBackend.Objects.Identity.words_prefix,
    ``AiurBackend.Objects.Memory.checked_fields_bounds,
    ``AiurBackend.Objects.Operands.checked_erased_operand,
    ``AiurBackend.Objects.Operands.checked_literal_operand,
    ``AiurBackend.Objects.Operands.checked_local_operand,
    ``AiurBackend.Objects.Operands.checked_operand_call,
    ``AiurBackend.Objects.Operands.checked_operand_reader,
    ``AiurBackend.Objects.Operands.checked_operand_success,
    ``AiurBackend.Objects.Operands.checked_unsupported_operand,
    ``AiurBackend.Objects.Operands.loaded_operand,
    ``AiurBackend.Objects.Operands.operand_flat_decoded,
    ``AiurBackend.Objects.Parser.byte_prefix_store,
    ``AiurBackend.Objects.Parser.byte_reader_call,
    ``AiurBackend.Objects.Parser.byte_reader_eval,
    ``AiurBackend.Objects.Parser.checked_empty_parser_table,
    ``AiurBackend.Objects.Parser.checked_word_reader_prefix,
    ``AiurBackend.Objects.Parser.empty_table_eval,
    ``AiurBackend.Objects.Parser.mem_store_map,
    ``AiurBackend.Objects.Parser.packed_word_codec,
    ``AiurBackend.Objects.Parser.packed_word_exact,
    ``AiurBackend.Objects.Parser.range_check_success,
    ``AiurBackend.Objects.Parser.stored_byte_prefix,
    ``AiurBackend.Objects.Parser.stored_declaration_table,
    ``AiurBackend.Objects.Parser.stored_empty_table,
    ``AiurBackend.Objects.Parser.word_reader_eval,
    ``AiurBackend.Objects.ProgramPrefix.checked_header_eval,
    ``AiurBackend.Objects.ProgramPrefix.checked_magic_prefix,
    ``AiurBackend.Objects.ProgramPrefix.checked_program_continuation,
    ``AiurBackend.Objects.ProgramPrefix.checked_program_header_reject,
    ``AiurBackend.Objects.ProgramPrefix.checked_program_prefix,
    ``AiurBackend.Objects.ProgramPrefix.checked_program_table,
    ``AiurBackend.Objects.ProgramPrefix.header_entry_codec,
    ``AiurBackend.Objects.ProgramPrefix.header_valid_iff,
    ``AiurBackend.Objects.ProgramPrefix.loaded_program_prefix,
    ``AiurBackend.Objects.ProgramPrefix.word_zero_iff,
    ``AiurBackend.Objects.Refinement.case_transition,
    ``AiurBackend.Objects.Refinement.constructor_operation,
    ``AiurBackend.Objects.Refinement.erased_projection,
    ``AiurBackend.Objects.Scalars.checked_boolean_scalar,
    ``AiurBackend.Objects.Scalars.checked_extension_scalar,
    ``AiurBackend.Objects.Scalars.checked_field_call,
    ``AiurBackend.Objects.Scalars.checked_field_reader,
    ``AiurBackend.Objects.Scalars.checked_field_scalar,
    ``AiurBackend.Objects.Scalars.checked_scalar_call,
    ``AiurBackend.Objects.Scalars.checked_scalar_reader,
    ``AiurBackend.Objects.Scalars.checked_unsupported_scalar,
    ``AiurBackend.Objects.Scalars.checked_word_scalar,
    ``AiurBackend.Objects.Scalars.field_canonical_iff,
    ``AiurBackend.Objects.Scalars.field_guard_exact,
    ``AiurBackend.Objects.Scalars.four_byte_eval,
    ``AiurBackend.Objects.Scalars.raw_field_reader,
    ``AiurBackend.Objects.Scalars.readonly_parser_call,
    ``AiurBackend.Objects.Scalars.scalar_flat_decoded,
    ``AiurBackend.Objects.Store.checked_fields_extends,
    ``AiurBackend.Objects.Store.construct_stored_fields,
    ``AiurBackend.Objects.Store.eval_store_preserves_representation,
    ``AiurBackend.Objects.Store.mem_store_bounds,
    ``AiurBackend.Objects.Store.mem_store_io,
    ``AiurBackend.Objects.Store.mem_store_load,
    ``AiurBackend.Objects.Store.mem_store_other_bucket,
    ``AiurBackend.Objects.Store.mem_store_preserves,
    ``AiurBackend.Objects.Store.reconstruct_ref_extends,
    ``AiurBackend.Objects.Store.store_extends_heap,
    ``AiurBackend.Objects.Store.store_preserves_reconstruction,
    ``AiurBackend.Objects.Store.store_preserves_representation,
    ``AiurBackend.Objects.Store.stored_cons_fields,
    ``AiurBackend.Objects.Store.stored_field_pointer,
    ``AiurBackend.Objects.Table.pack_limbs_injective,
    ``AiurBackend.Objects.Table.store_preserves_declaration_cell,
    ``AiurBackend.Objects.Table.store_preserves_declarations,
    ``AiurBackend.Objects.Table.store_preserves_program_reconstruction,
    ``AiurBackend.Objects.Table.store_preserves_table,
    ``AiurBackend.Objects.Unique.call_empty_result,
    ``AiurBackend.Objects.Unique.checked_unique_call,
    ``AiurBackend.Objects.Unique.checked_unique_table,
    ``AiurBackend.Objects.Unique.semantic_membership,
    ``AiurBackend.Objects.Unique.unique_cons_enter,
    ``AiurBackend.Objects.Unique.unique_nil_eval,
    ``AiurBackend.Objects.Unique.unique_spine_eval,
    ``AiurBackend.Objects.Unique.unique_step_duplicate,
    ``AiurBackend.Objects.Unique.unique_step_fresh,
    ``AiurBackend.Refinement.branch,
    ``AiurBackend.Refinement.direct_call,
    ``AiurBackend.Refinement.direct_call_overflow,
    ``AiurBackend.Refinement.pure_let,
    ``AiurBackend.Refinement.return_empty,
    ``AiurBackend.Refinement.return_instruction,
    ``AiurBackend.Refinement.return_instruction_needs_two,
    ``AiurBackend.Refinement.return_resume,
    ``AiurBackend.Refinement.self_call,
    ``AiurBackend.Refinement.tail_call,
    ``AiurBackend.Refinement.tail_self_call,
    ``AiurBackend.Refinement.transition_consumes_fuel,
    ``AiurBackend.Refinement.zero_fuel,
    ``certified_execution,
    ``Codec.Execution.reference_evaluates,
    ``evaluates_deterministic,
    ``execute_add_fuel,
    ``Profile.execute_refines,
    ``refinement_of_forward_and_termination,
    ``run_add_fuel
  ] ++
  withAxioms noChoice #[
    ``AiurBackend.Objects.Admission.advice_bytes_exact,
    ``AiurBackend.Objects.Admission.advice_reader_checked,
    ``AiurBackend.Objects.Admission.advice_slice_array,
    ``AiurBackend.Objects.Admission.advice_slice_of_lookup,
    ``AiurBackend.Objects.Admission.byte_fields_bytes,
    ``AiurBackend.Objects.Admission.byte_fields_cons,
    ``AiurBackend.Objects.Admission.loader_checked,
    ``AiurBackend.Objects.Admission.loader_code_checked,
    ``AiurBackend.Objects.CodeHeaders.block_header_ops_size,
    ``AiurBackend.Objects.CodeHeaders.empty_list_branch_checked,
    ``AiurBackend.Objects.CodeHeaders.function_count_ops_size,
    ``AiurBackend.Objects.CodeHeaders.function_header_ops_size,
    ``AiurBackend.Objects.CodeHeaders.group_function_header_bytes,
    ``AiurBackend.Objects.CodeHeaders.header_code_checked,
    ``AiurBackend.Objects.CodeHeaders.list_header_checked,
    ``AiurBackend.Objects.CodeHeaders.ops_prefix_checked,
    ``AiurBackend.Objects.CodeHeaders.program_function_arguments,
    ``AiurBackend.Objects.CodeHeaders.program_headers_checked,
    ``AiurBackend.Objects.CodeHeaders.program_headers_ops_size,
    ``AiurBackend.Objects.Declarations.declaration_code_checked,
    ``AiurBackend.Objects.Declarations.declarations_checked,
    ``AiurBackend.Objects.Declarations.group_declaration_bytes,
    ``AiurBackend.Objects.Declarations.raw_declaration_cell_decoded,
    ``AiurBackend.Objects.Equality.field_eq_exact,
    ``AiurBackend.Objects.Equality.field_sub_zero,
    ``AiurBackend.Objects.Equality.id_eq_checked,
    ``AiurBackend.Objects.Equality.raw_decode_bounds,
    ``AiurBackend.Objects.Equality.raw_eq_exact,
    ``AiurBackend.Objects.Identity.group_word_bytes,
    ``AiurBackend.Objects.Identity.id_reader_checked,
    ``AiurBackend.Objects.Identity.read_idxs_append,
    ``AiurBackend.Objects.Identity.read_idxs_single,
    ``AiurBackend.Objects.Memory.bytecode_heap_load,
    ``AiurBackend.Objects.Memory.bytecode_heap_load_iff,
    ``AiurBackend.Objects.Memory.checked_fields_sound,
    ``AiurBackend.Objects.Memory.reconstruct_ref_consumes,
    ``AiurBackend.Objects.Memory.reconstruct_ref_sound,
    ``AiurBackend.Objects.Memory.reconstruct_sound,
    ``AiurBackend.Objects.Memory.traverse_budget_le,
    ``AiurBackend.Objects.Memory.traverse_budget_sound,
    ``AiurBackend.Objects.Memory.word_value_exact,
    ``AiurBackend.Objects.Operands.operand_code_checked,
    ``AiurBackend.Objects.Operands.operand_flat_size,
    ``AiurBackend.Objects.Operands.operand_reader_checked,
    ``AiurBackend.Objects.Parser.byte_reader_checked,
    ``AiurBackend.Objects.Parser.bytecode_memory_congr,
    ``AiurBackend.Objects.Parser.empty_parser_checked,
    ``AiurBackend.Objects.Parser.mem_load_map,
    ``AiurBackend.Objects.Parser.word_reader_checked,
    ``AiurBackend.Objects.ProgramPrefix.byte_const_eq,
    ``AiurBackend.Objects.ProgramPrefix.group_header_bytes,
    ``AiurBackend.Objects.ProgramPrefix.header_ops_size,
    ``AiurBackend.Objects.ProgramPrefix.magic_valid_iff,
    ``AiurBackend.Objects.ProgramPrefix.program_code_checked,
    ``AiurBackend.Objects.ProgramPrefix.program_prefix_checked,
    ``AiurBackend.Objects.ProgramPrefix.program_prefix_ops_size,
    ``AiurBackend.Objects.Refinement.case_selection,
    ``AiurBackend.Objects.Refinement.case_transfer,
    ``AiurBackend.Objects.Refinement.checked_rank_equation,
    ``AiurBackend.Objects.Refinement.child_rank_lt,
    ``AiurBackend.Objects.Refinement.decode_bind_fields,
    ``AiurBackend.Objects.Refinement.field_rank_successor,
    ``AiurBackend.Objects.Refinement.no_ranked_cycle,
    ``AiurBackend.Objects.Refinement.rank_growth_bound,
    ``AiurBackend.Objects.Refinement.ranked_edges_well_founded,
    ``AiurBackend.Objects.Refinement.ranked_heap_represents,
    ``AiurBackend.Objects.Refinement.reversed_projection,
    ``AiurBackend.Objects.Scalars.byte_boolean_exact,
    ``AiurBackend.Objects.Scalars.canonical_field_exact,
    ``AiurBackend.Objects.Scalars.dispatch_checked,
    ``AiurBackend.Objects.Scalars.field_bytes_codec,
    ``AiurBackend.Objects.Scalars.field_reader_checked,
    ``AiurBackend.Objects.Scalars.packed_field_mod,
    ``AiurBackend.Objects.Scalars.prefix_byte_load,
    ``AiurBackend.Objects.Scalars.return_arms_checked,
    ``AiurBackend.Objects.Scalars.scalar_code_checked,
    ``AiurBackend.Objects.Scalars.scalar_reader_checked,
    ``AiurBackend.Objects.Store.represents_extends,
    ``AiurBackend.Objects.Table.checked_program_table,
    ``AiurBackend.Objects.Table.pack_limbs_bound,
    ``AiurBackend.Objects.Table.read_table_sound,
    ``AiurBackend.Objects.Table.reconstruct_program_sound,
    ``AiurBackend.Objects.Unique.bytecode_memory_map,
    ``AiurBackend.Objects.Unique.decode_decl_cons,
    ``AiurBackend.Objects.Unique.decode_decl_nil,
    ``AiurBackend.Objects.Unique.field_pred,
    ``AiurBackend.Objects.Unique.field_succ_nonzero,
    ``AiurBackend.Objects.Unique.raw_load,
    ``AiurBackend.Objects.Unique.read_declarations_spine,
    ``AiurBackend.Objects.Unique.read_idxs_of_all₂,
    ``AiurBackend.Objects.Unique.return_block_checked,
    ``AiurBackend.Objects.Unique.step_compare_arguments,
    ``AiurBackend.Objects.Unique.step_recurse_arguments,
    ``AiurBackend.Objects.Unique.unique_checked,
    ``AiurBackend.Objects.Unique.unique_step_ops,
    ``AiurBackend.Refinement.bind_transfer,
    ``AiurBackend.Refinement.branch_transfer,
    ``AiurBackend.Refinement.enter_reversed,
    ``AiurBackend.Refinement.read_args_decode,
    ``AiurBackend.Refinement.read_decode,
    ``Blake3.hash_size
  ] ++
  withAxioms #[``propext] #[
    ``AiurBackend.Objects.Admission.field_byte_exact,
    ``AiurBackend.Objects.CodeHeaders.function_header_bytes_length,
    ``AiurBackend.Objects.Declarations.declaration_bytes_length,
    ``AiurBackend.Objects.Declarations.declaration_cell_size,
    ``AiurBackend.Objects.Equality.bit_product,
    ``AiurBackend.Objects.Equality.field_bound,
    ``AiurBackend.Objects.Equality.field_of_nat_mod,
    ``AiurBackend.Objects.Identity.byte_prefix_split,
    ``AiurBackend.Objects.Identity.word_bytes_length,
    ``AiurBackend.Objects.Operands.u32_comparison_exact,
    ``AiurBackend.Objects.Parser.byte_field_exact,
    ``AiurBackend.Objects.Parser.byte_prefix_append,
    ``AiurBackend.Objects.Parser.byte_prefix_head,
    ``AiurBackend.Objects.ProgramPrefix.header_bytes_length,
    ``AiurBackend.Objects.Refinement.all₂_exists,
    ``AiurBackend.Objects.Refinement.all₂_length,
    ``AiurBackend.Objects.Refinement.all₂_lookup,
    ``AiurBackend.Objects.Refinement.construct_rank_le,
    ``AiurBackend.Objects.Refinement.construct_represents,
    ``AiurBackend.Objects.Refinement.field_comparison_exact,
    ``AiurBackend.Objects.Refinement.field_of_nat_exact,
    ``AiurBackend.Objects.Refinement.max_rank_le,
    ``AiurBackend.Objects.Refinement.rank_le_max,
    ``AiurBackend.Objects.Refinement.read_fields_length,
    ``AiurBackend.Objects.Scalars.scalar_flat_size,
    ``AiurBackend.Objects.Store.read_fields_extends,
    ``AiurBackend.Objects.Table.decode_id_exact,
    ``AiurBackend.Objects.Table.read_declarations_length,
    ``AiurBackend.Refinement.decode_bind,
    ``AiurBackend.Refinement.decode_encode,
    ``AiurBackend.Refinement.decode_locals_size,
    ``AiurBackend.Refinement.decode_stack_order,
    ``AiurBackend.Refinement.decode_stack_size,
    ``AiurBackend.Refinement.encode_decode,
    ``AiurBackend.Refinement.ordered_table_lookup,
    ``AiurBackend.Refinement.reversed_arguments,
    ``Goldilocks.reduce_canonical
  ] ++
  withAxioms #[] #[
    ``AiurBackend.Objects.Equality.field_n_injective,
    ``AiurBackend.Objects.Refinement.constructor_identity_iff,
    ``AiurBackend.Objects.Scalars.field_bytes_length,
    ``AiurBackend.Refinement.decode_at_block,
    ``Goldilocks.reduce_val
  ]

/-- Cover newly added and private/generated proof declarations as well as the
named manifest. Attribute declarations by source module, not their namespace,
so a macro cannot move an unexpected axiom outside the scanned namespace. -/
def checkAxiomFrontier : CommandElabM Unit := do
  let env ← getEnv
  let modules := env.allImportedModuleNames
  let mut count : Nat := 0
  for (name, info) in env.constants.toList do
    let some idx := env.getModuleIdxFor? name | continue
    unless (`Ix.Ixby).isPrefixOf modules[idx.toNat]! do continue
    match info with
    | .axiomInfo _ => throwError m!"IxBy source declares an axiom: {name}"
    | .thmInfo _ =>
      count := count + 1
      for axiomName in ← Lean.collectAxioms name do
        unless standard.contains axiomName do
          throwError m!"IxBy theorem {name} uses nonstandard axiom {axiomName}"
    | _ => pure ()
  logInfo m!"IxBy source axiom frontier passed for {count} theorem declarations"

run_cmd Ix.Tc.Verify.Audit.check roots "IxBy"
run_cmd checkAxiomFrontier

end Ix.Ixby.Audit
