import Ix.Tc.Verify.Audit.Basic
import Ix.Tc.Verify.Ctx
import Ix.Tc.Verify.Decl
import Ix.Tc.Verify.Execution
import Ix.Tc.Verify.Frame
import Ix.Tc.Verify.InstL
import Ix.Tc.Verify.NatFixture
import Ix.Tc.Verify.Run
import Ix.Tc.Verify.Support
import Ix.Tc.Verify.Totalization
import Ix.Tc.Verify.Whnf
import Ix.Tc.Verify.World

/-!
# Trust manifest for the completed `Ix.Tc.Verify` proof surface

These are the current completed foundations and reusable semantic interfaces
that later C1--C3 roots will consume.  A new headline theorem must be added here
when it becomes part of that exported proof surface.  The temporary C1/C2
statement skeletons are audited separately in `Audit/Statements.lean`
because their opaque relation names intentionally collide with the concrete
relations imported here.

The entries are deliberately repetitive at the root level: a change in the
transitive trust boundary of any one interface should produce a focused CI
failure.  Shared arrays below are only labels for exactly repeated sets.
-/

namespace Ix.Tc.Verify.Audit.Completed

open Ix.Tc.Verify.Audit

private def standard : Array Lean.Name :=
  #[``propext, ``Classical.choice, ``Quot.sound]

private def standardWithoutChoice : Array Lean.Name :=
  #[``propext, ``Quot.sound]

private def standardWithoutQuot : Array Lean.Name :=
  #[``propext, ``Classical.choice]

private def propextOnly : Array Lean.Name := #[``propext]

private def blake3Native : Array Lean.Name := #[
  nativeAxiom `Blake3
    `Blake3.HasherOps.hash._native.native_decide.ax_1
]

private def expressionNative : Array Lean.Name := blake3Native.push
  (nativeAxiom `Ix.Tc.Expr
    `Ix.Tc.KExpr.mkVar._native.native_decide.ax_1)

private def levelNative : Array Lean.Name := expressionNative.push
  (nativeAxiom `Ix.Tc.Level
    `Ix.Tc.KUniv.mkSucc._native.native_decide.ax_1)

private def contextNative : Array Lean.Name := expressionNative.push
  (nativeAxiom `Ix.Tc.Monad
    `Ix.Tc.TcM.ctxAddrForLbr._native.native_decide.ax_5)

private def inferNative : Array Lean.Name := levelNative.push
  (nativeAxiom `Ix.Tc.Monad
    `Ix.Tc.TcM.ctxAddrForLbr._native.native_decide.ax_5)

private def inductiveNative : Array Lean.Name := (inferNative.push
  (nativeAxiom `Ix.Environment
    `Ix.Name.mkStr._native.native_decide.ax_1)).push
  (nativeAxiom `Ix.Tc.Inductive
    `Ix.Tc.RecM.canonicalAuxOrder._native.native_decide.ax_17)

/- Direct upstream `sorryAx` origins.  Listing the declarations, rather than
merely allowing `sorryAx`, makes upstream debt movement visible in review. -/
private def inductiveWF : Lean.Name := ``Lean4Lean.VInductDecl.WF
private def addInduct : Lean.Name := ``Lean4Lean.VEnv.addInduct
private def addInductWF : Lean.Name := ``Lean4Lean.VEnv.addInduct_WF
private def forallEInv : Lean.Name :=
  ``Lean4Lean.VEnv.IsDefEqU.forallE_inv_stratified
private def sortInv : Lean.Name := ``Lean4Lean.VEnv.IsDefEqU.sort_inv

private def typingDebt : Array Lean.Name :=
  #[inductiveWF, addInduct, addInductWF, forallEInv, sortInv]

/- The empty legacy whole-`KEnv` inductive path is forbidden from every G2b
consumer root.  Keeping this list in the executable audit prevents an
innocent-looking helper from reintroducing the old `nomatch` dependency. -/
private def legacyWholeEnv : Array Lean.Name := #[
  ``Ix.Tc.AddKInduct,
  ``Ix.Tc.AddKInduct.to_addInduct,
  ``Ix.Tc.TrKEnv',
  ``Ix.Tc.TrKEnv
]

private def roots : Array RootAllowance := #[
  -- Level decision procedures.
  { root := ``Ix.Tc.univEq_sound, standardAxioms := standard },
  { root := ``Ix.Tc.univGeq_sound, standardAxioms := standard },

  -- Memoized expression walkers against their pure specifications.
  { root := ``Ix.Tc.lift_spec,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.subst_spec,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.simulSubst_spec,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.instantiateRev_spec,
    standardAxioms := standard, nativeAxioms := expressionNative },
  -- There is not yet an API-level `abstractFVars_spec`; protect the current
  -- walker master until that final wrapper replaces it.
  { root := ``Ix.Tc.abstractFVarsCached_spec,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TcM.instantiateUnivParams_wf,
    standardAxioms := standard, nativeAxioms := levelNative },

  -- G3a finite run support and generated-term resource bounds.
  { root := ``Ix.Tc.KExpr.LiftReach.finite,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.SubstReach.finite,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.InstUnivReach.finite,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := levelNative },
  { root := ``Ix.Tc.WalkerRequest.reach_finite,
    standardAxioms := standard,
    nativeAxioms := levelNative },
  { root := ``Ix.Tc.InternTable.exprSupport_finite,
    standardAxioms := standard },
  { root := ``Ix.Tc.RunSupport.collisionFree_of_le,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.RunSupport.singleton_collisionFree,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.WalkerRequest.Bounds.lift_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WalkerRequest.Bounds.subst_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.CheckConstSupport.initial_support,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.lift,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.subst,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.instUniv,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.mono,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.scope,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.ResourceBounds.mono,
    standardAxioms := standard,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.AmbientNat.checkSupport,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.resourceBounds,
    standardAxioms := standard,
    nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.supportAcceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },

  -- G3b closes the remaining formalized walker/direct-intern families and
  -- ties the exact finite request list to an actual TcM computation.
  { root := ``Ix.Tc.KExpr.SimulSubstReach.finite,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.InstRevReach.finite,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.AbstractReach.finite,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WalkerRequest.univReach_finite,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.InternTable.univSupport_finite,
    standardAxioms := standard },
  { root := ``Ix.Tc.RunSupport.pair_collisionFree,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.WalkerRequest.Bounds.simulSubst_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WalkerRequest.Bounds.instRev_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WalkerRequest.Bounds.abstractFVars_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.abstractFVars_eq,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.InternPreservesUnivs.pure,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.InternPreservesUnivs.runWalk,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.pure,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.bind,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.scratchGet,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.scratchInsert,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.liftIntern,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.WalkPreservesUnivs.internExpr,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.lift_preservesUnivs,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.subst_preservesUnivs,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.simulSubst_preservesUnivs,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.instantiateRev_preservesUnivs,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.abstractFVars_preservesUnivs,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WalkerRequest.Bounds.abstractFVarsCached_result,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.CheckConstSupport.initial_univ_support,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.internExpr,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.internUniv,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.simulSubst,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.instRev,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.CheckConstSupport.abstractFVars,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.ExecutionRequests.bind,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.ExecutionRequests.tryCatch,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.ExecutionRequests.weaken,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.ExecutionRequests.of_eq,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.initial,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.requestBounds,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.internExpr_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.internUniv_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunSupport.CoversIntern.of_expr_univs,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RunAssumptions.lift_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.subst_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.simulSubst_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.instRev_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.abstractFVarsCached_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.abstractFVars_spec,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.instantiateUnivParams_wf,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RunAssumptions.runIntern_supported_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.lift_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.subst_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.simulSubst_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.instRev_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.abstractFVars_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.instUniv_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.supportExecution,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.runAssumptions,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },

  -- Expression translation, typing, uniqueness, and defeq bridges.
  { root := ``Ix.Tc.TrKExprS.instL,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.TrKExprS.inst,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TrKExprS.wf, standardAxioms := standard },
  { root := ``Ix.Tc.TrKExpr.wf, standardAxioms := standard },
  { root := ``Ix.Tc.TrKExprS.uniq,
    standardAxioms := standard, sorryOrigins := typingDebt },
  { root := ``Ix.Tc.TrKExprS.defeqDFC,
    standardAxioms := standard, sorryOrigins := typingDebt },
  { root := ``Ix.Tc.TrKExpr.defeq,
    standardAxioms := standard, sorryOrigins := typingDebt },

  -- Legacy whole-environment compatibility interfaces.  G2b consumer roots
  -- below are forbidden from depending on these declarations.
  { root := ``Ix.Tc.TrKEnv.wf,
    standardAxioms := standard, sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrKEnv.find?,
    standardAxioms := standard, sorryOrigins := #[inductiveWF] },
  { root := ``Ix.Tc.TcM.tick.tcInv,
    standardAxioms := standard, sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.instantiateUnivParams.tcInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- The narrow upstream-context dependency behind translation uniqueness.
  { root := ``Ix.Tc.KVLCtx.IsDefEq.find?_uniq,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },

  -- Dual-context reconciliation entry points used by the checker proofs.
  { root := ``Ix.Tc.CtxRecon.wf, standardAxioms := standard },
  { root := ``Ix.Tc.CtxRecon.lookupVar,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.CtxRecon.fvar_resolves,
    standardAxioms := standard },

  -- G1a's non-circular world and one-way lazy-load boundary.
  { root := ``Ix.Tc.VerifyWorld.ofCatalog_catalogued_not_trusted,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.VerifyWorld.LE.trans,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.VerifyWorld.LE.catalogued_iff,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.LoadedAgrees.world_iff,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.LoadedAgrees.insert,
    standardAxioms := standard },
  { root := ``Ix.Tc.LoadedAgrees.of_extension,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.VerifyWorld.ofCatalog_loaded,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.VerifyWorld.ofCatalog_loaded_not_trusted,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- G1b's raw/pending boundary.  Raw correspondence has no declaration-WF
  -- premise; the fixture roots pin the concrete non-WF pending case.
  { root := ``Ix.Tc.RawExprRel.mono,
    standardAxioms := standard },
  { root := ``Ix.Tc.RawExprRel.reference_resolved,
    standardAxioms := standard },
  { root := ``Ix.Tc.RawDeclRel.mono,
    standardAxioms := standard },
  { root := ``Ix.Tc.PendingDecl.no_target_lookup,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.PendingDecl.no_self_expr_reference,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.PendingDecl.not_trustedDecl,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.IllTypedPending.pending_but_not_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.IllTypedPending.loaded_pending_but_not_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- G1c's trusted-only catalog log and explicit-WF promotion boundary.
  { root := ``Ix.Tc.RawDeclRel.wf_le,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogLog.wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogLog.catalogued,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogLog.find,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogRel.ofCatalog,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogRel.find,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedDecl.lookup,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogRel.lookup,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.Promotes.trans,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TrustedCatalogRel.promote,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.IllTypedPending.trustedCatalogRel,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WellTypedPromotion.promotes,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- G1d's world-based concrete-state invariant.  Loading stays
  -- representation-only, promotion requires a fresh WF witness, and the
  -- fixed-world Hoare roots pin no-promotion behavior on both outcomes.
  { root := ``Ix.Tc.TcStateWF.of_consts_eq,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcStateWF.load,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcStateWF.promote,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcStateWF.find?,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcInv.find?,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.IllTypedPending.tcInv_pending_but_not_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.tick.tcStateWF,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.instantiateUnivParams.tcStateWF,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- G2a's explicit ambient-inductive assumption boundary.  Audit every
  -- oracle projection so adding a field changes this manifest, then pin the
  -- constructive Nat model and its adversarial loaded-state witness.
  { root := ``Ix.Tc.RawInductiveConstRel.mono,
    standardAxioms := standard },
  { root := ``Ix.Tc.RawRecursorRuleRel.mono,
    standardAxioms := standard },
  { root := ``Ix.Tc.InductiveOracle.members,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.nonempty,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.fresh,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.after,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.envLE,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.blockWF,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.translateBlock,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.recursorFacts,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveOracle.catalogued,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.oracle,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.nat_lookup_good,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.badDecl_not_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.acceptance,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },

  -- G2b's C1--C3 consumer path.  These roots resolve exact concrete
  -- constants through trusted-world provenance and are mechanically barred
  -- from depending on the legacy whole-environment translation.
  { root := ``Ix.Tc.TrustedConstRel.mono,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.TrustedConstRel.trKExprS_const,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.TrustedCatalogRel.resolve,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.TcStateWF.resolve,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.TcInv.resolve,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.natResolved,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.natReferenceTranslates,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.bad_not_resolved,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.natResolvedInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },

  -- G4's lookup isolation, exhaustive semantic-cache provenance, monotone
  -- warm-world transport, and transactional public-check error boundary.
  { root := ``Ix.Tc.PendingDecl.lookup_isolation,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheEntry.SupportedBy.mono },
  { root := ``Ix.Tc.CacheAuthority.stable_mono,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheProvenance.mono,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheProvenance.pending_isolation_stable,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.KEnv.restoreBlockCheckResultsOnError_origin,
    standardAxioms := standard },
  { root := ``Ix.Tc.CacheInvariant.mono,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.insertWhnf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.insertWhnfNoDelta,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.insertWhnfNoDeltaCheap,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.insertWhnfCore,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.insertWhnfCoreCheap,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.of_intern_update,
    standardAxioms := standardWithoutChoice,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.clearReductionCaches,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.restoreCheckCachesOnError,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.isolateCheckErrors_error,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.TcM.reset_cache_frame,
    standardAxioms := standard,
    nativeAxioms := #[nativeAxiom `Blake3
      `Blake3.HasherOps.hash._native.native_decide.ax_1] },
  { root := ``Ix.Tc.KernelStateWF.pendingCacheIsolation,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.KernelStateWF.restoreCheckCachesOnError,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.warmCache_worldTransport,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.warmCache_cannotResolvePending,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.cacheAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },

  -- K1's concrete Theory reduction meaning, exact five-way cache overlay,
  -- and real ambient-Nat warm-hit witness.  The only sorries are the already
  -- named upstream inductive-environment boundary.
  { root := ``Ix.Tc.WhnfMeaning.refl,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfMeaning.symm,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfMeaning.mono,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.ExprCacheKind.isWhnf_iff },
  { root := ``Ix.Tc.WhnfCacheValid.mono,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfCacheValid.expr,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheProvenance.whnfMeaning,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.whnfHit,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.supportExpr_whnfMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.warmHit_whnfMeaning,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.RecM.tryReduceNative_noAccel,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.tryReduceBitvec_noAccel,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryReduceDecidable_noAccel,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.tryReduceFinValDecidableRec_noAccel,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.WhnfTheory.exprWF,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.WhnfTheory.transMeaning,
    standardAxioms := standard,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RawProjRel.none_ok,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.TcM.ctxAddrForLbr_zero,
    standardAxioms := standard, nativeAxioms := contextNative },
  { root := ``Ix.Tc.TcM.whnfKey_closed,
    standardAxioms := standard, nativeAxioms := contextNative },
  { root := ``Ix.Tc.ContextKeyFrame.whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.ctxAddrForLbr_wf,
    standardAxioms := standard, nativeAxioms := contextNative },
  { root := ``Ix.Tc.TcM.whnfKey_wf,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.whnfKey_matches_wf,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  -- K1c: exact intern-only framing, execution-indexed simultaneous
  -- substitution, and the production one-argument beta path.
  { root := ``Ix.Tc.InternUpdateFrame.whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.runIntern_whnf_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.runIntern_whnf_eval,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.simulSubst_whnf_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.simulSubst_whnf_eval,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfMeaning.beta,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.WhnfMeaning.betaSimul,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreLeaf.eval,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_betaOne,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_leaf,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_betaOne,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_betaOne_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_leaf_wf,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.warmStateInvAccelerated,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.warmKey_matches_wf,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.whnfCoreConst_noAccel_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaIdentityMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaSimulSpec,
    standardAxioms := standardWithoutQuot, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.AmbientNat.betaSimulMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaWalker_eval,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.AmbientNat.betaResultMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaCoreUncached_eval,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.AmbientNat.betaCoreUncached_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  -- K1d: both production zeta branches, including the legacy lifting walk,
  -- mixed-context semantic lookup, bounded driver, and inhabited fixtures.
  { root := ``Ix.Tc.CtxRecon.lctxFindLetVal,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TcM.lookupLetVal_eval,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RunAssumptions.lift_whnf_wf,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RunAssumptions.lift_whnf_eval,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfMeaning.zetaVar,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.WhnfMeaning.zetaFVar,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_varZeta,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_fvarZeta,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_nextLeaf,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_varZeta,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_fvarZeta,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_varZeta_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_fvarZeta_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.AmbientNat.bvarZetaLiftSpec,
    standardAxioms := standardWithoutQuot, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.AmbientNat.bvarZetaLookupEval,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.AmbientNat.bvarZetaMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.bvarZetaCoreUncachedEval,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.AmbientNat.bvarZetaAcceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fvarZetaMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fvarZetaCoreUncachedEval,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.AmbientNat.fvarZetaAcceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  -- K1e: exact projection/iota branches and bounded-driver composition.
  -- Semantic success is conditional on an explicit translated-source oracle;
  -- the two hostile fixtures prove that raw helper success cannot replace it.
  { root := ``Ix.Tc.WhnfMeaning.projection,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.WhnfMeaning.registeredDefEq,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveReductionOracle.projection,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.InductiveReductionOracle.iota,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_projection,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsStep_iota,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_projection,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_iota,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_projection_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsUncached_iota_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.projectionReduceEval,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.projectionCoreEval,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.projectionSource_not_translated,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.projectionAdversarialWitness,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.iotaStateInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.iotaTryEval,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.iotaCoreEval,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.iotaSource_not_translated,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.iotaAdversarialWitness,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  -- K1f: arbitrary-length structural traces compose exact production
  -- execution, fixed-world/context invariants, and local Theory meanings.
  -- The inhabited fixture takes two `.next` steps before its leaf; the
  -- hostile zero-fuel witness cannot be certified as a successful trace.
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.no_zero,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.eval,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.initialInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.finalInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.meaning,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.uncached_eval,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreTrace.uncached_acceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.AmbientNat.structuralNatLit_type,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralWhnfTheory,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopStateInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopSourceMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopBetaMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopFVarStep,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopBetaStep,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopTrace,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopAcceptance,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := typingDebt,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.structuralLoopZeroFuel,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  -- K1g: the public structural entry point's keyed body has exact full,
  -- cheap, miss, hit, and transient equations.  Misses require both an
  -- execution-indexed trace and universal provenance before insertion;
  -- hits require the physical entry, semantic invariant, and executed key
  -- match.  The Nat fixture runs cold-to-warm in both isolated partitions.
  { root := ``Ix.Tc.RecM.WhnfCoreNonLeaf.enter,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_varNotLet,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_varEnter,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfCoreKeyedEntry.eval,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsNonLeaf_fullHit,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsNonLeaf_cheapHit,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsNonLeaf_fullMiss,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsNonLeaf_cheapMiss,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlagsNonLeaf_transient,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfCoreCacheUpdate.full_whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfCoreCacheUpdate.cheap_whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_fullHit_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_cheapHit_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_fullMiss_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_cheapMiss_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfCoreWithFlags_transient_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.AmbientNat.betaArgMeaning,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullCoreProvenance,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.cheapCoreProvenance,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.coreCacheFreshStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullCoreWarmStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.bothCoreWarmStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.coreCacheKey_eval,
    standardAxioms := standard, nativeAxioms := contextNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.coreCacheKey_matches,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaTransientFalse,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaWalker_eval_state,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaStep_state,
    standardAxioms := standard, nativeAxioms := levelNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.coreCacheTrace,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullCoreColdAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullCoreWarmAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.cheapCorePolicyMissAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.cheapCoreWarmAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.coreCachePolicyIsolation,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  -- K1h: no-delta and full-WHNF now have execution-indexed bounded traces,
  -- exact public-prefix/cache/fuel equations, provenance-checked insertion,
  -- and semantic hit/miss acceptance.  The Nat fixture executes all nested
  -- cache layers, proves the cold call consumes exactly one fuel unit, and
  -- proves the warm public call preserves the entire state.
  { root := ``Ix.Tc.WhnfStateInv.of_semantic_fields_eq,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.TcM.stepTrace_disabled,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.TcM.bumpStats_disabled,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.TcM.tick_success,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.no_zero,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.eval,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.initialInv,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.finalInv,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.meaning,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.uncached_eval,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfNoDeltaTrace.uncached_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.no_zero,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.eval,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.initialInv,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.finalInv,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.meaning,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.uncached_eval,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfFullTrace.uncached_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.WhnfDriverNonLeaf.noDelta_enter,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfDriverNonLeaf.full_enter,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfDriverEntry.noDelta_eval,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfDriverEntry.full_eval,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModePrefix_disabled,
    standardAxioms := standard },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeMissCharge_disabled,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_fullHit,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_cheapHit,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_fullMiss,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_cheapMiss,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_stuck,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_transient,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImplNonLeaf_nativeNoInsert,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.WhnfDriverCacheUpdate.noDelta_whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfDriverCacheUpdate.noDeltaCheap_whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfDriverCacheUpdate.full_whnfStateInv,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_fullHit_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_cheapHit_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_fullMiss_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_cheapMiss_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_stuck_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfNoDeltaImpl_transient_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeNonLeaf_hit,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeNonLeaf_miss,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeNonLeaf_stuck,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeNonLeaf_transient,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccModeNonLeaf_nativeNoInsert,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccMode_hit_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccMode_miss_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccMode_stuck_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnfWithNatSuccMode_transient_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt },
  { root := ``Ix.Tc.RecM.whnf_public_eq_whnfWithNatSuccMode,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.AmbientNat.betaNoDeltaStep,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullNoDeltaProvenance,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfProvenance,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullNoDeltaWarmStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.noDeltaTrace,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullNoDeltaColdAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullNoDeltaWarmAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.noDeltaCachePolicyIsolation,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfChargedStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfPrefixCold,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfMissCharge,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfCharged_noDeltaHit,
    standardAxioms := standard, nativeAxioms := inferNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.betaFullWhnfStep,
    standardAxioms := standard, nativeAxioms := inferNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfTrace,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfWarmStateInv,
    standardAxioms := standard, nativeAxioms := expressionNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfColdAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := typingDebt,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfWarmAcceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfFuelDiscipline,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.fullWhnfCacheLayering,
    standardAxioms := standard, nativeAxioms := expressionNative,
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.WhnfPost.refl,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WF.bind,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.runBounded_wf,
    standardAxioms := standard,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.WhnfLeaf.eval,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnf_leaf_wf,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.RecM.whnf_leaf_wf_of_theory,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct, addInductWF] },
  { root := ``Ix.Tc.AmbientNat.noAccelStateInv,
    standardAxioms := standard, nativeAxioms := levelNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.whnfLeaf_noAccel_wf,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.AmbientNat.whnfLeaf_noAccel_acceptance,
    standardAxioms := standard, nativeAxioms := inferNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.TcM.whnfKey_fst,
    standardAxioms := standard, nativeAxioms := contextNative },
  { root := ``Ix.Tc.WhnfContextKeys.Matches.sourceAddr,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheProvenance.whnfMeaningOfMatches,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.CacheInvariant.whnfHitOfMatches,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct] },
  { root := ``Ix.Tc.AmbientNat.warmKey_matches,
    standardAxioms := standard, nativeAxioms := contextNative,
    sorryOrigins := #[inductiveWF, addInduct],
    forbiddenDependencies := legacyWholeEnv },
  { root := ``Ix.Tc.methodsN_zero,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_whnf,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_whnfCore,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_whnfMode,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_whnfCoreFlags,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_infer,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsN_succ_isDefEq,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.methodsOut_whnf,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.methodsOut_whnfCore,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.methodsOut_whnfMode,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.methodsOut_whnfCoreFlags,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.methodsOut_infer,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.methodsOut_isDefEq,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.TcM.runRec_apply,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.runRec_directInfer_zero,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.whnf_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.whnfCore_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.whnfNoDelta_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.infer_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.isDefEq_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.ensureSort_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.TcM.ensureForall_eq_runRec,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.unfoldConstValue_equation,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.tryDeltaUnfold_equation,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.deltaUnfoldOne_equation,
    standardAxioms := standard, nativeAxioms := levelNative },
  { root := ``Ix.Tc.RecM.applyIotaArg_false,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.applyIotaArg_true_lam,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.isNatLiteralRecursorApp_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isTransientNatLiteralWork_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.cleanupNatOffsetMajor_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.projectDecidableFinValMinor_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryReduceFinValDecidableRec_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryReduceProjectionDefinition_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.natRecLiteralParts_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isNatStuckRecursorAddr_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isStuckNatPredicateProbe_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.bitvecOfNatArgs_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.charOfNatExpr_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryReduceString_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.discoverBlockInductives_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.runBounded_zero,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.runBounded_succ,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.consumeBetaLams_equation,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.consumeBetaLamsFuel_zero,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.consumeBetaLamsFuel_succ,
    standardAxioms := standardWithoutQuot,
    nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.compareRank_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.RecM.isNatLike_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isNatZero_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.natSuccOf_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.isBoolTrue_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isDelta_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isRegular_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.defRankId_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.infer_eq_inferWith,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.inferCall_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.inferOnlyCall_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.isDefEqCall_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.whnfRec_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.whnfModeRec_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.whnfCoreFlagsRec_run,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.whnf_eq_whnfWithNatSuccMode,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfCore_eq_whnfCoreWithFlags,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.whnfNoDelta_eq_whnfNoDeltaImpl,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.ensureSortDirect_equation,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.ensureForallDirect_equation,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.peelProjForall_equation,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.checkNoUnsafeRefs_equation,
    standardAxioms := standard },
  { root := ``Ix.Tc.RecM.checkNoUnsafeRefs_go_nil,
    standardAxioms := standard },
  { root := ``Ix.Tc.RecM.checkNoUnsafeRefs_go_app,
    standardAxioms := standard },
  { root := ``Ix.Tc.RecM.validateUnivParamsSeen_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.validateUnivParamsSeen_go_nil,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.validateUnivParamsSeen_go_max,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.validateExprWellScoped_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.validateExprWellScoped_go_nil,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.validateExprWellScoped_go_app,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.peelRuleIhForalls_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.RecM.checkPositivityDomain_equation,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.checkPositivityDomainFuel_zero,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.checkNestedCtorFieldsFuel_zero,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.checkNestedCtorFieldsLoopFuel_zero,
    standardAxioms := standard, nativeAxioms := inferNative },
  { root := ``Ix.Tc.RecM.countForalls_equation,
    standardAxioms := standard, nativeAxioms := inferNative },
  -- The complete checker dispatch is transparent now; these roots pin its
  -- exact production trust boundary in addition to the local equations.
  { root := ``Ix.Tc.RecM.checkInductive,
    standardAxioms := standard, nativeAxioms := inductiveNative },
  { root := ``Ix.Tc.RecM.checkRecursorMemberImpl,
    standardAxioms := standard, nativeAxioms := inductiveNative },
  { root := ``Ix.Tc.RecM.checkConst,
    standardAxioms := standard, nativeAxioms := inductiveNative },
  { root := ``Ix.Tc.TcM.checkConst,
    standardAxioms := standard, nativeAxioms := inductiveNative },
  { root := ``Ix.Tc.extractNatValue_app_const_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.extractNatValue_nat_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.projectionDefinitionInfo_go_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.EquivManager.find_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.EquivManager.find_go_zero },
  { root := ``Ix.Tc.EquivManager.find_go_succ },
  { root := ``Ix.Tc.LocalContext.truncate_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.LocalContext.truncate_go_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.LocalContext.truncate_go_succ,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TcM.restoreDepth_apply,
    standardAxioms := standard, nativeAxioms := blake3Native },
  { root := ``Ix.Tc.TcM.restoreDepth_go_zero,
    standardAxioms := standard, nativeAxioms := blake3Native },
  { root := ``Ix.Tc.TcM.ctxSuffixNeed_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TcM.ctxSuffixNeed_succ,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.TcM.ctxSuffixNeed_of_fixed,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.render_equation,
    standardAxioms := standard },
  { root := ``Ix.Tc.KExpr.renderFuel_zero,
    standardAxioms := standard },
  { root := ``Ix.Tc.RecM.natOffset_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.natOffsetOrZero_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.evalNatOffsetLiteral_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.natOffsetFuel_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.evalNatOffsetLiteralFuel_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryEvalNatValueForPred_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.RecM.tryEvalNatValueForPredFuel_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.compareKUniv_succ_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.compareKUniv_max_equation,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.mergeSorted_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.mergeSorted_go_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.sortByCompare_equation,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.sortByCompareFuel_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.sortKConstsRefineFuel_zero,
    standardAxioms := standard, nativeAxioms := expressionNative },
  { root := ``Ix.Tc.KExpr.treeSize_pos,
    standardAxioms := propextOnly },
  { root := ``Ix.Tc.exprMentionsAddr_equation,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.exprMentionsAddr_go_nil,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.exprMentionsAddr_go_app,
    standardAxioms := standardWithoutChoice },
  { root := ``Ix.Tc.exprMentionsAddr_go_const,
    standardAxioms := standardWithoutChoice }
]

run_cmd Ix.Tc.Verify.Audit.check roots

end Ix.Tc.Verify.Audit.Completed
