// Generated by Aiur.TraceCuda; regenerate from Aiur bytecode.
use crate::trace_codegen::cuda::CudaLibrary;
unsafe extern "C" {
  fn aiur_trace_blake3_contract() -> *const u8;
  pub(super) fn aiur_trace_blake3_0(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
}
pub static CUDA: CudaLibrary = unsafe { CudaLibrary::new([244, 15, 191, 184, 67, 8, 78, 20, 119, 70, 132, 166, 36, 38, 181, 21, 154, 23, 223, 26, 42, 131, 221, 16, 233, 63, 222, 10, 252, 23, 145, 179], aiur_trace_blake3_contract, &[
Some(aiur_trace_blake3_0)
], &[162]) };
