// Generated by Aiur.TraceCuda; regenerate from Aiur bytecode.
use crate::trace_codegen::cuda::CudaLibrary;
unsafe extern "C" {
  fn aiur_trace_blake3_contract() -> *const u8;
  fn aiur_trace_blake3_schema() -> *const u8;
  pub(super) fn aiur_trace_blake3_0(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
}
pub static CUDA: CudaLibrary = unsafe { CudaLibrary::new([150, 101, 248, 224, 67, 209, 56, 216, 146, 162, 51, 114, 82, 15, 10, 181, 15, 234, 113, 117, 51, 141, 70, 70, 235, 90, 62, 221, 45, 109, 215, 133], aiur_trace_blake3_contract, aiur_trace_blake3_schema, &[
Some(aiur_trace_blake3_0)
], &[162], &[176]) };
