// Generated by Aiur.TraceCuda; regenerate from Aiur bytecode.
use crate::trace_codegen::cuda::CudaLibrary;
unsafe extern "C" {
  fn aiur_trace_fixtures_contract() -> *const u8;
  fn aiur_trace_fixtures_schema() -> *const u8;
  pub(super) fn aiur_trace_fixtures_0(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_1(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_2(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_3(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_4(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_5(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_6(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_7(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_8(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_9(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_10(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_11(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_12(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_14(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_15(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_16(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_17(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_18(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_19(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_20(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
  pub(super) fn aiur_trace_fixtures_21(device: i32, seeds: *const u8, encoding: u32, real: usize, rows: usize, width: usize, selectors: usize, auxiliaries: usize, output: *mut u64) -> i32;
}
pub static CUDA: CudaLibrary = unsafe { CudaLibrary::new([213, 235, 108, 220, 115, 159, 51, 229, 206, 4, 193, 234, 222, 143, 95, 162, 130, 93, 210, 36, 144, 208, 151, 97, 95, 24, 25, 23, 225, 30, 236, 67], aiur_trace_fixtures_contract, aiur_trace_fixtures_schema, &[
Some(aiur_trace_fixtures_0),
Some(aiur_trace_fixtures_1),
Some(aiur_trace_fixtures_2),
Some(aiur_trace_fixtures_3),
Some(aiur_trace_fixtures_4),
Some(aiur_trace_fixtures_5),
Some(aiur_trace_fixtures_6),
Some(aiur_trace_fixtures_7),
Some(aiur_trace_fixtures_8),
Some(aiur_trace_fixtures_9),
Some(aiur_trace_fixtures_10),
Some(aiur_trace_fixtures_11),
Some(aiur_trace_fixtures_12),
None,
Some(aiur_trace_fixtures_14),
Some(aiur_trace_fixtures_15),
Some(aiur_trace_fixtures_16),
Some(aiur_trace_fixtures_17),
Some(aiur_trace_fixtures_18),
Some(aiur_trace_fixtures_19),
Some(aiur_trace_fixtures_20),
Some(aiur_trace_fixtures_21)
], &[3, 3, 13, 3, 6, 2, 3, 7, 3, 3, 6, 15, 1, 0, 3, 2, 1, 162, 5, 2, 13, 17], &[24, 16, 24, 24, 40, 16, 24, 48, 24, 24, 48, 112, 8, 0, 24, 16, 8, 176, 40, 16, 24, 136]) };
