#!/usr/bin/env python3
"""Turn a TSV of imported files into `Tests/Ix/Kernel/ImportManifest.lean` rows.

Input: a TSV with the columns

    source_path  source_sha256  dest_path  dest_sha256  transformation

one row per imported file. A header line whose first field is `source_path`
and lines starting with `#` are skipped. `transformation` is `verbatim` for a
byte-identical copy, `rewritten` for the output of `scripts/vendor-conleche.py`
(the vendoring rewrite, `vendor-conleche.py rows` prints such rows); any
other text is the summary of an adapted file.

Output: `PortRow` literals (`⟨source, target, sourceSha, targetSha,
.verbatim⟩`, `.rewritten` or `.adapted "…"`), sorted by destination, one per line. With
`--splice MANIFEST` they replace the generated region of `conLecheRows`
(between the `-- BEGIN con-leche rows` and `-- END con-leche rows` markers);
otherwise they are printed.

Checks, before writing anything:
- every hash is 64 lowercase hex digits, paths are relative, and no
  destination appears twice;
- a verbatim row has equal source and destination hashes;
- `--check-dest ROOT` recomputes each destination hash from the tree at ROOT;
- `--check-source CHECKOUT --rev REV` recomputes each source hash with
  `git -C CHECKOUT show REV:PATH`, and each rewritten row's destination hash
  by `scripts/vendor-conleche.py` from that source.

Stdlib only; run from the repository root. `kernel-provenance` remains the
gate, and this tool only writes its input.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys

BEGIN = "-- BEGIN con-leche rows (generated by scripts/provenance-rows.py)"
END = "-- END con-leche rows"
SHA = re.compile(r"[0-9a-f]{64}")


def lean_string(text: str) -> str:
    out = []
    for char in text:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\t":
            out.append("\\t")
        elif ord(char) < 0x20:
            out.append(f"\\x{ord(char):02x}")
        else:
            out.append(char)
    return '"' + "".join(out) + '"'


def read_rows(path: Path) -> list[tuple[str, str, str, str, str]]:
    rows = []
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split("\t")
        if fields[0] == "source_path":
            continue
        if len(fields) != 5:
            raise SystemExit(f"{path}:{number}: expected 5 tab-separated fields, found {len(fields)}")
        source, source_sha, dest, dest_sha, transformation = (field.strip() for field in fields)
        for sha in (source_sha, dest_sha):
            if not SHA.fullmatch(sha):
                raise SystemExit(f"{path}:{number}: not a SHA-256: {sha!r}")
        for file in (source, dest):
            if not file or file.startswith("/") or ".." in Path(file).parts:
                raise SystemExit(f"{path}:{number}: not a relative path: {file!r}")
        if not transformation:
            raise SystemExit(f"{path}:{number}: empty transformation (use 'verbatim')")
        if transformation == "verbatim" and source_sha != dest_sha:
            raise SystemExit(f"{path}:{number}: verbatim row with different hashes: {dest}")
        rows.append((source, source_sha, dest, dest_sha, transformation))
    seen: set[str] = set()
    for row in rows:
        if row[2] in seen:
            raise SystemExit(f"{path}: destination listed twice: {row[2]}")
        seen.add(row[2])
    return sorted(rows, key=lambda row: row[2])


def check_dest(rows, root: Path) -> None:
    for _, _, dest, dest_sha, _ in rows:
        actual = hashlib.sha256((root / dest).read_bytes()).hexdigest()
        if actual != dest_sha:
            raise SystemExit(f"destination hash mismatch: {dest}: recorded {dest_sha}, tree {actual}")


def check_source(rows, checkout: Path, rev: str) -> None:
    for source, source_sha, dest, dest_sha, transformation in rows:
        shown = subprocess.run(["git", "-C", str(checkout), "show", f"{rev}:{source}"],
                               capture_output=True, check=False)
        if shown.returncode != 0:
            raise SystemExit(f"cannot read {source} at {rev}: {shown.stderr.decode(errors='replace')}")
        actual = hashlib.sha256(shown.stdout).hexdigest()
        if actual != source_sha:
            raise SystemExit(f"source hash mismatch: {source}: recorded {source_sha}, {rev} {actual}")
        if transformation == "rewritten":
            hashed = subprocess.run(["python3", "scripts/vendor-conleche.py", "hash", str(checkout),
                                     f"{rev}:{source}"], capture_output=True, text=True, check=True)
            _, rewritten, mapped, _ = hashed.stdout.split()
            if (rewritten, mapped) != (dest_sha, dest):
                raise SystemExit(f"rewrite mismatch: {source}: the script gives {mapped} {rewritten}, "
                                 f"recorded {dest} {dest_sha}")


def render(rows) -> list[str]:
    lines = []
    for index, (source, source_sha, dest, dest_sha, transformation) in enumerate(rows):
        kind = (".verbatim" if transformation == "verbatim" else ".rewritten"
                if transformation == "rewritten" else f".adapted {lean_string(transformation)}")
        comma = "," if index + 1 < len(rows) else ""
        lines.append(f"  ⟨{lean_string(source)}, {lean_string(dest)}, {lean_string(source_sha)}, "
                     f"{lean_string(dest_sha)}, {kind}⟩{comma}")
    return lines


def splice(manifest: Path, lines: list[str]) -> None:
    text = manifest.read_text(encoding="utf-8").split("\n")
    try:
        begin = text.index(BEGIN)
        end = text.index(END)
    except ValueError:
        raise SystemExit(f"{manifest}: generated-region markers not found")
    if end < begin:
        raise SystemExit(f"{manifest}: generated-region markers out of order")
    manifest.write_text("\n".join(text[: begin + 1] + lines + text[end:]), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("tsv", type=Path)
    parser.add_argument("--splice", type=Path, metavar="MANIFEST")
    parser.add_argument("--check-dest", type=Path, metavar="ROOT")
    parser.add_argument("--check-source", type=Path, metavar="CHECKOUT")
    parser.add_argument("--rev")
    args = parser.parse_args()
    if (args.check_source is None) != (args.rev is None):
        parser.error("--check-source and --rev go together")
    rows = read_rows(args.tsv)
    if args.check_dest is not None:
        check_dest(rows, args.check_dest)
    if args.check_source is not None:
        check_source(rows, args.check_source, args.rev)
    lines = render(rows)
    if args.splice is not None:
        splice(args.splice, lines)
        print(f"{len(rows)} rows spliced into {args.splice}", file=sys.stderr)
    else:
        print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
