//! Expressions with optional metadata.
//!
//! `KExpr<M>` is an Arc-wrapped expression. Each variant carries an `ExprInfo<M>`
//! with its blake3 hash, substitution annotations, and mdata.

use std::fmt;
use std::sync::Arc;

use crate::ix::address::Address;
use crate::ix::env::{
  BinderInfo, DataValue, EALL, EAPP, EFVAR, ELAM, ELET, ENAT, EPRJ, EREF,
  ESORT, ESTR, EVAR, Name,
};
use lean_ffi::nat::Nat;

use super::env::Addr;
use super::id::KId;
use super::level::KUniv;
use super::mode::{KernelMode, MetaDisplay};

/// Expression. Thin Arc wrapper — cheap to clone, O(1) identity via `Arc::ptr_eq`.
#[derive(Clone, Debug)]
pub struct KExpr<M: KernelMode>(Arc<ExprData<M>>);

/// A single mdata layer: key-value pairs from Lean's `Expr.mdata`.
pub type MData = Vec<(Name, DataValue)>;

/// Per-expression metadata: blake3 hash, substitution annotations, and mdata.
#[derive(Clone, Debug)]
pub struct ExprInfo<M: KernelMode> {
  /// Blake3 hash of semantic expression content. Metadata fields are stored
  /// for diagnostics/egress but do not contribute to the hash.
  pub addr: Addr,
  /// Loose bound variable range: upper bound on free de Bruijn indices.
  pub lbr: u64,
  /// Count of free `Var(0)` occurrences.
  pub count_0: u64,
  /// Whether any [`ExprData::FVar`] occurrence is reachable in this expression.
  ///
  /// FVars (free variables) are leaves carrying a unique [`FVarId`]; they are
  /// introduced when a binder is opened during inference / def-eq, and
  /// re-abstracted into de Bruijn binders before the result escapes the
  /// open scope. The flag lets callers (substitution, `abstract_fvars`,
  /// soundness assertions) skip walks when no fvars are reachable.
  pub has_fvars: bool,
  /// Lean mdata annotations. Semantically transparent, erased in Anon mode.
  pub mdata: M::MField<Vec<MData>>,
}

/// Per-`TypeChecker` unique identifier for a free variable. Generated by
/// [`crate::ix::kernel::lctx::NameGenerator`] and embedded into the blake3
/// content hash of [`ExprData::FVar`] nodes, so that two distinct fvars hash
/// distinctly. This is the soundness lever that lets cache keys be the
/// expression hash alone (no separate local-context key) — see the kernel
/// fvar plan and `refs/lean4/src/kernel/type_checker.h:27`.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, PartialOrd, Ord)]
pub struct FVarId(pub u64);

impl fmt::Display for FVarId {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(f, "fv${}", self.0)
  }
}

/// Expression data. Each variant carries its [`ExprInfo<M>`].
#[derive(Clone, Debug)]
pub enum ExprData<M: KernelMode> {
  Var(u64, M::MField<Name>, ExprInfo<M>),
  /// Free variable: opaque identity from the active local context.
  /// `FVarId` participates in the content hash; the user-facing `Name` is
  /// preserved (in Meta mode) for diagnostics. The looked-up type lives in
  /// the active [`crate::ix::kernel::lctx::LocalContext`], not on the node.
  FVar(FVarId, M::MField<Name>, ExprInfo<M>),
  Sort(KUniv<M>, ExprInfo<M>),
  Const(KId<M>, Box<[KUniv<M>]>, ExprInfo<M>),
  App(KExpr<M>, KExpr<M>, ExprInfo<M>),
  Lam(M::MField<Name>, M::MField<BinderInfo>, KExpr<M>, KExpr<M>, ExprInfo<M>),
  All(M::MField<Name>, M::MField<BinderInfo>, KExpr<M>, KExpr<M>, ExprInfo<M>),
  /// Let binding: name, type, value, body, non_dep flag.
  Let(M::MField<Name>, KExpr<M>, KExpr<M>, KExpr<M>, bool, ExprInfo<M>),
  /// Projection: struct type id, field index, struct value.
  Prj(KId<M>, u64, KExpr<M>, ExprInfo<M>),
  Nat(Nat, Address, ExprInfo<M>),
  Str(String, Address, ExprInfo<M>),
}

impl<M: KernelMode> ExprData<M> {
  pub fn info(&self) -> &ExprInfo<M> {
    match self {
      ExprData::Var(.., i)
      | ExprData::FVar(.., i)
      | ExprData::Sort(.., i)
      | ExprData::Const(.., i)
      | ExprData::App(.., i)
      | ExprData::Lam(.., i)
      | ExprData::All(.., i)
      | ExprData::Let(.., i)
      | ExprData::Prj(.., i)
      | ExprData::Nat(.., i)
      | ExprData::Str(.., i) => i,
    }
  }
}

impl<M: KernelMode> KExpr<M> {
  pub fn new(data: ExprData<M>) -> Self {
    KExpr(Arc::new(data))
  }

  pub fn data(&self) -> &ExprData<M> {
    &self.0
  }

  pub fn info(&self) -> &ExprInfo<M> {
    self.data().info()
  }

  pub fn addr(&self) -> &Addr {
    &self.info().addr
  }

  pub fn lbr(&self) -> u64 {
    self.info().lbr
  }

  pub fn count_0(&self) -> u64 {
    self.info().count_0
  }

  /// Whether any [`ExprData::FVar`] occurrence is reachable. Computed at
  /// construction time and propagated via OR through composite nodes, so
  /// the check is O(1) per call.
  pub fn has_fvars(&self) -> bool {
    self.info().has_fvars
  }

  pub fn mdata(&self) -> &M::MField<Vec<MData>> {
    &self.info().mdata
  }

  /// Content-addressed key for cache lookups. Returns the blake3 hash
  /// by value — `Addr` is `Copy`, so this is a 32-byte memcpy.
  pub fn hash_key(&self) -> Addr {
    *self.addr()
  }

  pub fn ptr_eq(&self, other: &KExpr<M>) -> bool {
    Arc::ptr_eq(&self.0, &other.0)
  }

  /// Content-addressed equality with a layered fast path.
  ///
  /// 1. `ptr_eq` on the outer `KExpr` Arc — fires when both sides
  ///    came through the [`InternTable`](super::env::InternTable).
  /// 2. 32-byte Blake3 hash compare — sound on its own (collisions
  ///    require an adversarial preimage attack), and a single AVX2
  ///    cycle on modern x86. Earlier revisions interposed an
  ///    `Arc::ptr_eq` fast path on a process-globally-interned `Addr`,
  ///    but that intern table dominated RSS at mathlib scale; the
  ///    pure-content compare keeps the same correctness with no
  ///    process-global state.
  pub fn hash_eq(&self, other: &KExpr<M>) -> bool {
    self.ptr_eq(other) || self.addr() == other.addr()
  }
}

impl<M: KernelMode> PartialEq for KExpr<M> {
  fn eq(&self, other: &Self) -> bool {
    self.hash_eq(other)
  }
}

impl<M: KernelMode> Eq for KExpr<M> {}

fn no_mdata<M: KernelMode>() -> M::MField<Vec<MData>> {
  M::meta_field(vec![])
}

fn mk_info<M: KernelMode>(
  addr: Addr,
  lbr: u64,
  count_0: u64,
  has_fvars: bool,
  mdata: M::MField<Vec<MData>>,
) -> ExprInfo<M> {
  ExprInfo { addr, lbr, count_0, has_fvars, mdata }
}

// =============================================================================
// Hash-first interning: each `*_mdata` constructor is split into a
// hash-only function (no allocation) and a `*_mdata_with_addr` builder
// that takes a precomputed canonical [`Addr`]. The plain `*_mdata` form is
// kept as a convenience wrapper for callers that don't pre-check the
// intern table.
//
// Hot-path callers in `ingress.rs` use the split form so they can ask
// `InternTable::try_get_expr(&hash)` *before* paying the
// blake3-hash + `intern_addr` + `Arc<ExprData>` allocation cost — a
// significant win because >60% of constructed values are immediately
// discarded for an existing canonical Arc on the intern table.
// =============================================================================

impl<M: KernelMode> KExpr<M> {
  pub fn var(idx: u64, name: M::MField<Name>) -> Self {
    Self::var_mdata(idx, name, no_mdata::<M>())
  }

  /// Compute the content hash for [`KExpr::var_mdata`] without allocating.
  ///
  /// `name` is descriptive metadata only and intentionally NOT hashed —
  /// two `Var(i)` nodes with different display names are content-equal,
  /// keeping hash equality alpha-invariant even in `Meta` mode.
  pub fn var_hash(
    idx: u64,
    _name: &M::MField<Name>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EVAR]);
    h.update(&idx.to_le_bytes());
    h.finalize()
  }

  pub fn var_mdata_with_addr(
    idx: u64,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info =
      mk_info::<M>(addr, idx + 1, if idx == 0 { 1 } else { 0 }, false, mdata);
    KExpr::new(ExprData::Var(idx, name, info))
  }

  pub fn fvar(id: FVarId, name: M::MField<Name>) -> Self {
    Self::fvar_mdata(id, name, no_mdata::<M>())
  }

  /// Compute the content hash for [`KExpr::fvar_mdata`] without allocating.
  /// Includes the [`FVarId`] so distinct fvars produce distinct hashes — the
  /// soundness lever for keying caches by expression alone. `name` is
  /// descriptive only and intentionally NOT hashed.
  pub fn fvar_hash(
    id: FVarId,
    _name: &M::MField<Name>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EFVAR]);
    h.update(&id.0.to_le_bytes());
    h.finalize()
  }

  pub fn fvar_mdata_with_addr(
    id: FVarId,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    // FVars are leaves: no loose bvars (lbr = 0), no Var(0) occurrences,
    // and `has_fvars` is true since this node *is* an fvar.
    let info = mk_info::<M>(addr, 0, 0, true, mdata);
    KExpr::new(ExprData::FVar(id, name, info))
  }

  pub fn fvar_mdata(
    id: FVarId,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::fvar_hash(id, &name, &mdata);
    Self::fvar_mdata_with_addr(id, name, mdata, addr)
  }

  pub fn var_mdata(
    idx: u64,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::var_hash(idx, &name, &mdata);
    Self::var_mdata_with_addr(idx, name, mdata, addr)
  }

  pub fn sort(u: KUniv<M>) -> Self {
    Self::sort_mdata(u, no_mdata::<M>())
  }

  pub fn sort_hash(
    u: &KUniv<M>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[ESORT]);
    h.update(u.addr().as_bytes());
    h.finalize()
  }

  pub fn sort_mdata_with_addr(
    u: KUniv<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Sort(u, mk_info::<M>(addr, 0, 0, false, mdata)))
  }

  pub fn sort_mdata(u: KUniv<M>, mdata: M::MField<Vec<MData>>) -> Self {
    let addr = Self::sort_hash(&u, &mdata);
    Self::sort_mdata_with_addr(u, mdata, addr)
  }

  pub fn cnst(id: KId<M>, univs: Box<[KUniv<M>]>) -> Self {
    Self::cnst_mdata(id, univs, no_mdata::<M>())
  }

  /// `id.addr` is the constant's content-address — its identity. The
  /// `id.name` field is display-only metadata, intentionally NOT hashed,
  /// so two references to the same address with different display names
  /// remain content-equal.
  pub fn cnst_hash(
    id: &KId<M>,
    univs: &[KUniv<M>],
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EREF]);
    h.update(id.addr.as_bytes());
    for u in univs.iter() {
      h.update(u.addr().as_bytes());
    }
    h.finalize()
  }

  pub fn cnst_mdata_with_addr(
    id: KId<M>,
    univs: Box<[KUniv<M>]>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Const(
      id,
      univs,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn cnst_mdata(
    id: KId<M>,
    univs: Box<[KUniv<M>]>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::cnst_hash(&id, &univs, &mdata);
    Self::cnst_mdata_with_addr(id, univs, mdata, addr)
  }

  pub fn app(f: KExpr<M>, a: KExpr<M>) -> Self {
    Self::app_mdata(f, a, no_mdata::<M>())
  }

  pub fn app_hash(
    f: &KExpr<M>,
    a: &KExpr<M>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EAPP]);
    h.update(f.addr().as_bytes());
    h.update(a.addr().as_bytes());
    h.finalize()
  }

  pub fn app_mdata_with_addr(
    f: KExpr<M>,
    a: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      f.lbr().max(a.lbr()),
      f.count_0() + a.count_0(),
      f.has_fvars() || a.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::App(f, a, info))
  }

  pub fn app_mdata(
    f: KExpr<M>,
    a: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::app_hash(&f, &a, &mdata);
    Self::app_mdata_with_addr(f, a, mdata, addr)
  }

  pub fn lam(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
  ) -> Self {
    Self::lam_mdata(name, bi, ty, body, no_mdata::<M>())
  }

  /// Compute the content hash for [`KExpr::lam_mdata`].
  ///
  /// Binder `name` and `bi` are display/elaboration metadata only and are
  /// intentionally NOT hashed. The kernel does not distinguish lambdas
  /// that differ only in binder name or binder info; this keeps hash
  /// equality structural and alpha-invariant in `Meta` mode (matching
  /// `Anon` mode where these fields are erased).
  pub fn lam_hash(
    _name: &M::MField<Name>,
    _bi: &M::MField<BinderInfo>,
    ty: &KExpr<M>,
    body: &KExpr<M>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[ELAM]);
    h.update(ty.addr().as_bytes());
    h.update(body.addr().as_bytes());
    h.finalize()
  }

  pub fn lam_mdata_with_addr(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(body.lbr().saturating_sub(1)),
      ty.count_0(),
      ty.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::Lam(name, bi, ty, body, info))
  }

  pub fn lam_mdata(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::lam_hash(&name, &bi, &ty, &body, &mdata);
    Self::lam_mdata_with_addr(name, bi, ty, body, mdata, addr)
  }

  pub fn all(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
  ) -> Self {
    Self::all_mdata(name, bi, ty, body, no_mdata::<M>())
  }

  /// See [`KExpr::lam_hash`] — binder `name`/`bi` intentionally not hashed.
  pub fn all_hash(
    _name: &M::MField<Name>,
    _bi: &M::MField<BinderInfo>,
    ty: &KExpr<M>,
    body: &KExpr<M>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EALL]);
    h.update(ty.addr().as_bytes());
    h.update(body.addr().as_bytes());
    h.finalize()
  }

  pub fn all_mdata_with_addr(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(body.lbr().saturating_sub(1)),
      ty.count_0(),
      ty.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::All(name, bi, ty, body, info))
  }

  pub fn all_mdata(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::all_hash(&name, &bi, &ty, &body, &mdata);
    Self::all_mdata_with_addr(name, bi, ty, body, mdata, addr)
  }

  pub fn let_(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
  ) -> Self {
    Self::let_mdata(name, ty, val, body, non_dep, no_mdata::<M>())
  }

  /// See [`KExpr::lam_hash`] — binder `name` and the cached `non_dep` flag
  /// are intentionally not hashed.
  pub fn let_hash(
    _name: &M::MField<Name>,
    ty: &KExpr<M>,
    val: &KExpr<M>,
    body: &KExpr<M>,
    _non_dep: bool,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[ELET]);
    h.update(ty.addr().as_bytes());
    h.update(val.addr().as_bytes());
    h.update(body.addr().as_bytes());
    h.finalize()
  }

  pub fn let_mdata_with_addr(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(val.lbr()).max(body.lbr().saturating_sub(1)),
      ty.count_0() + val.count_0(),
      ty.has_fvars() || val.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::Let(name, ty, val, body, non_dep, info))
  }

  pub fn let_mdata(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::let_hash(&name, &ty, &val, &body, non_dep, &mdata);
    Self::let_mdata_with_addr(name, ty, val, body, non_dep, mdata, addr)
  }

  pub fn prj(id: KId<M>, field: u64, val: KExpr<M>) -> Self {
    Self::prj_mdata(id, field, val, no_mdata::<M>())
  }

  /// `id.name` is display-only metadata, intentionally NOT hashed.
  pub fn prj_hash(
    id: &KId<M>,
    field: u64,
    val: &KExpr<M>,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[EPRJ]);
    h.update(id.addr.as_bytes());
    h.update(&field.to_le_bytes());
    h.update(val.addr().as_bytes());
    h.finalize()
  }

  pub fn prj_mdata_with_addr(
    id: KId<M>,
    field: u64,
    val: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info =
      mk_info::<M>(addr, val.lbr(), val.count_0(), val.has_fvars(), mdata);
    KExpr::new(ExprData::Prj(id, field, val, info))
  }

  pub fn prj_mdata(
    id: KId<M>,
    field: u64,
    val: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::prj_hash(&id, field, &val, &mdata);
    Self::prj_mdata_with_addr(id, field, val, mdata, addr)
  }

  pub fn nat(val: Nat, blob_addr: Address) -> Self {
    Self::nat_mdata(val, blob_addr, no_mdata::<M>())
  }

  pub fn nat_hash(
    blob_addr: &Address,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[ENAT]);
    h.update(blob_addr.as_bytes());
    h.finalize()
  }

  pub fn nat_mdata_with_addr(
    val: Nat,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Nat(
      val,
      blob_addr,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn nat_mdata(
    val: Nat,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::nat_hash(&blob_addr, &mdata);
    Self::nat_mdata_with_addr(val, blob_addr, mdata, addr)
  }

  pub fn str(val: String, blob_addr: Address) -> Self {
    Self::str_mdata(val, blob_addr, no_mdata::<M>())
  }

  pub fn str_hash(
    blob_addr: &Address,
    _mdata: &M::MField<Vec<MData>>,
  ) -> blake3::Hash {
    let mut h = blake3::Hasher::new();
    h.update(&[ESTR]);
    h.update(blob_addr.as_bytes());
    h.finalize()
  }

  pub fn str_mdata_with_addr(
    val: String,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Str(
      val,
      blob_addr,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn str_mdata(
    val: String,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = Self::str_hash(&blob_addr, &mdata);
    Self::str_mdata_with_addr(val, blob_addr, mdata, addr)
  }
}

/// Meta mode: shows names when available. Anon mode: positional/hash fallbacks.
impl<M: KernelMode> fmt::Display for KExpr<M> {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    fmt_expr(self, f, 0)
  }
}

fn fmt_expr<M: KernelMode>(
  e: &KExpr<M>,
  f: &mut fmt::Formatter<'_>,
  depth: usize,
) -> fmt::Result {
  if depth > 20 {
    return write!(f, "...");
  }
  match e.data() {
    ExprData::Var(idx, name, _) => {
      if name.has_meta() {
        name.meta_fmt(f)
      } else {
        write!(f, "#{idx}")
      }
    },
    ExprData::FVar(id, name, _) => {
      if name.has_meta() {
        name.meta_fmt(f)?;
        write!(f, "@{id}")
      } else {
        write!(f, "{id}")
      }
    },
    ExprData::Sort(u, _) => write!(f, "Sort {u}"),
    ExprData::Const(id, us, _) => {
      write!(f, "{id}")?;
      if !us.is_empty() {
        write!(f, ".{{")?;
        for (i, u) in us.iter().enumerate() {
          if i > 0 {
            write!(f, ", ")?;
          }
          write!(f, "{u}")?;
        }
        write!(f, "}}")?;
      }
      Ok(())
    },
    ExprData::App(..) => {
      let (head, args) = collect_spine(e);
      write!(f, "(")?;
      fmt_expr(&head, f, depth + 1)?;
      for a in &args {
        write!(f, " ")?;
        fmt_expr(a, f, depth + 1)?;
      }
      write!(f, ")")
    },
    ExprData::Lam(name, _, ty, body, _) => {
      write!(f, "(fun (")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, ") => ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::All(name, _, ty, body, _) => {
      write!(f, "((")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, ") -> ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::Let(name, ty, val, body, _, _) => {
      write!(f, "(let ")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, " := ")?;
      fmt_expr(val, f, depth + 1)?;
      write!(f, " in ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::Prj(id, field, val, _) => {
      fmt_expr(val, f, depth + 1)?;
      write!(f, ".{field}@{id}")
    },
    ExprData::Nat(val, _, _) => write!(f, "{val}"),
    ExprData::Str(val, _, _) => write!(f, "{val:?}"),
  }
}

fn collect_spine<M: KernelMode>(e: &KExpr<M>) -> (KExpr<M>, Vec<KExpr<M>>) {
  let mut args = Vec::new();
  let mut cur = e.clone();
  while let ExprData::App(func, arg, _) = cur.data() {
    args.push(arg.clone());
    cur = func.clone();
  }
  args.reverse();
  (cur, args)
}

#[cfg(test)]
mod tests {
  use super::super::mode::{Anon, Meta};
  use super::*;
  use crate::ix::address::Address;
  use crate::ix::env::BinderInfo;

  type ME = KExpr<Meta>;
  type AE = KExpr<Anon>;
  type MU = KUniv<Meta>;
  type AU = KUniv<Anon>;

  fn mk_name(s: &str) -> Name {
    let mut name = Name::anon();
    for part in s.split('.') {
      name = Name::str(name, part.to_string());
    }
    name
  }

  fn mk_addr(s: &str) -> Address {
    Address::hash(s.as_bytes())
  }

  // ---- Constructors & hashing ----

  #[test]
  fn var_hash_deterministic() {
    assert_eq!(AE::var(0, ()).addr(), AE::var(0, ()).addr());
  }

  #[test]
  fn var_different_indices() {
    assert_ne!(AE::var(0, ()).addr(), AE::var(1, ()).addr());
  }

  #[test]
  fn var_meta_name_does_not_affect_hash() {
    // Binder names are descriptive metadata only — they do NOT contribute
    // to the content hash, so two `Var(0)` nodes with different display
    // names are content-equal. Keeps hash equality alpha-invariant.
    assert_eq!(
      ME::var(0, mk_name("x")).addr(),
      ME::var(0, mk_name("y")).addr()
    );
  }

  #[test]
  fn sort_hash() {
    assert_ne!(
      AE::sort(AU::zero()).addr(),
      AE::sort(AU::succ(AU::zero())).addr()
    );
  }

  #[test]
  fn const_hash() {
    let c = AE::cnst(KId::new(mk_addr("Nat"), ()), Box::new([]));
    assert_eq!(c.lbr(), 0);
    assert_eq!(c.count_0(), 0);
  }

  #[test]
  fn const_meta_name_does_not_affect_hash() {
    // `id.name` is display-only metadata. Two `Const` nodes with the same
    // `id.addr` (the actual identity) are content-equal regardless of
    // their display names.
    let a = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Nat")), Box::new([]));
    let b = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Int")), Box::new([]));
    assert_eq!(a.addr(), b.addr());
  }

  #[test]
  fn app_hash_and_lbr() {
    let a = AE::app(AE::var(0, ()), AE::var(1, ()));
    assert_eq!(a.lbr(), 2);
    assert_eq!(a.count_0(), 1);
  }

  #[test]
  fn app_order_matters() {
    let v0 = AE::var(0, ());
    let v1 = AE::var(1, ());
    assert_ne!(AE::app(v0.clone(), v1.clone()).addr(), AE::app(v1, v0).addr());
  }

  #[test]
  fn lam_meta_name_does_not_affect_hash() {
    // Binder names are alpha-equivalent metadata; two lambdas differing
    // only in binder name hash identically (true alpha-invariance even
    // in `Meta` mode).
    let ty = ME::sort(MU::zero());
    let body = ME::var(0, mk_name("x"));
    let a =
      ME::lam(mk_name("x"), BinderInfo::Default, ty.clone(), body.clone());
    let b = ME::lam(mk_name("y"), BinderInfo::Default, ty, body);
    assert_eq!(a.addr(), b.addr());
  }

  #[test]
  fn lam_binder_info_does_not_affect_hash() {
    // Binder info (implicit / instance / etc.) is elaborator-facing
    // metadata; the kernel does not distinguish lambdas that differ only
    // in binder info.
    let ty = ME::sort(MU::zero());
    let body = ME::var(0, mk_name("x"));
    let a =
      ME::lam(mk_name("x"), BinderInfo::Default, ty.clone(), body.clone());
    let b = ME::lam(mk_name("x"), BinderInfo::Implicit, ty, body);
    assert_eq!(a.addr(), b.addr());
  }

  #[test]
  fn lam_lbr() {
    let e = AE::lam((), (), AE::sort(AU::zero()), AE::var(1, ()));
    assert_eq!(e.lbr(), 1);
    let e2 = AE::lam((), (), AE::var(0, ()), AE::var(0, ()));
    assert_eq!(e2.lbr(), 1);
  }

  #[test]
  fn all_hash_differs_from_lam() {
    let ty = AE::sort(AU::zero());
    let body = AE::var(0, ());
    assert_ne!(
      AE::lam((), (), ty.clone(), body.clone()).addr(),
      AE::all((), (), ty, body).addr()
    );
  }

  #[test]
  fn let_hash() {
    let e =
      AE::let_((), AE::sort(AU::zero()), AE::var(0, ()), AE::var(1, ()), true);
    assert_eq!(e.lbr(), 1);
    assert_eq!(e.count_0(), 1);
  }

  #[test]
  fn let_non_dep_does_not_affect_hash() {
    let ty = AE::sort(AU::zero());
    let val = AE::var(0, ());
    let body = AE::var(0, ());
    let a = AE::let_((), ty.clone(), val.clone(), body.clone(), true);
    let b = AE::let_((), ty, val, body, false);
    assert_eq!(a.addr(), b.addr());
  }

  #[test]
  fn prj_hash() {
    let p = AE::prj(KId::new(mk_addr("Prod"), ()), 0, AE::var(0, ()));
    assert_eq!(p.lbr(), 1);
  }

  #[test]
  fn nat_str_hash() {
    let n = AE::nat(Nat::from(42u64), mk_addr("42"));
    let s = AE::str("hello".into(), mk_addr("hello"));
    assert_ne!(n.addr(), s.addr());
    assert_eq!(n.lbr(), 0);
  }

  // ---- mdata accessor ----

  #[test]
  fn mdata_default_empty() {
    let e = ME::var(0, mk_name("x"));
    assert!(e.mdata().is_empty());
  }

  // ---- PartialEq ----

  #[test]
  fn eq_by_hash() {
    let a = AE::app(AE::var(0, ()), AE::var(1, ()));
    let b = AE::app(AE::var(0, ()), AE::var(1, ()));
    assert_eq!(a, b);
    assert_ne!(a, AE::var(0, ()));
  }

  // ---- Display ----

  #[test]
  fn display_var_anon() {
    assert_eq!(format!("{}", AE::var(0, ())), "#0");
  }

  #[test]
  fn display_var_meta_named() {
    assert_eq!(format!("{}", ME::var(0, mk_name("x"))), "x");
  }

  #[test]
  fn display_sort() {
    assert_eq!(format!("{}", AE::sort(AU::zero())), "Sort 0");
  }

  #[test]
  fn display_const_anon() {
    let c = AE::cnst(KId::new(mk_addr("Nat"), ()), Box::new([]));
    let s = format!("{c}");
    assert_eq!(s.len(), 8, "got '{s}'"); // 8 hex chars (hash only)
  }

  #[test]
  fn display_const_meta() {
    let c = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Nat")), Box::new([]));
    assert!(format!("{c}").starts_with("Nat@"));
  }

  #[test]
  fn display_const_with_univs() {
    let c =
      AE::cnst(KId::new(mk_addr("List"), ()), Box::new([AU::param(0, ())]));
    let s = format!("{c}");
    assert!(s.contains(".{u0}"), "got '{s}'");
  }

  #[test]
  fn display_app() {
    assert_eq!(
      format!("{}", AE::app(AE::var(0, ()), AE::var(1, ()))),
      "(#0 #1)"
    );
  }

  #[test]
  fn display_app_spine() {
    let e = AE::app(AE::app(AE::var(0, ()), AE::var(1, ())), AE::var(2, ()));
    assert_eq!(format!("{e}"), "(#0 #1 #2)");
  }

  #[test]
  fn display_lam_meta() {
    let e = ME::lam(
      mk_name("x"),
      BinderInfo::Default,
      ME::sort(MU::zero()),
      ME::var(0, mk_name("x")),
    );
    assert_eq!(format!("{e}"), "(fun (x : Sort 0) => x)");
  }

  #[test]
  fn display_all_anon() {
    let e = AE::all((), (), AE::sort(AU::zero()), AE::var(0, ()));
    assert_eq!(format!("{e}"), "((_ : Sort 0) -> #0)");
  }

  #[test]
  fn display_let() {
    let e =
      AE::let_((), AE::sort(AU::zero()), AE::var(0, ()), AE::var(0, ()), true);
    assert_eq!(format!("{e}"), "(let _ : Sort 0 := #0 in #0)");
  }

  #[test]
  fn display_nat() {
    assert_eq!(format!("{}", AE::nat(Nat::from(42u64), mk_addr("42"))), "42");
  }

  #[test]
  fn display_str() {
    assert_eq!(
      format!("{}", AE::str("hello".into(), mk_addr("hello"))),
      "\"hello\""
    );
  }
}
