//! Local context for free-variable based binder opening.
//!
//! Mirrors `refs/lean4/src/Lean/LocalContext.lean` and the C++ kernel's
//! `local_ctx`. During type checking, when a binder (`Lam`/`All`/`Let`) is
//! recursed into, we open it by replacing the bound `Var(0)` with a fresh
//! [`FVar`](super::expr::ExprData::FVar) and pushing a [`LocalDecl`] into the
//! [`LocalContext`]. The fresh fvar id is generated by [`NameGenerator`].
//!
//! Because each fvar carries a unique [`FVarId`] embedded in its content
//! hash, expressions that mention different fvars hash distinctly. This is
//! the soundness lever that lets WHNF / infer / def-eq caches key by
//! expression alone — see the kernel fvar plan.
//!
//! Stage A (current): types only; no kernel path uses these yet.
//!
//! Stage B will wire `infer_lambda` / `infer_forall` / `infer_let` /
//! `is_def_eq_binding` / eta / inductive validation through `LocalContext`,
//! and Stage C drops the legacy `ctx`/`let_vals`/`ctx_addr_for_lbr`
//! suffix-hash machinery.

use rustc_hash::FxHashMap;

use crate::ix::env::{BinderInfo, Name};

use super::env::InternTable;
use super::expr::{ExprData, FVarId, KExpr};
use super::mode::KernelMode;
use super::subst::abstract_fvars;

/// A single local-context entry. Either a regular binder (`CDecl`, from a
/// lambda or forall) or a let-binding (`LDecl`, with an associated value).
#[derive(Clone, Debug)]
pub enum LocalDecl<M: KernelMode> {
  /// Regular binder declaration: lambda- or forall-bound. Carries only
  /// the binder's type. Mirrors `Lean.LocalDecl.cdecl`.
  CDecl { name: M::MField<Name>, bi: M::MField<BinderInfo>, ty: KExpr<M> },
  /// Let-binding declaration: carries both type and value. WHNF zeta-reduces
  /// `FVar(id)` to `val` when the lookup hits an `LDecl`. Mirrors
  /// `Lean.LocalDecl.ldecl`.
  LDecl { name: M::MField<Name>, ty: KExpr<M>, val: KExpr<M> },
}

impl<M: KernelMode> LocalDecl<M> {
  pub fn ty(&self) -> &KExpr<M> {
    match self {
      LocalDecl::CDecl { ty, .. } | LocalDecl::LDecl { ty, .. } => ty,
    }
  }

  pub fn name(&self) -> &M::MField<Name> {
    match self {
      LocalDecl::CDecl { name, .. } | LocalDecl::LDecl { name, .. } => name,
    }
  }

  /// `Some(val)` for let-bindings, `None` otherwise.
  pub fn val(&self) -> Option<&KExpr<M>> {
    match self {
      LocalDecl::CDecl { .. } => None,
      LocalDecl::LDecl { val, .. } => Some(val),
    }
  }

  pub fn is_let(&self) -> bool {
    matches!(self, LocalDecl::LDecl { .. })
  }
}

/// Insertion-ordered local context indexed by [`FVarId`].
///
/// Push/pop is O(1) via `Vec` operations on `decls`. Lookup by `FVarId` is
/// O(1) via the parallel `index` map. The two structures are kept in sync
/// by `push` and `truncate`.
#[derive(Clone, Debug)]
pub struct LocalContext<M: KernelMode> {
  /// Insertion-ordered fvars and their declarations.
  decls: Vec<(FVarId, LocalDecl<M>)>,
  /// Position lookup: `index[fv_id] == i` iff `decls[i].0 == fv_id`.
  index: FxHashMap<FVarId, usize>,
}

impl<M: KernelMode> Default for LocalContext<M> {
  fn default() -> Self {
    Self::new()
  }
}

impl<M: KernelMode> LocalContext<M> {
  pub fn new() -> Self {
    LocalContext { decls: Vec::new(), index: FxHashMap::default() }
  }

  pub fn len(&self) -> usize {
    self.decls.len()
  }

  pub fn is_empty(&self) -> bool {
    self.decls.is_empty()
  }

  /// Look up a declaration by its [`FVarId`]. Returns `None` if the fvar is
  /// not bound in this context.
  pub fn find(&self, id: FVarId) -> Option<&LocalDecl<M>> {
    self.index.get(&id).map(|&i| &self.decls[i].1)
  }

  /// Push a declaration. The caller is responsible for ensuring `id` is
  /// fresh (typically from [`NameGenerator::fresh`]).
  pub fn push(&mut self, id: FVarId, decl: LocalDecl<M>) {
    let pos = self.decls.len();
    self.decls.push((id, decl));
    self.index.insert(id, pos);
  }

  /// Truncate the context to the given length, dropping any declarations
  /// pushed since. The dropped fvars become unresolvable via [`Self::find`].
  pub fn truncate(&mut self, len: usize) {
    while self.decls.len() > len {
      let (id, _) = self.decls.pop().expect("len > 0 by loop guard");
      self.index.remove(&id);
    }
  }

  /// Iterate decls in insertion order.
  pub fn iter(&self) -> impl Iterator<Item = (FVarId, &LocalDecl<M>)> {
    self.decls.iter().map(|(id, d)| (*id, d))
  }

  /// Abstract `body` over `fvars` and wrap it in a chain of `Lam` (or `Let`
  /// for `LDecl` entries) binders, innermost-first.
  ///
  /// The result has all of the listed fvars replaced by de Bruijn indices
  /// (`fvars[0]` becomes the outermost binder, `fvars[n-1]` the innermost).
  /// This is the inverse of the binder-opening pattern used during type
  /// checking: open with [`NameGenerator::fresh`], recurse, close back
  /// here so the result no longer mentions any of the opened fvars.
  ///
  /// Mirrors `Lean.LocalContext.mkLambda`.
  pub fn mk_lambda(
    &self,
    intern: &mut InternTable<M>,
    fvars: &[FVarId],
    body: KExpr<M>,
  ) -> KExpr<M> {
    let abstracted = abstract_fvars(intern, &body, fvars);
    self.wrap_binders(intern, fvars, abstracted, /* as_lambda */ true)
  }

  /// Abstract `body` over `fvars` and wrap it in a chain of `All` (or `Let`
  /// for `LDecl` entries) binders, innermost-first.
  ///
  /// Same shape as [`Self::mk_lambda`] but emits `All` for `CDecl` entries.
  /// Mirrors `Lean.LocalContext.mkForall`.
  pub fn mk_pi(
    &self,
    intern: &mut InternTable<M>,
    fvars: &[FVarId],
    body: KExpr<M>,
  ) -> KExpr<M> {
    let abstracted = abstract_fvars(intern, &body, fvars);
    self.wrap_binders(intern, fvars, abstracted, /* as_lambda */ false)
  }

  fn wrap_binders(
    &self,
    intern: &mut InternTable<M>,
    fvars: &[FVarId],
    body: KExpr<M>,
    as_lambda: bool,
  ) -> KExpr<M> {
    // Wrap from innermost to outermost: rightmost fvar is the innermost
    // binder, so iterate fvars in reverse.
    let mut acc = body;
    for fv in fvars.iter().rev() {
      let decl = self
        .find(*fv)
        .expect("LocalContext::wrap_binders: fvar not in context");
      acc = match decl {
        LocalDecl::CDecl { name, bi, ty } => {
          if as_lambda {
            intern.intern_expr(KExpr::lam(
              name.clone(),
              bi.clone(),
              ty.clone(),
              acc,
            ))
          } else {
            intern.intern_expr(KExpr::all(
              name.clone(),
              bi.clone(),
              ty.clone(),
              acc,
            ))
          }
        },
        LocalDecl::LDecl { name, ty, val } => {
          // Let-bindings always close as `Let`, regardless of `as_lambda`.
          // The `non_dep` flag is conservatively false; refining it would
          // require a body-occurrence analysis at close time.
          intern.intern_expr(KExpr::let_(
            name.clone(),
            ty.clone(),
            val.clone(),
            acc,
            false,
          ))
        },
      };
    }
    acc
  }
}

/// Fresh-id generator for [`FVarId`]. One per `TypeChecker`. Counter-based:
/// each call to [`Self::fresh`] returns a strictly larger id than any prior
/// call, so within a single check the ids are dense and unique.
///
/// Reset on every `TypeChecker::reset` so per-check ids are not reused
/// across different constants.
#[derive(Clone, Debug, Default)]
pub struct NameGenerator {
  next: u64,
}

impl NameGenerator {
  pub fn new() -> Self {
    NameGenerator { next: 0 }
  }

  pub fn fresh(&mut self) -> FVarId {
    let id = FVarId(self.next);
    self.next = self.next.checked_add(1).expect(
      "NameGenerator::fresh: u64 counter overflow (more than 2^64 fvars in \
       a single check)",
    );
    id
  }

  /// Number of fvars generated so far. Used by Stage B to save/restore the
  /// counter when needed (rare; binder open/close are usually nested in a
  /// way that does not require counter rollback).
  pub fn count(&self) -> u64 {
    self.next
  }
}

/// Cheap predicate: an `FVar` head-only check. Used by callers (Stage B+)
/// that want to dispatch on whether an expression starts with a free
/// variable without a full match.
pub fn is_fvar<M: KernelMode>(e: &KExpr<M>) -> bool {
  matches!(e.data(), ExprData::FVar(..))
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::ix::kernel::level::KUniv;
  use crate::ix::kernel::mode::Anon;

  type AE = KExpr<Anon>;
  type AU = KUniv<Anon>;

  fn anon_name() -> () {}
  fn anon_bi() -> () {}

  #[test]
  fn name_generator_unique() {
    let mut ngen = NameGenerator::new();
    let a = ngen.fresh();
    let b = ngen.fresh();
    let c = ngen.fresh();
    assert_ne!(a, b);
    assert_ne!(b, c);
    assert_ne!(a, c);
    assert_eq!(a.0, 0);
    assert_eq!(b.0, 1);
    assert_eq!(c.0, 2);
    assert_eq!(ngen.count(), 3);
  }

  #[test]
  fn lctx_push_find_truncate() {
    let mut ngen = NameGenerator::new();
    let mut lctx: LocalContext<Anon> = LocalContext::new();

    let id1 = ngen.fresh();
    let id2 = ngen.fresh();
    let ty1 = AE::sort(AU::zero());
    let ty2 = AE::sort(AU::succ(AU::zero()));

    lctx.push(
      id1,
      LocalDecl::CDecl { name: anon_name(), bi: anon_bi(), ty: ty1.clone() },
    );
    lctx.push(
      id2,
      LocalDecl::CDecl { name: anon_name(), bi: anon_bi(), ty: ty2.clone() },
    );

    assert_eq!(lctx.len(), 2);
    assert_eq!(lctx.find(id1).map(|d| d.ty()), Some(&ty1));
    assert_eq!(lctx.find(id2).map(|d| d.ty()), Some(&ty2));

    lctx.truncate(1);
    assert_eq!(lctx.len(), 1);
    assert!(lctx.find(id2).is_none());
    assert_eq!(lctx.find(id1).map(|d| d.ty()), Some(&ty1));

    lctx.truncate(0);
    assert!(lctx.is_empty());
    assert!(lctx.find(id1).is_none());
  }

  #[test]
  fn fvar_distinct_ids_distinct_hashes() {
    let mut ngen = NameGenerator::new();
    let id1 = ngen.fresh();
    let id2 = ngen.fresh();
    let fv1: AE = AE::fvar(id1, anon_name());
    let fv2: AE = AE::fvar(id2, anon_name());
    assert_ne!(fv1.addr(), fv2.addr());
    assert!(fv1.has_fvars());
    assert!(fv2.has_fvars());
    assert_eq!(fv1.lbr(), 0);
    assert_eq!(fv2.lbr(), 0);
  }

  #[test]
  fn is_fvar_predicate() {
    let mut ngen = NameGenerator::new();
    let fv: AE = AE::fvar(ngen.fresh(), anon_name());
    let v: AE = AE::var(0, anon_name());
    let s: AE = AE::sort(AU::zero());
    assert!(is_fvar(&fv));
    assert!(!is_fvar(&v));
    assert!(!is_fvar(&s));
  }
}
