//! Expressions with optional metadata.
//!
//! `KExpr<M>` is an Arc-wrapped expression. Each variant carries an `ExprInfo<M>`
//! with its blake3 hash, substitution annotations, and mdata.

use std::fmt;
use std::sync::Arc;

use bignat::Nat;
use ix_common::address::Address;
use ix_common::env::{BinderInfo, DataValue, Name};

use super::env::Addr;
use super::id::KId;
use super::level::KUniv;
use super::mode::{KernelMode, MetaDisplay};

/// Expression. Thin Arc wrapper — cheap to clone, O(1) identity via `Arc::ptr_eq`.
#[derive(Clone, Debug)]
pub struct KExpr<M: KernelMode>(Arc<ExprData<M>>);

/// A single mdata layer: key-value pairs from Lean's `Expr.mdata`.
pub type MData = Vec<(Name, DataValue)>;

/// Per-expression metadata: blake3 hash, substitution annotations, and mdata.
#[derive(Clone, Debug)]
pub struct ExprInfo<M: KernelMode> {
  /// Blake3 hash of semantic expression content. Metadata fields are stored
  /// for diagnostics/egress but do not contribute to the hash.
  pub addr: Addr,
  /// Loose bound variable range: upper bound on free de Bruijn indices.
  pub lbr: u64,
  /// Count of free `Var(0)` occurrences.
  pub count_0: u64,
  /// Whether any [`ExprData::FVar`] occurrence is reachable in this expression.
  ///
  /// FVars (free variables) are leaves carrying a unique [`FVarId`]; they are
  /// introduced when a binder is opened during inference / def-eq, and
  /// re-abstracted into de Bruijn binders before the result escapes the
  /// open scope. The flag lets callers (substitution, `abstract_fvars`,
  /// soundness assertions) skip walks when no fvars are reachable.
  pub has_fvars: bool,
  /// Lean mdata annotations. Semantically transparent, erased in Anon mode.
  pub mdata: M::MField<Vec<MData>>,
}

/// Per-`TypeChecker` unique identifier for a free variable. Generated by
/// [`crate::lctx::NameGenerator`] and embedded into the blake3
/// content hash of [`ExprData::FVar`] nodes, so that two distinct fvars hash
/// distinctly. This is the soundness lever that lets cache keys be the
/// expression hash alone (no separate local-context key) — see the kernel
/// fvar plan and `refs/lean4/src/kernel/type_checker.h:27`.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, PartialOrd, Ord)]
pub struct FVarId(pub u64);

impl fmt::Display for FVarId {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(f, "fv${}", self.0)
  }
}

/// Expression data. Each variant carries its [`ExprInfo<M>`].
#[derive(Clone, Debug)]
pub enum ExprData<M: KernelMode> {
  Var(u64, M::MField<Name>, ExprInfo<M>),
  /// Free variable: opaque identity from the active local context.
  /// `FVarId` participates in the content hash; the user-facing `Name` is
  /// preserved (in Meta mode) for diagnostics. The looked-up type lives in
  /// the active [`crate::lctx::LocalContext`], not on the node.
  FVar(FVarId, M::MField<Name>, ExprInfo<M>),
  Sort(KUniv<M>, ExprInfo<M>),
  Const(KId<M>, Box<[KUniv<M>]>, ExprInfo<M>),
  App(KExpr<M>, KExpr<M>, ExprInfo<M>),
  Lam(M::MField<Name>, M::MField<BinderInfo>, KExpr<M>, KExpr<M>, ExprInfo<M>),
  All(M::MField<Name>, M::MField<BinderInfo>, KExpr<M>, KExpr<M>, ExprInfo<M>),
  /// Let binding: name, type, value, body, non_dep flag.
  Let(M::MField<Name>, KExpr<M>, KExpr<M>, KExpr<M>, bool, ExprInfo<M>),
  /// Projection: struct type id, field index, struct value.
  Prj(KId<M>, u64, KExpr<M>, ExprInfo<M>),
  Nat(Nat, Address, ExprInfo<M>),
  Str(String, Address, ExprInfo<M>),
}

impl<M: KernelMode> ExprData<M> {
  pub fn info(&self) -> &ExprInfo<M> {
    match self {
      ExprData::Var(.., i)
      | ExprData::FVar(.., i)
      | ExprData::Sort(.., i)
      | ExprData::Const(.., i)
      | ExprData::App(.., i)
      | ExprData::Lam(.., i)
      | ExprData::All(.., i)
      | ExprData::Let(.., i)
      | ExprData::Prj(.., i)
      | ExprData::Nat(.., i)
      | ExprData::Str(.., i) => i,
    }
  }
}

impl<M: KernelMode> KExpr<M> {
  pub fn new(data: ExprData<M>) -> Self {
    KExpr(Arc::new(data))
  }

  pub fn data(&self) -> &ExprData<M> {
    &self.0
  }

  pub fn info(&self) -> &ExprInfo<M> {
    self.data().info()
  }

  pub fn addr(&self) -> &Addr {
    &self.info().addr
  }

  pub fn lbr(&self) -> u64 {
    self.info().lbr
  }

  pub fn count_0(&self) -> u64 {
    self.info().count_0
  }

  /// Whether any [`ExprData::FVar`] occurrence is reachable. Computed at
  /// construction time and propagated via OR through composite nodes, so
  /// the check is O(1) per call.
  pub fn has_fvars(&self) -> bool {
    self.info().has_fvars
  }

  pub fn mdata(&self) -> &M::MField<Vec<MData>> {
    &self.info().mdata
  }

  /// Canonical identity key for cache lookups: the intern-assigned uid.
  /// `Addr` is a plain `u64`, allocated process-globally and never reused,
  /// so uid equality implies "same construction event or same intern-table
  /// canonical value" — strictly, structural equality.
  pub fn hash_key(&self) -> Addr {
    *self.addr()
  }

  pub fn ptr_eq(&self, other: &KExpr<M>) -> bool {
    Arc::ptr_eq(&self.0, &other.0)
  }

  /// Canonical-identity equality: `ptr_eq` or equal intern uid. Sound in
  /// the affirmative (equal uid ⇒ structurally equal); INCOMPLETE in the
  /// negative — two structurally equal expressions built without sharing
  /// an [`InternTable`](super::env::InternTable) carry distinct uids.
  /// Callers that need a definitive verdict use `==` (structural with this
  /// as the fast path); callers where a false negative merely costs a
  /// cache miss or a def-eq fallback use this directly.
  pub fn hash_eq(&self, other: &KExpr<M>) -> bool {
    self.ptr_eq(other) || self.addr() == other.addr()
  }

  /// Structural equality mirroring exactly what the intern identity
  /// covers: display names, binder info, and mdata are NOT compared
  /// (matching the historical content-hash semantics). Equal interned
  /// subtrees prune at the uid fast path, so canonical-vs-canonical
  /// comparison is O(1).
  fn structural_eq(&self, other: &Self) -> bool {
    if self.hash_eq(other) {
      return true;
    }
    match (self.data(), other.data()) {
      (ExprData::Var(i, _, _), ExprData::Var(j, _, _)) => i == j,
      (ExprData::FVar(x, _, _), ExprData::FVar(y, _, _)) => x == y,
      (ExprData::Sort(u, _), ExprData::Sort(v, _)) => u == v,
      (ExprData::Const(id1, us1, _), ExprData::Const(id2, us2, _)) => {
        id1.addr == id2.addr
          && us1.len() == us2.len()
          && us1.iter().zip(us2.iter()).all(|(a, b)| a == b)
      },
      (ExprData::App(f1, a1, _), ExprData::App(f2, a2, _)) => {
        f1.structural_eq(f2) && a1.structural_eq(a2)
      },
      (ExprData::Lam(_, _, t1, b1, _), ExprData::Lam(_, _, t2, b2, _))
      | (ExprData::All(_, _, t1, b1, _), ExprData::All(_, _, t2, b2, _)) => {
        t1.structural_eq(t2) && b1.structural_eq(b2)
      },
      (
        ExprData::Let(_, t1, v1, b1, nd1, _),
        ExprData::Let(_, t2, v2, b2, nd2, _),
      ) => {
        nd1 == nd2
          && t1.structural_eq(t2)
          && v1.structural_eq(v2)
          && b1.structural_eq(b2)
      },
      (ExprData::Prj(id1, f1, v1, _), ExprData::Prj(id2, f2, v2, _)) => {
        id1.addr == id2.addr && f1 == f2 && v1.structural_eq(v2)
      },
      // Literals: the blob address IS the identity (mirroring the old
      // content hash, which hashed only the address). The value conjunct
      // is defense in depth: load-time blob verification makes it
      // redundant, and if that invariant were ever violated it degrades
      // to inequality — the conservative direction.
      (ExprData::Nat(v1, ba1, _), ExprData::Nat(v2, ba2, _)) => {
        ba1 == ba2 && v1 == v2
      },
      (ExprData::Str(v1, ba1, _), ExprData::Str(v2, ba2, _)) => {
        ba1 == ba2 && v1 == v2
      },
      _ => false,
    }
  }
}

impl<M: KernelMode> PartialEq for KExpr<M> {
  fn eq(&self, other: &Self) -> bool {
    self.structural_eq(other)
  }
}

impl<M: KernelMode> Eq for KExpr<M> {}

fn no_mdata<M: KernelMode>() -> M::MField<Vec<MData>> {
  M::meta_field(vec![])
}

fn mk_info<M: KernelMode>(
  addr: Addr,
  lbr: u64,
  count_0: u64,
  has_fvars: bool,
  mdata: M::MField<Vec<MData>>,
) -> ExprInfo<M> {
  ExprInfo { addr, lbr, count_0, has_fvars, mdata }
}

/// Process-global uid allocator for expression/universe identity.
///
/// Every constructed node takes a fresh uid, so uid equality means "same
/// construction event" — or, after [`InternTable`](super::env::InternTable)
/// hash-consing, "same canonical value". Uids are NEVER reused (the counter
/// is global, not per-table), so cache keys built from uids stay sound
/// across intern-table clears: a stale key can only miss, never alias.
///
/// This replaces the per-node blake3 content hash: profiling on the Zisk
/// guest put `app_hash` + the blake3 wrapper at ~20% of cycles on
/// reduction-heavy constants, all of it spent computing identity that the
/// intern table can assign in one atomic increment.
static NEXT_UID: std::sync::atomic::AtomicU64 =
  std::sync::atomic::AtomicU64::new(1);

#[inline]
pub(crate) fn fresh_uid() -> Addr {
  let uid = NEXT_UID.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
  // Uid exhaustion guard. Uids are ASSIGNED (sequential), never computed
  // from content, so two distinct terms can only alias if the counter
  // wraps — which would take centuries at nanosecond allocation rates
  // (and >2^67 guest cycles in-circuit). Abort rather than reason about
  // it: identity soundness must not rest on "probably won't happen".
  assert!(uid < u64::MAX, "kernel uid counter exhausted");
  uid
}

// =============================================================================
// Constructors: each `*_mdata` form allocates a fresh uid; the
// `*_mdata_with_addr` builders remain for the intern table and callers
// that already hold a fresh uid. Structural identity (what used to be the
// content hash) is decided by `InternTable`'s shallow keys — see
// `env.rs::ExprKey` — which mirror what the historical hash functions
// covered: names, binder info, and mdata are excluded.
// =============================================================================

impl<M: KernelMode> KExpr<M> {
  pub fn var(idx: u64, name: M::MField<Name>) -> Self {
    Self::var_mdata(idx, name, no_mdata::<M>())
  }

  /// Compute the content hash for [`KExpr::var_mdata`] without allocating.
  ///
  pub fn var_mdata_with_addr(
    idx: u64,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info =
      mk_info::<M>(addr, idx + 1, if idx == 0 { 1 } else { 0 }, false, mdata);
    KExpr::new(ExprData::Var(idx, name, info))
  }

  pub fn fvar(id: FVarId, name: M::MField<Name>) -> Self {
    Self::fvar_mdata(id, name, no_mdata::<M>())
  }

  pub fn fvar_mdata_with_addr(
    id: FVarId,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    // FVars are leaves: no loose bvars (lbr = 0), no Var(0) occurrences,
    // and `has_fvars` is true since this node *is* an fvar.
    let info = mk_info::<M>(addr, 0, 0, true, mdata);
    KExpr::new(ExprData::FVar(id, name, info))
  }

  pub fn fvar_mdata(
    id: FVarId,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::fvar_mdata_with_addr(id, name, mdata, addr)
  }

  pub fn var_mdata(
    idx: u64,
    name: M::MField<Name>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::var_mdata_with_addr(idx, name, mdata, addr)
  }

  pub fn sort(u: KUniv<M>) -> Self {
    Self::sort_mdata(u, no_mdata::<M>())
  }

  pub fn sort_mdata_with_addr(
    u: KUniv<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Sort(u, mk_info::<M>(addr, 0, 0, false, mdata)))
  }

  pub fn sort_mdata(u: KUniv<M>, mdata: M::MField<Vec<MData>>) -> Self {
    let addr = fresh_uid();
    Self::sort_mdata_with_addr(u, mdata, addr)
  }

  pub fn cnst(id: KId<M>, univs: Box<[KUniv<M>]>) -> Self {
    Self::cnst_mdata(id, univs, no_mdata::<M>())
  }

  pub fn cnst_mdata_with_addr(
    id: KId<M>,
    univs: Box<[KUniv<M>]>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Const(
      id,
      univs,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn cnst_mdata(
    id: KId<M>,
    univs: Box<[KUniv<M>]>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::cnst_mdata_with_addr(id, univs, mdata, addr)
  }

  pub fn app(f: KExpr<M>, a: KExpr<M>) -> Self {
    Self::app_mdata(f, a, no_mdata::<M>())
  }

  pub fn app_mdata_with_addr(
    f: KExpr<M>,
    a: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      f.lbr().max(a.lbr()),
      f.count_0() + a.count_0(),
      f.has_fvars() || a.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::App(f, a, info))
  }

  pub fn app_mdata(
    f: KExpr<M>,
    a: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::app_mdata_with_addr(f, a, mdata, addr)
  }

  pub fn lam(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
  ) -> Self {
    Self::lam_mdata(name, bi, ty, body, no_mdata::<M>())
  }

  /// Compute the content hash for [`KExpr::lam_mdata`].
  ///
  pub fn lam_mdata_with_addr(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(body.lbr().saturating_sub(1)),
      ty.count_0(),
      ty.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::Lam(name, bi, ty, body, info))
  }

  pub fn lam_mdata(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::lam_mdata_with_addr(name, bi, ty, body, mdata, addr)
  }

  pub fn all(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
  ) -> Self {
    Self::all_mdata(name, bi, ty, body, no_mdata::<M>())
  }

  pub fn all_mdata_with_addr(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(body.lbr().saturating_sub(1)),
      ty.count_0(),
      ty.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::All(name, bi, ty, body, info))
  }

  pub fn all_mdata(
    name: M::MField<Name>,
    bi: M::MField<BinderInfo>,
    ty: KExpr<M>,
    body: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::all_mdata_with_addr(name, bi, ty, body, mdata, addr)
  }

  pub fn let_(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
  ) -> Self {
    Self::let_mdata(name, ty, val, body, non_dep, no_mdata::<M>())
  }

  pub fn let_mdata_with_addr(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info = mk_info::<M>(
      addr,
      ty.lbr().max(val.lbr()).max(body.lbr().saturating_sub(1)),
      ty.count_0() + val.count_0(),
      ty.has_fvars() || val.has_fvars() || body.has_fvars(),
      mdata,
    );
    KExpr::new(ExprData::Let(name, ty, val, body, non_dep, info))
  }

  pub fn let_mdata(
    name: M::MField<Name>,
    ty: KExpr<M>,
    val: KExpr<M>,
    body: KExpr<M>,
    non_dep: bool,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::let_mdata_with_addr(name, ty, val, body, non_dep, mdata, addr)
  }

  pub fn prj(id: KId<M>, field: u64, val: KExpr<M>) -> Self {
    Self::prj_mdata(id, field, val, no_mdata::<M>())
  }

  pub fn prj_mdata_with_addr(
    id: KId<M>,
    field: u64,
    val: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    let info =
      mk_info::<M>(addr, val.lbr(), val.count_0(), val.has_fvars(), mdata);
    KExpr::new(ExprData::Prj(id, field, val, info))
  }

  pub fn prj_mdata(
    id: KId<M>,
    field: u64,
    val: KExpr<M>,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::prj_mdata_with_addr(id, field, val, mdata, addr)
  }

  pub fn nat(val: Nat, blob_addr: Address) -> Self {
    Self::nat_mdata(val, blob_addr, no_mdata::<M>())
  }

  pub fn nat_mdata_with_addr(
    val: Nat,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Nat(
      val,
      blob_addr,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn nat_mdata(
    val: Nat,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::nat_mdata_with_addr(val, blob_addr, mdata, addr)
  }

  pub fn str(val: String, blob_addr: Address) -> Self {
    Self::str_mdata(val, blob_addr, no_mdata::<M>())
  }

  pub fn str_mdata_with_addr(
    val: String,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
    addr: Addr,
  ) -> Self {
    KExpr::new(ExprData::Str(
      val,
      blob_addr,
      mk_info::<M>(addr, 0, 0, false, mdata),
    ))
  }

  pub fn str_mdata(
    val: String,
    blob_addr: Address,
    mdata: M::MField<Vec<MData>>,
  ) -> Self {
    let addr = fresh_uid();
    Self::str_mdata_with_addr(val, blob_addr, mdata, addr)
  }
}

/// Meta mode: shows names when available. Anon mode: positional/hash fallbacks.
impl<M: KernelMode> fmt::Display for KExpr<M> {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    fmt_expr(self, f, 0)
  }
}

fn fmt_expr<M: KernelMode>(
  e: &KExpr<M>,
  f: &mut fmt::Formatter<'_>,
  depth: usize,
) -> fmt::Result {
  if depth > 20 {
    return write!(f, "...");
  }
  match e.data() {
    ExprData::Var(idx, name, _) => {
      if name.has_meta() {
        name.meta_fmt(f)
      } else {
        write!(f, "#{idx}")
      }
    },
    ExprData::FVar(id, name, _) => {
      if name.has_meta() {
        name.meta_fmt(f)?;
        write!(f, "@{id}")
      } else {
        write!(f, "{id}")
      }
    },
    ExprData::Sort(u, _) => write!(f, "Sort {u}"),
    ExprData::Const(id, us, _) => {
      write!(f, "{id}")?;
      if !us.is_empty() {
        write!(f, ".{{")?;
        for (i, u) in us.iter().enumerate() {
          if i > 0 {
            write!(f, ", ")?;
          }
          write!(f, "{u}")?;
        }
        write!(f, "}}")?;
      }
      Ok(())
    },
    ExprData::App(..) => {
      let (head, args) = collect_spine(e);
      write!(f, "(")?;
      fmt_expr(&head, f, depth + 1)?;
      for a in &args {
        write!(f, " ")?;
        fmt_expr(a, f, depth + 1)?;
      }
      write!(f, ")")
    },
    ExprData::Lam(name, _, ty, body, _) => {
      write!(f, "(fun (")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, ") => ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::All(name, _, ty, body, _) => {
      write!(f, "((")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, ") -> ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::Let(name, ty, val, body, _, _) => {
      write!(f, "(let ")?;
      if name.has_meta() {
        name.meta_fmt(f)?;
      } else {
        write!(f, "_")?;
      }
      write!(f, " : ")?;
      fmt_expr(ty, f, depth + 1)?;
      write!(f, " := ")?;
      fmt_expr(val, f, depth + 1)?;
      write!(f, " in ")?;
      fmt_expr(body, f, depth + 1)?;
      write!(f, ")")
    },
    ExprData::Prj(id, field, val, _) => {
      fmt_expr(val, f, depth + 1)?;
      write!(f, ".{field}@{id}")
    },
    ExprData::Nat(val, _, _) => write!(f, "{val}"),
    ExprData::Str(val, _, _) => write!(f, "{val:?}"),
  }
}

fn collect_spine<M: KernelMode>(e: &KExpr<M>) -> (KExpr<M>, Vec<KExpr<M>>) {
  let mut args = Vec::new();
  let mut cur = e.clone();
  while let ExprData::App(func, arg, _) = cur.data() {
    args.push(arg.clone());
    cur = func.clone();
  }
  args.reverse();
  (cur, args)
}

#[cfg(test)]
mod tests {
  use super::super::mode::{Anon, Meta};
  use super::*;
  use ix_common::address::Address;
  use ix_common::env::BinderInfo;

  type ME = KExpr<Meta>;
  type AE = KExpr<Anon>;
  type MU = KUniv<Meta>;
  type AU = KUniv<Anon>;

  fn mk_name(s: &str) -> Name {
    let mut name = Name::anon();
    for part in s.split('.') {
      name = Name::str(name, part.to_string());
    }
    name
  }

  fn mk_addr(s: &str) -> Address {
    Address::hash(s.as_bytes())
  }

  // ---- Constructors & hashing ----

  #[test]
  fn var_hash_deterministic() {
    // Identity is intern-assigned now: independently built nodes carry
    // distinct uids but remain structurally equal (`==`).
    assert_eq!(AE::var(0, ()), AE::var(0, ()));
  }

  #[test]
  fn var_different_indices() {
    assert_ne!(AE::var(0, ()).addr(), AE::var(1, ()).addr());
  }

  #[test]
  fn var_meta_name_does_not_affect_hash() {
    // Binder names are descriptive metadata only — they do NOT contribute
    // to the content hash, so two `Var(0)` nodes with different display
    // names are content-equal. Keeps hash equality alpha-invariant.
    assert_eq!(ME::var(0, mk_name("x")), ME::var(0, mk_name("y")));
  }

  #[test]
  fn sort_hash() {
    assert_ne!(
      AE::sort(AU::zero()).addr(),
      AE::sort(AU::succ(AU::zero())).addr()
    );
  }

  #[test]
  fn const_hash() {
    let c = AE::cnst(KId::new(mk_addr("Nat"), ()), Box::new([]));
    assert_eq!(c.lbr(), 0);
    assert_eq!(c.count_0(), 0);
  }

  #[test]
  fn const_meta_name_does_not_affect_hash() {
    // `id.name` is display-only metadata. Two `Const` nodes with the same
    // `id.addr` (the actual identity) are content-equal regardless of
    // their display names.
    let a = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Nat")), Box::new([]));
    let b = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Int")), Box::new([]));
    assert_eq!(a, b);
  }

  #[test]
  fn app_hash_and_lbr() {
    let a = AE::app(AE::var(0, ()), AE::var(1, ()));
    assert_eq!(a.lbr(), 2);
    assert_eq!(a.count_0(), 1);
  }

  #[test]
  fn app_order_matters() {
    let v0 = AE::var(0, ());
    let v1 = AE::var(1, ());
    assert_ne!(AE::app(v0.clone(), v1.clone()).addr(), AE::app(v1, v0).addr());
  }

  #[test]
  fn lam_meta_name_does_not_affect_hash() {
    // Binder names are alpha-equivalent metadata; two lambdas differing
    // only in binder name hash identically (true alpha-invariance even
    // in `Meta` mode).
    let ty = ME::sort(MU::zero());
    let body = ME::var(0, mk_name("x"));
    let a =
      ME::lam(mk_name("x"), BinderInfo::Default, ty.clone(), body.clone());
    let b = ME::lam(mk_name("y"), BinderInfo::Default, ty, body);
    assert_eq!(a, b);
  }

  #[test]
  fn lam_binder_info_does_not_affect_hash() {
    // Binder info (implicit / instance / etc.) is elaborator-facing
    // metadata; the kernel does not distinguish lambdas that differ only
    // in binder info.
    let ty = ME::sort(MU::zero());
    let body = ME::var(0, mk_name("x"));
    let a =
      ME::lam(mk_name("x"), BinderInfo::Default, ty.clone(), body.clone());
    let b = ME::lam(mk_name("x"), BinderInfo::Implicit, ty, body);
    assert_eq!(a, b);
  }

  #[test]
  fn lam_lbr() {
    let e = AE::lam((), (), AE::sort(AU::zero()), AE::var(1, ()));
    assert_eq!(e.lbr(), 1);
    let e2 = AE::lam((), (), AE::var(0, ()), AE::var(0, ()));
    assert_eq!(e2.lbr(), 1);
  }

  #[test]
  fn all_hash_differs_from_lam() {
    let ty = AE::sort(AU::zero());
    let body = AE::var(0, ());
    assert_ne!(
      AE::lam((), (), ty.clone(), body.clone()).addr(),
      AE::all((), (), ty, body).addr()
    );
  }

  #[test]
  fn let_hash() {
    let e =
      AE::let_((), AE::sort(AU::zero()), AE::var(0, ()), AE::var(1, ()), true);
    assert_eq!(e.lbr(), 1);
    assert_eq!(e.count_0(), 1);
  }

  #[test]
  fn let_non_dep_distinguishes_hash() {
    let ty = AE::sort(AU::zero());
    let val = AE::var(0, ());
    let body = AE::var(0, ());
    let a = AE::let_((), ty.clone(), val.clone(), body.clone(), true);
    let b = AE::let_((), ty, val, body, false);
    assert_ne!(a.addr(), b.addr());
  }

  #[test]
  fn prj_hash() {
    let p = AE::prj(KId::new(mk_addr("Prod"), ()), 0, AE::var(0, ()));
    assert_eq!(p.lbr(), 1);
  }

  #[test]
  fn nat_str_hash() {
    let n = AE::nat(Nat::from(42u64), mk_addr("42"));
    let s = AE::str("hello".into(), mk_addr("hello"));
    assert_ne!(n.addr(), s.addr());
    assert_eq!(n.lbr(), 0);
  }

  // ---- mdata accessor ----

  #[test]
  fn mdata_default_empty() {
    let e = ME::var(0, mk_name("x"));
    assert!(e.mdata().is_empty());
  }

  // ---- PartialEq ----

  #[test]
  fn eq_by_hash() {
    let a = AE::app(AE::var(0, ()), AE::var(1, ()));
    let b = AE::app(AE::var(0, ()), AE::var(1, ()));
    assert_eq!(a, b);
    assert_ne!(a, AE::var(0, ()));
  }

  // ---- Display ----

  #[test]
  fn display_var_anon() {
    assert_eq!(format!("{}", AE::var(0, ())), "#0");
  }

  #[test]
  fn display_var_meta_named() {
    assert_eq!(format!("{}", ME::var(0, mk_name("x"))), "x");
  }

  #[test]
  fn display_sort() {
    assert_eq!(format!("{}", AE::sort(AU::zero())), "Sort 0");
  }

  #[test]
  fn display_const_anon() {
    let c = AE::cnst(KId::new(mk_addr("Nat"), ()), Box::new([]));
    let s = format!("{c}");
    assert_eq!(s.len(), 8, "got '{s}'"); // 8 hex chars (hash only)
  }

  #[test]
  fn display_const_meta() {
    let c = ME::cnst(KId::new(mk_addr("Nat"), mk_name("Nat")), Box::new([]));
    assert!(format!("{c}").starts_with("Nat@"));
  }

  #[test]
  fn display_const_with_univs() {
    let c =
      AE::cnst(KId::new(mk_addr("List"), ()), Box::new([AU::param(0, ())]));
    let s = format!("{c}");
    assert!(s.contains(".{u0}"), "got '{s}'");
  }

  #[test]
  fn display_app() {
    assert_eq!(
      format!("{}", AE::app(AE::var(0, ()), AE::var(1, ()))),
      "(#0 #1)"
    );
  }

  #[test]
  fn display_app_spine() {
    let e = AE::app(AE::app(AE::var(0, ()), AE::var(1, ())), AE::var(2, ()));
    assert_eq!(format!("{e}"), "(#0 #1 #2)");
  }

  #[test]
  fn display_lam_meta() {
    let e = ME::lam(
      mk_name("x"),
      BinderInfo::Default,
      ME::sort(MU::zero()),
      ME::var(0, mk_name("x")),
    );
    assert_eq!(format!("{e}"), "(fun (x : Sort 0) => x)");
  }

  #[test]
  fn display_all_anon() {
    let e = AE::all((), (), AE::sort(AU::zero()), AE::var(0, ()));
    assert_eq!(format!("{e}"), "((_ : Sort 0) -> #0)");
  }

  #[test]
  fn display_let() {
    let e =
      AE::let_((), AE::sort(AU::zero()), AE::var(0, ()), AE::var(0, ()), true);
    assert_eq!(format!("{e}"), "(let _ : Sort 0 := #0 in #0)");
  }

  #[test]
  fn display_nat() {
    assert_eq!(format!("{}", AE::nat(Nat::from(42u64), mk_addr("42"))), "42");
  }

  #[test]
  fn display_str() {
    assert_eq!(
      format!("{}", AE::str("hello".into(), mk_addr("hello"))),
      "\"hello\""
    );
  }
}
