module
import Tests.Ixby.Common
import Ix.MultiStark.Verify.Transcript

namespace Tests.MultiStark.Verify.Transcript

open _root_.MultiStark.Verify
open _root_.MultiStark.Verify.Transcript
open Tests.Ixby (Check runChecks)

private def value (n : Nat) : Field := Ix.Ixby.Goldilocks.reduce n
private def limits : Limits := {}

private def synthetic : Except Error (Array Nat) := do
  let action : Action (Array Nat) := do
    observeField limits (value 0x0102030405060708)
    observeField limits (value 0x1122334455667788)
    let apcs ← sampleExt limits
    let afri ← sampleExt limits
    observeField limits (value 0xdeadbeef)
    let beta ← sampleExt limits
    observeField limits (value 0x0a0b0c0d01020304)
    observeField limits (value 2)
    let index ← sampleBits 20
    return #[apcs.c0.val, apcs.c1.val, afri.c0.val, afri.c1.val,
      beta.c0.val, beta.c1.val, index]
  return (← action.run {}).1

/-- Pinned native `types.rs` PCS challenger vectors at 9a906122, also exercised
by the Aiur verifier's self-tests. These are NOT generated by the pure code. -/
private def syntheticExpected : Array Nat := #[
  17795849114622667264, 4116843485681689527,
  11768399386651893439, 10948618071942561750,
  12096272534537655203, 11431251745744402868, 458922]

private def errorIs {α : Type} (result : Except Error α) (error : Error) : Bool :=
  match result with | .error actual => actual == error | .ok _ => false

private def okEquals {α : Type} [BEq α] (result : Except Error α) (expected : α) : Bool :=
  match result with | .ok actual => actual == expected | .error _ => false

private def forced (words : Array Nat) : Challenger :=
  { input := #[9], output := (words.flatMap (Codec.Wire.littleEndian 8)).reverse }

private def params : Parameters := ⟨1, 0, 0, 1, 3, 0, 0⟩
private def key : Key := ⟨params, #[⟨1, 0, 0, 1, 1, #[.const 0], #[0], #[]⟩], none, #[none]⟩
private def digest (byte : UInt8) : Digest := ⟨Array.replicate 32 byte, by simp⟩
private def proof : Proof := {
  active := #[true], commitments := ⟨#[digest 1], #[digest 2], #[digest 3]⟩
  accumulators := #[⟨0, 0⟩], logDegrees := #[2]
  fri := ⟨#[], #[], #[], #[], #[], 0⟩
  quotient := #[], preprocessed := none, stage1 := #[], stage2 := #[] }
private def claims : Array (Array Field) := #[#[1, 2, 3]]

private def fingerprint (key : Key) (claims : Array (Array Field)) (proof : Proof) : Option Challenges :=
  match replay limits key claims proof with | .ok (challenges, _) => some challenges | .error _ => none

private def checks : IO (List Check) := do
  let initial : Challenger := { input := #[1, 2], output := #[3, 4] }
  let p := Ix.Ixby.goldilocksModulus
  let rejection := forced #[p, 42, 43]
  let expected := fingerprint key claims proof
  let single : Action Nat := do
    observeField limits (value 0x0102030405060708)
    sampleBits 20
  return [
    ("native PCS challenger vector including six field samples and query index",
      okEquals synthetic syntheticExpected),
    ("native single raw sample_bits vector", match single.run {} with
      | .ok (n, _) => n == 1019203 | .error _ => false),
    ("output bytes are consumed from the end", (drawByte initial).1 == 4 &&
      (drawByte initial).2 == { initial with output := #[3] }),
    ("observations append input and discard pending output", match
        (observeBytes limits #[7, 8]).run initial with
      | .ok (_, state) => state == { input := #[1, 2, 7, 8], output := #[] }
      | .error _ => false),
    ("empty byte observations are inert", okEquals ((observeBytes limits #[]).run initial) ((), initial)),
    ("empty cap observations are inert", okEquals ((observeCap limits #[]).run initial) ((), initial)),
    ("empty field observations are inert", okEquals ((observeFields limits #[]).run initial) ((), initial)),
    ("modulus draw is discarded and the next canonical word returned",
      match sampleFieldWith 2 rejection with
      | .ok (v, state) => v.val == 42 && state == forced #[43]
      | .error _ => false),
    ("rejection bound exhaustion is an explicit failure", errorIs
      (sampleFieldWith 1 rejection) .sampleExhausted),
    ("zero rejection budget never samples", errorIs
      (sampleFieldWith 0 (forced #[42])) .sampleExhausted),
    ("canonical boundary p-1 is accepted without another draw", match
        sampleFieldWith 1 (forced #[p - 1, 42]) with
      | .ok (v, state) => v.val == p - 1 && state == forced #[42]
      | .error _ => false),
    ("extension sampling threads rejected bytes into its second coefficient", match
        (sampleExt { sampleAttempts := 2 }).run rejection with
      | .ok (v, state) => v == ⟨42, 43⟩ && state.output.isEmpty
      | .error _ => false),
    ("sample_bits consumes a raw noncanonical u64 without rejection", match
        (sampleBits 20).run (forced #[2 ^ 64 - 1, 42]) with
      | .ok (n, state) => n == 2 ^ 20 - 1 && state == forced #[42]
      | .error _ => false),
    ("zero-bit sample still consumes a raw word", match (sampleBits 0).run (forced #[17, 42]) with
      | .ok (n, state) => n == 0 && state == forced #[42]
      | .error _ => false),
    ("zero-bit PoW neither observes nor samples", okEquals ((checkWitness limits 0 99).run initial) ((), initial)),
    ("out-of-range bit count rejected", errorIs ((sampleBits 64).run initial) .bitRange),
    ("out-of-range PoW count rejected", errorIs ((checkWitness limits 64 0).run initial) .bitRange),
    ("observation byte budget enforced before append", errorIs
      ((observeBytes { observationBytes := 3 } #[7, 8]).run initial) .observationLimit),
    ("noncanonical integer observation is not reduced", errorIs
      ((observeNat limits p).run initial) .fieldRange),
    ("seed includes raw protocol tag and seven u64 parameters", match seed limits params with
      | .ok state => state.input.size == 70 && state.output.isEmpty &&
        state.input.extract 0 14 == "multi-stark/v0".toUTF8.data &&
        state.input.extract 14 70 == params.words.flatMap (Codec.Wire.littleEndian 8)
      | .error _ => false),
    ("oversized seed parameters rejected", errorIs
      (seed limits { params with numQueries := 65536 }) .fieldRange),
    ("full synthetic prefix replay succeeds", expected.isSome),
    ("claim values bound before challenges", expected != fingerprint key #[#[1, 2, 4]] proof),
    ("claim partitioning is length-bound", expected != fingerprint key #[#[1], #[2, 3]] proof),
    ("parameters seed all challenges", expected != fingerprint
      { key with params := { params with queryPowBits := 1 } } claims proof),
    ("inactive circuits still contribute shape words", expected != fingerprint
      { key with circuits := key.circuits.push ⟨1, 0, 0, 1, 1, #[], #[], #[]⟩ } claims proof),
    ("activation bitmap is observed", expected != fingerprint key claims { proof with active := #[false] }),
    ("trace degrees are observed", expected != fingerprint key claims { proof with logDegrees := #[3] }),
    ("preprocessed commitment is observed", expected != fingerprint
      { key with preprocessed := some #[digest 4] } claims proof),
    ("stage1 commitment is observed", expected != fingerprint key claims
      { proof with commitments := { proof.commitments with stage1 := #[digest 4] } }),
    ("stage2 commitment is observed", expected != fingerprint key claims
      { proof with commitments := { proof.commitments with stage2 := #[digest 4] } }),
    ("quotient commitment is observed", expected != fingerprint key claims
      { proof with commitments := { proof.commitments with quotient := #[digest 4] } }),
    ("intermediate accumulators are observed", expected != fingerprint key claims
      { proof with accumulators := #[⟨1, 0⟩] })
  ]

public def suite : IO UInt32 := runChecks "stage2-transcript" checks

end Tests.MultiStark.Verify.Transcript
