/-
Orphan-theorem detector — uses Lean's elaborated environment for precise
constant-dependency tracking. Runs the transitive closure of
`Aiur.Toplevel.compile_correct`'s body and prints every theorem declared
in `Ix/Aiur/Proofs/*.lean` that is NOT in that closure.

Run:
  cd /workspace/dev/lean/ix
  lake env lean tools/OrphanCheck.lean
-/
import Ix.Aiur

open Lean Elab Command

namespace Aiur.OrphanCheck

/-- Strip auto-generated suffixes from a `Name` to recover the user-named
parent. E.g. `Foo.bar._unary` → `Foo.bar`, `Foo.bar.brecOn` → `Foo.bar`.
Returns `none` if no recognized suffix. -/
def stripAutoGenSuffix (n : Name) : Option Name :=
  match n with
  | .str p s =>
    if s == "_unary" || s == "brecOn" || s == "below" || s == "recOn"
        || s == "casesOn" || s == "rec" || s == "induct" || s == "_mutual"
        || s == "noConfusion" || s == "noConfusionType" || s == "sizeOf"
        || s == "eq_def" || s == "eq_unfold" || s == "congr_simp"
        || s == "injEq" then
      some p
    else none
  | _ => none

/-- Transitively collect all constant names referenced from `root`, walking
through `value?` of every visited `ConstantInfo`. Also marks parent names
of auto-generated mutual peers (`_unary`/`.brec`/`.below`/etc.) — when an
auto-gen child is reachable, its user-named parent is too. -/
partial def collectUsed (env : Environment) (root : Name) : NameSet :=
  go ({} : NameSet) [root]
where
  go (acc : NameSet) : List Name → NameSet
    | [] => acc
    | n :: rest =>
      if acc.contains n then go acc rest
      else
        let acc := acc.insert n
        -- If `n` is auto-generated (e.g. `Foo._unary`), also mark its parent.
        let acc :=
          match stripAutoGenSuffix n with
          | some parent => if acc.contains parent then acc else acc.insert parent
          | none => acc
        match env.find? n with
        | none => go acc rest
        | some info =>
          let cs : List Name :=
            match info.value? with
            | some e => e.foldConsts (init := []) (fun c xs => c :: xs)
            | none => []
          let typeCs : List Name :=
            info.type.foldConsts (init := []) (fun c xs => c :: xs)
          go acc (cs ++ typeCs ++ rest)

/-- Substring containment for `String`. -/
private def String.containsSubstr (s sub : String) : Bool :=
  (s.splitOn sub).length > 1

/-- Strip the `_private.<module>.<idx>.` prefix from a private name to get
the original user-authored core. Returns the input unchanged if not a
private mangled name. -/
def stripPrivatePrefix (s : String) : String :=
  if s.startsWith "_private." then
    -- Format: _private.<module-with-dots>.<idx>.<core>
    -- Drop "_private." then drop until first digit-only segment, then take rest.
    let parts := s.splitOn "."
    let rec dropUntilDigit : List String → List String
      | [] => []
      | p :: rest =>
        if p.length > 0 && p.all Char.isDigit then rest
        else dropUntilDigit rest
    String.intercalate "." (dropUntilDigit parts)
  else s

/-- Names like `Foo.beq.eq_1`, `Foo.bar.eq_2`, … are equation lemmas. -/
def isEqUnfoldName (s : String) : Bool :=
  let parts := s.splitOn "."
  match parts.reverse with
  | last :: _ =>
    (last.startsWith "eq_" && (last.drop 3).all Char.isDigit && last.length > 3)
    || (last.startsWith "match_")
  | [] => false

/-- Heuristic: a `Name` is auto-generated (equation lemma, recursor, match
unfold, etc.) and therefore not user-authored. User-authored `private`
theorems are NOT filtered — `_private.*`-mangled names are stripped to
their core before pattern-checking. -/
def isAutoGenerated (n : Name) : Bool :=
  let raw := n.toString
  let s := stripPrivatePrefix raw
  let isPrivate := raw.startsWith "_private."
  -- For private-mangled user theorems, ONLY filter if the stripped core
  -- matches an auto-gen pattern (don't trust `n.isInternal`).
  -- For non-private names, also use `n.isInternal` to catch hygienic helpers.
  (!isPrivate && n.isInternal)
    || s.endsWith ".eq_def"
    || s.endsWith ".eq_unfold"
    || s.endsWith ".brecOn"
    || s.endsWith ".below"
    || s.endsWith ".recOn"
    || s.endsWith ".casesOn"
    || s.endsWith ".rec"
    || s.endsWith ".noConfusion"
    || s.endsWith ".noConfusionType"
    || s.endsWith ".sizeOf"
    || s.endsWith "._unary"
    || s.endsWith ".congr_simp"
    || s.endsWith ".injEq"
    || s.endsWith ".mk.injEq"
    || s.endsWith ".induct"
    || String.containsSubstr s ".hcongr_"
    || String.containsSubstr s "._sparseCasesOn_"
    || String.containsSubstr s ".match_"
    || isEqUnfoldName s
    -- Auto-generated structure-field projection theorems (manually identified):
    || s == "Aiur.CompileInv.valIdx_growth"
    || s == "Aiur.CompileInv.ops_monotone"
    || s == "Aiur.CompileInv.degrees_monotone"

/-- Predicate: `n` is a user-authored `theorem` declared in `Ix/Aiur/Proofs/*.lean`. -/
def isProofsTheorem (env : Environment) (n : Name) : Option Name :=
  if isAutoGenerated n then none
  else
    match env.find? n with
    | some (.thmInfo _) =>
      match env.getModuleIdxFor? n with
      | some idx =>
        let modName := env.header.moduleNames[idx.toNat]!
        if modName.toString.startsWith "Ix.Aiur.Proofs." then some modName
        else none
      | none => none
    | _ => none

end Aiur.OrphanCheck

open Aiur.OrphanCheck in
def main : IO Unit := do
  -- The `#eval` form below is what actually executes when this file is
  -- elaborated; `main` exists so it can also be invoked via `lake env`.
  pure ()

open Aiur.OrphanCheck in
#eval show CommandElabM Unit from do
  let env ← getEnv
  let used := collectUsed env `Aiur.Toplevel.compile_correct
  -- Group orphans by module.
  let mut byModule : Std.HashMap Name (Array Name) := {}
  let mut total : Nat := 0
  for (n, _) in env.constants.toList do
    if let some modName := isProofsTheorem env n then
      if !used.contains n && n != `Aiur.Toplevel.compile_correct then
        let arr := byModule.getD modName #[]
        byModule := byModule.insert modName (arr.push n)
        total := total + 1
  let modKeys := byModule.toList.map Prod.fst
  let sortedMods := modKeys.toArray.qsort (·.toString < ·.toString)
  IO.println s!"# Orphan theorems (not transitively used by `Aiur.Toplevel.compile_correct`)"
  IO.println ""
  IO.println s!"**Total**: {total} orphans across {sortedMods.size} modules."
  IO.println s!"**Used by compile_correct**: {used.size} constants."
  IO.println ""
  for m in sortedMods do
    let arr := byModule.getD m #[]
    let sorted := arr.qsort (·.toString < ·.toString)
    IO.println s!"## {m} ({sorted.size} orphans)"
    IO.println ""
    for n in sorted do
      IO.println s!"  {n}"
    IO.println ""
