import Ix.Tc.Verify.Check.ValidatorSoundness
import Ix.Tc.Verify.Check.DeclarationIngress

/-!
# Standalone declaration validation

This module lifts expression-validator soundness to the production
`validateConstWellScoped` boundary for the standalone declaration kinds
handled by K3.  Finite-run coverage and no-wrap size budgets are explicit
resources; neither is inferred from a successful validator return.
-/

namespace Ix.Tc

/-- Static resources needed to interpret successful standalone validation.
The size inequalities justify transporting the validator's `UInt64` binder
depths into the unbounded raw-to-Theory scoping relation. -/
inductive StandaloneValidationResources (support : RunSupport) :
    KConst .anon → Prop
  | axiom
      {name : Mode.anon.F Name} {levelParams : Mode.anon.F (Array Name)}
      {isUnsafe : Bool} {levels : UInt64} {type : KExpr .anon} :
    type.ValidationCoverage support →
    type.size < UInt64.size →
    StandaloneValidationResources support
      (.axio name levelParams isUnsafe levels type)
  | defn
      {name : Mode.anon.F Name} {levelParams : Mode.anon.F (Array Name)}
      {kind : Ix.DefKind} {safety : Ix.DefinitionSafety}
      {hints : Lean.ReducibilityHints} {levels : UInt64}
      {type value : KExpr .anon}
      {leanAll : Mode.anon.F (Array (KId .anon))} {block : KId .anon} :
    type.ValidationCoverage support →
    type.size < UInt64.size →
    value.ValidationCoverage support →
    value.size < UInt64.size →
    StandaloneValidationResources support
      (.defn name levelParams kind safety hints levels type value leanAll block)

namespace RecM

/-- Expose one concrete `TcM` bind generated by declaration validation. -/
private theorem runTcBind {α β : Type}
    (x : TcM .anon α) (k : α → TcM .anon β)
    (state : TcState .anon) :
    (x >>= k) state = match x state with
      | .ok value after => k value after
      | .error err after => .error err after := by
  show EStateM.bind x k state = _
  unfold EStateM.bind
  cases x state <;> rfl

/-- Successful execution of the exact production declaration validator
establishes the standalone syntax certificate consumed by raw ingress. -/
theorem validateConstWellScoped_sound
    {support : RunSupport} {c : KConst .anon}
    (hresources : StandaloneValidationResources support c)
    (hcollision : support.CollisionFree)
    {methods : Methods .anon} {state after : TcState .anon}
    (hrun : (validateConstWellScoped c).run methods state = .ok () after) :
    StandaloneScope c := by
  cases hresources with
  | @«axiom» name levelParams isUnsafe levels type hcoverage hsize =>
      unfold validateConstWellScoped at hrun
      rw [ReaderT.run_bind, runTcBind] at hrun
      simp only [KConst.ty, KConst.lvls] at hrun
      cases htype :
          (validateExprWellScoped type 0 levels.toNat).run methods state with
      | error err failed =>
          rw [htype] at hrun
          contradiction
      | ok _ nextState =>
          rw [htype] at hrun
          have hscope := validateExprWellScoped_sound hcoverage hcollision
            htype
          exact .axiom hscope.choose_spec.choose_spec.2 hsize
  | @defn name levelParams kind safety hints levels type value leanAll block
      htypeCoverage htypeSize hvalueCoverage hvalueSize =>
      unfold validateConstWellScoped at hrun
      rw [ReaderT.run_bind, runTcBind] at hrun
      simp only [KConst.ty, KConst.lvls] at hrun
      cases htype :
          (validateExprWellScoped type 0 levels.toNat).run methods state with
      | error err failed =>
          rw [htype] at hrun
          contradiction
      | ok _ nextState =>
          rw [htype] at hrun
          simp only at hrun
          cases hvalue :
              (validateExprWellScoped value 0 levels.toNat).run methods
                nextState with
          | error err failed =>
              rw [hvalue] at hrun
              contradiction
          | ok _ finalState =>
              rw [hvalue] at hrun
              have htypeScope := validateExprWellScoped_sound
                htypeCoverage hcollision htype
              have hvalueScope := validateExprWellScoped_sound
                hvalueCoverage hcollision hvalue
              exact .defn htypeScope.choose_spec.choose_spec.2 htypeSize
                hvalueScope.choose_spec.choose_spec.2 hvalueSize

end RecM

namespace PendingDecl

/-- Exact production validation supplies the scope premise needed to move a
pending raw declaration into the pre-translation relation. -/
theorem toPre_of_validation
    {trProj : RawProjRel} {world : VerifyWorld} {support : RunSupport}
    {id : KId .anon} {decl : Lean4Lean.VDecl} {concrete : KConst .anon}
    (hprojection : trProj.SubstCompatible)
    (hliterals : ∀ literal, world.venv.ContainsLits literal)
    (hpending : PendingDecl trProj world id decl)
    (hcatalog : world.catalog id = some concrete)
    (hresources : StandaloneValidationResources support concrete)
    (hcollision : support.CollisionFree)
    {methods : Methods .anon} {state after : TcState .anon}
    (hrun : (RecM.validateConstWellScoped concrete).run methods state =
      .ok () after) :
    PreDeclRel world.venv world.nameOf trProj id concrete decl :=
  hpending.toPre_of_scope hprojection hliterals hcatalog
    (RecM.validateConstWellScoped_sound hresources hcollision hrun)

end PendingDecl

end Ix.Tc
