name: "LSpec CI"
on:
  pull_request:
  push:
    branches:
      - main
      - sb/rust-and-c
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v4.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: run LSpec binary
        run: lake exe lspec
  nix:
    name: Lean Tests with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # Installs `elan` and `lake` via Nix, which then downloads the Lean toolchain binary
      # from https://github.com/leanprover/lean4/releases
      - run: nix develop .#ci --command bash -c "lake build && lake exe lspec"
