name: Nix CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Runs Lean tests via Nix
  nix-test:
    name: Nix Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # Ix CLI
      - run: nix build --print-build-logs --accept-flake-config
      - run: nix run .#default -- --help
      # Ix tests
      - run: nix build .#test --print-build-logs --accept-flake-config
      - run: nix run .#test

  # Tests Nix devShell support on Ubuntu
  nix-devshell:
    name: Nix devShell Tests
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # Builds and runs tests using Lake as a Nix package
      - run: nix develop --accept-flake-config --command bash -c "lake build && lake test"
