name: Nix CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Runs Lean tests via Nix
  nix-test:
    name: Nix Tests
    strategy:
      matrix:
        os: [ubuntu-latest, warp-macos-latest-arm64-6x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # Ix CLI
      - run: nix build
      - run: nix run .#default -- --help
      # Ix tests
      - run: nix build .#test
      - run: nix run .#test

  # Test Nix devShell support
  nix-devshell:
    name: Nix devShell Tests
    strategy:
      matrix:
        os: [ubuntu-latest, warp-macos-latest-arm64-6x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: argumentcomputer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # Builds and runs tests using Lake as a Nix package
      - run: nix develop --command bash -c "lake build && lake test"
